---
permalink: switch-cisco-3232c/cn1610-replace-CL2.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Puede utilizar los switches Cisco Nexus 3232C como switches de clúster en su clúster AFF o FAS . 
---
= Sustituya el interruptor CN1610 CL2 por el interruptor 3232C C2.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos pasos para reemplazar su switch CN1610 (CL2) con un switch Nexus 3232C (C2).

.Pasos
. Desactive los puertos de interconexión del clúster que están conectados físicamente al switch CL2:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo se desactivan los cuatro puertos de interconexión del clúster para los nodos n1 y n2:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin false*
cluster::*> *network port modify -node n1 -port e0c -up-admin false*
cluster::*> *network port modify -node n2 -port e0b -up-admin false*
cluster::*> *network port modify -node n2 -port e0c -up-admin false*
----
====
. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step3]] Apague los puertos ISL 13 a 16 en el switch CN1610 activo CL1 utilizando el comando apropiado.
+
Para obtener más información sobre los comandos de Cisco , consulte las guías que se enumeran en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo se desactivan los puertos ISL del 13 al 16 en el switch CN1610 CL1:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16*
(CL1)(Interface 0/13-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Cree un enlace ISL temporal entre CL1 y C2:
+
Para obtener más información sobre los comandos de Cisco , consulte las guías que se enumeran en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra la creación de un enlace ISL temporal entre CL1 (puertos 13-16) y C2 (puertos e1/24/1-4) mediante Cisco. `switchport mode trunk` dominio:

[listing, subs="+quotes"]
----
C2# configure
C2(config)# *interface port-channel 2*
C2(config-if)# *switchport mode trunk*
C2(config-if)# *spanning-tree port type network*
C2(config-if)# *mtu 9216*
C2(config-if)# *interface breakout module 1 port 24 map 10g-4x*
C2(config)# *interface e1/24/1-4*
C2(config-if-range)# *switchport mode trunk*
C2(config-if-range)# *mtu 9216*
C2(config-if-range)# *channel-group 2 mode active*
C2(config-if-range)# *exit*
C2(config-if)# *exit*
----
====
. Retire los cables que están conectados al switch CN1610 CL2 en todos los nodos.
+
Utilizando el cableado compatible, debe volver a conectar los puertos desconectados en todos los nodos al switch Nexus 3232C C2.

. Retire cuatro cables ISL de los puertos 13 a 16 del switch CN1610 CL1.
+
Debe conectar los cables de ruptura Cisco QSFP28 a SFP+ apropiados que conectan el puerto 1/24 del nuevo switch Cisco 3232C C2 a los puertos 13 a 16 del switch CN1610 CL1 existente.

+
[NOTE]
====
Al volver a conectar cualquier cable al nuevo switch Cisco 3232C, los cables utilizados deben ser de fibra óptica o cables twinax de Cisco .

====
. Haga que el ISL sea dinámico configurando la interfaz ISL 3/1 en el switch CN1610 activo para deshabilitar el modo estático.
+
Esta configuración coincide con la configuración ISL en el switch 3232C C2 cuando los ISL se activan en ambos switches.

+
Para obtener más información sobre los comandos de Cisco , consulte las guías que se enumeran en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra la interfaz ISL 3/1 configurada para hacer que el ISL sea dinámico:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 3/1*
(CL1)(Interface 3/1)# *no port-channel static*
(CL1)(Interface 3/1)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Active los ISL 13 a 16 en el conmutador CN1610 activo CL1.
+
Para obtener más información sobre los comandos de Cisco , consulte las guías que se enumeran en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo se activan los puertos ISL del 13 al 16 en la interfaz de canal de puerto 3/1:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16,3/1*
(CL1)(Interface 0/13-0/16,3/1)# *no shutdown*
(CL1)(Interface 0/13-0/16,3/1)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Verifique que los ISL sean `up` en el interruptor CN1610 CL1.
+
El "estado de enlace" debería ser `Up` "Tipo" debería ser `Dynamic` y la columna "Puerto activo" debería ser `True` para los puertos 0/13 a 0/16.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra los ISL que se verifican como `up` en el interruptor CN1610 CL1:

[listing, subs="+quotes"]
----
(CL1)# *show port-channel 3/1*
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port        Port
Ports  Timeout       Speed       Active
------ ------------- ----------  -------
0/13   actor/long    10 Gb Full  True
       partner/long
0/14   actor/long    10 Gb Full  True
       partner/long
0/15   actor/long    10 Gb Full  True
       partner/long
0/16   actor/long    10 Gb Full  True
       partner/long
----
====
. Verifique que los ISL sean `up` en el interruptor C2 del 3232C:
+
`show port-channel summary`

+
Para obtener más información sobre los comandos de Cisco , consulte las guías que se enumeran en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
Los puertos Eth1/24/1 a Eth1/24/4 deberían indicar `(P)` , lo que significa que los cuatro puertos ISL están activos en el canal del puerto.  Eth1/31 y Eth1/32 deberían indicar `(D)` ya que no están conectados.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra los ISL que se verifican como `up` en el interruptor C2 del 3232C:

[listing, subs="+quotes"]
----
C2# *show port-channel summary*

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
------------------------------------------------------------------------------
1	    Po1(SU)     Eth      LACP      Eth1/31(D)   Eth1/32(D)
2	    Po2(SU)     Eth      LACP      Eth1/24/1(P) Eth1/24/2(P) Eth1/24/3(P)
                                     Eth1/24/4(P)
----
====
. Active todos los puertos de interconexión del clúster que estén conectados al switch 3232C C2 en todos los nodos:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo activar los puertos de interconexión del clúster conectados al switch 3232C C2:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin true*
cluster::*> *network port modify -node n1 -port e0c -up-admin true*
cluster::*> *network port modify -node n2 -port e0b -up-admin true*
cluster::*> *network port modify -node n2 -port e0c -up-admin true*
----
====
. Revertir todas las LIF de interconexión de clúster migradas que estén conectadas a C2 en todos los nodos:
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver cluster -lif n1_clus3*
cluster::*> *network interface revert -vserver cluster -lif n2_clus2*
cluster::*> *network interface revert -vserver cluster -lif n2_clus3*
----
====
. Verifique que todos los puertos de interconexión del clúster hayan vuelto a sus puertos originales:
+
`network interface show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que las LIF del clúster 2 vuelven a sus puertos de origen; la reversión de las LIF se realiza correctamente si los puertos de la columna "Puerto actual" tienen el estado de `true` en la columna "Está en casa".  Si el valor "Es hogar" es `false` , entonces el LIF no se revierte.

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true

8 entries were displayed.
----
====
. Verifique que todos los puertos del clúster estén conectados:
+
`network port show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra la salida que verifica que todas las interconexiones del clúster son `up` :

[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
       (network port show)

Node: n1
                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -
e0b   cluster   cluster     up    9000  auto/10000     -
e0c   cluster   cluster     up    9000  auto/10000     -        -
e0d   cluster   cluster     up    9000  auto/10000     -        -
Node: n2

                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -
e0b   cluster   cluster     up    9000  auto/10000     -
e0c   cluster   cluster     up    9000  auto/10000     -
e0d   cluster   cluster     up    9000  auto/10000     -

8 entries were displayed.
----
====
. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step16]] Migrar las LIF asociadas con el primer conmutador CN1610 CL1:
+
`network interface migrate -vserver cluster -lif _lif-name_ -source-node _node-name_`

+
.Mostrar ejemplo
[%collapsible]
====
Debe migrar cada LIF del clúster individualmente a los puertos del clúster apropiados alojados en el conmutador de clúster C2, como se muestra en el siguiente ejemplo:

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e0b*
cluster::*> *network interface migrate -vserver cluster -lif n1_clus4 -source-node n1
-destination-node n1 -destination-port e0c*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e0b*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus4 -source-node n2
-destination-node n2 -destination-port e0c*
----
====


.¿Que sigue?
Después de haber reemplazado el interruptor CN1610 CL2, puedeslink:cn1610-replace-CL1.html["Sustituir el interruptor CN1610 CL1 por el interruptor 3232C C1."] .
