---
permalink: switch-cisco-3232c/cn1610-migrate-to-3232c-overview.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Antes de configurar los switches Cisco Nexus 3232c, revise una descripción general del proceso y la nomenclatura. 
---
= Requisitos de migración
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Los conmutadores Cisco Nexus 3232C se pueden utilizar como conmutadores de clúster en su clúster AFF o FAS . Los conmutadores de clúster le permiten crear clústeres ONTAP con más de dos nodos.


NOTE: El procedimiento requiere el uso de comandos ONTAP y comandos de switches Cisco Nexus serie 3000; se utilizan comandos ONTAP a menos que se indique lo contrario.

Si es necesario, consulte lo siguiente para obtener más información:

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 y CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== Requisitos de migración CN1610

Los conmutadores del clúster admiten las siguientes conexiones de nodo:

* NetApp CN1610: puertos 0/1 a 0/12 (10 GbE)
* Cisco Nexus 3232C: puertos e1/1-30 (40 o 100 o 4x10GbE)


Los conmutadores del clúster utilizan los siguientes puertos de enlace entre conmutadores (ISL).

* NetApp CN1610: puertos 0/13 a 0/16 (10 GbE)
* Cisco Nexus 3232C: puertos 1/31-32 (100GbE)


[NOTE]
====
Debe utilizar cables breakout 4x10G en el switch de clúster Cisco Nexus 3232C.

====
La siguiente tabla muestra las conexiones de cableado necesarias en cada etapa a medida que se realiza la transición de los switches NetApp CN1610 a los switches de clúster Cisco Nexus 3232C:

|===
| Escenario | Descripción | Cables necesarios 


 a| 
Inicial
 a| 
CN1610 a CN1610 (SFP+ a SFP+)
 a| 
4 cables de fibra óptica o cobre SFP+ de conexión directa



 a| 
Transición
 a| 
CN1610 a 3232C (QSFP a SFP+)
 a| 
1 QSFP y 4 cables de conexión de fibra óptica o cobre SFP+



 a| 
Final
 a| 
3232C a 3232C (QSFP a QSFP)
 a| 
2 cables QSFP de fibra óptica o cobre de conexión directa

|===
Debe haber descargado los archivos de configuración de referencia (RCF) correspondientes.  El número de puertos 10 GbE y 40/100 GbE se define en los RCF disponibles enlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Descarga del archivo de configuración de referencia del switch de red en clúster de Cisco"^] .

Las versiones de ONTAP y NX-OS compatibles con este procedimiento se enumeran enlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco"^] .

Las versiones de ONTAP y FASTPATH ​​compatibles con este procedimiento se enumeran enlink:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["Switches NetApp CN1601 y CN1610"^] .

.Acerca de los ejemplos utilizados
Los ejemplos del procedimiento de migración utilizan cuatro nodos:

* Dos nodos utilizan cuatro puertos de interconexión de clúster 10 GbE: *e0a*, *e0b*, *e0c* y *e0d*.
* Los otros dos nodos utilizan dos cables de fibra de interconexión de clúster de 40 GbE: *e4a* y *e4e*.
+
Ellink:https://hwu.netapp.com/["_Universo del Hardware_"^] Contiene información sobre los cables de fibra óptica en clúster para sus plataformas.



Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los nodos son *n1*, *n2*, *n3* y *n4*.
* Los resultados de los comandos pueden variar según las diferentes versiones del software ONTAP .
* Los interruptores CN1610 que se reemplazarán son *CL1* y *CL2*.
* Los switches Nexus 3232C que reemplazan a los switches CN1610 son *C1* y *C2*.
* *n1_clus1* es la primera interfaz lógica de clúster (LIF) que está conectada al conmutador de clúster 1 (CL1 o C1) para el nodo *n1*.
* *n1_clus2* es el primer LIF de clúster que está conectado al conmutador de clúster 2 (CL2 o C2) para el nodo *n1*.
* *n1_clus3* es la segunda LIF que está conectada al conmutador de clúster 2 (CL2 o C2) para el nodo *n1*.
* *n1_clus4* es la segunda LIF que está conectada al conmutador de clúster 1 (CL1 o C1) para el nodo *n1*.
* El número de puertos 10 GbE y 40/100 GbE se define en los archivos de configuración de referencia (RCF) disponibles enlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Descarga del archivo de configuración de referencia del switch de red en clúster de Cisco"^] .


.¿Que sigue?
Después de revisar los requisitos de migración, puedeslink:cn1610-prepare-to-migrate.html["Prepárate para migrar tus conmutadores."] .
