---
permalink: switch-cisco-3232c/configure-reqs-3232c.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Puede utilizar switches Cisco Nexus 3232C como switches de clúster en su clúster AFF o FAS. 
---
= Requisitos de configuración de los switches Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento de los switches Cisco Nexus 3232C, asegúrese de revisar los requisitos de la configuración y de la red.



== Requisitos de configuración

Para configurar el clúster, necesita el número y el tipo de cables y conectores de cable adecuados para los switches. Según el tipo de switch que esté configurando inicialmente, debe conectarse al puerto de la consola del switch con el cable de consola incluido; también debe proporcionar información de red específica.



== Requisitos de red

Necesita la siguiente información de red para todas las configuraciones de los switches:

* Subred IP para el tráfico de red de gestión
* Nombres de host y direcciones IP para cada una de las controladoras del sistema de almacenamiento y todos los switches aplicables
* La mayoría de las controladoras del sistema de almacenamiento se gestionan a través de la interfaz e0M mediante la conexión al puerto de servicio Ethernet (icono de llave inglesa). En los sistemas A800 y A700 de AFF de AFF, la interfaz e0M utiliza un puerto Ethernet dedicado.


Consulte la https://hwu.netapp.com["Hardware Universe"^] para obtener la información más reciente.

.¿Qué sigue?
Después de confirmar los requisitos de configuración, revise el link:required-documentation-3232c.html["documentación requerida"].
