---
permalink: switch-cisco-3232c/configure-reqs-3232c.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Puede utilizar los switches Cisco Nexus 3232C como switches de clúster en su clúster AFF o FAS . 
---
= Requisitos de configuración para los switches Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del switch Cisco Nexus 3232C, asegúrese de revisar los requisitos de configuración y de red.



== Requisitos de configuración

Para configurar su clúster, necesita el número y tipo adecuados de cables y conectores de cable para sus conmutadores.  Dependiendo del tipo de switch que esté configurando inicialmente, deberá conectarse al puerto de consola del switch con el cable de consola incluido; también deberá proporcionar información de red específica.



== Requisitos de red

Necesitará la siguiente información de red para todas las configuraciones de conmutadores:

* Subred IP para la gestión del tráfico de red
* Nombres de host y direcciones IP para cada uno de los controladores del sistema de almacenamiento y todos los conmutadores aplicables
* La mayoría de los controladores del sistema de almacenamiento se administran a través de la interfaz e0M conectándose al puerto de servicio Ethernet (ícono de llave inglesa). En los sistemas AFF A800 y AFF A700 , la interfaz e0M utiliza un puerto Ethernet dedicado.


Consulte el https://hwu.netapp.com["Hardware Universe"^] Para obtener la información más reciente. Ver link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"^] para obtener más información sobre los requisitos de instalación del conmutador.

.¿Qué sigue?
Una vez que haya confirmado los requisitos de configuración, puede revisarlink:required-documentation-3232c.html["documentación requerida"] .
