---
permalink: switch-cisco-3232c/install-upgrade-rcf-overview-3232c.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: 'SSH es un requisito cuando se utilizan el Monitor de estado del conmutador de clúster (CSHM) y las funciones de recopilación de registros. Para habilitar SSH en los conmutadores de clúster Cisco 3232c, primero genere las claves SSH y luego habilite SSH.' 
---
= Descripción general de la instalación o actualización del archivo de configuración de referencia (RCF).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Instale el archivo de configuración de referencia (RCF) después de configurar los conmutadores Nexus 3232C por primera vez. Actualiza tu versión RCF cuando tienes una versión existente del archivo RCF instalado en tu conmutador.

Consulte el artículo de la base de conocimientoslink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Cómo borrar la configuración de un switch de interconexión Cisco manteniendo la conectividad remota"^] Para obtener más información sobre la instalación o actualización de su RCF.

.Configuraciones RCF disponibles
La siguiente tabla describe los RCF disponibles para diferentes configuraciones.  Elija el RCF aplicable a su configuración.

Para obtener detalles específicos sobre el uso de puertos y VLAN, consulte la sección de notas importantes y el banner en su RCF.

[cols="1,2"]
|===
| Nombre RCF | Descripción 


 a| 
Ruptura de alta disponibilidad de 2 clústeres
 a| 
Admite dos clústeres ONTAP con al menos ocho nodos, incluidos los nodos que utilizan puertos Cluster+HA compartidos.



 a| 
Ruptura de 4 clústeres HA
 a| 
Admite cuatro clústeres ONTAP con al menos cuatro nodos, incluidos los nodos que utilizan puertos Cluster+HA compartidos.



 a| 
1-Cluster-HA
 a| 
Todos los puertos están configurados para 40/100GbE.  Admite tráfico compartido de clúster/HA en puertos.  Requerido para los sistemas AFF A320, AFF A250 y FAS500f .  Además, todos los puertos pueden utilizarse como puertos de clúster dedicados.



 a| 
1-Clúster-HA-Ruptura
 a| 
Los puertos están configurados para breakout 4x10GbE, breakout 4x25GbE (RCF 1.6+ en switches 100GbE) y 40/100GbE.  Admite tráfico compartido de clúster/HA en puertos para nodos que utilizan puertos compartidos de clúster/HA: sistemas AFF A320, AFF A250 y FAS500f .  Además, todos los puertos pueden utilizarse como puertos de clúster dedicados.



 a| 
Almacenamiento de alta disponibilidad en clúster
 a| 
Los puertos están configurados para 40/100GbE para Cluster+HA, 4x10GbE breakout para Cluster y 4x25GbE breakout para Cluster+HA, y 100GbE para cada par de almacenamiento HA.



 a| 
Grupo
 a| 
Dos versiones de RCF con diferentes asignaciones de puertos 4x10GbE (breakout) y puertos 40/100GbE. Se admiten todos los nodos FAS/ AFF , excepto los sistemas AFF A320, AFF A250 y FAS500f .



 a| 
Almacenamiento
 a| 
Todos los puertos están configurados para conexiones de almacenamiento NVMe de 100 GbE.

|===
.Documentación sugerida
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco (NSS)"^]
+
Consulte la tabla de compatibilidad de switches para conocer las versiones compatibles de ONTAP y RCF en el sitio de soporte de NetApp .  Tenga en cuenta que puede haber dependencias de comandos entre la sintaxis de comandos en RCF y la sintaxis que se encuentra en versiones específicas de NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Switches Cisco Nexus serie 3000"^]
+
Consulte las guías de software y actualización correspondientes disponibles en el sitio web de Cisco para obtener documentación completa sobre los procedimientos de actualización y degradación de los switches de Cisco .



.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los nombres de los dos switches de Cisco son *cs1* y *cs2*.
* Los nombres de los nodos son *cluster1-01*, *cluster1-02*, *cluster1-03* y *cluster1-04*.
* Los nombres LIF del clúster son *cluster1-01_clus1*, *cluster1-01_clus2*, *cluster1-02_clus1*, *cluster1-02_clus2*, *cluster1-03_clus1*, *cluster1-03_clus2*, *cluster1-04_clus1* y *cluster1-04_clus2*.
* El `cluster1::*>` El indicador muestra el nombre del clúster.


Los ejemplos de este procedimiento utilizan cuatro nodos.  Estos nodos utilizan dos puertos de interconexión de clúster 10GbE *e0a* y *e0b*.  Ver el https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para verificar los puertos de clúster correctos en sus plataformas.


NOTE: Los resultados del comando pueden variar dependiendo de las diferentes versiones de ONTAP.

Para obtener detalles de las configuraciones RCF disponibles, consultelink:configure-software-overview-3232c-cluster.html["Flujo de trabajo de instalación de software"] .

.Comandos utilizados
El procedimiento requiere el uso de comandos ONTAP y comandos de switches Cisco Nexus serie 3000; se utilizan comandos ONTAP a menos que se indique lo contrario.

.¿Que sigue?
Después de haber revisado el procedimiento de instalación o actualización de RCF,link:install-rcf-software-3232c.html["instalar el RCF"] olink:upgrade-rcf-software-3232c.html["Mejora tu RCF"] según sea necesario.
