---
permalink: switch-cisco-3232c/migrate-from-switchless-complete-migration.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Puede utilizar switches Cisco Nexus 3232C como switches de clúster en su clúster AFF o FAS. 
---
= Complete la migración desde un clúster de dos nodos sin switches a un clúster de dos nodos con switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Complete los siguientes pasos para finalizar la migración del clúster de dos nodos sin switch a un clúster con switches de dos nodos en switches Nexus 3232C.

.Pasos
. Verifique que todos los puertos de interconexión de clúster ahora se reviertan a sus puertos raíz:
+
`network interface show -role cluster`

+
La `Is Home` la columna debe mostrar un valor de `true` para todos los puertos enumerados en la `Current Port` columna. Si el valor mostrado es `false`, el puerto no se ha revertido.

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. Compruebe que todos los puertos de interconexión del clúster se encuentren en la `up` provincia:
+
`network port show -role cluster`

. Muestre los números de puerto del switch del clúster a través de los cuales cada puerto del clúster está conectado a cada nodo:
+
`network device-discovery show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1          /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    C2                  Ethernet1/7      N3K-C3232C
n2          /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    C2                  Ethernet1/8      N3K-C3232C
----
====
. Mostrar switches de clúster detectados y supervisados:
+
`system cluster-switch show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch show*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.101      NX3232CV
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP

C2                          cluster-network     10.10.1.102      NX3232CV
Serial Number: FOX000002
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP 2 entries were displayed.
----
====
. Compruebe que la detección del clúster sin switches ha cambiado la opción de clúster sin switches a deshabilitado:
+
`network options switchless-cluster show`

. Compruebe la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y versiones posteriores
--
Puede utilizar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad de la conectividad del clúster y, a continuación, muestre los detalles:

`network interface check cluster-connectivity start` y.. `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere varios segundos antes de ejecutar el `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Todos los lanzamientos de ONTAP
--
En todas las versiones de ONTAP, también se puede utilizar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step7]] Si suprimió la creación automática de casos, vuelva a activarlo llamando a un mensaje AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.El futuro
link:../switch-cshm/config-overview.html["Configure la supervisión de estado del switch"].
