---
permalink: switch-cisco-3232c/migrate-from-two-node-switchless-cluster.html 
sidebar: sidebar 
keywords: migrate, two-node cluster, switchless, cisco nexus 3232c 
summary: Si tiene un clúster sin switches de dos nodos, puede migrar de forma no disruptiva a un clúster con switches de dos nodos que incluya los switches de red de clústeres Cisco Nexus 3232C. 
---
= Migre de un clúster sin switches de dos nodos a un clúster con switches de clúster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene un clúster _sin switch_ de dos nodos, puede migrar a un clúster _switch_ de dos nodos que incluya los switches de red de clústeres Cisco Nexus 3232C. Se trata de un procedimiento no disruptivo.



== Revise los requisitos

.Requisitos de migración
Antes de la migración, asegúrese de revisarla link:migrate-requirements-3232c.html["Requisitos de migración"].

.Lo que necesitará
Asegúrese de que:

* Los puertos están disponibles para las conexiones de nodos. Los switches de clúster utilizan los puertos de enlace entre switches (ISL) e1/31-32.
* Tiene los cables adecuados para las conexiones del clúster:
+
** Los nodos con conexiones de clúster de 10 GbE requieren módulos ópticos QSFP con cables de fibra de cable de cable de cobre QSFP a SFP+.
** Los nodos con conexiones de clúster de 40/100 GbE requieren el soporte de módulos ópticos QSFP/ QSFP28 con cables de fibra o cables de conexión directa de cobre QSFP/QSFP28.
** Los switches de clúster requieren el cableado ISL apropiado: 2 cables de conexión directa de cobre o fibra QSFP28.


* Las configuraciones están correctamente configuradas y funcionan.
+
Los dos nodos deben estar conectados y funcionar en un valor de clúster sin switch de dos nodos.

* Todos los puertos del clúster están en el estado *up*.
* Se admite el switch de clúster Cisco Nexus 3232C.
* La configuración de red del clúster existente tiene lo siguiente:
+
** Infraestructura de clúster Nexus 3232C redundante y totalmente funcional en ambos switches
** Las versiones más recientes de RCF y NX-OS en sus switches
** Conectividad de gestión en ambos switches
** Acceso de consola a ambos switches
** Todas las interfaces lógicas de clúster (LIF) en el estado *up* sin haber sido migradas
** Personalización inicial del conmutador
** Todos los puertos ISL habilitados y cableado






== Migrar los switches

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la nomenclatura de conmutador y nodo siguiente:

* Switches de clúster Nexus 3232C, C1 y C2.
* Los nodos son n1 y n2.


Los ejemplos de este procedimiento utilizan dos nodos, cada uno utilizando dos puertos de interconexión de clúster de 40 GbE e4a y e4e. La link:https://hwu.netapp.com/["_Hardware Universe_"^] tiene detalles acerca de los puertos de clúster en las plataformas.

* n1_clus1 es la primera interfaz lógica del clúster (LIF) que se conecta al switch del clúster C1 para el nodo n1.
* n1_clus2 es la primera LIF del clúster que se conecta al switch de clúster C2 del nodo n1.
* n2_clus1 es la primera LIF de clúster que se conecta al switch de clúster C1 para el nodo n2.
* n2_clus2 es la segunda LIF del clúster que se conecta al switch de clúster C2 del nodo n2.
* El número de puertos 10 GbE y 40/100 GbE se define en los archivos de configuración de referencia (RCF) disponibles en la https://["Descarga del archivo de configuración de referencia del conmutador de red de clúster Cisco®"^] página.


[NOTE]
====
Para ello, es necesario utilizar tanto comandos de la ONTAP como comandos de la serie Cisco Nexus 3000; los comandos de la ONTAP se usan a menos que se indique lo contrario.

====


=== Paso 1: Mostrar y migrar puertos físicos y lógicos

. Si se habilita AutoSupport en este clúster, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ es la duración de la ventana de mantenimiento en horas.

+
[NOTE]
====
El mensaje de AutoSupport notifica al soporte técnico de esta tarea de mantenimiento para que la creación automática de casos se suprima durante la ventana de mantenimiento.

====
. Determine el estado administrativo u operativo de cada interfaz de clúster:
+
.. Mostrar los atributos del puerto de red:
+
`network port show -role cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
4 entries were displayed.
----
====
.. Muestra información sobre las interfaces lógicas y sus nodos principales designados:
+
`network interface show -role cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true

4 entries were displayed.
----
====
.. Compruebe que la detección de clústeres sin switch esté habilitada mediante el comando de privilegio avanzado:
+
`network options detect-switchless-cluster show``

+
.Muestra el ejemplo
[%collapsible]
====
El resultado en el ejemplo siguiente muestra que la detección de clústeres sin switch está habilitada:

[listing]
----
cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: true
----
====


. Verifique que los RCF e imagen adecuados estén instalados en los nuevos conmutadores 3232C y realice las personalizaciones necesarias del sitio, como agregar usuarios, contraseñas y direcciones de red.
+
Debe preparar ambos switches en este momento. Si necesita actualizar el software RCF e Image, debe seguir estos pasos:

+
.. Vaya a la página _Cisco Ethernet Switches_ del sitio de soporte de NetApp.
+
http://["Switches Ethernet de Cisco"^]

.. Anote el conmutador y las versiones de software necesarias en la tabla de esa página.
.. Descargue la versión adecuada de RCF.
.. Haga clic en *CONTINUAR* en la página *Descripción*, acepte el contrato de licencia y, a continuación, siga las instrucciones de la página *Descargar* para descargar el RCF.
.. Descargue la versión adecuada del software Image.
+
https://["Página de descarga del archivo de configuración de referencia del switch de red de Cisco Cluster y Management"^]



. Haga clic en *CONTINUAR* en la página *Descripción*, acepte el contrato de licencia y, a continuación, siga las instrucciones de la página *Descargar* para descargar el RCF.
. En los switches Nexus 3232C C1 y C2, deshabilite todos los puertos C1 y C2 que están orientados al nodo, pero no deshabilite los puertos ISL e1/31-32.
+
Para obtener más información acerca de los comandos de Cisco, consulte las guías que se enumeran en https://["Referencias de comandos NX-OS de Cisco Nexus serie 3000"^].

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo, se muestran los puertos 1 a 30 deshabilitados en los switches del clúster Nexus 3232C C1 y C2 utilizando una configuración compatible con RCF `NX3232_RCF_v1.0_24p10g_24p100g.txt`:

[listing]
----
C1# copy running-config startup-config
[########################################] 100% Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit
C2# copy running-config startup-config
[########################################] 100% Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. Conecte los puertos 1/31 y 1/32 de C1 a los mismos puertos de C2 utilizando el cableado compatible.
. Compruebe que los puertos ISL están operativos en C1 y C2:
+
`show port-channel summary`

+
Para obtener más información acerca de los comandos de Cisco, consulte las guías que se enumeran en https://["Referencias de comandos NX-OS de Cisco Nexus serie 3000"^].

+
.Muestra el ejemplo
[%collapsible]
====
El siguiente ejemplo muestra Cisco `show port-channel summary` Comando que se utiliza para verificar que los puertos ISL están operativos en C1 y C2:

[listing]
----
C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
      Port-
Group Channel      Type   Protocol  Member Ports
-------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------

Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Muestra la lista de dispositivos vecinos en el conmutador.
+
Para obtener más información acerca de los comandos de Cisco, consulte las guías que se enumeran en https://["Referencias de comandos NX-OS de Cisco Nexus serie 3000"^].

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestra el comando Cisco `show cdp neighbors` se utiliza para mostrar los dispositivos vecinos en el conmutador:

[listing]
----
C1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3232C  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3232C  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
----
====
. Muestre la conectividad de puerto del clúster en cada nodo:
+
`network device-discovery show`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestra la conectividad de puerto de clúster mostrada para una configuración de clúster de dos nodos sin switch:

[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. Migre los LIF n1_clus1 y n2_clus1 a los puertos físicos de sus nodos de destino:
+
`network interface migrate -vserver cluster -lif _lif-name_ source-node _source-node-name_ -destination-port _destination-port-name_`

+
.Muestra el ejemplo
[%collapsible]
====
Debe ejecutar el comando para cada nodo local tal y como se muestra en el ejemplo siguiente:

[listing]
----
cluster::*> network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
–destination-node n1 -destination-port e4e
cluster::*> network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
–destination-node n2 -destination-port e4e
----
====




=== Paso 2: Apague las LIF reasignadas y desconecte los cables

. Compruebe que las interfaces del clúster han migrado correctamente:
+
`network interface show -role cluster`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo, se muestra el estado "is Home" de las LIF n1_clus1 y n2_clus1 se ha convertido en "false" una vez completada la migración:

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
 4 entries were displayed.
----
====
. Apague los puertos del clúster de las LIF n1_clus1 y n2_clus1, que se migraron en el paso 9:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Muestra el ejemplo
[%collapsible]
====
Debe ejecutar el comando para cada puerto tal y como se muestra en el ejemplo siguiente:

[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin false
cluster::*> network port modify -node n2 -port e4a -up-admin false
----
====
. Hacer ping a las interfaces remotas del clúster y realizar una comprobación del servidor RPC:
+
`cluster ping-cluster -node _node-name_`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestra el nodo n1 con alas y el estado RPC indicado posteriormente:

[listing]
----
cluster::*> cluster ping-cluster -node n1

Host is n1 Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
====
. Desconecte el cable del e4a del nodo n1.
+
Puede consultar la configuración en ejecución y conectar el primer puerto de 40 GbE del switch C1 (puerto 1/7 en este ejemplo) a e4a en la n1 utilizando el cableado compatible con los switches Nexus 3232C.





=== Paso 3: Habilite los puertos del clúster

. Desconecte el cable del e4a del nodo n2.
+
Puede consultar la configuración en ejecución y conectar e4a al siguiente puerto 40 GbE disponible en C1, puerto 1/8, utilizando el cableado compatible.

. Habilite todos los puertos orientados al nodo en C1.
+
Para obtener más información acerca de los comandos de Cisco, consulte las guías que se enumeran en https://["Referencias de comandos NX-OS de Cisco Nexus serie 3000"^].

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestran los puertos 1 a 30 habilitados en los switches del clúster Nexus 3232C C1 y C2 que utilizan la configuración admitida en RCF `NX3232_RCF_v1.0_24p10g_26p100g.txt`:

[listing]
----
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# no shutdown
C1(config-if-range)# exit
C1(config)# exit
----
====
. Active el primer puerto del clúster, e4a, en cada nodo:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin true
cluster::*> network port modify -node n2 -port e4a -up-admin true
----
====
. Compruebe que los clústeres estén en ambos nodos:
+
`network port show -role cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

4 entries were displayed.
----
====
. Para cada nodo, revierte todos los LIF de interconexión de clúster migrados:
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.Muestra el ejemplo
[%collapsible]
====
Debe revertir cada LIF a su puerto de inicio de forma individual, como se muestra en el ejemplo siguiente:

[listing]
----
cluster::*> network interface revert -vserver cluster -lif n1_clus1
cluster::*> network interface revert -vserver cluster -lif n2_clus1
----
====
. Compruebe que todas las LIF se han revertido a sus puertos principales:
+
`network interface show -role cluster`

+
La `Is Home` la columna debe mostrar un valor de `true` para todos los puertos enumerados en la `Current Port` columna. Si el valor mostrado es `false`, el puerto no se ha revertido.

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====




=== Paso 4: Habilite las LIF reasignadas

. Muestre la conectividad de puerto del clúster en cada nodo:
+
`network device-discovery show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    n1                  e4e              FAS9000
----
====
. Migre clus2 al puerto e4a de la consola de cada nodo:
+
`network interface migrate cluster -lif _lif-name_ -source-node _source-node-name_ -destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.Muestra el ejemplo
[%collapsible]
====
Debe migrar cada LIF a su puerto de inicio de forma individual, como se muestra en el ejemplo siguiente:

[listing]
----
cluster::*> network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
–destination-node n1 -destination-port e4a
cluster::*> network interface migrate -vserver cluster -lif n2_clus2 -source-node n2 –destination-node n2 -destination-port e4a
----
====
. Apague los puertos de clúster clus2 LIF en ambos nodos:
+
`network port modify`

+
.Muestra el ejemplo
[%collapsible]
====
En el ejemplo siguiente se muestran los puertos especificados que se están estableciendo en `false`, apagando los puertos en ambos nodos:

[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin false
cluster::*> network port modify -node n2 -port e4e -up-admin false
----
====
. Compruebe el estado de LIF del clúster:
+
`network interface show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. Desconecte el cable del e4e en el nodo n1.
+
Puede consultar la configuración en ejecución y conectar el primer puerto de 40 GbE del switch C2 (puerto 1/7 en este ejemplo) a e4e en el nodo n1, utilizando el cableado adecuado para el modelo de switch Nexus 3232C.

. Desconecte el cable del e4e en el nodo n2.
+
Puede consultar la configuración en ejecución y conectar e4e al siguiente puerto de 40 GbE disponible en C2, puerto 1/8, utilizando el cableado adecuado para el modelo de switch Nexus 3232C.

. Habilite todos los puertos orientados al nodo en C2.
+
.Muestra el ejemplo
[%collapsible]
====
En el ejemplo siguiente se muestran los puertos 1 a 30 activados en los switches de clúster C1 y C2 de Nexus 3132Q-V. mediante una configuración compatible con RCF `NX3232C_RCF_v1.0_24p10g_26p100g.txt`:

[listing]
----
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. Active el segundo puerto del clúster, e4e, en cada nodo:
+
`network port modify`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestra el segundo puerto e4e del clúster que se está poniendo en marcha en cada nodo:

[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin true
cluster::*> network port modify -node n2 -port e4e -up-admin true
----
====
. Para cada nodo, revierte todos los LIF de interconexión de clúster migrados: `network interface revert`
+
.Muestra el ejemplo
[%collapsible]
====
En el ejemplo siguiente se muestran los LIF migrados que se han revertido a sus puertos principales.

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. Verifique que todos los puertos de interconexión de clúster ahora se reviertan a sus puertos raíz:
+
`network interface show -role cluster`

+
La `Is Home` la columna debe mostrar un valor de `true` para todos los puertos enumerados en la `Current Port` columna. Si el valor mostrado es `false`, el puerto no se ha revertido.

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. Compruebe que todos los puertos de interconexión del clúster se encuentren en la `up` provincia:
+
`network port show -role cluster`

. Muestre los números de puerto del switch del clúster a través de los cuales cada puerto del clúster está conectado a cada nodo: `network device-discovery show`
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1          /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    C2                  Ethernet1/7      N3K-C3232C
n2          /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    C2                  Ethernet1/8      N3K-C3232C
----
====
. Mostrar switches de clúster detectados y supervisados:
+
`system cluster-switch show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.101      NX3232CV
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP

C2                          cluster-network     10.10.1.102      NX3232CV
Serial Number: FOX000002
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP 2 entries were displayed.
----
====
. Compruebe que la detección del clúster sin switches ha cambiado la opción de clúster sin switches a deshabilitado:
+
`network options switchless-cluster show`

. Hacer ping a las interfaces remotas del clúster y realizar una comprobación del servidor RPC:
+
`cluster ping-cluster -node _node-name_`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1 Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
====
. Habilite la función de recogida de registro de supervisión del estado del switch para recopilar archivos de registro relacionados con el switch:
+
`system cluster-switch log setup-password`

+
`system cluster-switch log enable-collection`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> system cluster-switch log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
C1
C2

cluster::*> system cluster-switch log setup-password

Enter the switch name: C1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log setup-password

Enter the switch name: C2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster::*>
----
====
+
[NOTE]
====
Si alguno de estos comandos devuelve un error, póngase en contacto con el soporte de NetApp.

====
. Si ha suprimido la creación automática de casos, vuelva a habilitarla invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


