---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Antes de configurar los switches Cisco Nexus 3232c, revise una descripción general del proceso y la nomenclatura. 
---
= Requisitos de migración
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Si tiene un clúster sin conmutador de dos nodos, puede migrar a un clúster conmutado de dos nodos que incluya conmutadores de red de clúster Cisco Nexus 3232C. Este es un procedimiento que no produce interrupciones.

.Antes de empezar
Verifique las siguientes instalaciones y conexiones:

* Hay puertos disponibles para conexiones de nodos.  Los conmutadores del clúster utilizan los puertos Inter-Switch Link (ISL) e1/31-32.
* Dispones de los cables adecuados para las conexiones del clúster:
+
** Los nodos con conexiones de clúster de 10 GbE requieren módulos ópticos QSFP con cables de fibra de ruptura o cables de cobre de ruptura QSFP a SFP+.
** Los nodos con conexiones de clúster 40/100 GbE requieren módulos ópticos QSFP/QSFP28 compatibles con cables de fibra o cables de conexión directa de cobre QSFP/QSFP28.
** Los conmutadores del clúster requieren el cableado ISL apropiado:
+
*** 2 cables QSFP28 de fibra o cobre de conexión directa.




* Las configuraciones están correctamente establecidas y funcionando.
+
Los dos nodos deben estar conectados y funcionando en una configuración de clúster sin conmutador de dos nodos.

* Todos los puertos del clúster están en estado *activo*.
* Se admiten los switches de clúster Cisco Nexus 3232C.
* La configuración de red del clúster existente tiene lo siguiente:
+
** Una infraestructura de clúster Nexus 3232C redundante y totalmente funcional en ambos switches
** Las últimas versiones de RCF y NX-OS en sus switches
** Conectividad de gestión en ambos switches
** Acceso por consola a ambos interruptores
** Todas las interfaces lógicas del clúster (LIF) en estado *activo* sin haber sido migradas.
** Personalización inicial del interruptor
** Todos los puertos ISL están habilitados y cableados.




.Acerca de los ejemplos utilizados
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Conmutadores de clúster Nexus 3232C, *C1* y *C2*.
* Los nodos son *n1* y *n2*.


Los ejemplos de este procedimiento utilizan dos nodos, cada uno de los cuales utiliza dos puertos de interconexión de clúster de 40 GbE *e4a* y *e4e*.  Ellink:https://hwu.netapp.com/["_Universo del Hardware_"^] Contiene detalles sobre los puertos del clúster en sus plataformas.

* *n1_clus1* es la primera interfaz lógica de clúster (LIF) que se conectará al conmutador de clúster *C1* para el nodo *n1*.
* *n1_clus2* es el primer LIF de clúster que se conectará al conmutador de clúster *C2* para el nodo *n1*.
* *n2_clus1* es el primer LIF de clúster que se conectará al conmutador de clúster *C1* para el nodo *n2*.
* *n2_clus2* es el segundo LIF de clúster que se conectará al conmutador de clúster *C2* para el nodo *n2*.
* El número de puertos 10 GbE y 40/100 GbE se define en los archivos de configuración de referencia (RCF) disponibles en el https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Descarga del archivo de configuración de referencia del switch de red en clúster de Cisco"^] página.


[NOTE]
====
El procedimiento requiere el uso de comandos ONTAP y comandos de switches Cisco Nexus serie 3000; se utilizan comandos ONTAP a menos que se indique lo contrario.

====
.¿Que sigue?
link:migrate-from-switchless-prepare-to-migrate.html["Prepárate para la migración"].
