---
permalink: switch-cisco-3232c/replace-cluster-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3232c, cluster switch 
summary: Puede reemplazar sin interrupciones un switch Cisco Nexus 3232C defectuoso en un clúster realizando una secuencia específica de tareas. 
---
= Reemplazar un switch de clúster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos pasos para reemplazar un switch Cisco Nexus 3232C defectuoso en un clúster. Este es un procedimiento que no produce interrupciones.



== Requisitos de revisión

.Lo que necesitarás
Asegúrese de que la configuración de clúster y red existente tenga las siguientes características:

* La infraestructura del clúster Nexus 3232C es redundante y completamente funcional en ambos switches.
+
La página de switches Ethernet de Cisco tiene las últimas versiones de RCF y NX-OS para sus switches.

* Todos los puertos del clúster deben estar en estado *activo*.
* Debe existir conectividad de gestión en ambos conmutadores.
* Todas las interfaces lógicas del clúster (LIF) están en estado *activo* y no se migran.


El switch de reemplazo Cisco Nexus 3232C tiene las siguientes características:

* La conectividad de la red de gestión funciona correctamente.
* El acceso a la consola para el interruptor de repuesto ya está habilitado.
* La imagen del sistema operativo RCF y NX-OS apropiada se carga en el switch.
* La personalización inicial del switch está completa.


.Para más información
Véase lo siguiente:

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]
* link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"^]




== Habilitar el registro en la consola

NetApp recomienda encarecidamente que habilite el registro de consola en los dispositivos que esté utilizando y que realice las siguientes acciones al reemplazar su switch:

* Deje activado el AutoSupport durante el mantenimiento.
* Active un AutoSupport de mantenimiento antes y después del mantenimiento para deshabilitar la creación de casos durante la duración del mismo.  Consulte este artículo de la base de conocimientos.link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: Cómo suprimir la creación automática de casos durante las ventanas de mantenimiento programadas"^] Para obtener más detalles.
* Habilite el registro de sesión para cualquier sesión de la CLI.  Para obtener instrucciones sobre cómo habilitar el registro de sesiones, consulte la sección "Registro de salida de sesión" en este artículo de la base de conocimientos.link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Cómo configurar PuTTY para una conectividad óptima a los sistemas ONTAP"^] .




== Reemplace el interruptor

.Acerca de esta tarea
Este procedimiento de sustitución describe el siguiente escenario:

* El clúster inicialmente tiene cuatro nodos conectados a dos conmutadores de clúster Nexus 3232C, CL1 y CL2.
* Planea reemplazar el conmutador de clúster CL2 con C2 (pasos 1 a 21):
+
** En cada nodo, migre las LIF del clúster conectadas al conmutador de clúster CL2 a los puertos del clúster conectados al conmutador de clúster CL1.
** Desconecta el cableado de todos los puertos del conmutador de clúster CL2 y vuelve a conectar el cableado a los mismos puertos del conmutador de clúster de reemplazo C2.
** Se revierten las LIF del clúster migrado en cada nodo.




.Acerca de los ejemplos
Este procedimiento de reemplazo sustituye el segundo conmutador de clúster Nexus 3232C CL2 por el nuevo conmutador 3232C C2.

Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los cuatro nodos son n1, n2, n3 y n4.
* n1_clus1 es la primera interfaz lógica de clúster (LIF) conectada al conmutador de clúster C1 para el nodo n1.
* n1_clus2 es el primer LIF de clúster conectado al conmutador de clúster CL2 o C2 para el nodo n1.
* n1_clus3 es la segunda LIF conectada al conmutador de clúster C2 para el nodo n1.
* n1_clus4 es la segunda LIF conectada al conmutador de clúster CL1, para el nodo n1.


El número de puertos 10 GbE y 40/100 GbE se define en los archivos de configuración de referencia (RCF) disponibles enlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Descarga del archivo de configuración de referencia del switch de red en clúster de Cisco"^] .

Los ejemplos de este procedimiento de reemplazo utilizan cuatro nodos.  Dos de los nodos utilizan cuatro puertos de interconexión de clúster de 10 GB: e0a, e0b, e0c y e0d.  Los otros dos nodos utilizan dos puertos de interconexión de clúster de 40 GB: e4a y e4e.  Ver ellink:https://hwu.netapp.com["Hardware Universe"^] para verificar los puertos de clúster correctos para su plataforma.



=== Paso 1: Visualizar y migrar los puertos del clúster al switch

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ es la duración de la ventana de mantenimiento en horas.

+
[NOTE]
====
El mensaje de AutoSupport notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante la ventana de mantenimiento.

====
. Muestra información sobre los dispositivos de tu configuración:
+
`network device-discovery show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface         Platform
----------- ------ ------------------- ----------------  ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1/1    N3K-C3232C
            e0b    CL2                 Ethernet1/1/1    N3K-C3232C
            e0c    CL2                 Ethernet1/1/2    N3K-C3232C
            e0d    CL1                 Ethernet1/1/2    N3K-C3232C

n2         /cdp
            e0a    CL1                 Ethernet1/1/3    N3K-C3232C
            e0b    CL2                 Ethernet1/1/3    N3K-C3232C
            e0c    CL2                 Ethernet1/1/4    N3K-C3232C
            e0d    CL1                 Ethernet1/1/4    N3K-C3232C

n3         /cdp
            e4a    CL1                 Ethernet1/7      N3K-C3232C
            e4e    CL2                 Ethernet1/7      N3K-C3232C

n4         /cdp
            e4a    CL1                 Ethernet1/8      N3K-C3232C
            e4e    CL2                 Ethernet1/8      N3K-C3232C
----
====
. Determinar el estado administrativo u operativo de cada interfaz de clúster.
+
.. Mostrar los atributos del puerto de red:
+
`network port show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
(network port show)
Node: n1
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- ------------
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- ------------
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
----
====
.. Mostrar información sobre las interfaces lógicas (LIF):
+
`network interface show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
             Logical    Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port   Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e0a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e0e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e0a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e0e     true
----
====
.. Mostrar los conmutadores de clúster detectados:
+
`system cluster-switch show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo de salida muestra los conmutadores del clúster:

[listing, subs="+quotes"]
----
cluster::> *system cluster-switch show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                         cluster-network    10.10.1.101      NX3232C
        Serial Number: FOX000001
         Is Monitored: true
               Reason: None
     Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
       Version Source: CDP

CL2                         cluster-network    10.10.1.102      NX3232C
        Serial Number: FOX000002
         Is Monitored: true
               Reason: None
     Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
       Version Source: CDP
----
====


. Verifique que el RCF y la imagen apropiados estén instalados en el nuevo switch Nexus 3232C y realice las personalizaciones necesarias del sitio.
+
.. Visite el sitio de soporte de NetApp .
+
http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. Vaya a la página *Conmutadores Ethernet de Cisco * y observe las versiones de software requeridas en la tabla.
+
https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco"^]

.. Descargue la versión adecuada del RCF.
.. Haz clic en *CONTINUAR* en la página *Descripción*, acepta el acuerdo de licencia y luego navega a la página *Descarga*.
.. Descargue la versión correcta del software de imagen desde la página *Descarga del archivo de configuración de referencia del switch de red de administración y clúster de Cisco*.
+
link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Descarga del archivo de configuración de referencia del switch de red de administración y clúster de Cisco"^]



. Migrar las LIF del clúster a los puertos de nodo físico conectados al switch de reemplazo C2:
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _node-name_ -destination-node _node-name_ -destination-port _port-name_`

+
.Mostrar ejemplo
[%collapsible]
====
Debe migrar todas las LIF del clúster individualmente, como se muestra en el siguiente ejemplo:

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 -destination-
node n1 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 -destination-
node n1 -destination-port e0d*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 -destination-
node n2 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 -destination-
node n2 -destination-port e0d*
cluster::*> *network interface migrate -vserver Cluster -lif n3_clus2 -source-node n3 -destination-
node n3 -destination-port e4a*
cluster::*> *network interface migrate -vserver Cluster -lif n4_clus2 -source-node n4 -destination-
node n4 -destination-port e4a*
----
====
. Verifique el estado de los puertos del clúster y sus designaciones de origen:
+
`network interface show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4a     false
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4a     false
----
====
. Desactive los puertos de interconexión del clúster que están conectados físicamente al switch original CL2:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos de interconexión del clúster están desactivados en todos los nodos:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin false*
cluster::*> *network port modify -node n1 -port e0c -up-admin false*
cluster::*> *network port modify -node n2 -port e0b -up-admin false*
cluster::*> *network port modify -node n2 -port e0c -up-admin false*
cluster::*> *network port modify -node n3 -port e4e -up-admin false*
cluster::*> *network port modify -node n4 -port e4e -up-admin false*
----
====
. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none
.
.
n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
.
.
n3
.
.
.n4
.
.
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e0a    10.10.0.1
Cluster n1_clus2 n1        e0b    10.10.0.2
Cluster n1_clus3 n1        e0c    10.10.0.3
Cluster n1_clus4 n1        e0d    10.10.0.4
Cluster n2_clus1 n2        e0a    10.10.0.5
Cluster n2_clus2 n2        e0b    10.10.0.6
Cluster n2_clus3 n2        e0c    10.10.0.7
Cluster n2_clus4 n2        e0d    10.10.0.8
Cluster n3_clus1 n4        e0a    10.10.0.9
Cluster n3_clus2 n3        e0e    10.10.0.10
Cluster n4_clus1 n4        e0a    10.10.0.11
Cluster n4_clus2 n4        e0e    10.10.0.12
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11
10.10.0.12 Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12
Larger than PMTU communication succeeds on 32 path(s) RPC status:
8 paths up, 0 paths down (tcp check)
8 paths up, 0 paths down (udp check)
----
--
====


=== Paso 2: Migrar los ISL para cambiar CL1 y C2

. Desactive los puertos 1/31 y 1/32 en el conmutador de clúster CL1.
+
Para obtener más información sobre los comandos de Cisco , consulte las guías que se enumeran en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/31-32*
(CL1)(config-if-range)# *shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Retire todos los cables conectados al conmutador de clúster CL2 y vuelva a conectarlos al conmutador de reemplazo C2 para todos los nodos.
. Retire los cables de enlace entre conmutadores (ISL) de los puertos e1/31 y e1/32 del conmutador de clúster CL2 y vuelva a conectarlos a los mismos puertos del conmutador de reemplazo C2.
. Habilite los puertos ISL 1/31 y 1/32 en el conmutador de clúster CL1.
+
Para obtener más información sobre los comandos de Cisco , consulte las guías que se enumeran en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/31-32*
(CL1)(config-if-range)# *no shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Verifique que los ISL estén activos en CL1.
+
Para obtener más información sobre los comandos de Cisco , consulte las guías que se enumeran en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
Los puertos Eth1/31 y Eth1/32 deberían indicar `(P)` , lo que significa que los puertos ISL están activos en el canal de puertos:

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
CL1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Verifique que los ISL estén activos en el conmutador de clúster C2.
+
Para obtener más información sobre los comandos de Cisco , consulte las guías que se enumeran en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
Los puertos Eth1/31 y Eth1/32 deben indicar (P), lo que significa que ambos puertos ISL están activos en el canal de puerto.

[listing, subs="+quotes"]
----
C2# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. En todos los nodos, active todos los puertos de interconexión del clúster conectados al switch de reemplazo C2:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin true*
cluster::*> *network port modify -node n1 -port e0c -up-admin true*
cluster::*> *network port modify -node n2 -port e0b -up-admin true*
cluster::*> *network port modify -node n2 -port e0c -up-admin true*
cluster::*> *network port modify -node n3 -port e4e -up-admin true*
cluster::*> *network port modify -node n4 -port e4e -up-admin true*
----
====




=== Paso 3: Restablezca todos los LIF a los puertos asignados originalmente.

. Revertir todas las LIF de interconexión de clúster migradas en todos los nodos:
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.Mostrar ejemplo
[%collapsible]
====
Debe revertir individualmente todas las LIF de interconexión del clúster como se muestra en el siguiente ejemplo:

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver cluster -lif n1_clus3*
cluster::*> *network interface revert -vserver cluster -lif n2_clus2*
cluster::*> *network interface revert -vserver cluster -lif n2_clus3*
Cluster::*> *network interface revert -vserver cluster -lif n3_clus2*
Cluster::*> *network interface revert -vserver cluster -lif n4_clus2*
----
====
. Verifique que los puertos de interconexión del clúster hayan vuelto a su estado original:
+
`network interface show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que todas las LIF se han revertido correctamente porque los puertos enumerados en la sección `Current Port` La columna tiene un estado de `true` en el `Is Home` columna.  Si un puerto tiene un valor de `false` , el LIF no se ha revertido.

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
             n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
             n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
             n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
             n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
             n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
             n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
             n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
             n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
             n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
             n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
             n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
             n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
----
====
. Verifique que los puertos del clúster estén conectados:
+
`network port show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
 --------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
----
====
. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none
.
.
n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
.
.
n3
.
.
.n4
.
.
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e0a    10.10.0.1
Cluster n1_clus2 n1        e0b    10.10.0.2
Cluster n1_clus3 n1        e0c    10.10.0.3
Cluster n1_clus4 n1        e0d    10.10.0.4
Cluster n2_clus1 n2        e0a    10.10.0.5
Cluster n2_clus2 n2        e0b    10.10.0.6
Cluster n2_clus3 n2        e0c    10.10.0.7
Cluster n2_clus4 n2        e0d    10.10.0.8
Cluster n3_clus1 n4        e0a    10.10.0.9
Cluster n3_clus2 n3        e0e    10.10.0.10
Cluster n4_clus1 n4        e0a    10.10.0.11
Cluster n4_clus2 n4        e0e    10.10.0.12
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11
10.10.0.12 Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12
Larger than PMTU communication succeeds on 32 path(s) RPC status:
8 paths up, 0 paths down (tcp check)
8 paths up, 0 paths down (udp check)
----
--
====


=== Paso 4: Verifique que todos los puertos y LIF se hayan migrado correctamente.

. Para visualizar la información sobre los dispositivos de su configuración, introduzca los siguientes comandos:
+
Puedes ejecutar los siguientes comandos en cualquier orden:

+
** `network device-discovery show`
** `network port show -role cluster`
** `network interface show -role cluster`
** `system cluster-switch show`


+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    C1                 Ethernet1/1/1    N3K-C3232C
            e0b    C2                 Ethernet1/1/1    N3K-C3232C
            e0c    C2                 Ethernet1/1/2    N3K-C3232C
            e0d    C1                 Ethernet1/1/2    N3K-C3232C
n2         /cdp
            e0a    C1                 Ethernet1/1/3    N3K-C3232C
            e0b    C2                 Ethernet1/1/3    N3K-C3232C
            e0c    C2                 Ethernet1/1/4    N3K-C3232C
            e0d    C1                 Ethernet1/1/4    N3K-C3232C
n3         /cdp
            e4a    C1                 Ethernet1/7      N3K-C3232C
            e4e    C2                 Ethernet1/7      N3K-C3232C

n4         /cdp
            e4a    C1                 Ethernet1/8      N3K-C3232C
            e4e    C2                 Ethernet1/8      N3K-C3232C

cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

cluster::*> *network interface show -role cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            nm1_clus1  up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true

cluster::*> *system cluster-switch show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                          cluster-network   10.10.1.101      NX3232C
             Serial Number: FOX000001
              Is Monitored: true
                    Reason: None
          Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
            Version Source: CDP
CL2                          cluster-network   10.10.1.102      NX3232C
             Serial Number: FOX000002
              Is Monitored: true
                    Reason: None
          Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
            Version Source: CDP

C2                          cluster-network    10.10.1.103      NX3232C
             Serial Number: FOX000003
              Is Monitored: true
                    Reason: None
          Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
            Version Source: CDP 3 entries were displayed.
----
====
. Elimine el conmutador de clúster CL2 reemplazado si no se ha eliminado automáticamente:
+
`system cluster-switch delete -device cluster-switch-name`

. Verifique que se estén monitoreando los conmutadores de clúster adecuados:
+
`system cluster-switch show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo se monitorizan los conmutadores del clúster porque `Is Monitored` El estado es `true` .

[listing, subs="+quotes"]
----
cluster::> *system cluster-switch show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                         cluster-network    10.10.1.101      NX3232C
            Serial Number: FOX000001
             Is Monitored: true
                   Reason: None
         Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
           Version Source: CDP

C2                          cluster-network    10.10.1.103      NX3232C
            Serial Number: FOX000002
             Is Monitored: true
                   Reason: None
         Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
           Version Source: CDP
----
====
. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.¿Que sigue?
Después de haber reemplazado el interruptor, puedeslink:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"] .
