---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: Si desea documentar las plataformas compatibles, debe completar la hoja de trabajo de cableado en blanco utilizando como guía la hoja de trabajo de cableado de muestra completada.  Cada switch se puede configurar como un único puerto 100GbE, 40GbE o 4 puertos 10GbE. 
---
= Hoja de trabajo completa de cableado de Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea documentar las plataformas compatibles, descargue un PDF de esta página y complete la hoja de trabajo de cableado.

La hoja de cálculo de cableado de muestra proporciona ejemplos de asignaciones de puertos recomendadas desde los conmutadores a los controladores.  La hoja de trabajo en blanco proporciona una plantilla que puede utilizar para configurar su clúster.

Cada switch se puede configurar como un único puerto 100GbE, 40GbE o 4 puertos 10GbE.



== Ejemplo de hoja de trabajo de cableado

La definición de puerto de muestra en cada par de conmutadores es la siguiente:

[cols="1, 1, 1, 1"]
|===
2+| Interruptor de clúster A 2+| Interruptor de clúster B 


| Puerto de conmutación | Uso de nodos y puertos | Puerto de conmutación | Uso de nodos y puertos 


 a| 
1
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
1
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
2
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
2
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
3
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
3
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
4
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
4
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
5
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
5
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
6
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
6
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
7
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
7
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
8
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
8
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
9
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
9
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
10
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
10
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
11
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
11
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
12
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
12
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
13
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
13
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
14
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
14
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
15
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
15
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
16
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
16
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
17
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
17
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
18
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
18
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
19
 a| 
Nodo 19 de 40G/100GbE
 a| 
19
 a| 
Nodo 19 de 40G/100GbE



 a| 
20
 a| 
Nodo 20 de 40G/100GbE
 a| 
20
 a| 
Nodo 20 de 40G/100GbE



 a| 
21
 a| 
Nodo 21 de 40G/100GbE
 a| 
21
 a| 
Nodo 21 de 40G/100GbE



 a| 
22
 a| 
Nodo 22 de 40G/100GbE
 a| 
22
 a| 
Nodo 22 de 40G/100GbE



 a| 
23
 a| 
Nodo 23 de 40G/100GbE
 a| 
23
 a| 
Nodo 23 de 40G/100GbE



 a| 
24
 a| 
Nodo 24 de 40G/100GbE
 a| 
24
 a| 
Nodo 24 de 40G/100GbE



 a| 
25 a 30
 a| 
Reservado
 a| 
25 a 30
 a| 
Reservado



 a| 
31
 a| 
ISL 100GbE al puerto 31 del switch B
 a| 
31
 a| 
ISL 100GbE al puerto 31 del switch A



 a| 
32
 a| 
ISL 100GbE al puerto 32 del switch B
 a| 
32
 a| 
ISL de 100 GbE al puerto 32 del conmutador A

|===


== Hoja de trabajo de cableado en blanco

Puede utilizar la hoja de trabajo de cableado en blanco para documentar las plataformas que se admiten como nodos en un clúster.  La sección _Conexiones de clúster admitidas_ de https://hwu.netapp.com["Hardware Universe"^] Define los puertos del clúster utilizados por la plataforma.

[cols="1, 1, 1, 1"]
|===
2+| Interruptor de clúster A 2+| Interruptor de clúster B 


| Puerto de conmutación | Uso de nodos/puertos | Puerto de conmutación | Uso de nodos/puertos 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25 a 30
 a| 
Reservado
 a| 
25 a 30
 a| 
Reservado



 a| 
31
 a| 
ISL 100GbE al puerto 31 del switch B
 a| 
31
 a| 
ISL 100GbE al puerto 31 del switch A



 a| 
32
 a| 
ISL 100GbE al puerto 32 del switch B
 a| 
32
 a| 
ISL de 100 GbE al puerto 32 del conmutador A

|===
.¿Qué sigue?
Después de haber completado tus hojas de trabajo de cableado, tú link:install-switch-3232c.html["instalar el interruptor"].
