---
permalink: switch-cisco-3232c/upgrade-3232c-storage-switches.html 
sidebar: sidebar 
keywords: upgrade, cisco nexus, 3232c storage switch 
summary: 'El software Cisco NX-OS y los archivos de configuración de referencia (RCF) se pueden actualizar en los switches de almacenamiento Cisco Nexus 3232C.' 
---
= Actualizar un switch de almacenamiento Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos pasos para actualizar el software Cisco NX-OS y los archivos de configuración de referencia (RCF) en los switches Cisco Nexus 3232C.



== Requisitos de revisión

.Antes de empezar
Asegúrese de que se cumplan las siguientes condiciones antes de actualizar el software NX-OS y los RCF en el switch de almacenamiento:

* El switch funciona correctamente (no debería haber errores en los registros ni problemas similares).
* Si solo va a instalar NX-OS y a mantener su versión actual de RCF, habrá comprobado o configurado las variables de arranque deseadas en el RCF para que reflejen las imágenes de arranque deseadas.
+
Si necesita cambiar las variables de arranque para que reflejen las imágenes de arranque actuales, debe hacerlo antes de volver a aplicar el RCF para que se instancie la versión correcta en futuros reinicios.

* Usted ha consultado el software y las guías de actualización correspondientes disponibles en el sitio web. http://www.cisco.com/en/US/products/ps9670/prod_installation_guides_list.html["Switches Cisco Nexus serie 3000"^] Consulte la página para obtener la documentación completa sobre los procedimientos de actualización y degradación del almacenamiento de Cisco .
* El número de puertos 10 GbE y 40/100 GbE se define en los archivos de configuración de referencia (RCF) disponibles en el https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco®"^] página.




== Reemplace el interruptor

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los nombres de los dos conmutadores de almacenamiento son S1 y S2.
* Los nodos son nodo1 y nodo2.


Los ejemplos de este procedimiento utilizan dos nodos: el nodo 1 con dos puertos de almacenamiento y el nodo 2 con dos puertos de almacenamiento. Ver ellink:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para verificar los puertos de almacenamiento correctos en sus plataformas. Ver link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"^] para obtener más información sobre los requisitos de instalación del conmutador.


NOTE: El procedimiento requiere el uso de comandos ONTAP y comandos de switches Cisco Nexus serie 3000; se utilizan comandos ONTAP a menos que se indique lo contrario.  Los resultados del comando pueden variar dependiendo de las diferentes versiones de ONTAP.



=== Paso 1: Compruebe el estado de salud de los conmutadores y puertos.

. Si AutoSupport está habilitado, suprima la creación automática de casos mediante la invocación de un mensaje de AutoSupport :
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ es la duración de la ventana de mantenimiento en horas.

+

NOTE: El mensaje de AutoSupport notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante la ventana de mantenimiento.

. Compruebe que los conmutadores de almacenamiento estén disponibles:
+
`system switch ethernet show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

S2
                            storage-network    172.17.227.6     NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
====
. Verifique que los puertos del nodo estén en buen estado y operativos:
+
`storage port show -port-type ENET`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. Compruebe que no haya problemas con el conmutador de almacenamiento o el cableado:
+
`system health alert show -instance`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====




=== Paso 2: Copie el RCF al switch Cisco S2

. Copie el RCF del switch S2 a la memoria flash de arranque del switch utilizando uno de los siguientes protocolos de transferencia: FTP, HTTP, TFTP, SFTP o SCP.
+
Para obtener más información sobre los comandos de Cisco , consulte la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo se utiliza HTTP para copiar un RCF a la memoria flash de arranque del switch S2:

[listing, subs="+quotes"]
----
S2# *copy http://172.16.10.1//cfg/Nexus_3232C_RCF_v1.6-Storage.txt bootflash: vrf management*
% Total    % Received % Xferd  Average  Speed   Time    Time     Time                          Current
                               Dload    Upload  Total   Spent    Left                          Speed
  100        3254       100    3254     0       0       8175     0 --:--:-- --:--:-- --:--:-   8301
Copy complete, now saving to disk (please wait)...
Copy complete.
S2#
----
====
. Aplique el RCF descargado previamente a la memoria flash de arranque:
+
`copy bootflash:`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra el archivo RCF. `Nexus_3232C_RCF_v1.6-Storage.txt` Se está instalando en el switch S2:

[listing, subs="+quotes"]
----
S2# *copy Nexus_3232C_RCF_v1.6-Storage.txt running-config echo-commands*
----
====
. Verifique que el archivo RCF sea la versión más reciente correcta:
+
`show running-config`

+
Al comprobar la salida para verificar que tiene el RCF correcto, asegúrese de que la siguiente información sea correcta:

+
** El estandarte de RCF
** Configuración del nodo y del puerto
** Personalizaciones
+
El resultado varía según la configuración de su sitio.  Compruebe la configuración del puerto y consulte las notas de la versión para conocer los cambios específicos del RCF que haya instalado.

+
[NOTE]
====
En la salida del banner del `show banner motd` Para ejecutar este comando, debe leer y seguir las instrucciones de la sección *NOTAS IMPORTANTES* para garantizar la configuración y el funcionamiento correctos del conmutador.

====
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
S2# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Cisco Nexus 3232C
* Filename : Nexus_3232C_RCF_v1.6-Storage.txt
* Date     : Oct-20-2020
* Version  : v1.6
*
* Port Usage : Storage configuration
* Ports  1-32: Controller and Shelf Storage Ports
* Ports 33-34: Disabled
*
* IMPORTANT NOTES*
* - This RCF utilizes QoS and requires TCAM re-configuration, requiring RCF
*   to be loaded twice with the Storage Switch rebooted in between.
*
* - Perform the following 4 steps to ensure proper RCF installation:
*
*   (1) Apply RCF first time, expect following messages:
*       - Please save config and reload the system...
*       - Edge port type (portfast) should only be enabled on ports...
*       - TCAM region is not configured for feature QoS class IPv4 ingress...
*
*   (2) Save running-configuration and reboot Cluster Switch
*
*   (3) After reboot, apply same RCF second time and expect following messages:
*       - % Invalid command at '^' marker
*       - Syntax error while parsing...
*
*   (4) Save running-configuration again
******************************************************************************
S2#
----
====
+

NOTE: Al aplicar RCF por primera vez, el mensaje *ERROR: Failed to write VSH commands* es normal y puede ignorarse.



. Después de verificar que las versiones del software y la configuración del interruptor sean correctas, copie el `running-config` archivo al `startup-config` archivo en el switch S2.
+
Para obtener más información sobre los comandos de Cisco , consulte la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra el `running-config` archivo copiado correctamente al `startup-config` archivo:

[listing]
----
S2# copy running-config startup-config
[########################################] 100% Copy complete.
----
====




=== Paso 3: Copie la imagen de NX-OS al switch Cisco S2 y reinícielo.

. Copie la imagen NX-OS al switch S2.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.9.3.4.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.3.4.bin  /bootflash/nxos.9.3.4.bin
/code/nxos.9.3.4.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.

cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.9.3.4.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.3.4.img  /bootflash/n9000-epld.9.3.4.img
/code/n9000-epld.9.3.4.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. Instale la imagen del sistema para que la nueva versión se cargue la próxima vez que se reinicie el switch S2.
+
El switch se reiniciará en 10 segundos con la nueva imagen, tal como se muestra en la siguiente salida:

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *install all nxos bootflash:nxos.9.3.4.bin*
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  bootable          Impact  Install-type  Reason
------  --------  --------------  ------------  ------
     1       yes      disruptive         reset  default upgrade is not hitless


Images will be upgraded according to following table:
Module       Image                  Running-Version(pri:alt)           New-Version  Upg-Required
------  ----------  ----------------------------------------  --------------------  ------------
     1        nxos                                    9.3(3)                9.3(4)           yes
     1        bios     v08.37(01/28/2020):v08.23(09/23/2015)    v08.38(05/29/2020)            no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] *y*
input string too long
Do you want to continue with the installation (y/n)?  [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
S2#
----
====
. Guarde la configuración.
+
Para obtener más información sobre los comandos de Cisco , consulte la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referencias de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
Se le solicita que reinicie el sistema.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *copy running-config startup-config*
[########################################] 100% Copy complete.
S2# *reload*
This command will reboot the system. (y/n)?  [n] *y*
----
====
. Confirme que el número de versión de la nueva versión de NX-OS está en el switch:
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.38
 NXOS: version 9.3(4)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]


Hardware
  cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: S2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)

Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset due to upgrade
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

S2#
----
====




=== Paso 4: Vuelva a comprobar el estado de salud de los conmutadores y puertos.

. Vuelva a comprobar que los conmutadores de almacenamiento estén disponibles después del reinicio:
+
`system switch ethernet show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

S2
                            storage-network    172.17.227.6    NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
====
. Verifique que los puertos del switch estén en buen estado y operativos después del reinicio:
+
`storage port show -port-type ENET`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. Verifique nuevamente que no haya problemas con el conmutador de almacenamiento o el cableado del clúster:
+
`system health alert show -instance`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. Repita el procedimiento para actualizar el software NX-OS y RCF en el switch S1.
. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


