---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  pdf:
    zip-level: 1
    zip-filename: ontap-systems-switches-pdfs.zip
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Cambia la documentación para sistemas de almacenamiento ONTAP
    url: "/index.html"
  - title: Notas de publicación
    entries:
    - title: Novedades para los switches
      url: "/whats-new.html"
    - title: Fin del soporte técnico
      url: "/eoa-switches.html"
  - title: Empezar
    entries:
    - title: Obtenga información sobre los conmutadores de sistemas ONTAP.
      url: "/get-started/learn-switch-concept.html"
    - title: Inicio rápido
      url: "/get-started/get-up-and-running.html"
  - title: Conmutadores de sistemas AFX
    url: "/afx/index.html"
    entries:
    - section: switch-cisco-9808
    - section: switch-cisco-9332d-gx2b
    - section: switch-cisco-9364d-gx2a
  - title: Conmutadores de clúster
    url: "/cluster/index.html"
    entries:
    - section: switch-bes-53248
    - section: switch-cisco-9336c-fx2
  - title: Conmutadores de almacenamiento
    url: "/storage/index.html"
    entries:
    - section: switch-cisco-9336c-fx2-storage
  - title: Conmutadores compartidos
    url: "/shared/index.html"
    entries:
    - section: switch-cisco-9336c-fx2-shared
      pdf-filename: switch-cisco-9336c-fx2-almacenamiento
  - title: Supervisa el estado del interruptor
    url: "/cshm/index.html"
    entries:
    - section: switch-cshm-configure
    - section: switch-cshm-monitor
    - section: switch-cshm-log-collection
  - title: Interruptores de fin de disponibilidad
    url: "/eoa/index.html"
    entries:
    - section: switch-nvidia-sn2100
    - section: switch-nvidia-sn2100-storage
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
