---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: Conozca los nuevos interruptores para sistemas FAS y AFF . 
---
= ¿Qué novedades hay para los interruptores?
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Conozca los nuevos interruptores para sistemas FAS y AFF .  Para obtener información adicional sobre el interruptor, consulte la https://hwu.netapp.com/Switch/Index["NetApp Hardware Universe"^] .



== Nuevo soporte para interruptores

[cols="25h,~,~"]
|===
| Interruptores | Descripción | Disponible a partir de 


 a| 
Conmutador Cisco de 32 puertos 400 GbE (X190300-CS-PI y X190300-PE)
 a| 
Compatibilidad con conmutadores Cisco 9332D-GX2B intra-clúster/HA/almacenamiento.
 a| 
ONTAP 9.17.1



 a| 
Conmutador Cisco de 64 puertos 400 GbE (X190310-CS-PI)
 a| 
Compatibilidad con conmutadores Cisco 9364D-GX2A intra-clúster/HA/almacenamiento.
 a| 
ONTAP 9.17.1



 a| 
Conmutador de clúster y almacenamiento Cisco Nexus 9336C-FX2-T de 12 puertos 10/25/40/100GbE (X190212-CS-PE y X190212-CS-PI)
 a| 
Admite configuraciones de clúster 10/25/40/100GbE y configuraciones de almacenamiento 100GbE (almacenamiento conectado al switch).
 a| 
ONTAP 9.10.1



 a| 
Conmutador de clúster y almacenamiento Cisco Nexus 9336C-FX2-T de 12 puertos 10/25/40/100GbE (X190212-CS-PE y X190212-CS-PI)
 a| 
Admite configuraciones de clúster 10/25/40/100GbE y configuraciones de almacenamiento 100GbE (almacenamiento conectado al switch).
 a| 
ONTAP 9.10.1



 a| 
Conmutador NVIDIA de 16 puertos 100GbE (X190006-PE y X190006-PI)
 a| 
Compatibilidad con el conmutador de interconexión de clústeres y el conmutador de almacenamiento NVIDIA SN2100, incluida la compatibilidad con configuraciones IP de MetroCluster .
 a| 
ONTAP 9.10.1



 a| 
Switch Cisco de 36 puertos 100GbE (X190200-CS-PE y X190200-CS-PI)
 a| 
Admite una infraestructura compartida (clúster, alta disponibilidad y almacenamiento conectado al switch) en el mismo par de switches Cisco Nexus 9336C-FX2, incluyendo soporte para configuraciones IP de MetroCluster .
 a| 
ONTAP 9.9.1



 a| 
Switch Cisco de 36 puertos 100GbE (X190200-CS-PE y X190200-CS-PI), (X190210-FE-PE y X190210-FE-PI)
 a| 
El switch de interconexión de clúster y el switch de almacenamiento Cisco Nexus 9336C-FX2 admiten sistemas de almacenamiento AFF y ASA , así como conectividad de datos front-end.
 a| 
ONTAP 9.8



 a| 
Conmutador Broadcom BES-53248 (X190005 y X190005R)
 a| 
El conmutador de interconexión de clúster Broadcom BES-53248 admite controladores AFF/ FAS con puertos 10/25GbE y 40/100GbE.
 a| 
ONTAP 9.8



 a| 
Switch Cisco de 36 puertos 100GbE (X190200) y switch Cisco de 32 puertos 100GbE (X190100 y X190100R)
 a| 
El switch de almacenamiento Cisco Nexus 3232C admite la conexión de estantes de unidades NVMe NS224 a sistemas de almacenamiento AFF y ASA :

* AFF A800/ AFF ASA A800
* AFF A700/ AFF ASA A700
* AFF A400/ AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8

|===