---
permalink: switch-nvidia-sn2100/cabling-considerations-sn2100-cluster.html 
sidebar: sidebar 
keywords: SN2100 cabling setup, sn2100 switches configuration, cumulus linux os 
summary: Antes de configurar su switch NVIDIA SN2100, revise la siguiente información. 
---
= Revisar las consideraciones de cableado y configuración
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de configurar su switch NVIDIA SN2100, revise las siguientes consideraciones.



== Detalles del puerto NVIDIA

|===


| *Conmutar puertos* | *Uso de puertos* 


 a| 
swp1s0-3
 a| 
4 nodos de puerto de clúster de ruptura 10GbE



 a| 
swp2s0-3
 a| 
4 nodos de puerto de clúster de ruptura de 25 GbE



 a| 
swp3-14
 a| 
nodos de puerto de clúster 40/100GbE



 a| 
swp15-16
 a| 
Puertos de enlace entre conmutadores (ISL) de 100 GbE

|===
Ver el link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] para obtener más información sobre los puertos de conmutación.



== Retrasos en la conexión con conexiones ópticas

Si experimenta retrasos de conexión superiores a cinco segundos, Cumulus Linux 5.4 y versiones posteriores incluyen soporte para conexión rápida.  Puedes configurar los enlaces utilizando el `nv set` El comando es el siguiente:

[listing, subs="+quotes"]
----
*nv set interface <interface-id> link fast-linkup on*
*nv config apply*
*reload the switchd*
----
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus-cs13:mgmt:~$ *nv set interface swp5 link fast-linkup on*
cumulus@cumulus-cs13:mgmt:~$ *nv config apply*
*switchd need to reload on this config change*

Are you sure? [y/N] *y*
applied [rev_id: 22]

Only switchd reload required
----
====


== Compatibilidad con conexiones de cobre

Para solucionar este problema, son necesarios los siguientes cambios de configuración.

[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
. Identifique el nombre de cada interfaz que utilice cables de cobre 40GbE/100GbE:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface pluggables*

Interface  Identifier     Vendor Name     Vendor PN    Vendor SN      Vendor Rev
---------  -------------  --------------  -----------  -------------  ----------
swp3       0x11 (QSFP28)  Molex           112-00576    93A2229911111  B0
swp4       0x11 (QSFP28)  Molex           112-00576    93A2229922222  B0
----
. Agrega las siguientes dos líneas a la `/etc/cumulus/switchd.conf` archivo para cada puerto (swp<n>) que utilice cables de cobre 40GbE/100GbE:
+
** `interface.swp<n>.enable_media_depended_linkup_flow=TRUE`
** `interface.swp<n>.enable_short_tuning=TRUE`
+
Por ejemplo:

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo nano /etc/cumulus/switchd.conf*
.
.
interface.swp3.enable_media_depended_linkup_flow=TRUE
interface.swp3.enable_short_tuning=TRUE
interface.swp4.enable_media_depended_linkup_flow=TRUE
interface.swp4.enable_short_tuning=TRUE
----


. Reinicia el `switchd` servicio:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo systemctl restart switchd.service*
----
. Confirma que los puertos están activos:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP              Summary
-----  --------- ----  -----  ---------- ----------------- --------
UP     swp3      100G  9216   Trunk/L2                     Master: bridge(UP)
UP     swp4      100G  9216   Trunk/L2                     Master: bridge(UP)
----


--
.Cumulus Linux 5.x
--
. Identifique el nombre de cada interfaz que utilice cables de cobre 40GbE/100GbE:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show interface --view=pluggables*

Interface  Identifier     Vendor Name     Vendor PN    Vendor SN      Vendor Rev
---------  -------------  --------------  -----------  -------------  ----------
swp3       0x11 (QSFP28)  Molex           112-00576    93A2229911111  B0
swp4       0x11 (QSFP28)  Molex           112-00576    93A2229922222  B0
----
. Configure los enlaces utilizando el `nv set` El comando es el siguiente:
+
** `nv set interface <interface-id> link fast-linkup on`
** `nv config apply`
** Recarga el `switchd` servicio
+
Por ejemplo:

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set interface swp5 link fast-linkup on*
cumulus@cumulus:mgmt:~$ *nv config apply*
switchd need to reload on this config change

Are you sure? [y/N] *y*
applied [rev_id: 22]

Only switchd reload required
----


. Confirma que los puertos están activos:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP              Summary
-----  --------- ----  -----  ---------- ----------------- --------
UP     swp3      100G  9216   Trunk/L2                     Master: bridge(UP)
UP     swp4      100G  9216   Trunk/L2                     Master: bridge(UP)
----


--
====
Consulte el artículo de la base de conocimientoslink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric_Interconnect_and_Management_Switches/NVIDIA_SN2100_switch_fails_to_connect_using_40_100GbE_copper_cable["El switch SN2100 no se conecta usando cables de cobre 40/100GbE."^] Para obtener más detalles.

En Cumulus Linux 4.4.2, las conexiones de cobre no son compatibles con los switches SN2100 con NIC X1151A, NIC X1146A o puertos 100GbE integrados. Por ejemplo:

* AFF A800 en los puertos e0a y e0b
* AFF A320 en los puertos e0g y e0h




== Módulo QSA

Al utilizar adaptadores QSFP+ (40 GbE) a SFP+ (10 GbE) o adaptadores QSFP28 (100 GbE) a SFP28 (25 GbE) (QSA), insértelos en puertos de conmutador 40 GbE/100 GbE sin conexión (swp3-swp14). No inserte el módulo QSA en un puerto que esté configurado para conexión.

Cuando se utiliza un módulo QSA para conectarse a los puertos de clúster 10GbE/25GbE en una plataforma, es posible que el enlace no se establezca.

Para resolver este problema, haga lo siguiente:

* Para 10 GbE, configure manualmente la velocidad del enlace a 10 000 y desactive la negociación automática.
* Para 25 GbE, configure manualmente la velocidad del enlace a 25000 y desactive la negociación automática.




== Configuración de la velocidad de la interfaz en los puertos de conexión.

Dependiendo del transceptor en el puerto del switch, es posible que deba configurar la velocidad en la interfaz del switch a una velocidad fija. Si utiliza puertos de conexión de 10 GbE y 25 GbE o un módulo QSA, verifique que la negociación automática esté desactivada y configure la velocidad de la interfaz en el conmutador.

[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
Por ejemplo:

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net add int swp1s3 link autoneg off && net com*
--- /etc/network/interfaces     2019-11-17 00:17:13.470687027 +0000
+++ /run/nclu/ifupdown2/interfaces.tmp  2019-11-24 00:09:19.435226258 +0000
@@ -37,21 +37,21 @@
     alias 10G Intra-Cluster Node
     link-autoneg off
     link-speed 10000  *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp1s3
iface swp1s3
     alias 10G Intra-Cluster Node
-    link-autoneg off
+    link-autoneg on
     link-speed 10000 *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp2s0
iface swp2s0
     alias 25G Intra-Cluster Node
     link-autoneg off
     link-speed 25000 *<---- port speed set*
----
Compruebe el estado de la interfaz y del puerto para verificar que la configuración se haya aplicado:

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface*

State  Name      Spd    MTU    Mode        LLDP             Summary
-----  --------  -----  -----  ----------  ---------------  --------------------------------------
.
.
UP     swp1s0     10G   9216   Trunk/L2    cs07 (e4c)       Master: br_default(UP)
UP     swp1s1     10G   9216   Trunk/L2    cs07 (e4d)       Master: br_default(UP)
UP     swp1s2     10G   9216   Trunk/L2    cs08 (e4c)       Master: br_default(UP)
UP     swp1s3     10G   9216   Trunk/L2    cs08 (e4d)       Master: br_default(UP)
.
.
UP     swp3       40G   9216   Trunk/L2    cs03 (e4e)       Master: br_default(UP)
UP     swp4       40G   9216   Trunk/L2    cs04 (e4e)       Master: br_default(UP)
DN     swp5       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp6       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp7       N/A   9216   Trunk/L2                     Master: br_default(UP)
.
.
UP     swp15      100G  9216   BondMember  cs01 (swp15)     Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  cs01 (swp16)     Master: cluster_isl(UP)
.
.
----
--
.Cumulus Linux 5.x
--
Por ejemplo:

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set interface swp1s3 link auto-negotiate off*
cumulus@cumulus:mgmt:~$ *nv set interface swp1s3 link speed 10G*
cumulus@cumulus:mgmt:~$ *nv show interface swp1s3*

link                                                                                            
  auto-negotiate        off                     off                     off                   
  duplex                full                    full                    full                  
  speed                 10G                     10G                     10G                   
  fec                   auto                    auto                    auto                  
  mtu                   9216                    9216                    9216                  
[breakout]                                                                                    
  state                 up                      up                      up
----
Compruebe el estado de la interfaz y del puerto para verificar que la configuración se haya aplicado:

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show interface*

State  Name      Spd    MTU    Mode        LLDP             Summary
-----  --------  -----  -----  ----------  ---------------  --------------------------------------
.
.
UP     swp1s0     10G   9216   Trunk/L2    cs07 (e4c)       Master: br_default(UP)
UP     swp1s1     10G   9216   Trunk/L2    cs07 (e4d)       Master: br_default(UP)
UP     swp1s2     10G   9216   Trunk/L2    cs08 (e4c)       Master: br_default(UP)
UP     swp1s3     10G   9216   Trunk/L2    cs08 (e4d)       Master: br_default(UP)
.
.
UP     swp3       40G   9216   Trunk/L2    cs03 (e4e)       Master: br_default(UP)
UP     swp4       40G   9216   Trunk/L2    cs04 (e4e)       Master: br_default(UP)
DN     swp5       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp6       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp7       N/A   9216   Trunk/L2                     Master: br_default(UP)
.
.
UP     swp15      100G  9216   BondMember  cs01 (swp15)     Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  cs01 (swp16)     Master: cluster_isl(UP)
.
.
----
--
====
Ver el link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^]y el artículo de la Base de conocimientos link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"^] Para más información.

.¿Que sigue?
Después de revisar los requisitos de cableado y configuración, puedeslink:install-cable-shelves-sn2100-cluster.html["Cablee los estantes NS224 como almacenamiento conectado al interruptor."] .
