---
permalink: switch-nvidia-sn2100/components-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Si desea crear clústeres ONTAP con más de dos nodos, necesitará dos conmutadores de red de clúster compatibles.  Puede utilizar interruptores de administración adicionales, que son opcionales. 
---
= Componentes y números de pieza para los interruptores NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del switch NVIDIA SN2100, asegúrese de revisar la lista de componentes y números de pieza del kit de gabinete y riel.



== Detalles del gabinete

Instale el conmutador NVIDIA SN2100 (X190006) en el gabinete de conmutadores dobles/simples de NVIDIA con los soportes estándar que se incluyen con el conmutador.



== Detalles del kit de rieles

La siguiente tabla enumera el número de pieza y la descripción de los kits de interruptores y rieles SN2100:

[cols="1,2"]
|===
| Número de pieza | Descripción 


 a| 
X190006-PE
 a| 
Conmutador de clúster, NVIDIA SN2100, 16PT 100GbE, PTSX



 a| 
X190006-PI
 a| 
Conmutador de clúster, NVIDIA SN2100, 16PT 100GbE, PSIN



 a| 
X-MTEF-KIT-D
 a| 
Kit de rieles, interruptor doble NVIDIA lado a lado



 a| 
X-MTEF-KIT-E
 a| 
Kit de rieles, interruptor único NVIDIA de profundidad corta

|===

NOTE: Consulte la documentación de NVIDIA para obtener más detalles sobre https://docs.nvidia.com/networking/display/sn2000pub/Installation["Instalación del kit de interruptor y riel SN2100"^] .

.¿Que sigue?
Una vez que haya confirmado sus componentes y números de pieza, puede revisar el link:required-documentation-sn2100-cluster.html["documentación requerida"].
