---
permalink: switch-nvidia-sn2100/components-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Si desea crear clústeres de ONTAP con más de dos nodos, necesita dos switches de red de clúster compatibles. Puede usar switches de gestión adicionales, que son opcionales. 
---
= Componentes y números de pieza para conmutadores NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del switch NVIDIA SN2100, asegúrese de revisar la lista de componentes y números de pieza para el kit de armarios y rieles.



== Detalles del armario

Se instala el switch NVIDIA SN2100 (X190006) en el armario de conmutación doble/simple NVIDIA con los soportes estándar incluidos con el switch.



== Detalles del kit de rieles

La tabla siguiente muestra el número de pieza y la descripción de los interruptores SN2100 y los kits de raíles:

[cols="1,2"]
|===
| Número de pieza | Descripción 


 a| 
X190006-PE
 a| 
Cluster Switch, NVIDIA SN2100, 16PT 100GbE, PTSX



 a| 
X190006-PI
 a| 
Cluster Switch, NVIDIA SN2100, 16PT 100GbE, PSIN



 a| 
X-MTEF-KIT-D
 a| 
Kit de rieles, conmutador doble NVIDIA lado a lado



 a| 
X-MTEF-KIT-E
 a| 
Kit de rieles, profundidad corta de un único conmutador NVIDIA

|===

NOTE: Consulte la documentación de NVIDIA para obtener más información acerca de https://["Instalación del kit de rieles y interruptor SN2100"^].
