---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Para la instalación y el mantenimiento del conmutador NVIDIA SN2100, asegúrese de revisar todos los requisitos y la documentación recomendada. 
---
= Requisitos de configuración para los switches NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del conmutador NVIDIA SN2100, asegúrese de revisar todos los requisitos de configuración.



== Requisitos de instalación

Si desea crear clústeres de ONTAP con más de dos nodos, necesita dos switches de red de clúster compatibles. Puede usar switches de gestión adicionales, que son opcionales.

Se instala el switch NVIDIA SN2100 (X190006) en el armario de conmutación doble/simple NVIDIA con los soportes estándar incluidos con el switch.

Para conocer las directrices de cableado, consulte link:cabling-considerations-sn2100-cluster.html["Revise las consideraciones sobre el cableado y la configuración"].



== Soporte de ONTAP y Linux

El conmutador NVIDIA SN2100 es un conmutador 10/25/40/100GbE que ejecuta Cumulus Linux. El conmutador admite lo siguiente:

* ONTAP 9.10.1P3 y versiones posteriores
+
El switch de SN2100 proporciona aplicaciones de clúster y almacenamiento en ONTAP 9.10.1P3 y versiones posteriores en diferentes pares de switches.

* Versiones de sistema operativo Cumulus Linux (CL)
+
** Las versiones específicas de CL están cualificadas y son compatibles con NetApp. Para obtener información de compatibilidad actual, consulte la link:https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Información sobre switches Ethernet de NVIDIA"^] página o el link:https://hwu.netapp.com["Hardware Universe de NetApp"^].
** Para descargar el software SN2100 Cumulus de NVIDIA, debe tener credenciales de inicio de sesión para acceder al portal de soporte empresarial de NVIDIA. Consulte el artículo de la base de conocimientos https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access["Cómo registrarse con NVIDIA para el acceso al portal de soporte empresarial"^] .




* Puede instalar Cumulus Linux cuando el conmutador esté ejecutando Cumulus Linux o ONIE.

