---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Para la instalación y el mantenimiento del conmutador NVIDIA SN2100, asegúrese de revisar todos los requisitos y la documentación recomendada. 
---
= Requisitos de configuración para los switches NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del conmutador NVIDIA SN2100, asegúrese de revisar todos los requisitos de configuración.



== Requisitos de instalación

Si desea crear clústeres de ONTAP con más de dos nodos, necesita dos switches de red de clúster compatibles. Puede usar switches de gestión adicionales, que son opcionales.

Se instala el switch NVIDIA SN2100 (X190006) en el armario de conmutación doble/simple NVIDIA con los soportes estándar incluidos con el switch.

Para conocer las directrices de cableado, consulte link:cabling-considerations-sn2100-cluster.html["Revise las consideraciones sobre el cableado y la configuración"].



== Soporte de ONTAP y Linux

El conmutador NVIDIA SN2100 es un conmutador 10/25/40/100GbE que ejecuta Cumulus Linux. El conmutador admite lo siguiente:

* ONTAP 9.10.1P3. El switch SN2100 sirve a las aplicaciones de clúster y almacenamiento de ONTAP 9.10.1P3 sobre diferentes pares de switches.
* Versión de Cumulus Linux (CL) OS. Para descargar el software SN2100 Cumulus, inicie sesión en https://["Portal de soporte empresarial de NVIDIA"^]. Tenga en cuenta que debe tener credenciales de inicio de sesión para acceder al software Cumulus. Para obtener información actual sobre compatibilidad, consulte https://["Switches Ethernet de NVIDIA"^] página de información.
* Puede instalar Cumulus Linux cuando el conmutador esté ejecutando Cumulus Linux o ONIE.

