---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Para la instalación y el mantenimiento del switch NVIDIA SN2100, asegúrese de revisar todos los requisitos y la documentación recomendada. 
---
= Requisitos de configuración para los switches NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del switch NVIDIA SN2100, asegúrese de revisar todos los requisitos de configuración.



== Requisitos de instalación

Si desea crear clústeres ONTAP con más de dos nodos, necesitará dos conmutadores de red de clúster compatibles.  Puede utilizar interruptores de administración adicionales, que son opcionales.

Instale el conmutador NVIDIA SN2100 (X190006) en el gabinete de conmutadores dobles/simples de NVIDIA con los soportes estándar que se incluyen con el conmutador.

Para obtener instrucciones sobre el cableado, consultelink:cabling-considerations-sn2100-cluster.html["Revisar las consideraciones de cableado y configuración"] .



== Soporte ONTAP y Linux

El switch NVIDIA SN2100 es un switch 10/25/40/100GbE que ejecuta Cumulus Linux.  El conmutador admite lo siguiente:

* ONTAP 9.10.1P3 y versiones posteriores
+
El switch SN2100 sirve a aplicaciones de Cluster y Almacenamiento en ONTAP 9.10.1P3 y posteriores a través de diferentes pares de switches.

* Versiones del sistema operativo Cumulus Linux (CL)
+
** NetApp califica y ofrece soporte para versiones específicas de CL.  Para obtener información actualizada sobre compatibilidad, consulte lalink:https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Información sobre los switches Ethernet de NVIDIA"^] página o lalink:https://hwu.netapp.com["NetApp Hardware Universe"^] .
** Para descargar el software SN2100 Cumulus de NVIDIA, debe tener credenciales de inicio de sesión para acceder al Portal de Soporte Empresarial de NVIDIA.  Consulte el artículo de la base de conocimientos https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access["Cómo registrarse en NVIDIA para acceder al portal de soporte empresarial"^] .




* Puedes instalar Cumulus Linux cuando el switch esté ejecutando Cumulus Linux u ONIE.


.¿Que sigue?
Después de revisar los requisitos de configuración, puede confirmar su link:components-sn2100-cluster.html["componentes y números de pieza"].
