---
permalink: switch-nvidia-sn2100/install-cumulus-mode-sn2100-cluster.html 
sidebar: sidebar 
keywords: install cumulus mode, sn2100 SN2100 switches setup, cumulus linux, cumulus mode 
summary: 'El sistema operativo Cumulus Linux (CL) se puede instalar cuando el switch ejecuta Cumulus Linux u ONIE.' 
---
= Instalar Cumulus Linux en modo Cumulus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para instalar el sistema operativo Cumulus Linux (CL) cuando el switch esté funcionando en modo Cumulus.


NOTE: El sistema operativo Cumulus Linux (CL) se puede instalar cuando el switch ejecuta Cumulus Linux u ONIE (véaselink:install-onie-mode-sn2100-cluster.html["Instalar en modo ONIE"] ).

.Antes de empezar
Asegúrese de tener lo siguiente:

* Conocimientos de Linux de nivel intermedio.
* Conocimientos básicos de edición de texto, permisos de archivos UNIX y monitorización de procesos.  Se incluyen varios editores de texto preinstalados, entre ellos: `vi` y `nano` .
* Acceso a una consola Linux o UNIX.  Si utiliza Windows, use un entorno Linux como herramienta de línea de comandos para interactuar con Cumulus Linux.
* El requisito de velocidad de transmisión está configurado en 115200 en el conmutador de consola serie para el acceso a la consola del conmutador NVIDIA SN2100, como se muestra a continuación:
+
** 115200 baudios
** 8 bits de datos
** 1 bit de parada
** paridad: ninguna
** Control de flujo: ninguno




.Acerca de esta tarea
Tenga en cuenta lo siguiente:


NOTE: Cada vez que se instala Cumulus Linux, se borra y se reconstruye toda la estructura del sistema de archivos.


CAUTION: La contraseña predeterminada para la cuenta de usuario cumulus es *cumulus*.  La primera vez que inicie sesión en Cumulus Linux, deberá cambiar esta contraseña predeterminada.  Asegúrese de actualizar cualquier script de automatización antes de instalar una nueva imagen.  Cumulus Linux proporciona opciones de línea de comandos para cambiar automáticamente la contraseña predeterminada durante el proceso de instalación.

.Pasos
[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
. Inicia sesión en el switch.
+
El primer inicio de sesión en el switch requiere el nombre de usuario/contraseña *cumulus*/*cumulus* con `sudo` privilegios.

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Comprueba la versión de Cumulus para Linux: `net show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show system*
Hostname......... cumulus
Build............ *Cumulus Linux 4.4.3*
Uptime........... 0:08:20.860000
Model............ Mlnx X86
CPU.............. x86_64 Intel Atom C2558 2.40GHz
Memory........... 8GB
Disk............. 14.7GB
ASIC............. Mellanox Spectrum MT52132
Ports............ 16 x 100G-QSFP28
Part Number...... MSN2100-CB2FC
Serial Number.... MT2105T05177
Platform Name.... x86_64-mlnx_x86-r0
Product Name..... MSN2100
ONIE Version..... 2019.11-5.2.0020-115200
Base MAC Address. 04:3F:72:43:92:80
Manufacturer..... Mellanox
----
. Configure el nombre de host, la dirección IP, la máscara de subred y la puerta de enlace predeterminada.  El nuevo nombre de host solo surtirá efecto después de reiniciar la sesión de consola/SSH.
+

NOTE: Un switch Cumulus Linux proporciona al menos un puerto de administración Ethernet dedicado llamado `eth0` .  Esta interfaz está diseñada específicamente para su uso en la gestión fuera de banda.  Por defecto, la interfaz de administración utiliza DHCPv4 para el direccionamiento.

+

CAUTION: No utilice guiones bajos (_), apóstrofes (') ni caracteres no ASCII en el nombre de host.

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net add hostname sw1*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip address 10.233.204.71/24*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *net pending*
cumulus@cumulus:mgmt:~$ *net commit*
----
+
Este comando modifica ambos `/etc/hostname` y `/etc/hosts` archivos.

. Confirme que el nombre de host, la dirección IP, la máscara de subred y la puerta de enlace predeterminada se han actualizado.
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Configure la fecha, la hora, la zona horaria y el servidor NTP en el conmutador.
+
.. Verifique la zona horaria actual:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *cat /etc/timezone*
----
.. Actualización a la nueva zona horaria:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure --frontend noninteractive tzdata*
----
.. Verifique su zona horaria actual:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. Para configurar la zona horaria mediante el asistente guiado, ejecute el siguiente comando:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Configure el reloj del software según la zona horaria configurada:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. Establezca el valor actual del reloj del software al del reloj del hardware:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *sudo hwclock -w*
----
.. Agregue un servidor NTP si es necesario:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add time ntp server _<cumulus.network.ntp.org>_ iburst*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
.. Verifique que `ntpd` se está ejecutando en el sistema:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. Especifique la interfaz de origen NTP.  Por defecto, la interfaz de origen que utiliza NTP es `eth0` .  Puede configurar una interfaz de origen NTP diferente de la siguiente manera:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add time ntp source _<src_int>_*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----


. Instalar Cumulus Linux 4.4.3:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*
----
+
El instalador inicia la descarga. Escriba *y* cuando se le solicite.

. Reinicie el switch NVIDIA SN2100:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. La instalación se inicia automáticamente y aparecen las siguientes opciones en la pantalla de GRUB.  No realice ninguna selección.
+
** Cumulus-Linux GNU/Linux
** ONIE: Instalar sistema operativo
** INSTALACIÓN DE CÚMULOS
** Cumulus-Linux GNU/Linux


. Repita los pasos del 1 al 4 para iniciar sesión.
. Verifique que la versión de Cumulus Linux sea la 4.4.3: `net show version`
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u0
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3"*
----
. Crea un nuevo usuario y agrégalo a la lista. `sudo` grupo.  Este usuario solo será efectivo después de reiniciar la sesión de consola/SSH.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----


--
.Cumulus Linux 5.4.0
--
. Inicia sesión en el switch.
+
El primer inicio de sesión en el switch requiere el nombre de usuario/contraseña *cumulus*/*cumulus* con `sudo` privilegios.

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Comprueba la versión de Cumulus para Linux: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.3.0  system build version
uptime              6 days, 8:37:36      system uptime
timezone            Etc/UTC              system time zone
----
. Configure el nombre de host, la dirección IP, la máscara de subred y la puerta de enlace predeterminada.  El nuevo nombre de host solo surtirá efecto después de reiniciar la sesión de consola/SSH.
+

NOTE: Un switch Cumulus Linux proporciona al menos un puerto de administración Ethernet dedicado llamado `eth0` .  Esta interfaz está diseñada específicamente para su uso en la gestión fuera de banda.  Por defecto, la interfaz de administración utiliza DHCPv4 para el direccionamiento.

+

CAUTION: No utilice guiones bajos (_), apóstrofes (') ni caracteres no ASCII en el nombre de host.

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip address 10.233.204.71/24*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *nv config apply*
cumulus@cumulus:mgmt:~$ *nv config save*
----
+
Este comando modifica ambos `/etc/hostname` y `/etc/hosts` archivos.

. Confirme que el nombre de host, la dirección IP, la máscara de subred y la puerta de enlace predeterminada se han actualizado.
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Configure la zona horaria, la fecha, la hora y el servidor NTP en el conmutador.
+
.. Configura la zona horaria:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set system timezone US/Eastern*
cumulus@sw1:~$ *nv config apply*
----
.. Verifique su zona horaria actual:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. Para configurar la zona horaria mediante el asistente guiado, ejecute el siguiente comando:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Configure el reloj del software según la zona horaria configurada:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. Establezca el valor actual del reloj del software al del reloj del hardware:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo hwclock -w*
----
.. Agregue un servidor NTP si es necesario:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp mgmt listen eth0*
cumulus@sw1:~$ *nv set service ntp mgmt server <server> iburst on*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----
+
Consulte el artículo de la base de conocimientoslink:https://kb.netapp.com/on-prem/Switches/Nvidia-KBs/NTP_Server_configuration_is_not_working_with_NVIDIA_SN2100_Switches["La configuración del servidor NTP no funciona con los switches NVIDIA SN2100."^] Para obtener más detalles.

.. Verifique que `ntpd` se está ejecutando en el sistema:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. Especifique la interfaz de origen NTP.  Por defecto, la interfaz de origen que utiliza NTP es `eth0` .  Puede configurar una interfaz de origen NTP diferente de la siguiente manera:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp default listen _<src_int>_*
cumulus@sw1:~$ *nv config apply*
----


. Instalar Cumulus Linux 5.4.0:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-5.4-mlx-amd64.bin*
----
+
El instalador inicia la descarga. Escriba *y* cuando se le solicite.

. Reinicie el switch NVIDIA SN2100:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. La instalación se inicia automáticamente y aparecen las siguientes opciones en la pantalla de GRUB.  No realice ninguna selección.
+
** Cumulus-Linux GNU/Linux
** ONIE: Instalar sistema operativo
** INSTALACIÓN DE CÚMULOS
** Cumulus-Linux GNU/Linux


. Repita los pasos del 1 al 4 para iniciar sesión.
. Verifique que la versión de Cumulus Linux sea la 5.4.0: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0  system build version
uptime              6 days, 13:37:36     system uptime
timezone            Etc/UTC              system time zone
----
. Verifique que cada nodo tenga conexión con cada conmutador:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost                          RemotePort
---------  -----  ----------  ----------------------------------  -----------
eth0       100M   Mgmt        mgmt-sw1                            Eth110/1/29
swp2s1     25G    Trunk/L2    node1                               e0a
swp15      100G   BondMember  sw2                                 swp15
swp16      100G   BondMember  sw2                                 swp16
----
. Crea un nuevo usuario y agrégalo a la lista. `sudo` grupo.  Este usuario solo será efectivo después de reiniciar la sesión de consola/SSH.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. Agregue grupos de usuarios adicionales para que el usuario administrador pueda acceder a ellos. `nv` comandos:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user 'admin' to group 'nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
Ver https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["Cuentas de usuario de NVIDIA"^] Para más información.



--
.Cumulus Linux 5.11.0
--
. Inicia sesión en el switch.
+
Cuando inicie sesión en el switch por primera vez, le solicitará el nombre de usuario y la contraseña *cumulus*/*cumulus* con `sudo` privilegios.

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Comprueba la versión de Cumulus para Linux: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0  system build version
uptime              6 days, 8:37:36      system uptime
timezone            Etc/UTC              system time zone
----
. Configure el nombre de host, la dirección IP, la máscara de subred y la puerta de enlace predeterminada.  El nuevo nombre de host solo surtirá efecto después de reiniciar la sesión de consola/SSH.
+

NOTE: Un switch Cumulus Linux proporciona al menos un puerto de administración Ethernet dedicado llamado `eth0` .  Esta interfaz está diseñada específicamente para su uso en la gestión fuera de banda.  Por defecto, la interfaz de administración utiliza DHCPv4 para el direccionamiento.

+

CAUTION: No utilice guiones bajos (_), apóstrofes (') ni caracteres no ASCII en el nombre de host.

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv unset interface eth0 ip address dhcp*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip address 10.233.204.71/24*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *nv config apply*
cumulus@cumulus:mgmt:~$ *nv config save*
----
+
Este comando modifica ambos `/etc/hostname` y `/etc/hosts` archivos.

. Confirme que el nombre de host, la dirección IP, la máscara de subred y la puerta de enlace predeterminada se han actualizado.
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Configure la zona horaria, la fecha, la hora y el servidor NTP en el conmutador.
+
.. Configura la zona horaria:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set system timezone US/Eastern*
cumulus@sw1:~$ *nv config apply*
----
.. Verifique su zona horaria actual:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. Para configurar la zona horaria mediante el asistente guiado, ejecute el siguiente comando:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Configure el reloj del software según la zona horaria configurada:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. Establezca el valor actual del reloj del software al del reloj del hardware:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo hwclock -w*
----
.. Agregue un servidor NTP si es necesario:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp mgmt listen eth0*
cumulus@sw1:~$ *nv set service ntp mgmt server <server> iburst on*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----
+
Consulte el artículo de la base de conocimientoslink:https://kb.netapp.com/on-prem/Switches/Nvidia-KBs/NTP_Server_configuration_is_not_working_with_NVIDIA_SN2100_Switches["La configuración del servidor NTP no funciona con los switches NVIDIA SN2100."^] Para obtener más detalles.

.. Verifique que `ntpd` se está ejecutando en el sistema:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. Especifique la interfaz de origen NTP.  Por defecto, la interfaz de origen que utiliza NTP es `eth0` .  Puede configurar una interfaz de origen NTP diferente de la siguiente manera:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp default listen _<src_int>_*
cumulus@sw1:~$ *nv config apply*
----


. Instalar Cumulus Linux 5.11.0:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-5.11.0-mlx-amd64.bin*
----
+
El instalador inicia la descarga. Escriba *y* cuando se le solicite.

. Reinicie el switch NVIDIA SN2100:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. La instalación se inicia automáticamente y aparecen las siguientes opciones en la pantalla de GRUB.  No realice ninguna selección.
+
** Cumulus-Linux GNU/Linux
** ONIE: Instalar sistema operativo
** INSTALACIÓN DE CÚMULOS
** Cumulus-Linux GNU/Linux


. Repita los pasos del 1 al 4 para iniciar sesión.
. Verifique que la versión de Cumulus Linux sea la 5.11.0:
+
`nv show system`

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied                description
------------------- ---------------------- ---------------------
build               Cumulus Linux 5.11.0
uptime              153 days, 2:44:16
hostname            cumulus                cumulus
product-name        Cumulus Linux
product-release     5.11.0
platform            x86_64-mlnx_x86-r0
system-memory       2.76 GB used / 2.28 GB free / 7.47 GB total
swap-memory         0 Bytes used / 0 Bytes free / 0 Bytes total
health-status       not OK
date-time           2025-04-23 09:55:24
status              N/A
timezone            Etc/UTC
maintenance
  mode              disabled
  ports             enabled
version
  kernel            6.1.0-cl-1-amd64
  build-date        Thu Nov 14 13:06:38 UTC 2024
  image             5.11.0
  onie              2019.11-5.2.0020-115200
----
. Verifique que cada nodo tenga conexión con cada conmutador:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv show interface lldp*

LocalPort  Speed  Mode        RemoteHost                          RemotePort
---------  -----  ----------  ----------------------------------  -----------
eth0       100M   eth   mgmt-sw1                                  Eth110/1/14
swp2s1     25G    Trunk/L2    node1                               e0a
swp1s1     10G    swp   sw2                                       e0a
swp9       100G   swp   sw3                                       e4a
swp10      100G   swp   sw4                                       e4a
swp15      100G   swp   sw5                                       swp15
swp16      100G   swp   sw6                                       swp16
----


Ver https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-511/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["Cuentas de usuario de NVIDIA"^] Para más información.

--
====
.¿Que sigue?
Después de haber instalado Cumulus Linux en modo Cumulus, usted link:install-rcf-sn2100-cluster.html["Instalar el script del archivo de configuración de referencia (RCF)."].
