---
permalink: switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched NVIDIA SN2100 cluster environment,switchless cluster environments,NVIDIA SN2100 switches 
summary: Si ya dispone de un entorno de clúster sin switches de dos nodos, puede migrar a un entorno de clústeres con switches de dos nodos mediante switches NVIDIA SN2100 para permitir el escalado más allá de los dos nodos del clúster. 
---
= Migre a un clúster con switches de dos nodos con switches de clúster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ya dispone de un entorno de clúster sin switches de dos nodos, puede migrar a un entorno de clústeres con switches de dos nodos mediante switches NVIDIA SN2100 para permitir el escalado más allá de los dos nodos del clúster.

El procedimiento que utilice dependerá de si tiene dos puertos de red de clúster dedicados en cada controladora o un único puerto de clúster de cada controladora. El proceso documentado funciona para todos los nodos utilizando puertos ópticos o Twinax, pero no es compatible con este switch si los nodos utilizan puertos RJ45 10GBASE-T integrados para los puertos de red del clúster.



== Revise los requisitos

.Configuración con dos nodos sin switches
Asegúrese de que:

* La configuración sin switch de dos nodos está correctamente configurada y funciona.
* Los nodos ejecutan ONTAP 9.10.1P3 y una versión posterior.
* Todos los puertos del clúster están en el estado *up*.
* Todas las interfaces lógicas de cluster (LIF) están en el estado *up* y en sus puertos de inicio.


.Configuración de switch de clúster NVIDIA SN2100
Asegúrese de que:

* Ambos switches tienen conectividad de red de gestión.
* Hay acceso de la consola a los switches de clúster.
* El switch de nodo a nodo NVIDIA SN2100 y las conexiones de switch a switch utilizan cables Twinax o de fibra.
+

IMPORTANT: Consulte link:cabling-considerations-sn2100-cluster.html["Revise las consideraciones sobre el cableado y la configuración"] para obtener advertencias e información adicional. La https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - interruptores"^] también contiene más información sobre el cableado.

* Los cables de enlace entre switches (ISL) están conectados a los puertos swp15 y swp16 en ambos switches NVIDIA SN2100.
* Se ha completado la personalización inicial de los dos conmutadores SN2100, de modo que:
+
** Los conmutadores SN2100 ejecutan la última versión de Cumulus Linux
** Los archivos de configuración de referencia (RCF) se aplican a los conmutadores
** Cualquier personalización de sitio, como SMTP, SNMP y SSH, se configura en los nuevos switches.
+
La https://hwu.netapp.com["Hardware Universe"^] contiene la información más reciente acerca de los puertos del clúster reales para las plataformas.







== Migrar los switches

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de nodo y conmutador de cluster:

* Los nombres de los interruptores SN2100 son _sw1_ y _sw2_.
* Los nombres de las SVM del clúster son _1_ y _2_.
* Los nombres de las LIF son _1_clus1_ y _1_clus2_ en el nodo 1, y _2_clus1_ y _2_clus2_ en el nodo 2, respectivamente.
* La `cluster1::*>` prompt indica el nombre del clúster.
* Los puertos de clúster utilizados en este procedimiento son _e3a_ y _e3b_.
* Los puertos de arranque tienen el formato: swp[Port]s[breakout Port 0-3]. Por ejemplo, cuatro puertos de arranque en swp1 son _swp1s0_, _swp1s1_, _swp1s2_ y _swp1s3_.




=== Paso 1: Preparación para la migración

. Si se habilita AutoSupport en este clúster, elimine la creación automática de casos invocando un mensaje de AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=xh`
+
donde _x_ es la duración de la ventana de mantenimiento en horas.

. Cambie el nivel de privilegio a Advanced, introduzca `y` cuando se le solicite continuar: `set -privilege advanced`
+
El aviso avanzado (`*>`) aparece.





=== Paso 2: Configure los puertos y el cableado

[role="tabbed-block"]
====
.Cumulus Linux 4,4.x
--
. Deshabilite todos los puertos orientados al nodo (no los puertos ISL) en los nuevos switches del clúster sw1 y sw2.
+
No debe deshabilitar los puertos ISL.

+
Los siguientes comandos desactivan los puertos orientados al nodo en los switches sw1 y sw2:

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*

cumulus@sw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
. Compruebe que el ISL y los puertos físicos del ISL entre los dos switches SN2100 sw1 y sw2 están en los puertos swp15 y swp16:
+
`net show interface`

+
Los siguientes comandos muestran que los puertos ISL están activos en los switches sw1 y SW2:

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw2 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw2 (swp16)  Master: cluster_isl(UP)

cumulus@sw2:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw1 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw1 (swp16)  Master: cluster_isl(UP)
----


--
.Cumulus Linux 5.x
--
. Deshabilite todos los puertos orientados al nodo (no puertos ISL) en los dos switches de clúster nuevos sw1 y SW2.
+
No debe deshabilitar los puertos ISL.

+
Los siguientes comandos desactivan los puertos orientados al nodo en los switches sw1 y sw2:

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state down*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv save*

cumulus@sw2:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state down*
cumulus@sw2:~$ *nv config apply*
cumulus@sw2:~$ *nv save*
----
. Compruebe que el ISL y los puertos físicos del ISL entre los dos switches SN2100 sw1 y sw2 están en los puertos swp15 y swp16:
+
`nv show interface`

+
Los ejemplos siguientes muestran que los puertos ISL están activos en los switches sw1 y SW2:

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface*

Interface     MTU    Speed  State  Remote Host  Remote Port                          Type    Summary
------------- ------ -----  ------ ------------ ------------------------------------ ------- -------
...
...
+ swp14       9216          down                                                     swp
+ swp15       9216   100G   up     ossg-rcf1    Intra-Cluster Switch ISL Port swp15  swp
+ swp16       9216   100G   up     ossg-rcf2    Intra-Cluster Switch ISL Port swp16  swp


cumulus@sw2:~$ *nv show interface*

Interface     MTU    Speed  State  Remote Host  Remote Port                          Type    Summary
------------- ------ -----  ------ ------------ ------------------------------------ ------- -------
...
...
+ swp14       9216          down                                                     swp
+ swp15       9216   100G   up     ossg-rcf1    Intra-Cluster Switch ISL Port swp15  swp
+ swp16       9216   100G   up     ossg-rcf2    Intra-Cluster Switch ISL Port swp16  swp
----


--
====
. [[step3]] Verifique que todos los puertos del clúster estén activos:
+
`network port show`

+
Cada puerto debe aparecer `up` para `Link` y saludable para `Health Status`.

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show*

Node: node1

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. Compruebe que todas las LIF del clúster estén en funcionamiento:
+
`network interface show`

+
Cada LIF de clúster debería mostrar el valor true para `Is Home` y que tengan un `Status Admin/Oper` de `up/up`.

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. Deshabilite la reversión automática en las LIF del clúster:
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   false
          node1_clus2   false
          node2_clus1   false
          node2_clus2   false

----
====
. Desconecte el cable del puerto del clúster e3a del nodo 1 y, a continuación, conecte e3a al puerto 3 del conmutador del cluster sw1, utilizando el cableado adecuado admitido por los conmutadores SN2100.
+
La https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - interruptores"^] contiene más información sobre el cableado.

. Desconecte el cable del puerto del clúster e3a en el nodo 2 y, a continuación, conecte e3a al puerto 4 del interruptor del cluster sw1, utilizando el cableado adecuado admitido por los interruptores SN2100.


[role="tabbed-block"]
====
.Cumulus Linux 4,4.x
--
. [[step8]] En el switch sw1, habilite todos los puertos orientados al nodo.
+
Los siguientes comandos habilitan todos los puertos orientados al nodo del switch sw1.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----


. [[STEP]] En el switch sw1, verifique que todos los puertos estén activos:
+
`net show interface all`

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3a)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3a)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----


--
.Cumulus Linux 5.x
--
. [[step8]] En el switch sw1, habilite todos los puertos orientados al nodo.
+
Los siguientes comandos habilitan todos los puertos orientados al nodo del switch sw1.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv unset interface swp1s0-3,swp2s0-3,swp3-14 link state down*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----


. [[step9]] En el switch sw1, verifique que todos los puertos estén activos:
+
`nv show interface`

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface*

Interface    State  Speed  MTU    Type      Remote Host                 Remote Port  Summary
-----------  -----  -----  -----  --------  --------------------------  -----------  ----------
...
...
swp1s0       up     10G    9216   swp       odq-a300-1a                         e0a
swp1s1       up     10G    9216   swp       odq-a300-1b                         e0a
swp1s2       down   10G    9216   swp
swp1s3       down   10G    9216   swp
swp2s0       down   25G    9216   swp
swp2s1       down   25G    9216   swp
swp2s2       down   25G    9216   swp
swp2s3       down   25G    9216   swp
swp3         down          9216   swp
swp4         down          9216   swp
...
...
swp14        down          9216   swp
swp15        up     100G   9216   swp       ossg-int-rcf10                    swp15
swp16        up     100G   9216   swp       ossg-int-rcf10                    swp16
----


--
====
. [[step10]] Verifique que todos los puertos del clúster estén activos:
+
`network port show -ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo, se muestra que todos los puertos del clúster están en los nodos 1 y 2:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. Muestra información sobre el estado de los nodos en el clúster:
+
`cluster show`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestra información sobre el estado y la elegibilidad de los nodos en el clúster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

----
====
. Desconecte el cable del puerto del clúster e3b del nodo 1 y, a continuación, conecte e3b al puerto 3 del switch del clúster sw2, utilizando el cableado adecuado compatible con los switches SN2100.
. Desconecte el cable del puerto del clúster e3b en el nodo 2 y, a continuación, conecte e3b al puerto 4 del switch del clúster sw2, utilizando el cableado adecuado compatible con los conmutadores SN2100.


[role="tabbed-block"]
====
.Cumulus Linux 4,4.x
--
. [[step14]] En el switch SW2, habilite todos los puertos orientados al nodo.
+
Los siguientes comandos habilitan los puertos orientados al nodo en el switch sw2:

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
. [[step15]] En el switch SW2, verifique que todos los puertos estén activos:
+
`net show interface all`

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3b)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3b)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----


. [[step16]] En ambos conmutadores sw1 y SW2, verifique que ambos nodos tengan cada uno una conexión a cada conmutador:
+
`net show lldp`

+
En el siguiente ejemplo se muestran los resultados adecuados para ambos interruptores sw1 y sw2:



[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3b
swp4       100G   Trunk/L2    node2              e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
--
.Cumulus Linux 5.x
--
. [[step14]] En el switch SW2, habilite todos los puertos orientados al nodo.
+
Los siguientes comandos habilitan los puertos orientados al nodo en el switch sw2:

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *nv unset interface swp1s0-3,swp2s0-3,swp3-14 link state down*
cumulus@sw2:~$ *nv config apply*
cumulus@sw2:~$ *nv config save*
----
. [[step15]] En el switch SW2, verifique que todos los puertos estén activos:
+
`nv show interface`

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *nv show interface*

Interface    State  Speed  MTU    Type      Remote Host                 Remote Port  Summary
-----------  -----  -----  -----  --------  --------------------------  -----------  ----------
...
...
swp1s0       up     10G    9216   swp       odq-a300-1a                         e0a
swp1s1       up     10G    9216   swp       odq-a300-1b                         e0a
swp1s2       down   10G    9216   swp
swp1s3       down   10G    9216   swp
swp2s0       down   25G    9216   swp
swp2s1       down   25G    9216   swp
swp2s2       down   25G    9216   swp
swp2s3       down   25G    9216   swp
swp3         down          9216   swp
swp4         down          9216   swp
...
...
swp14        down          9216   swp
swp15        up     100G   9216   swp       ossg-int-rcf10                    swp15
swp16        up     100G   9216   swp       ossg-int-rcf10                    swp16
----


. [[step16]] En ambos conmutadores sw1 y SW2, verifique que ambos nodos tengan cada uno una conexión a cada conmutador:
+
`nv show interface --view=lldp`

+
Los siguientes ejemplos muestran los resultados adecuados para los switches sw1 y SW2:

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface --view=lldp*

Interface    Speed  Type      Remote Host                         Remote Port
-----------  -----  --------  ----------------------------------  -----------
...
...
swp1s0       10G    swp       odq-a300-1a                         e0a
swp1s1       10G    swp       odq-a300-1b                         e0a
swp1s2       10G    swp
swp1s3       10G    swp
swp2s0       25G    swp
swp2s1       25G    swp
swp2s2       25G    swp
swp2s3       25G    swp
swp3                swp
swp4                swp
...
...
swp14               swp
swp15        100G   swp       ossg-int-rcf10                      swp15
swp16        100G   swp       ossg-int-rcf10                      swp16

cumulus@sw2:~$ *nv show interface --view=lldp*

Interface    Speed  Type      Remote Host                         Remote Port
-----------  -----  --------  ----------------------------------  -----------
...
...
swp1s0       10G    swp       odq-a300-1a                         e0a
swp1s1       10G    swp       odq-a300-1b                         e0a
swp1s2       10G    swp
swp1s3       10G    swp
swp2s0       25G    swp
swp2s1       25G    swp
swp2s2       25G    swp
swp2s3       25G    swp
swp3                swp
swp4                swp
...
...
swp14               swp
swp15        100G   swp       ossg-int-rcf10                      swp15
swp16        100G   swp       ossg-int-rcf10                      swp16
----


--
====
. [[step17]] Muestra información sobre los dispositivos de red detectados en el cluster:
+
`network device-discovery show -protocol lldp`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
====
. Compruebe que todos los puertos del clúster estén activos:
+
`network port show -ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo, se muestra que todos los puertos del clúster están en los nodos 1 y 2:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

----
====




=== Paso 3: Complete el procedimiento

. Activa la reversión automática en todos los LIF del clúster:
+
`net interface modify -vserver Cluster -lif * -auto-revert true`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *net interface modify -vserver Cluster -lif * -auto-revert true*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
----
====
. Compruebe que se muestran todas las interfaces `true` para `Is Home`:
+
`net interface show -vserver Cluster`

+

NOTE: Esto puede tardar un minuto en completarse.

+
.Muestra el ejemplo
[%collapsible]
====
En el ejemplo siguiente, se muestra que todas las LIF están activas en los nodos 1 y 2, y eso `Is Home` los resultados son verdaderos:

[listing, subs="+quotes"]
----
cluster1::*> *net interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true

----
====
. Compruebe que la configuración está desactivada:
+
`network options switchless-cluster show`

+
.Muestra el ejemplo
[%collapsible]
====
El resultado falso en el ejemplo siguiente muestra que las opciones de configuración están deshabilitadas:

[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: *false*
----
====
. Compruebe el estado de los miembros del nodo en el clúster:
+
`cluster show`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestra información sobre el estado y la elegibilidad de los nodos en el clúster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Compruebe que la red de clúster tiene conectividad completa:
+
`cluster ping-cluster -node node-name`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node1*
Host is node1
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. Para configurar la recopilación de registros, ejecute el siguiente comando para cada conmutador. Se le pedirá que introduzca el nombre del switch, el nombre de usuario y la contraseña para la recopilación de registros.
+
`system switch ethernet log setup-password`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. Para iniciar la recopilación de registros, ejecute el siguiente comando, sustituyendo EL DISPOSITIVO por el conmutador utilizado en el comando anterior. Esto inicia ambos tipos de recopilación de registros: Los registros detallados de *Support* y una recopilación horaria de datos *Periódicos*.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device sw1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device sw2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Espere 10 minutos y compruebe que se complete la recopilación de registros:

+
`system switch ethernet log show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> system switch ethernet log show
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------- ---------
1      sw1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete
2      sw2 (b8:ce:f6:19:1b:96)      4/29/2022 03:07:42   complete
----
====
+

CAUTION: Si alguno de estos comandos devuelve un error, póngase en contacto con el soporte de NetApp.

. Vuelva a cambiar el nivel de privilegio a admin:
+
`set -privilege admin`

. Si ha suprimido la creación automática de casos, rehabilitarla invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


