---
permalink: switch-nvidia-sn2100/migrate-cisco-sn2100-cluster-switch.html 
sidebar: sidebar 
keywords: migrating to a cluster with NVIDIA SN2100 cluster switches, how to migrate 
summary: Puede migrar sin interrupciones los switches de clúster Cisco más antiguos para un clúster ONTAP a los switches de red de clúster NVIDIA SN2100. 
---
= Migrar de un conmutador de clúster Cisco a un conmutador de clúster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede migrar los conmutadores de clúster de Cisco para un clúster ONTAP a conmutadores de clúster NVIDIA SN2100. Este es un procedimiento que no produce interrupciones.



== Requisitos de revisión

Debe tener en cuenta cierta información de configuración, conexiones de puertos y requisitos de cableado cuando reemplace algunos conmutadores de clúster Cisco antiguos con conmutadores de clúster NVIDIA SN2100. Verlink:configure-overview-sn2100-cluster.html["Descripción general de la instalación y configuración de los switches NVIDIA SN2100"] .

.Interruptores compatibles
Se admiten los siguientes conmutadores de clúster de Cisco :

* Nexus 9336C-FX2
* Nexus 92300YC
* Nexus 5596UP
* Nexus 3232C
* Nexus 3132Q-V


Para obtener detalles sobre los puertos compatibles y sus configuraciones, consulte la https://hwu.netapp.com/["Hardware Universe"^] .

.Lo que necesitarás
Asegúrese de que:

* El clúster existente está configurado y funcionando correctamente.
* Todos los puertos del clúster están en estado *activo* para garantizar un funcionamiento sin interrupciones.
* Los conmutadores de clúster NVIDIA SN2100 están configurados y funcionando bajo la versión correcta de Cumulus Linux instalada con el archivo de configuración de referencia (RCF) aplicado.
* La configuración de red del clúster existente presenta lo siguiente:
+
** Un clúster NetApp redundante y totalmente funcional que utiliza ambos switches Cisco antiguos.
** Conectividad de gestión y acceso a la consola tanto para los switches Cisco antiguos como para los nuevos.
** Todas las LIF del clúster en estado activo están en sus puertos de origen.
** Puertos ISL habilitados y cableados entre los switches Cisco antiguos y entre los switches nuevos.


* Algunos de los puertos de los switches NVIDIA SN2100 están configurados para funcionar a 40 GbE o 100 GbE.
* Usted ha planificado, migrado y documentado la conectividad de 40 GbE y 100 GbE desde los nodos a los conmutadores de clúster NVIDIA SN2100.



NOTE: Si está cambiando la velocidad de los puertos del clúster e0a y e1a en los sistemas AFF A800 o AFF C800 , podría observar que se reciben paquetes malformados después de la conversión de velocidad.  Ver https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["Error 1570339"^] y el artículo de la Base de Conocimiento https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["Errores CRC en puertos T6 tras la conversión de 40GbE a 100GbE"^] para ayuda.



== Migrar los interruptores

.Acerca de los ejemplos
En este procedimiento, se utilizan switches de clúster Cisco Nexus 3232C como ejemplos de comandos y salidas.

Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los switches de clúster Cisco Nexus 3232C existentes son _c1_ y _c2_.
* Los nuevos conmutadores de clúster NVIDIA SN2100 son _sw1_ y _sw2_.
* Los nodos son _nodo1_ y _nodo2_.
* Los LIF del clúster son _node1_clus1_ y _node1_clus2_ en el nodo 1, y _node2_clus1_ y _node2_clus2_ en el nodo 2 respectivamente.
* El `cluster1::*>` El indicador muestra el nombre del clúster.
* Los puertos del clúster utilizados en este procedimiento son _e3a_ y _e3b_.
* Los puertos de ruptura adoptan el formato: swp[puerto]s[puerto de ruptura 0-3].  Por ejemplo, cuatro puertos de ruptura en swp1 son _swp1s0_, _swp1s1_, _swp1s2_ y _swp1s3_.


.Acerca de esta tarea
Este procedimiento cubre el siguiente escenario:

* El interruptor c2 se reemplaza primero por el interruptor sw2.
+
** Desactive los puertos de los nodos del clúster.  Todos los puertos deben apagarse simultáneamente para evitar la inestabilidad del clúster.
** Luego, el cableado entre los nodos y c2 se desconecta de c2 y se vuelve a conectar a sw2.


* El interruptor c1 se reemplaza por el interruptor sw1.
+
** Desactive los puertos de los nodos del clúster.  Todos los puertos deben apagarse simultáneamente para evitar la inestabilidad del clúster.
** Luego, el cableado entre los nodos y c1 se desconecta de c1 y se vuelve a conectar a sw1.






=== Paso 1: Prepararse para la migración

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
donde _x_ es la duración de la ventana de mantenimiento en horas.

. Cambie el nivel de privilegio a avanzado, ingresando *y* cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el indicador avanzado (*>).

. Deshabilitar la reversión automática en los LIF del clúster:
+
`network interface modify -vserver Cluster -lif * -auto-revert false`





=== Paso 2: Configurar puertos y cableado

. Determinar el estado administrativo u operativo de cada interfaz de clúster.
+
Cada puerto debería mostrarse para `Link` y saludable para `Health Status` .

+
.. Mostrar los atributos del puerto de red:
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
.. Muestra información sobre las interfaces lógicas y sus nodos de origen designados:
+
`network interface show -vserver Cluster`

+
Cada LIF debería mostrar `up/up` para `Status Admin/Oper` y cierto para `Is Home` .

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current     Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node        Port    Home
----------- -----------  ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2       e3b     true

----
====


. Los puertos del clúster en cada nodo están conectados a los conmutadores del clúster existentes de la siguiente manera (desde la perspectiva de los nodos):
+
`network device-discovery show -protocol lldp`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /lldp
            e3a    c1 (6a:ad:4f:98:3b:3f)    Eth1/1            -
            e3b    c2 (6a:ad:4f:98:4c:a4)    Eth1/1            -
node2      /lldp
            e3a    c1 (6a:ad:4f:98:3b:3f)    Eth1/2            -
            e3b    c2 (6a:ad:4f:98:4c:a4)    Eth1/2            -
----
====
. Los puertos y conmutadores del clúster están conectados de la siguiente manera (desde la perspectiva de los conmutadores):
+
`show cdp neighbors`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1         124   H           AFF-A400         e3a
node2                 Eth1/2         124   H           AFF-A400         e3a
c2                    Eth1/31        179   S I s       N3K-C3232C       Eth1/31
c2                    Eth1/32        175   S I s       N3K-C3232C       Eth1/32

c2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1        124    H           AFF-A400         e3b
node2                 Eth1/2        124    H           AFF-A400         e3b
c1                    Eth1/31       175    S I s       N3K-C3232C       Eth1/31
c1                    Eth1/32       175    S I s       N3K-C3232C       Eth1/32
----
====
. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e3a
Cluster node1_clus2 169.254.49.125 node1     e3b
Cluster node2_clus1 169.254.47.194 node2     e3a
Cluster node2_clus2 169.254.19.183 node2     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step5]] En el switch c2, apague los puertos conectados a los puertos del clúster de los nodos para realizar la conmutación por error de las LIF del clúster.
+
[listing, subs="+quotes"]
----
(c2)# *configure*
Enter configuration commands, one per line. End with CNTL/Z.

(c2)(Config)# *interface*
(c2)(config-if-range)# *shutdown _<interface_list>_*
(c2)(config-if-range)# *exit*
(c2)(Config)# *exit*
(c2)#
----
. Traslade los puertos del clúster de nodos del antiguo switch c2 al nuevo switch sw2, utilizando el cableado adecuado compatible con NVIDIA SN2100.
. Mostrar los atributos del puerto de red:
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. Los puertos del clúster en cada nodo ahora están conectados a los conmutadores del clúster de la siguiente manera, desde la perspectiva de los nodos:
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   Eth1/1            -
            e3b    sw2 (b8:ce:f6:19:1a:7e)   swp3              -
node2      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   Eth1/2            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4              -
----
====
. En el switch sw2, verifique que todos los puertos del clúster de nodos estén activos:
+
`net show interface`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. En el switch c1, apague los puertos conectados a los puertos del clúster de los nodos para realizar la conmutación por error de las LIF del clúster.
+
[listing, subs="+quotes"]
----
(c1)# *configure*
Enter configuration commands, one per line. End with CNTL/Z.

(c1)(Config)# *interface*
(c1)(config-if-range)# *shutdown _<interface_list>_*
(c1)(config-if-range)# *exit*
(c1)(Config)# *exit*
(c1)#
----
. Traslade los puertos del clúster de nodos del antiguo conmutador c1 al nuevo conmutador sw1, utilizando el cableado adecuado compatible con NVIDIA SN2100.
. Verifique la configuración final del clúster:
+
`network port show -ipspace Cluster`

+
Cada puerto debería mostrar `up` para `Link` y saludable para `Health Status` .

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. Los puertos del clúster en cada nodo ahora están conectados a los conmutadores del clúster de la siguiente manera, desde la perspectiva de los nodos:
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3            -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4            -
----
====
. En los conmutadores sw1 y sw2, verifique que todos los puertos del clúster de nodos estén activos:
+
`net show interface`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw2 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw2 (swp16)       Master: cluster_isl(UP)


cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- -----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. Verifique que ambos nodos tengan una conexión a cada conmutador:
+
`net show lldp`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra los resultados correspondientes para ambos interruptores:

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3a
swp4       100G   Trunk/L2    node2               e3a
swp15      100G   BondMember  sw2                 swp15
swp16      100G   BondMember  sw2                 swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3b
swp4       100G   Trunk/L2    node2               e3b
swp15      100G   BondMember  sw1                 swp15
swp16      100G   BondMember  sw1                 swp16
----
====




=== Paso 3: Verificar la configuración

. Habilitar la reversión automática en los LIF del clúster:
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. Verifique que todas las LIF de la red del clúster hayan vuelto a sus puertos de origen:
+
`network interface show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. Vuelva a cambiar el nivel de privilegios a administrador:
+
`set -privilege admin`

. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.¿Que sigue?
Después de migrar tus switches, puedes link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
