---
permalink: switch-nvidia-sn2100/replace-sn2100-switch-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia msn2100 cluster switch - nvidia SN2100 
summary: 'La sustitución de un switch NVIDIA SN2100 defectuoso en una red de clúster es un procedimiento no disruptivo \(NDU\).' 
---
= Sustituya un conmutador de clúster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para sustituir un conmutador NVIDIA SN2100 defectuoso en una red de clúster. Este es un procedimiento no disruptivo (NDU).



== Revise los requisitos

.Infraestructura de red y clúster existente
Asegúrese de que:

* El clúster existente se ha verificado como completamente funcional, con al menos un switch de clúster completamente conectado.
* Todos los puertos del clúster están activos.
* Todas las interfaces lógicas de clúster (LIF) están en funcionamiento y en sus puertos raíz.
* La ONTAP `cluster ping-cluster -node node1` El comando indica que la conectividad básica y la comunicación más grande que PMTU se realizan correctamente en todas las rutas.


.Conmutador de sustitución NVIDIA SN2100
Asegúrese de que:

* La conectividad de la red de gestión en el switch de reemplazo es funcional.
* El acceso de la consola al interruptor de sustitución está en su lugar.
* Las conexiones de nodos son los puertos swp1 a swp14.
* Todos los puertos de enlace entre switches (ISL) están deshabilitados en los puertos swp15 y swp16.
* El archivo de configuración de referencia (RCF) y el interruptor de imagen del sistema operativo Cumulus se cargan en el conmutador.
* Se ha completado la personalización inicial del conmutador.


Asegúrese también de que cualquier personalización de sitio anterior, como STP, SNMP y SSH, se copie al nuevo switch.


NOTE: Debe ejecutar el comando para migrar una LIF de clúster desde el nodo donde se aloja la LIF del clúster.



== Sustituya el interruptor

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la nomenclatura de conmutador y nodo siguiente:

* Los nombres de los conmutadores NVIDIA SN2100 existentes son _sw1_ y _sw2_.
* El nombre del nuevo switch NVIDIA SN2100 es _nsw2_.
* Los nombres de nodo son _1_ y _2_.
* Los puertos de clúster de cada nodo se denominan _e3a_ y _e3b_.
* Los nombres de LIF del clúster son _1_clus1_ y _1_clus2_ para los nodos 1, y _2_clus1_ y _2_clus2_ para los nodos 2.
* El prompt de cambios en todos los nodos del clúster es `cluster1::*>`
* Los puertos de arranque tienen el formato: swp[Port]s[breakout Port 0-3]. Por ejemplo, cuatro puertos de arranque en swp1 son _swp1s0_, _swp1s1_, _swp1s2_ y _swp1s3_.


.Acerca de la topología de red del clúster
Este procedimiento se basa en la siguiente topología de red de clúster:

.Mostrar topología de ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false


cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true


cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
+

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw2                e3a
swp4       100G   Trunk/L2    sw2                e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16


cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw1                e3b
swp4       100G   Trunk/L2    sw1                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====


=== Paso 1: Prepararse para la sustitución

. Si se habilita AutoSupport en este clúster, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
donde _x_ es la duración de la ventana de mantenimiento en horas.

. Cambie el nivel de privilegio a avanzado, introduciendo *y* cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el mensaje avanzado (*>).

. Instale el RCF y la imagen adecuados en el interruptor, nsw2, y realice las preparaciones necesarias del sitio.
+
Si es necesario, verifique, descargue e instale las versiones apropiadas del software RCF y Cumulus para el nuevo interruptor.

+
.. Puede descargar el software Cumulus correspondiente para los switches de clúster del sitio _NVIDIA Support_. Siga los pasos de la página de descarga para descargar Cumulus Linux para la versión del software ONTAP que está instalando.
.. El RCF adecuado está disponible en link:https://mysupport.netapp.com/site/products/all/details/nvidia-cluster-storage-switch/downloads-tab["_Cluster de NVIDIA y switches de almacenamiento_"^] página. Siga los pasos de la página de descarga para descargar el RCF correcto para la versión del software ONTAP que está instalando.






=== Paso 2: Configure los puertos y el cableado

. En el nuevo switch nsw2, inicie sesión como administrador y apague todos los puertos que se conectarán a las interfaces de clúster del nodo (puertos swp1 a swp14).
+
Los LIF de los nodos del clúster ya deberían haber realizado la conmutación al otro puerto del clúster para cada nodo.

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
====
. Deshabilite la reversión automática en las LIF del clúster:
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

Warning: Disabling the auto-revert feature of the cluster logical interface may effect the availability of your cluster network. Are you sure you want to continue? {y|n}: *y*
----
====
. Compruebe que todas las LIF del clúster tengan la reversión automática habilitada:
+
`net interface show -vserver Cluster -fields auto-revert`

. Apague los puertos ISL swp15 y swp16 en el conmutador SN2100 sw1.
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. Retire todos los cables del conmutador SN2100 sw1 y, a continuación, conéctelos a los mismos puertos del conmutador SN2100 nsw2.
. Suba los puertos ISL swp15 y swp16 entre los switches sw1 y nsw2.
+
.Muestra el ejemplo
[%collapsible]
====
Los siguientes comandos habilitan los puertos ISL swp15 y swp16 en el switch sw1:

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
En el siguiente ejemplo, se muestra que los puertos ISL están activos en la switch sw1:

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------- ----------------------
...
...
UP     swp15        100G  9216   BondMember  nsw2 (swp15)   Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  nsw2 (swp16)   Master: cluster_isl(UP)
----
+ el siguiente ejemplo muestra que los puertos ISL están activos en el switch nsw2:

+

[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------  -----------------------
...
...
UP     swp15        100G  9216   BondMember  sw1 (swp15)    Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)    Master: cluster_isl(UP)
----
====
. Compruebe que el puerto `e3b` está activo en todos los nodos:
+
`network port show -ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
La salida debe ser similar a la siguiente:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ------------ -------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false


Node: node2
                                                                         Ignore
                                                   Speed(Mbps) Health    Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status    Status
--------- ------------ ---------------- ---- ----- ----------- --------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false
----
====
. Los puertos de clúster de cada nodo ahora están conectados a los switches de clúster del siguiente modo, desde la perspectiva de los nodos:
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp3          -
node2      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp4          -
----
====
. Compruebe que todos los puertos de clúster del nodo estén activos:
+
`net show interface`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. Compruebe que ambos nodos tengan una conexión cada uno con cada switch:
+
`net show lldp`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo, se muestran los resultados adecuados para ambos switches:

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  nsw2               swp15
swp16      100G   BondMember  nsw2               swp16


cumulus@nsw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1                e3b
swp4       100G   Trunk/L2    node2                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====
. Habilite la reversión automática en las LIF del clúster:
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. En el switch nsw2, conecte los puertos conectados a los puertos de red de los nodos.
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net del interface swp1-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
====
. Muestra información sobre los nodos de un clúster:
+
`cluster show`

+
.Muestra el ejemplo
[%collapsible]
====
En este ejemplo, se muestra que el estado del nodo para el nodo 1 y el nodo 2 en este clúster es TRUE.

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node          Health  Eligibility
------------- ------- ------------
node1         true    true
node2         true    true
----
====
. Compruebe que todos los puertos físicos del clúster estén en funcionamiento:
+
`network port show ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node node1                                                               Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper  Status   Status
--------- ----------- ----------------- ----- ----- ----------- -------- ------
e3a       Cluster     Cluster           up    9000  auto/10000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/10000  healthy  false

Node: node2
                                                                         Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ----- ----- ----------- -------- ------
e3a       Cluster      Cluster          up    9000  auto/10000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/10000  healthy  false
----
====




=== Paso 3: Complete el procedimiento

. Compruebe que la red de clúster esté en buen estado.
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost      RemotePort
---------  -----  ----------  --------------  -----------
swp3       100G   Trunk/L2    node1           e3a
swp4       100G   Trunk/L2    node2           e3a
swp15      100G   BondMember  nsw2            swp15
swp16      100G   BondMember  nsw2            swp16
----
====
. Habilite la función de recogida de registros de control de estado del switch Ethernet para recopilar archivos de registro relacionados con el switch mediante los comandos:
+
`system switch ethernet log setup-password` y.. `system switch ethernet log enable-collection`

+
.. Introduzca: `system switch ethernet log setup-password`
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*sw1*
*nsw2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *nsw2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
.. Seguido de: `system switch ethernet log enable-collection`
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
====
+

NOTE: Si alguno de estos comandos devuelve un error, póngase en contacto con el soporte de NetApp.



. Inicie la función de recopilación de registros del switch:
+
`system switch ethernet log collect -device *`

+
Espere 10 minutos y compruebe que la recopilación del registro se ha realizado correctamente mediante el comando: `system switch ethernet log show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show*
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      sw1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete   
2      nsw2 (b8:ce:f6:19:1b:96)     4/29/2022 03:07:42   complete
----
====
. Vuelva a cambiar el nivel de privilegio a admin:
+
`set -privilege admin`

. Si ha suprimido la creación automática de casos, vuelva a habilitarla invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


