---
permalink: switch-nvidia-sn2100/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for SN2100 switches' 
summary: Puede utilizar este procedimiento para instalar el archivo de configuración correspondiente para la supervisión del estado del switch del clúster de los switches de clúster NVIDIA SN2100. 
---
= Instale el archivo de configuración del monitor de estado del switch Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para instalar el archivo de configuración correspondiente para la supervisión del estado del switch Ethernet de los switches de clúster NVIDIA. Los modelos admitidos son:

* X190006-PE
* X190006-PI



NOTE: Este procedimiento de instalación se aplica a ONTAP 9.10.1 y versiones posteriores.

.Antes de empezar
* Verifique que necesita descargar el archivo de configuración ejecutando `system switch ethernet show` y comprobando si se muestra *OTHER* para su modelo.
+
Si su modelo sigue mostrando *OTHER* después de aplicar el archivo de configuración, póngase en contacto con el servicio de asistencia técnica de NetApp.

* Asegúrese de que el clúster de ONTAP esté en funcionamiento.
* Active SSH para utilizar todas las funciones disponibles en CSHM.


.Pasos
. Descargue el archivo zip de configuración del monitor de estado del switch Ethernet según la versión de ONTAP correspondiente. Este archivo está disponible en la https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Switches Ethernet de NVIDIA"^] página.
+
.. En la página de descarga del software NVIDIA SN2100, seleccione *Nvidia CSHM File*.
.. En la página Precaución/debe leer, seleccione la casilla de verificación para aceptar.
.. En la página Contrato de licencia de usuario final, seleccione la casilla de verificación para aceptar y haga clic en *Aceptar y continuar*.
.. En la página Nvidia CSHM File - Download, seleccione el archivo de configuración aplicable. Están disponibles los siguientes archivos:




[role="tabbed-block"]
====
.ONTAP 9.15.1 y versiones posteriores
--
* X190006-PE.zip
* X190006-PI.zip


--
.ONTAP 9.11.1 a 9.14.1
--
* X190006-PE_PRIOR_9.15.1.zip
* X190006-PI_PRIOR_9.15.1.zip


--
====
. [[step2]]Cargue el archivo zip correspondiente al servidor web interno.
. Acceda a la configuración de modo avanzado desde uno de los sistemas ONTAP en el clúster.
+
`set -privilege advanced`

. Ejecute el comando switch health monitor configure.
+
[listing, subs="+quotes"]
----
cluster1::> *system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/_[filename.zip]_*
----
. Compruebe que el resultado del comando termine con el siguiente texto para su versión de ONTAP:


[role="tabbed-block"]
====
.ONTAP 9.15.1 y versiones posteriores
--
La supervisión de estado del switch Ethernet ha instalado el archivo de configuración.

--
.ONTAP 9.11.1 a 9.14.1
--
SHM instaló el archivo de configuración.

--
.ONTAP 9.10.1
--
El paquete descargado de CSHM se ha procesado correctamente.

--
====
Si se produce un error, póngase en contacto con el soporte de NetApp.

. [[step6]]Espere hasta dos veces el intervalo de sondeo del monitor de estado del switch Ethernet, que se encuentra ejecutando `system switch ethernet polling-interval show`, antes de completar el siguiente paso.
. Ejecute el comando `system switch ethernet show` en el sistema ONTAP y asegúrese de que los conmutadores del clúster se descubran con el campo Monitorizado establecido en *Verdadero* y el campo de número de serie no muestre *Desconocido*.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
----

