---
permalink: switch-nvidia-sn2100/upgrade-cl-version.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Complete los siguientes pasos para actualizar su versión de Cumulus Linux. 
---
= Actualice las versiones de Cumulus Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Complete el siguiente procedimiento para actualizar la versión de Cumulus Linux según sea necesario.

.Lo que necesitará
* Conocimientos de Linux de nivel intermedio.
* Estar familiarizado con la edición de texto básica, los permisos de archivos UNIX y la supervisión de procesos. Una variedad de editores de texto están preinstalados, incluyendo `vi` y.. `nano`.
* Acceso a un shell de Linux o UNIX. Si ejecuta Windows, utilice un entorno Linux como herramienta de línea de comandos para interactuar con Cumulus Linux.
* El requisito de velocidad en baudios se establece en 115200 en el conmutador de consola serie para el acceso a la consola del conmutador NVIDIA SN2100 de la siguiente manera:
+
** 115200 baudios
** 8 bits de datos
** 1 bit de parada
** paridad: none
** control de flujo: ninguno




.Acerca de esta tarea
Tenga en cuenta lo siguiente:


NOTE: Cada vez que se actualiza Cumulus Linux, se borra y reconstruye toda la estructura del sistema de archivos. La configuración existente se borrará. Debe guardar y registrar la configuración del switch antes de actualizar Cumulus Linux.


CAUTION: La contraseña predeterminada para la cuenta de usuario de cumulus es *cumulus*. La primera vez que inicie sesión en Cumulus Linux, debe cambiar esta contraseña predeterminada. Debe actualizar todos los scripts de automatización antes de instalar una imagen nueva. Cumulus Linux proporciona opciones de línea de comandos para cambiar automáticamente la contraseña predeterminada durante el proceso de instalación.

.Pasos
[role="tabbed-block"]
====
.De Cumulus Linux 4,4.x a Cumulus Linux 5.x
--
. Compruebe la versión actual de Cumulus Linux y los puertos conectados:
+
[listing, subs="+quotes"]
----
admin@sw1:mgmt:~$ *net show system*
Hostname......... cumulus
Build............ *Cumulus Linux 4.4.3*
Uptime........... 0:08:20.860000
Model............ Mlnx X86
CPU.............. x86_64 Intel Atom C2558 2.40GHz
Memory........... 8GB
Disk............. 14.7GB
ASIC............. Mellanox Spectrum MT52132
Ports............ 16 x 100G-QSFP28
Part Number...... MSN2100-CB2FC
Serial Number.... MT2105T05177
Platform Name.... x86_64-mlnx_x86-r0
Product Name..... MSN2100
ONIE Version..... 2019.11-5.2.0020-115200
Base MAC Address. 04:3F:72:43:92:80
Manufacturer..... Mellanox

admin@sw1:mgmt:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                    Summary
-----  ------  ----  -----  ----------  ----------------------  --------------------
.
.
UP     swp1    100G  9216   Trunk/L2    node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2    node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2    SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2    SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2    SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2    SHFFG1826000102 (e0b)   Master: bridge(UP))
.
.
----
. Descargue la imagen de Cumulux Linux 5.x:
+
[listing, subs="+quotes"]
----
admin@sw1:mgmt:~$ *sudo onie-install -a -i http://10.60.132.97/x/eng/testbedN,svl/nic/files/NVIDIA/cumulus-linux-5.4.0-mlx-amd64.bin/*
[sudo] password for cumulus:
Fetching installer: http://10.60.132.97/x/eng/testbedN,svl/nic/files/NVIDIA/cumulus-linux-5.4.0-mlx-amd64.bin
Downloading URL: http://10.60.132.97/x/eng/testbedN,svl/nic/files/NVIDIA/cumulus-linux-5.4.0-mlx-amd64.bin
######################################################################### 100.0%
Success: HTTP download complete.
EFI variables are not supported on this system
Warning: SecureBoot is not available.
Image is signed.
.
.
.
Staging installer image...done.
WARNING:
WARNING: Activating staged installer requested.
WARNING: This action will wipe out all system data.
WARNING: Make sure to back up your data.
WARNING:
Are you sure (y/N)? *y*
Activating staged installer...done.
Reboot required to take effect.
----
. Reinicie el switch:
+
[listing, subs="+quotes"]
----
admin@sw1:mgmt:~$ *sudo onie-install -a -i http://10.60.132.97/x/eng/testbedN,svl/nic/files/NVIDIA/cumulus-linux-5.4.0-mlx-amd64.bin/*
 *sudo reboot*
----
. Cambie la contraseña:
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password:
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)

ZTP in progress. To disable, do 'ztp -d'
----
. Compruebe la versión de Cumulus Linux: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
           operational    applied
---------- -------------- ----------
hostname   cumulus        cumulus
build      Cumulus Linux 5.4.0
uptime     14:07:08
timezone   Etc/UTC
----
. Cambie el nombre de host:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv config apply*
Warning: The following files have been changed since the last save, and they WILL be overwritten.
- /etc/nsswitch.conf
- /etc/synced/synced.conf
.
.
----
. Cierre la sesión e inicie sesión en el conmutador de nuevo para ver el nombre del conmutador actualizado en el prompt:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *exit*
logout

Debian GNU/Linux 10 cumulus ttyS0

cumulus login: *cumulus*
Password:
Last login: Tue Dec 15 21:43:13 UTC 2020 on ttyS0
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)


ZTP in progress. To disable, do 'ztp -d'

cumulus@sw1:mgmt:~$
----
. Establezca la dirección IP:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip address 10.231.80.206*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip gateway 10.231.80.1*
cumulus@sw1:mgmt:~$ *nv config apply*
applied [rev_id: 2]
cumulus@sw1:mgmt:~$ *ip route show vrf mgmt*
default via 10.231.80.1 dev eth0 proto kernel
unreachable default metric 4278198272
10.231.80.0/22 dev eth0 proto kernel scope link src 10.231.80.206
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Cree un nuevo usuario y agregue este usuario a `sudo` grupo. Este usuario sólo se hace efectivo después de reiniciar la sesión de la consola/SSH.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. Agregue grupos de usuarios adicionales al que pueda acceder el usuario administrador `nv` comandos:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user `admin' to group `nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
Consulte https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["Cuentas de usuario de NVIDIA"^] si quiere más información.



--
.De Cumulus Linux 5.x a Cumulus Linux 5.x
--
. Compruebe la versión actual de Cumulus Linux y los puertos conectados:
+
[listing, subs="+quotes"]
----
admin@sw1:mgmt:~$ *nv show system*
                    operational          applied
------------------- -------------------- -----------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.3.0
uptime              6 days, 8:37:36
timezone            Etc/UTC

admin@sw1:mgmt:~$ *nv show interface*
Interface     MTU   Speed State Remote Host         Remote Port- Type      Summary
------------- ----- ----- ----- ------------------- ------------ --------- -------------
+ cluster_isl 9216  200G  up                                      bond
+ eth0        1500  100M  up    mgmt-sw1            Eth105/1/14   eth       IP Address: 10.231.80 206/22
  eth0                                                                      IP Address: fd20:8b1e:f6ff:fe31:4a0e/64
+ lo          65536       up                                      loopback  IP Address: 127.0.0.1/8
  lo                                                                        IP Address: ::1/128
+ swp1s0      9216 10G    up cluster01                e0b         swp
.
.
.
+ swp15      9216 100G    up sw2                      swp15       swp
+ swp16      9216 100G    up sw2                      swp16       swp
----
. Descargue la imagen de Cumulux Linux 5.4.0:
+
[listing, subs="+quotes"]
----
admin@sw1:mgmt:~$ *sudo onie-install -a -i http://10.60.132.97/x/eng/testbedN,svl/nic/files/NVIDIA/cumulus-linux-5.4.0-mlx-amd64.bin/*
[sudo] password for cumulus:
Fetching installer: http://10.60.132.97/x/eng/testbedN,svl/nic/files/NVIDIA/cumulus-linux-5.4.0-mlx-amd64.bin
Downloading URL: http://10.60.132.97/x/eng/testbedN,svl/nic/files/NVIDIA/cumulus-linux-5.4.0-mlx-amd64.bin
######################################################################### 100.0%
Success: HTTP download complete.
EFI variables are not supported on this system
Warning: SecureBoot is not available.
Image is signed.
.
.
.
Staging installer image...done.
WARNING:
WARNING: Activating staged installer requested.
WARNING: This action will wipe out all system data.
WARNING: Make sure to back up your data.
WARNING:
Are you sure (y/N)? *y*
Activating staged installer...done.
Reboot required to take effect.
----
. Reinicie el switch:
+
[listing, subs="+quotes"]
----
admin@sw1:mgmt:~$ *sudo reboot*
----
. Cambie la contraseña:
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password:
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)

ZTP in progress. To disable, do 'ztp -d'
----
. Compruebe la versión de Cumulus Linux: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational    applied
-------------- ----------------
hostname       cumulus cumulus
build          Cumulus Linux 5.4.0
uptime         14:07:08
timezone       Etc/UTC
----
. Cambie el nombre de host:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv config apply*
Warning: The following files have been changed since the last save, and they WILL be overwritten.
- /etc/nsswitch.conf
- /etc/synced/synced.conf
.
.
----
. Cierre la sesión y vuelva a iniciar sesión en el conmutador para ver el nombre del conmutador actualizado en el prompt:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *exit*
logout

Debian GNU/Linux 10 cumulus ttyS0

cumulus login: *cumulus*
Password:
Last login: Tue Dec 15 21:43:13 UTC 2020 on ttyS0
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)


ZTP in progress. To disable, do 'ztp -d'

cumulus@sw1:mgmt:~$
----
. Establezca la dirección IP:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip address 10.231.80.206*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip gateway 10.231.80.1*
cumulus@sw1:mgmt:~$ *nv config apply*
applied [rev_id: 2]
cumulus@sw1:mgmt:~$ *ip route show vrf mgmt*
default via 10.231.80.1 dev eth0 proto kernel
unreachable default metric 4278198272
10.231.80.0/22 dev eth0 proto kernel scope link src 10.231.80.206
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Cree un nuevo usuario y agregue este usuario a `sudo` grupo. Este usuario sólo se hace efectivo después de reiniciar la sesión de la consola/SSH.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. Agregue grupos de usuarios adicionales al que pueda acceder el usuario administrador `nv` comandos:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user `admin' to group `nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
Consulte https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["Cuentas de usuario de NVIDIA"^] si quiere más información.



--
====
.El futuro
link:install-rcf-sn2100-cluster.html["Instale la secuencia de comandos del archivo de configuración de referencia (RCF)"].
