---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-storage/configure-reqs-9336c-storage.html 
keywords: shared storage cluster switch 
summary: A partir de ONTAP 9.9.1, puede utilizar los conmutadores Cisco Nexus 9336C-FX2 para combinar la funcionalidad de almacenamiento y clúster en un escenario de conmutador compartido. 
---
= Requisitos de configuración para los conmutadores de almacenamiento Cisco Nexus 9336C-FX2 y 9336C-FX2-T
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento de los conmutadores Cisco Nexus 9336C-FX2 y 9336C-FX2-T, asegúrese de revisar la configuración y los requisitos de red.



== Requisitos de configuración

Para la configuración, necesitará el número y tipo adecuados de cables y conectores de cable para sus conmutadores.

Dependiendo del tipo de switch que esté configurando inicialmente, deberá conectarse al puerto de consola del switch con el cable de consola incluido; también deberá proporcionar información de red específica.



== Requisitos de red

Necesita la siguiente información de red para todas las configuraciones del conmutador.

* Subred IP para la gestión del tráfico de red
* Nombres de host y direcciones IP para cada uno de los controladores del sistema de almacenamiento y todos los conmutadores aplicables
* La mayoría de los controladores del sistema de almacenamiento se administran a través de la interfaz e0M conectándose al puerto de servicio Ethernet (ícono de llave inglesa). En los sistemas AFF A800 y AFF A700s , la interfaz e0M utiliza un puerto Ethernet dedicado.
* Consulte el https://hwu.netapp.com["Hardware Universe"] Para obtener la información más reciente.


Para obtener más información sobre la configuración inicial de su switch, consulte la siguiente guía: https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Guía de instalación y actualización de Cisco Nexus 9336C-FX2"] .

.¿Qué sigue?
Después de revisar los requisitos de configuración, puede confirmar su link:components-9336c-storage.html["componentes y números de pieza"].
