---
permalink: switch-cisco-9336c-fx2-storage/configure-software-overview-9336c-storage.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Descripción general de la configuración de software de los switches de almacenamiento Cisco Nexus 9336C-FX2 
---
= Flujo de trabajo de instalación de software para los switches de almacenamiento Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar y configurar el software para un switch de almacenamiento Cisco Nexus 9336C-FX2, siga estos pasos:

. link:install-nxos-overview-9336c-storage.html["Prepárese para instalar o actualizar NX-OS y RCF"].
+
Los archivos de configuración de referencia y el software del sistema operativo Cisco NX deben instalarse en los switches de almacenamiento Nexus 9336C-FX2 de Cisco.

. link:install-nxos-software-9336c-storage.html["Instale o actualice el software NX-OS"].
+
Descargue e instale o actualice el software NX-OS en el switch de almacenamiento Nexus 9336C-FX2 de Cisco.

. link:install-rcf-software-9336c-storage.html["Instale o actualice el archivo de configuración de RCF"].
+
Instale o actualice el RCF después de configurar por primera vez el switch de almacenamiento Nexus 9336C-FX2 de Cisco. También puede utilizar este procedimiento para actualizar la versión de RCF.


