---
permalink: switch-cisco-9336c-fx2-storage/install-nxos-software-9336c-storage.html 
sidebar: sidebar 
keywords: procedure, install, nx-os, software, nexus, cluster, switch, install the nx-os software - cisco nexus 9336c-fx2 
summary: Puede utilizar este procedimiento para instalar el software NX-OS en el conmutador de clúster Nexus 9336C-FX2. 
---
= Instale o actualice el software NX-OS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sigue este procedimiento para instalar o actualizar el software NX-OS en los switches Nexus 9336C-FX2 y 9336C-FX2-T.

Antes de comenzar, complete el procedimiento enlink:install-nxos-overview-9336c-storage.html["Prepárese para instalar NX-OS y RCF."] .



== Requisitos de revisión

.Antes de empezar
Asegúrese de tener lo siguiente:

* Una copia de seguridad actualizada de la configuración del switch.
* Un clúster en pleno funcionamiento (sin errores en los registros ni problemas similares).


.Documentación sugerida
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["página del switch Ethernet de Cisco"^]
+
Consulte la tabla de compatibilidad del switch para conocer las versiones compatibles de ONTAP y NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-guides-list.html["Guías de actualización y degradación de software"^]
+
Consulte las guías de software y actualización correspondientes disponibles en el sitio web de Cisco para obtener documentación completa sobre los procedimientos de actualización y degradación de los switches de Cisco .

* link:https://www.cisco.com/c/dam/en/us/td/docs/dcn/tools/nexus-9k3k-issu-matrix/index.html["Matriz de actualización e ISSU de Cisco Nexus 9000 y 3000"^]
+
Proporciona información sobre la actualización/degradación disruptiva del software Cisco NX-OS en los switches de la serie Nexus 9000, según sus versiones actuales y objetivo.

+
En la página, seleccione *Actualización disruptiva* y seleccione su versión actual y la versión objetivo de la lista desplegable.



.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los nombres de los dos Cisco switches son s1 y s2.
* Los nombres de los nodos son cluster1-01 y cluster1-02.




== Instala o actualiza el software

El procedimiento requiere el uso de comandos ONTAP y comandos de switches Cisco Nexus serie 9000; se utilizan comandos ONTAP a menos que se indique lo contrario.

.Pasos
. Conecte el conmutador a la red de administración.
. Utilice el `ping` comando para verificar la conectividad con el servidor que aloja el software NX-OS y el RCF.
+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo verifica que el switch puede alcanzar el servidor en la dirección IP 172.19.2.1:

[listing, subs="+quotes"]
----
s2# *ping 172.19.2.1 VRF management*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Si estás configurando tu switch por primera vez, salta al paso 5. Si estás actualizando tu switch, sigue con el siguiente paso.
. Comprueba el estado administrativo u operativo de cada puerto de almacenamiento de nodo y de cada puerto de estantería de almacenamiento.
+
.. Muestra los atributos del puerto de almacenamiento del nodo:
+
[source, cli]
----
storage port show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
.
.
----
====
.. Muestra los atributos del puerto de la estantería de almacenamiento:
+
[source, cli]
----
storage shelf port show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verifica que la supervisión del estado del conmutador (CSHM) esté activada para el switch, así los switches serán supervisados:
+
[source, cli]
----
system switch ethernet show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====


. Inicia sesión en el switch usando SSH o usando una consola serie.
. Copie el software NX-OS y las imágenes EPLD al conmutador Nexus 9336C-FX2.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.9.3.5.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.3.5.bin  /bootflash/nxos.9.3.5.bin
/code/nxos.9.3.5.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.


s2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.9.3.5.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.3.5.img  /bootflash/n9000-epld.9.3.5.img
/code/n9000-epld.9.3.5.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. Verifique la versión en ejecución del software NX-OS:
+
`show version`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.38
  NXOS: version 9.3(4)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]


Hardware
  cisco Nexus9000 C9336C-FX2 Chassis
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: s2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)


Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset Requested by CLI command reload
  System version: 9.3(4)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
----
====
. Instale la imagen NX-OS.
+
La instalación del archivo de imagen provoca que este se cargue cada vez que se reinicie el switch.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *install all nxos bootflash:nxos.9.3.5.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.5.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.5.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.5.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS



Compatibility check is done:
Module  Bootable  Impact          Install-type  Reason
------  --------  --------------- ------------  ---------
  1     yes       Disruptive      Reset         Default upgrade is not hitless



Images will be upgraded according to following table:

Module   Image    Running-Version(pri:alt)                 New-Version         Upg-Required
------- --------- ---------------------------------------- ------------------- ------------
  1      nxos     9.3(4)                                   9.3(5)                  yes
  1      bios     v08.37(01/28/2020):v08.23(09/23/2015)    v08.38(05/29/2020)      yes


Switch will be reloaded for disruptive upgrade.

Do you want to continue with the installation (y/n)? [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS

Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. Verifique la nueva versión del software NX-OS después de que el switch se haya reiniciado:
+
`show version`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version*

Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 05.33
  NXOS: version 9.3(5)
  BIOS compile time:  09/08/2018
  NXOS image file is: bootflash:///nxos.9.3.5.bin
  NXOS compile time:  11/4/2018 21:00:00 [11/05/2018 06:11:06]


Hardware
  cisco Nexus9000 C9336C-FX2 Chassis
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: s2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)

Last reset at 277524 usecs after Mon Nov  2 22:45:12 2020
  Reason: Reset due to upgrade
  System version: 9.3(4)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
----
====
. Actualice la imagen EPLD y reinicie el switch.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                        0x7
IO   FPGA                        0x17
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2

s2# *install epld bootflash:n9000-epld.9.3.5.img module all*
Compatibility check:
Module        Type         Upgradable        Impact    Reason
------  ------------------ ----------------- --------- -----------
     1         SUP         Yes       disruptive  Module Upgradable

Retrieving EPLD versions.... Please wait.
Images will be upgraded according to following table:
Module  Type   EPLD              Running-Version   New-Version  Upg-Required
------- ------ ----------------- ----------------- ------------ ------------
     1  SUP    MI FPGA           0x07              0x07         No
     1  SUP    IO FPGA           0x17              0x19         Yes
     1  SUP    MI FPGA2          0x02              0x02         No
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] *y*

Proceeding to upgrade Modules.

Starting Module 1 EPLD Upgrade

Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sectors)
Module 1 EPLD upgrade is successful.
Module   Type  Upgrade-Result
-------- ----- --------------
     1   SUP   Success

EPLDs upgraded.

Module 1 EPLD upgrade is successful.
----
====
. Después de que el switch se reinicie, inicia sesión de nuevo y verifica que la nueva versión de EPLD se cargó correctamente.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                        0x7
IO   FPGA                        0x19
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
----
====
. Si estás configurando tu switch por primera vez, salta al paso 14. Si estás actualizando tu switch, sigue con el siguiente paso.
. Verifica el estado de salud de cada puerto de almacenamiento de nodo y de cada puerto de estantería de almacenamiento.
+
.. Muestra los atributos del puerto de almacenamiento del nodo:
+
[source, cli]
----
storage port show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
.
.
----
====
.. Muestra los atributos del puerto de la estantería de almacenamiento:
+
[source, cli]
----
storage shelf port show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verifica que el control del estado del switch (CSHM) esté activado para los switches para que se monitoreen:
+
[source, cli]
----
system switch ethernet show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====


. Repite los pasos 5 al 13 para instalar el software NX-OS en el switch s1.


.¿Que sigue?
Después de instalar o actualizar el software NX-OS, puedelink:install-rcf-software-9336c-storage.html["instalar o actualizar el RCF"] .
