---
permalink: switch-cisco-9336c-fx2-storage/install-nxos-overview-9336c-storage.html 
sidebar: sidebar 
keywords: cisco, nx-os, software, reference, configuration, file, rcf, install, fx2, cluster, switch, install nx-os software and rcfs on cisco nexus 9336-fx2 cluster switches - cisco nexus 9336x-fx2 
summary: 'Se deben instalar el software Cisco NX-OS y los archivos de configuración de referencia \(RCF\) en los switches de clúster Cisco Nexus 9336C-FX2.' 
---
= Prepárese para instalar o actualizar el software NX-OS y RCF
:allow-uri-read: 


[role="lead"]
Antes de instalar el software NX-OS y el archivo de configuración de referencia (RCF), siga este procedimiento.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la nomenclatura de conmutador y nodo siguiente:

* Los nombres de los dos switches de Cisco son cs1 y cs2.
* Los nombres de nodo son cluster1-01 y cluster1-02.
* Los nombres de las LIF de clúster son cluster1-01_clus1 y cluster1-01_clus2 para cluster1-01 y cluster1-02_clus1 y cluster1-02_clus2 para cluster1-02.
* La `cluster1::*>` prompt indica el nombre del clúster.


.Acerca de esta tarea
Para ello, es necesario utilizar tanto comandos de la ONTAP como comandos de la serie Cisco Nexus 9000; los comandos de la ONTAP se usan a menos que se indique lo contrario.

.Pasos
. Si se habilita AutoSupport en este clúster, elimine la creación automática de casos invocando un mensaje de AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=x h`
+
donde x es la duración de la ventana de mantenimiento en horas.

+

NOTE: El mensaje de AutoSupport notifica al soporte técnico de esta tarea de mantenimiento para que la creación automática de casos se suprima durante la ventana de mantenimiento.

. Cambie el nivel de privilegio a avanzado, introduciendo *y* cuando se le solicite continuar:
+
[source, cli]
----
set -privilege advanced
----
+
El aviso avanzado (`*>`) aparece.

. Muestre cuántas interfaces de interconexión de clúster se han configurado en cada nodo para cada switch de interconexión de clúster:
+
[source, cli]
----
network device-discovery show -protocol lldp
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/lldp
            e0a    cs1                       Eth1/2            N9K-C9336C
            e0b    cs2                       Eth1/2            N9K-C9336C
cluster1-01/lldp
            e0a    cs1                       Eth1/1            N9K-C9336C
            e0b    cs2                       Eth1/1            N9K-C9336C

4 entries were displayed.
----
====
. Compruebe el estado administrativo u operativo de cada interfaz de clúster.
+
.. Mostrar los atributos del puerto de red:
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: cluster1-02
                                                                       Ignore
                                                  Speed(Mbps)  Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status  Status
--------- ------------ ---------------- ---- ---- ------------ ------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: cluster1-01
                                                                       Ignore
                                                  Speed(Mbps)  Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status  Status
--------- ------------ ---------------- ---- ---- ------------ ------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false

4 entries were displayed.
----
====
.. Mostrar información acerca de las LIF:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical            Status     Network            Current       Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node          Port    Home
----------- ------------------ ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.209.69/16  cluster1-01   e0a     true
            cluster1-01_clus2  up/up      169.254.49.125/16  cluster1-01   e0b     true
            cluster1-02_clus1  up/up      169.254.47.194/16  cluster1-02   e0a     true
            cluster1-02_clus2  up/up      169.254.19.183/16  cluster1-02   e0b     true

4 entries were displayed.
----
====


. Compruebe la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y versiones posteriores
--
Puede utilizar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad de la conectividad del clúster y, a continuación, muestre los detalles:

`network interface check cluster-connectivity start` y.. `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere varios segundos antes de ejecutar el `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source               Destination         Packet
Node   Date                       LIF                  LIF                 Loss
------ -------------------------- -------------------- ------------------- -----------
node1
       3/5/2024 19:21:18 -06:00   cluster1-01_clus2    cluster1-02-clus1   none
       3/5/2024 19:21:20 -06:00   cluster1-01_clus2    cluster1-02_clus2   none
node2
       3/5/2024 19:21:18 -06:00   cluster1-02_clus2    cluster1-01_clus1   none
       3/5/2024 19:21:20 -06:00   cluster1-02_clus2    cluster1-01_clus2   none
----
--
.Todos los lanzamientos de ONTAP
--
En todas las versiones de ONTAP, también se puede utilizar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is cluster1-02
Getting addresses from network interface table...
Cluster cluster1-01_clus1 169.254.209.69 cluster1-01     e0a
Cluster cluster1-01_clus2 169.254.49.125 cluster1-01     e0b
Cluster cluster1-02_clus1 169.254.47.194 cluster1-02     e0a
Cluster cluster1-02_clus2 169.254.19.183 cluster1-02     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step6]] Verifique que el comando de reversión automática esté habilitado en todas las LIF de clúster:
+
[source, cli]
----
network interface show -vserver Cluster -fields auto-revert
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface           Auto-revert
--------- ------------------- ------------
Cluster
          cluster1-01_clus1   true
          cluster1-01_clus2   true
          cluster1-02_clus1   true
          cluster1-02_clus2   true
4 entries were displayed.
----
====


.El futuro
Una vez que se haya preparado para instalar el software NX-OS y RCF, debelink:install-nxos-software-9336c-storage.html["instalar o actualizar el software NX-OS"] .
