---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Si aún no dispone de la información de configuración y la documentación necesarias, deberá recopilarlas antes de configurar el clúster y los conmutadores de red de administración. 
---
= Instalar los conmutadores de almacenamiento 9336C-FX2 y 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para instalar los conmutadores de almacenamiento Cisco Nexus 9336C-FX2 y 9336C-FX2-T.

.Antes de empezar
Asegúrese de tener lo siguiente:

* Acceso a un servidor HTTP, FTP o TFTP en el sitio de instalación para descargar las versiones aplicables de NX-OS y el archivo de configuración de referencia (RCF).
* Versión aplicable de NX-OS, descargada de https://software.cisco.com/download/home["Descarga de software de Cisco"^] página.
* Licencias aplicables, información de red y configuración, y cables.
* Terminadolink:setup-worksheet-9336c-storage.html["hojas de trabajo de cableado"] .
* Los archivos RCF de red de clúster y de red de administración de NetApp aplicables se descargaron del sitio de soporte de NetApp en http://mysupport.netapp.com/["mysupport.netapp.com"^] .  Todos los switches de red de clúster y de red de administración de Cisco vienen con la configuración predeterminada de fábrica estándar de Cisco . Estos conmutadores también tienen la versión actual del software NX-OS pero no tienen los RCF cargados.
* Documentación requerida del interruptor. Verlink:required-documentation-9336c-storage.html["Documentación requerida"] Para más información.


.Pasos
. Instale en rack los conmutadores y controladores de la red del clúster y de la red de administración.
+
[cols="1,2"]
|===
| Si estás instalando tu... | Entonces... 


 a| 
Cisco Nexus 9336C-FX2 en un gabinete de sistema NetApp
 a| 
Verlink:install-switch-and-passthrough-panel-9336c-storage.html["Instale el switch en el armario NetApp."] Para obtener instrucciones sobre cómo instalar el switch en un armario NetApp .



 a| 
Equipos en un rack de telecomunicaciones
 a| 
Consulte los procedimientos proporcionados en las guías de instalación del hardware del switch y las instrucciones de instalación y configuración de NetApp .

|===
. Conecte los conmutadores de red del clúster y de la red de administración a los controladores utilizando las hojas de trabajo de cableado completadas.
. Encienda la alimentación de los conmutadores y controladores de la red del clúster y de la red de administración.


.¿Que sigue?
Opcionalmente, puedes link:install-switch-and-passthrough-panel-9336c-storage.html["Instalar un conmutador Cisco Nexus 9336C-FX2 en un gabinete NetApp"]. De lo contrario, vaya a link:setup-switch-9336c-storage.html["configurar el conmutador"].
