---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, storage, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Si aún no tienes la información y la documentación de configuración necesarias, necesitas reunir esa información antes de configurar tus switches de red de almacenamiento y gestión. 
---
= Instalar los conmutadores de almacenamiento 9336C-FX2 y 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para instalar los conmutadores de almacenamiento Cisco Nexus 9336C-FX2 y 9336C-FX2-T.

.Antes de empezar
Asegúrese de tener lo siguiente:

* Acceso a un servidor HTTP, FTP o TFTP en el sitio de instalación para descargar las versiones aplicables de NX-OS y el archivo de configuración de referencia (RCF).
* Versión aplicable de NX-OS, descargada de https://software.cisco.com/download/home["Descarga de software de Cisco"^] página.
* Licencias aplicables, información de red y configuración, y cables.
* Terminadolink:setup-worksheet-9336c-storage.html["hojas de trabajo de cableado"] .
* RCF aplicables de la red de almacenamiento NetApp y de la red de gestión descargados del NetApp Support Site en http://mysupport.netapp.com/["mysupport.netapp.com"^].
+
Todos los switches de red de almacenamiento y de red de gestión de Cisco llegan con la configuración predeterminada de fábrica estándar de Cisco. Estos switches también tienen la versión actual del software NX-OS pero no tienen los RCF cargados.

* Documentación requerida del interruptor. Verlink:required-documentation-9336c-storage.html["Documentación requerida"] Para más información.


.Pasos
. Monta en rack los switches de red, los switches de gestión y los controladores.
+
[cols="1,2"]
|===
| Si estás instalando tu... | Entonces... 


 a| 
Cisco Nexus 9336C-FX2 en un gabinete de sistema NetApp
 a| 
Verlink:install-switch-and-passthrough-panel-9336c-storage.html["Instale el switch en el armario NetApp."] Para obtener instrucciones sobre cómo instalar el switch en un armario NetApp .



 a| 
Equipos en un rack de telecomunicaciones
 a| 
Consulte los procedimientos proporcionados en las guías de instalación del hardware del switch y las instrucciones de instalación y configuración de NetApp .

|===
. Conecta los switches de red y de red de gestión a los controladores usando las hojas de trabajo de cableado completadas.
. Enciende los conmutadores de red y de gestión, así como los controladores.


.¿Que sigue?
Opcionalmente, puedes link:install-switch-and-passthrough-panel-9336c-storage.html["Instalar un conmutador Cisco Nexus 9336C-FX2 en un gabinete NetApp"]. De lo contrario, vaya a link:setup-switch-9336c-storage.html["configurar el conmutador"].
