---
permalink: switch-cisco-9336c-fx2-storage/install-upgrade-rcf-overview-9336c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2 
summary: Puede instalar el RCF después de configurar el conmutador Nexus 9336C-FX2 por primera vez. También puede utilizar este procedimiento para actualizar su versión de RCF. 
---
= Instale o actualice la descripción general del archivo de configuración de referencia (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El archivo de configuración de referencia (RCF) se instala después de configurar el switch de almacenamiento Nexus 9336C-FX2 por primera vez. Actualiza tu versión RCF cuando tienes una versión existente del archivo RCF instalado en tu conmutador.

Consulte el artículo de la base de conocimientos link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Cómo borrar la configuración en un switch de interconexión de Cisco manteniendo la conectividad remota"^]para obtener más información al instalar o actualizar su RCF.

.Configuraciones de RCF disponibles
En la siguiente tabla se describen los CFR disponibles para diferentes configuraciones. Seleccione el RCF aplicable a su configuración.

Si quiere más información sobre el uso de VLAN y puertos específicos, consulte el banner y la sección de notas importantes de su RCF.

[cols="1,2"]
|===
| Nombre de RCF | Descripción 


 a| 
2-Cluster-HA-Breakout
 a| 
Admite dos clústeres ONTAP con al menos ocho nodos, incluidos los nodos que utilizan puertos compartidos Cluster+HA.



 a| 
4-Cluster-HA-Breakout
 a| 
Admite cuatro clústeres ONTAP con al menos cuatro nodos, incluidos los nodos que utilizan puertos compartidos Cluster+HA.



 a| 
1-Cluster-HA
 a| 
Todos los puertos están configurados para 40/100GbE. Admite el tráfico de clúster/alta disponibilidad compartido en los puertos. Necesario para los sistemas AFF A320, AFF A250 y FAS500f. Además, todos los puertos se pueden utilizar como puertos de clúster dedicados.



 a| 
1-Cluster-HA-Breakout
 a| 
Los puertos se configuran para 4 puertos de separación de 10 GbE, 4 GbE (RCF 1,6+ en switches 100GbE) y 40/100GbE. Admite el tráfico compartido de clúster/alta disponibilidad en los puertos para los nodos que utilizan puertos de clúster/alta disponibilidad compartidos: Sistemas AFF A320, AFF A250 y FAS500f. Además, todos los puertos se pueden utilizar como puertos de clúster dedicados.



 a| 
Cluster-HA-Storage
 a| 
Los puertos están configurados para 40/100GbE para Cluster+HA, 4x10GbE breakout para Cluster y 4x25GbE breakout para Cluster+HA, y 100GbE para cada par de almacenamiento HA.



 a| 
Clúster
 a| 
Dos versiones de RCF con diferentes asignaciones de puertos 4x10GbE (breakout) y puertos 40/100GbE.  Se admiten todos los nodos FAS y AFF , excepto los sistemas AFF A320, AFF A250 y FAS500f .



 a| 
Reducida
 a| 
Todos los puertos se configuran para conexiones de almacenamiento NVMe de 100GbE Gb.

|===
.Documentación sugerida
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco"^]
+
Consulte la tabla de compatibilidad de switches para conocer las versiones de ONTAP y RCF compatibles en el sitio de soporte de NetApp. Tenga en cuenta que puede haber dependencias de comandos entre la sintaxis del comando en el RCF y la sintaxis encontrada en versiones específicas de NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Switches Cisco Nexus serie 9000"^]
+
Consulte las guías de software y actualización correspondientes disponibles en el sitio web de Cisco para obtener documentación completa sobre los procedimientos de actualización y degradación del conmutador Cisco.



.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la nomenclatura de conmutador y nodo siguiente:

* Los nombres de los dos switches de Cisco son cs1 y cs2.
* Los nombres de los nodos son node1-01, node1-02, node1-03 y node1-04.
* Los nombres del clúster LIF son node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 y node1-04_clus2.
* La `cluster1::*>` prompt indica el nombre del clúster.


Ver el https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para verificar los puertos correctos en su plataforma.


NOTE: Los resultados del comando pueden variar en función de las diferentes versiones de ONTAP.

.Comandos utilizados
Para ello, es necesario utilizar tanto comandos de la ONTAP como comandos de la serie Cisco Nexus 9000; los comandos de la ONTAP se usan a menos que se indique lo contrario.

.El futuro
Después de revisar el procedimiento de instalación o actualización de RCF, puedelink:install-rcf-software-9336c-storage.html["instalar el RCF"] olink:upgrade-rcf-software-9336c-storage.html["Mejora tu RCF"] según sea necesario.
