---
permalink: switch-cisco-9336c-fx2-storage/migrate-to-2n-switched-9336-storage.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched 9336C-FX2 cluster environment,switchless cluster environments,9336C-FX2 switches 
summary: Si tiene un entorno de clúster sin conmutación de dos nodos existente, puede migrar a un entorno de clúster conmutado de dos nodos mediante conmutadores Cisco Nexus 9336C-FX2 para poder escalar más allá de dos nodos en el clúster. 
---
= Migrar a un clúster conmutado de dos nodos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene un entorno de clúster _sin conmutador_ existente de dos nodos, puede migrar a un entorno de clúster _con conmutador_ de dos nodos utilizando conmutadores Cisco Nexus 9336C-FX2 para permitirle escalar más allá de dos nodos en el clúster.

El proceso de migración funciona para todos los nodos que utilizan puertos ópticos o Twinax, pero no es compatible con este conmutador si los nodos utilizan puertos RJ45 10Gb BASE-T integrados para los puertos de red del clúster.



== Requisitos de revisión

.Antes de empezar
Asegúrese de tener lo siguiente:

* Para la configuración sin interruptor de dos nodos:
+
** La configuración sin interruptor de dos nodos está correctamente configurada y funcionando.
** Los nodos ejecutan ONTAP 9.8 o posterior.
** Todos los puertos del clúster están en estado *activo*.
** Todas las interfaces lógicas del clúster (LIF) están en estado *activo* y en sus puertos de inicio.


* Para la configuración del conmutador Cisco Nexus 9336C-FX2:
+
** Ambos switches tienen conectividad de red de gestión.
** Existe acceso mediante consola a los conmutadores del clúster.
** Las conexiones de conmutador nodo a nodo y de conmutador a conmutador Nexus 9336C-FX2 utilizan cables Twinax o de fibra.


* Ver link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - Interruptores"^] Para obtener más información sobre el cableado.
* Ver link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"^] para obtener más información sobre los requisitos de instalación del conmutador.
* Los cables de enlace entre conmutadores (ISL) están conectados a los puertos 1/35 y 1/36 en ambos conmutadores 9336C-FX2.
* Se ha completado la personalización inicial de ambos conmutadores 9336C-FX2, de modo que:
+
** Los conmutadores 9336C-FX2 ejecutan la última versión del software.
** Los archivos de configuración de referencia (RCF) se aplican a los conmutadores.  Cualquier personalización del sitio, como SMTP, SNMP y SSH, se configura en los nuevos conmutadores.




.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de nodos y conmutadores de clúster:

* Los nombres de los conmutadores 9336C-FX2 son cs1 y cs2.
* Los nombres de las SVM del clúster son nodo1 y nodo2.
* Los nombres de los LIF son node1_clus1 y node1_clus2 en el nodo 1, y node2_clus1 y node2_clus2 en el nodo 2 respectivamente.
* El `cluster1::*>` El indicador muestra el nombre del clúster.
* Los puertos del clúster utilizados en este procedimiento son e0a y e0b.


Ver https://hwu.netapp.com["Hardware Universe"^] Para obtener información sobre los puertos del clúster para sus plataformas.



== Migrar los interruptores



=== Paso 1: Prepararse para la migración

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
donde x es la duración de la ventana de mantenimiento en horas.

+

NOTE: El mensaje de AutoSupport notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante la ventana de mantenimiento.

. Cambie el nivel de privilegio a avanzado, ingresando `y` cuando se le solicite continuar:
+
`set -privilege advanced`

+
La solicitud avanzada(`*>` ) aparece.





=== Paso 2: Configurar puertos y cableado

. Deshabilite todos los puertos orientados a nodos (excepto los puertos ISL) en ambos conmutadores de clúster nuevos cs1 y cs2.
+
No deshabilite los puertos ISL.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos orientados al nodo del 1 al 34 están deshabilitados en el switch cs1:

[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs1(config-if-range)# shutdown
----
====
. Verifique que el ISL y los puertos físicos en el ISL entre los dos conmutadores 9336C-FX2 cs1 y cs2 estén activos en los puertos 1/35 y 1/36:
+
`show port-channel summary`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos ISL están activos en el switch cs1:

[listing]
----
cs1# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
El siguiente ejemplo muestra que los puertos ISL están activos en el switch cs2:

[listing]
----
(cs2)# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====
. Mostrar la lista de dispositivos vecinos:
+
`show cdp neighbors`

+
Este comando proporciona información sobre los dispositivos conectados al sistema.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo enumera los dispositivos vecinos en el switch cs1:

[listing]
----
cs1# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
El siguiente ejemplo enumera los dispositivos vecinos en el switch cs2:

[listing]
----
cs2# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====
. Verifique que todos los puertos del clúster estén activos:
+
`network port show -ipspace Cluster`

+
Cada puerto debería mostrarse para `Link` y saludable para `Health Status` .

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
====
. Verifique que todas las LIF del clúster estén activas y operativas:
+
`network interface show -vserver Cluster`

+
Cada clúster LIF debería mostrar `true` para `Is Home` y tener un `Status Admin/Oper` de arriba/arriba

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -vserver Cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. Verifique que la reversión automática esté habilitada en todas las LIF del clúster:
+
`network interface show -vserver Cluster -fields auto-revert`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====
. Desconecte el cable del puerto de clúster e0a en el nodo 1 y, luego, conecte e0a al puerto 1 en el conmutador de clúster cs1, utilizando el cableado adecuado compatible con los conmutadores 9336C-FX2.
+
El https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - Interruptores"^] Contiene más información sobre el cableado.

. Desconecte el cable del puerto de clúster e0a en el nodo 2 y, luego, conecte e0a al puerto 2 en el conmutador de clúster cs1, utilizando el cableado adecuado compatible con los conmutadores 9336C-FX2.
. Habilite todos los puertos orientados a nodos en el conmutador de clúster cs1.
+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos 1/1 a 1/34 están habilitados en el switch cs1:

[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs1(config-if-range)# no shutdown
----
====
. Verifique que todas las LIF del clúster estén activas, operativas y se muestren como `true` para `Is Home` :
+
`network interface show -vserver Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que todas las LIF están activas en los nodos 1 y 2 y que `Is Home` Los resultados son ciertos:

[listing]
----
cluster1::*> network interface show -vserver Cluster

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true

4 entries were displayed.
----
====
. Mostrar información sobre el estado de los nodos en el clúster:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra información sobre el estado y la elegibilidad de los nodos del clúster:

[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. Desconecte el cable del puerto de clúster e0b en el nodo 1 y, luego, conecte e0b al puerto 1 en el conmutador de clúster cs2, utilizando el cableado adecuado compatible con los conmutadores 9336C-FX2.
. Desconecte el cable del puerto de clúster e0b en el nodo 2 y, luego, conecte e0b al puerto 2 en el conmutador de clúster cs2, utilizando el cableado adecuado compatible con los conmutadores 9336C-FX2.
. Habilite todos los puertos orientados a nodos en el conmutador de clúster cs2.
+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos 1/1 a 1/34 están habilitados en el switch cs2:

[listing]
----
cs2# config
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs2(config-if-range)# no shutdown
----
====
. Verifique que todos los puertos del clúster estén activos:
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que todos los puertos del clúster están activos en los nodos 1 y 2:

[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
====




=== Paso 3: Verificar la configuración

. Verifique que todas las interfaces muestren verdadero para `Is Home` :
+
`network interface show -vserver Cluster`

+

NOTE: Esto podría tardar varios minutos en completarse.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que todas las LIF están activas en los nodos 1 y 2 y que `Is Home` Los resultados son ciertos:

[listing]
----
cluster1::*> network interface show -vserver Cluster

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true

4 entries were displayed.
----
====
. Verifique que ambos nodos tengan una conexión a cada conmutador:
+
`show cdp neighbors`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra los resultados correspondientes para ambos interruptores:

[listing]
----
(cs1)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           FAS2980       e0a
node2              Eth1/2         133    H           FAS2980       e0a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 4

(cs2)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           FAS2980       e0b
node2              Eth1/2         133    H           FAS2980       e0b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 4
----
====
. Muestra información sobre los dispositivos de red detectados en su clúster:
+
`network device-discovery show -protocol cdp`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C9336C
            e0b    cs2                       0/2               N9K-C9336C
node1      /cdp
            e0a    cs1                       0/1               N9K-C9336C
            e0b    cs2                       0/1               N9K-C9336C

4 entries were displayed.
----
====
. Verifique que la configuración esté desactivada:
+
`network options switchless-cluster show`

+

NOTE: El comando podría tardar varios minutos en completarse.  Espere el anuncio de "tiempo de vida de 3 minutos a expirar".

+
.Mostrar ejemplo
[%collapsible]
====
El resultado erróneo del siguiente ejemplo muestra que la configuración está desactivada:

[listing]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: false
----
====
. Verifique el estado de los nodos miembros del clúster:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra información sobre el estado y la elegibilidad de los nodos del clúster:

[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[paso 7]] Vuelva a cambiar el nivel de privilegios a administrador:
+
`set -privilege admin`

. Para ONTAP 9.8 y versiones posteriores, habilite la función de recopilación de registros del monitor de estado del switch Ethernet para recopilar archivos de registro relacionados con el switch, utilizando los siguientes comandos:
+
`system switch ethernet log setup-password`y `system switch ethernet log enable-collection`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system switch ethernet log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
====
+

NOTE: Si alguno de estos comandos devuelve un error, póngase en contacto con el soporte de NetApp .

. Para las versiones de ONTAP 9.5P16, 9.6P12 y 9.7P10 y versiones de parche posteriores, habilite la función de recopilación de registros del monitor de estado del conmutador Ethernet para recopilar archivos de registro relacionados con el conmutador, utilizando los siguientes comandos:
+
`system cluster-switch log setup-password`y `system cluster-switch log enable-collection`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::*> system cluster-switch log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
====
+

NOTE: Si alguno de estos comandos devuelve un error, póngase en contacto con el soporte de NetApp .

. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


