---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: 'Reemplazar un conmutador Nexus 9336C-FX2 defectuoso en una red de clúster es un procedimiento no disruptivo (NDU).' 
---
= Reemplace los conmutadores de almacenamiento Cisco Nexus 9336C-FX2 y 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede reemplazar los conmutadores Nexus 9336C-FX2 y 9336C-FX2-T defectuosos en una red de clúster. Este es un procedimiento que no produce interrupciones.

.Antes de empezar
Antes de instalar el software NX-OS y los RCF en los conmutadores de almacenamiento Cisco Nexus 9336C-FX2 y 9336C-FX2-T, asegúrese de lo siguiente:

* Su sistema puede admitir los conmutadores de almacenamiento Cisco Nexus 9336C-FX2 y 9336C-FX2-T.
* Ha consultado la tabla de compatibilidad de switches en la página de switches Ethernet de Cisco para conocer las versiones compatibles de ONTAP, NX-OS y RCF.
* Usted ha consultado el software y las guías de actualización correspondientes disponibles en el sitio web de Cisco .
* Has descargado los formularios RCF correspondientes.
* La configuración de red existente presenta las siguientes características:
+
** La página de switches Ethernet de Cisco tiene las últimas versiones de RCF y NX-OS para sus switches.
** Debe existir conectividad de gestión en ambos conmutadores.


* El switch de reemplazo Cisco Nexus 9336C-FX2 tiene las siguientes características:
+
** La conectividad de la red de gestión funciona correctamente.
** El acceso a la consola para el interruptor de repuesto ya está habilitado.
** La imagen del sistema operativo RCF y NX-OS apropiada se carga en el switch.
** La configuración inicial del conmutador está completa.




.Acerca de esta tarea
Este procedimiento reemplaza el segundo conmutador de almacenamiento Nexus 9336C-FX2 s2 por el nuevo 9336C-FX ns2. Los dos nodos son cluster1-01 y cluster1-02.

Pasos a seguir:

* Confirma que el interruptor a sustituir es s2.
* Desconecta los cables del switch s2.
* Vuelve a conectar los cables al switch ns2.
* Verifica todas las configuraciones de los dispositivos en el switch ns2.
+

NOTE: Pueden existir dependencias entre la sintaxis de los comandos en las versiones RCF y NX-OS.



.Pasos
. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ es la duración de la ventana de mantenimiento en horas.

. Revisa el estado de salud de los puertos del nodo de almacenamiento para asegurarte de que hay conexión con el switch de almacenamiento s1:
+
`storage port show -port-type ENET`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
cluster1-02
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
.
.
----
====
. Verifica que el switch de almacenamiento s1 está disponible:
+
`network device-discovery show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
cluster1-01/cdp
           e5a   s1                        Ethernet1/1 NX9336C
           e4a   cluster1-02               e4a         AFF-A700
           e4e   cluster1-02               e4e         AFF-A700
cluster1-01/lldp
           e5a   s1                        Ethernet1/1 -
           e4a   cluster1-02               e4a         -
           e4e   cluster1-02               e4e         -
cluster1-02/cdp
           e3b   s1                        Ethernet1/2 NX9336C
           e4a   cluster1-01               e4a         AFF-A700
           e4e   cluster1-01               e4e         AFF-A700
cluster1-02/lldp
           e3b   s1                        Ethernet1/2 -
           e4a   cluster1-01               e4a         -
           e4e   cluster1-01               e4e         -
.
.
----
====
. Dirigir las cosas `lldp neighbors` Comando en el interruptor de funcionamiento para confirmar que puede ver ambos nodos y todos los estantes:
+
`show lldp neighbors`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
cluster1-01      Eth1/1       121          S             e5a
cluster1-02      Eth1/2       121          S             e5a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. Verifica los puertos del estante de almacenamiento en el sistema de almacenamiento:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   s1
3.20    1   -             -
3.20    2   Ethernet1/6   s1
3.20    3   -             -
3.30    0   Ethernet1/7   s1
3.20    1   -             -
3.30    2   Ethernet1/8   s1
3.20    3   -             -
.
.
----
====
. Quita todos los cables conectados al switch de almacenamiento s2.
. Vuelve a conectar todos los cables al switch de reemplazo ns2.
. Vuelva a comprobar el estado de salud de los puertos del nodo de almacenamiento:
+
`storage port show -port-type ENET`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
cluster1-02
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
.
.
----
====
. Verifique que ambos interruptores estén disponibles:
+
`network device-discovery show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
cluster1-01/cdp
          e3a  s1                         Ethernet1/1 NX9336C
          e4a  cluster1-02                e4a         AFF-A700
          e4e  cluster1-02                e4e         AFF-A700
          e7b  ns2                       Ethernet1/1 NX9336C
cluster1-01/lldp
          e3a  s1                         Ethernet1/1 -
          e4a  cluster1-02                e4a         -
          e4e  cluster1-02                e4e         -
          e7b  ns2                        Ethernet1/1 -
cluster1-02/cdp
          e3a  s1                         Ethernet1/2 NX9336C
          e4a  cluster1-01                e4a         AFF-A700
          e4e  cluster1-01                e4e         AFF-A700
          e7b  ns2                        Ethernet1/2 NX9336C
cluster1-02/lldp
          e3a  s1                         Ethernet1/2 -
          e4a  cluster1-01                e4a         -
          e4e  cluster1-01                e4e         -
          e7b  ns2                        Ethernet1/2 -
.
.
----
====
. Verifique los puertos de los estantes en el sistema de almacenamiento:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     s1
3.20    1     Ethernet1/5     ns2
3.20    2     Ethernet1/6     s1
3.20    3     Ethernet1/6     ns2
3.30    0     Ethernet1/7     s1
3.20    1     Ethernet1/7     ns2
3.30    2     Ethernet1/8     s1
3.20    3     Ethernet1/8     ns2
storage::*>
----
====
. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.¿Que sigue?
Después de haber reemplazado los interruptores, puedes link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
