---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-storage/required-documentation-9336c-storage.html 
keywords: shared storage cluster switch 
summary: Para la instalación y el mantenimiento del conmutador Cisco Nexus 9336C-FX2, asegúrese de revisar la documentación específica del conmutador y del controlador para configurar los conmutadores Cisco 9336-FX2 y el clúster ONTAP . 
---
= Requisitos de documentación para los conmutadores de almacenamiento Cisco Nexus 9336C-FX2 y 9336C-FX2-T
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento de los conmutadores Cisco Nexus 9336C-FX2 y 9336C-FX2-T, asegúrese de revisar la documentación específica del conmutador y del controlador para configurar los conmutadores Cisco 9336-FX2 y el clúster ONTAP .



== Documentación del interruptor

Para configurar los switches Cisco Nexus 9336C-FX2, necesita la siguiente documentación de https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Soporte para switches Cisco Nexus serie 9000"^] página:

[cols="1,2"]
|===
| Título del documento | Descripción 


 a| 
_Guía de instalación de hardware de la serie Nexus 9000_
 a| 
Proporciona información detallada sobre los requisitos del sitio, detalles del hardware del switch y opciones de instalación.



 a| 
_Guías de configuración de software para switches Cisco Nexus serie 9000_ (elija la guía correspondiente a la versión de NX-OS instalada en sus switches)
 a| 
Proporciona la información de configuración inicial del switch que necesita antes de poder configurarlo para el funcionamiento de ONTAP .



 a| 
_Guía de actualización y degradación de software NX-OS de la serie Cisco Nexus 9000_ (elija la guía correspondiente a la versión de NX-OS instalada en sus switches)
 a| 
Proporciona información sobre cómo degradar el software del switch a uno compatible con ONTAP , si fuera necesario.



 a| 
_Índice maestro de referencia de comandos de Cisco Nexus serie 9000 NX-OS_
 a| 
Proporciona enlaces a las diversas referencias de comandos proporcionadas por Cisco.



 a| 
_Referencia de MIB de Cisco Nexus 9000_
 a| 
Describe los archivos de la Base de Información de Gestión (MIB) para los switches Nexus 9000.



 a| 
_Referencia de mensajes del sistema NX-OS de la serie Nexus 9000_
 a| 
Describe los mensajes del sistema para los switches Cisco Nexus serie 9000, aquellos que son informativos y otros que podrían ayudar a diagnosticar problemas con los enlaces, el hardware interno o el software del sistema.



 a| 
_Notas de la versión de NX-OS de la serie Cisco Nexus 9000 (elija las notas correspondientes a la versión de NX-OS instalada en sus switches)_
 a| 
Describe las características, errores y limitaciones de la serie Cisco Nexus 9000.



 a| 
Información sobre cumplimiento normativo y seguridad para la serie Cisco Nexus 9000
 a| 
Proporciona información sobre cumplimiento normativo, seguridad y requisitos legales de organismos internacionales para los switches de la serie Nexus 9000.

|===


== Documentación de los sistemas ONTAP

Para configurar un sistema ONTAP , necesita los siguientes documentos para su versión del sistema operativo de https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^] .

[cols="1,2"]
|===
| Nombre | Descripción 


 a| 
Instrucciones de instalación y configuración específicas del controlador
 a| 
Describe cómo instalar el hardware de NetApp .



 a| 
Documentación de ONTAP
 a| 
Proporciona información detallada sobre todos los aspectos de las versiones de ONTAP .



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Proporciona información sobre la configuración y compatibilidad del hardware de NetApp .

|===


== Documentación del kit de rieles y del gabinete

Para instalar un switch Cisco 9336-FX2 en un gabinete NetApp , consulte la siguiente documentación de hardware.

[cols="1,2"]
|===
| Nombre | Descripción 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Gabinete de sistema 42U, guía profunda"^]
 a| 
Describe las FRU asociadas con el gabinete del sistema 42U y proporciona instrucciones de mantenimiento y reemplazo de FRU.



 a| 
link:install-switch-and-passthrough-panel-9336c-storage.html["Instale un switch Cisco 9336-FX2 en un gabinete NetApp"^]
 a| 
Describe cómo instalar un switch Cisco Nexus 9336C-FX2 en un gabinete NetApp de cuatro postes.

|===