---
permalink: switch-cisco-9336c-fx2-storage/upgrade-rcf-software-9336c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: Puede utilizar este procedimiento para actualizar su versión de RCF. 
---
= Actualiza tu archivo de configuración de referencia (RCF).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Actualizas tu versión de RCF cuando tienes una versión existente del archivo RCF instalada en tus switches operativos.

.Antes de empezar
Asegúrese de tener lo siguiente:

* Una copia de seguridad actualizada de la configuración del switch.
* Un clúster en pleno funcionamiento (sin errores en los registros ni problemas similares).
* El RCF actual.
* Si está actualizando su versión de RCF, necesita una configuración de arranque en RCF que refleje las imágenes de arranque deseadas.
+
Si necesita cambiar la configuración de arranque para que refleje las imágenes de arranque actuales, debe hacerlo antes de volver a aplicar el RCF para que se instancie la versión correcta en futuros reinicios.




NOTE: No se necesita ningún enlace entre conmutadores (ISL) operativo durante este procedimiento. Esto es así por diseño porque los cambios de versión de RCF pueden afectar la conectividad de ISL temporalmente. Para garantizar un funcionamiento ininterrumpido del clúster, el siguiente procedimiento migra todas las LIF del clúster al conmutador asociado operativo mientras se realizan los pasos en el conmutador de destino.


CAUTION: Antes de instalar una nueva versión del software del switch y los RCF, debe borrar la configuración del switch y realizar una configuración básica.  Debe estar conectado al switch mediante la consola serie o haber guardado la información de configuración básica antes de borrar la configuración del switch.



== Paso 1: Prepárese para la actualización

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
Donde _x_ es la duración de la ventana de mantenimiento en horas.

. Cambie el nivel de privilegio a avanzado, ingresando *y* cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el indicador avanzado (*>).

. Muestra los puertos en cada nodo que están conectados a los conmutadores:
+
[source, cli]
----
network device-discovery show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
node1-01/cdp
            e3a    cs1                       Ethernet1/7     N9K-C9336C
            e3b    cs2                       Ethernet1/7     N9K-C9336C
node1-02/cdp
            e3a    cs1                       Ethernet1/8     N9K-C9336C
            e3b    cs2                       Ethernet1/8     N9K-C9336C
.
.
.
----
====
. Verifique que todos los puertos de almacenamiento se encuentren en buen estado:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e3a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
                   e7a ENET  -         100   enabled  online
                   e7b ENET  -         100   enabled  online
node1-02
                   e3a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
                   e7a ENET  -         100   enabled  online
                   e7b ENET  -         100   enabled  online
.
.
.
----
====
. Desactive la reversión automática en los LIF del clúster.
+
`network interface modify -vserver Cluster -lif * -auto-revert false`





== Paso 2: Configurar puertos

. En el conmutador cs1, apague los puertos conectados a todos los puertos de los nodos.
+
[listing, subs="+quotes"]
----
cs1> *enable*
cs1# *configure*
cs1(config)# *interface eth1/1/1-2,eth1/7-8*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
+

CAUTION: Asegúrese de apagar *todos* los puertos conectados para evitar problemas de conexión de red. Consulte el artículo de la base de conocimientos https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["Nodo fuera de quórum al migrar la LIF del clúster durante la actualización del sistema operativo del switch"^] Para obtener más detalles.

. Verifique que los LIF del clúster hayan conmutado por error a los puertos alojados en el conmutador cs1. Esto podría tardar unos segundos.
+
[source, cli]
----
network interface show -role cluster
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e7a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e7b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e7a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e7b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e7a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e7b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e7a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e7b     true

8 entries were displayed.
----
====
. Verifique que el clúster esté en buen estado:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------  -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false

4 entries were displayed.
----
====
. Si aún no lo ha hecho, guarde una copia de la configuración actual del switch copiando el resultado del siguiente comando en un archivo de texto:
+
`show running-config`

+
.. Registre cualquier adición personalizada entre el actual `running-config` y el archivo RCF en uso (como una configuración SNMP para su organización).
.. Para NX-OS 10.2 y versiones posteriores, utilice el `show diff running-config` comando para comparar con el archivo RCF guardado en la memoria flash de arranque. De lo contrario, utilice una herramienta de comparación o diff de terceros.


. Guarde los detalles de configuración básicos en el `write_erase.cfg` archivo en la memoria flash de arranque.
+
[NOTE]
====
Asegúrese de configurar lo siguiente:

** Nombre de usuario y contraseña
** Dirección IP de gestión
** Puerta de enlace predeterminada
** Cambiar nombre


====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

. Al actualizar a la versión 1.12 de RCF o posterior, ejecute los siguientes comandos:
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1280 >> bootflash:write_erase.cfg`

+
Consulte el artículo de la base de conocimientoslink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Cómo borrar la configuración de un switch de interconexión Cisco manteniendo la conectividad remota"^] Para obtener más detalles.

. Verifique que el `write_erase.cfg` El archivo se ha rellenado según lo previsto:
+
`*show file bootflash:write_erase.cfg*`

. Emitir el `write erase` comando para borrar la configuración guardada actual:
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copie la configuración básica guardada previamente en la configuración de inicio.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. Reinicia el switch:
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Una vez que la dirección IP de administración vuelva a ser accesible, inicie sesión en el switch a través de SSH.
+
Es posible que necesites actualizar las entradas del archivo host relacionadas con las claves SSH.

. Copie el RCF al bootflash del conmutador cs1 utilizando uno de los siguientes protocolos de transferencia: FTP, TFTP, SFTP o SCP.
+
Para obtener más información sobre los comandos de Cisco , consulte la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^] guías.

+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo muestra cómo se utiliza TFTP para copiar un RCF a la memoria flash de arranque del switch cs1:

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *Nexus_9336C_RCF_v1.6-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Aplique el RCF descargado previamente a la memoria flash de arranque.
+
Para obtener más información sobre los comandos de Cisco , consulte la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^] guías.

+
Este ejemplo muestra el archivo RCF. `NX9336C-FX2-RCF-v1.13-1-Storage.txt` Instalando en el switch cs1:

+
[listing, subs="+quotes"]
----
cs1# *copy Nexus_9336C_RCF_v1.6-Storage.txt running-config echo-commands*
----
+
[CAUTION]
====
Asegúrese de leer detenidamente las secciones *Notas de instalación*, *Notas importantes* y *banner* de su RCF. Debe leer y seguir estas instrucciones para garantizar la configuración y el funcionamiento adecuados del conmutador.

====
. Verifique que el archivo RCF sea la versión más reciente correcta:
+
`show running-config`

+
Al comprobar la salida para verificar que tiene el RCF correcto, asegúrese de que la siguiente información sea correcta:

+
** El estandarte de RCF
** Configuración del nodo y del puerto
** Personalizaciones
+
El resultado varía según la configuración de su sitio.  Compruebe la configuración del puerto y consulte las notas de la versión para conocer los cambios específicos del RCF que haya instalado.



. Vuelva a aplicar cualquier personalización anterior a la configuración del switch.
. Después de verificar que las versiones de RCF, las adiciones personalizadas y la configuración del interruptor sean correctas, copie el `running-config` archivo al `startup-config` archivo.
+
Para obtener más información sobre los comandos de Cisco , consulte la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^] guías.

+
`cs1# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. Reiniciar interruptor cs1.  Puede ignorar las alertas de "monitor de estado del conmutador de clúster" y los eventos de "puertos de clúster inactivos" que se informan en los nodos mientras se reinicia el conmutador.
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Verifique que todos los puertos de almacenamiento se encuentren en buen estado:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e3a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
                   e7a  ENET  -          100 enabled  online
                   e7b  ENET  -          100 enabled  online
node1-02
                   e3a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
                   e7a  ENET  -          100 enabled  online
                   e7b  ENET  -          100 enabled  online
.
.
.
----
====
. Verifique que el clúster esté en buen estado:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health   Eligibility   Epsilon
----------------- -------- ------------- -------
node1-01          true     true          false
node1-02          true     true          false
node1-03          true     true          true
node1-04          true     true          false

4 entries were displayed.
----
====
. Repita los pasos 4 a 19 en el interruptor cs2.
. Habilitar la reversión automática en los LIF del clúster.
+
`network interface modify -vserver Cluster -lif * -auto-revert true`





== Paso 3: Verifique la configuración de red y el estado del clúster.

. Verifique que los puertos del switch conectados a los puertos del clúster estén *activos*.
+
[source, cli]
----
show interface brief
----
. Verifique que los nodos esperados sigan conectados:
+
[source, cli]
----
show cdp neighbors
----
. Verifique que los nodos del clúster se encuentren en sus VLAN de clúster correctas utilizando los siguientes comandos:
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----
. Verifique que los LIF del clúster hayan vuelto a su puerto de origen:
+
[source, cli]
----
network interface show -role cluster
----
+
Si alguna LIF del clúster no ha regresado a sus puertos de origen, reviértala manualmente desde el nodo local:

+
`network interface revert -vserver vserver_name -lif <lif-name>`

. Verifique que el clúster esté en buen estado:
+
[source, cli]
----
cluster show
----
. Verifique la conectividad de las interfaces del clúster remoto:
+
.. Puedes usar el `network interface check cluster-connectivity show` comando para mostrar los detalles de una comprobación de accesibilidad para la conectividad del clúster:
+
[source, cli]
----
network interface check cluster-connectivity show
----
.. Alternativamente, puede utilizar el `cluster ping-cluster -node <node-name>` comando para comprobar la conectividad:
+
[source, cli]
----
cluster ping-cluster -node <node-name>
----




.¿Que sigue?
Después de actualizar tu RCF, puedeslink:configure-ssh-keys.html["verificar la configuración de SSH"] .
