---
permalink: switch-cisco-9808/configure-install-rcf-9808.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: Instalas el RCF en los nuevos switches Cisco Nexus 9808 como parte de la instalación y configuración de un nuevo sistema AFX 2K, al reemplazar un módulo supervisor defectuoso o al restablecer un switch a los ajustes predeterminados de fábrica. 
---
= Instala el RCF - Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Instalas el RCF en los nuevos switches Cisco Nexus 9808 como parte de la instalación de un nuevo sistema AFX 2K, al reemplazar un módulo supervisor o al restablecer un switch a la configuración predeterminada de fábrica.

.Antes de empezar
* Los conmutadores deben estar encendidos y debes haber completado el procedimiento link:configure-complete-initial-setup-9808.html["Completa la configuración inicial del conmutador"].
* Debes haber instalado la versión deseada de NX-OS usando el procedimiento de link:configure-install-nxos-9808.html["Instala el NX-OS"].
* Debes haber leído la página link:configure-install-upgrade-rcf-overview-9808.html["Descripción general de la instalación o actualización de RCF"].
* Si vas a instalar el RCF en un switch como parte de la sustitución de un módulo supervisor o de un restablecimiento del switch a los ajustes predeterminados de fábrica, verifica que tu clúster esté completamente funcional, es decir, que no haya errores en los registros ni problemas similares.
+
Si estás instalando el RCF como parte de la instalación de un nuevo sistema AFX, puedes omitir este requisito porque los controladores de tu sistema AFX aún no están encendidos en este punto de la instalación y configuración de tu sistema AFX.



.Acerca de esta tarea
* Si has instalado conmutadores como parte de la instalación de un nuevo sistema AFX 2K, instala el archivo de configuración de referencia (RCF) en el primer conmutador (cs1) y luego repite los pasos para el segundo conmutador (cs2) usando este procedimiento.
* Este procedimiento solo requiere el uso de comandos de los switches Cisco Nexus 9000 Series.
* En los ejemplos de este procedimiento, el primer switch se llama cs1 y el segundo switch se llama cs2.




[[step-1-prepare-to-install-the-rcf]]
== Paso 1: Prepárate para instalar el RCF

Prepárate para instalar el RCF en el conmutador o conmutadores asegurándote de que tienes las conexiones necesarias para descargar el RCF y luego descárgalo.

.Pasos
. Debes tener acceso a un servidor HTTP, FTP o TFTP. El acceso a uno de estos servidores te permite descargar una versión compatible del RCF.
. Descarga el RCF compatible con tu tipo de sistema AFX desde el sitio de soporte de NetApp en link:http://mysupport.netapp.com/["mysupport.netapp.com"^].
+

NOTE: Los nuevos conmutadores no se suministran con el RCF instalado. Debes instalar el RCF en los conmutadores.

. Cada conmutador debe estar conectado a una consola o debes tener acceso remoto a cada conmutador.
. Debes estar conectado a los conmutadores mediante la consola serie o haber conservado la información de configuración básica. Esto se debe a que el procedimiento de actualización de RCF requiere que borres los ajustes del conmutador y realices una configuración básica.




[[step-2-install-the-rcf]]
== Paso 2: instalar el RCF

Instalas el RCF en el primer switch (cs1) copiando y aplicando el RCF a la bootflash, revisando la salida del banner, verificando que la versión del RCF sea la correcta, registrando cualquier adición personalizada, guardando los detalles básicos de configuración, comprobando que el archivo  `write_erase.cfg` esté completo, borrando la configuración guardada actual, copiando la configuración básica guardada previamente en la configuración de inicio y luego reiniciando el switch. Repites estos pasos en el segundo switch (cs2) si estás instalando el RCF como parte de una nueva instalación del sistema AFX.

. Inicia sesión en el switch cs1 usando SSH o usando una consola serie.
. Copie el RCF al bootflash del conmutador cs1 utilizando uno de los siguientes protocolos de transferencia: FTP, TFTP, SFTP o SCP.
+
Para más información sobre los comandos de Cisco, consulta la guía correspondiente en las  https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^] guides.

+
`copy <protocol>: bootflash: vrf management`

+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo muestra cómo se utiliza TFTP para copiar un RCF a la memoria flash de arranque del switch cs1:

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *RCF-v10.1-NX9808-CL1-ST1.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Aplica el RCF que copiaste previamente en la bootflash.
+
Para más información sobre los comandos de Cisco, consulta la guía correspondiente en las  https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^] guides.

+
Este ejemplo muestra el archivo RCF `RCF-v10.1-NX9808-CL1-ST1.txt` instalándose en el switch cs1:

+
[listing, subs="+quotes"]
----
cs1# *copy RCF-v10.1-NX9808-CL1-ST1.txt running-config echo-commands*
----
. Examine la salida del banner de `show banner motd` dominio. Debe leer y seguir estas instrucciones para garantizar la configuración y el funcionamiento adecuados del conmutador.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : NX9808
* Filename : RCF-v10.1-NX9808-CL1-ST1.txt
* Date     : 06-15-2026
* Version  : v10.1
* Port Usage:
* Ports   1-18 (LC1-LC8) : 400GbE Cluster/Storage/HA ports.
* Ports   19-35 (LC1-LC8): 4 * 100 GbE Storage shelf ports, int e1-e8/{19-35}/1-4
* Port    36 (LC1-LC8)   : Intra-Cluster ISL Ports, int e1-e8/36
* IMPORTANT NOTES
* Interface port-channel998/9 is reserved to identify the version of this file.

******************************************************************************
----
====
. Comprueba que la RCF sea la versión correcta:
+
`show running-config`

+
Al comprobar la salida para verificar que tiene el RCF correcto, asegúrese de que la siguiente información sea correcta:

+
** El estandarte de RCF
** Configuración del nodo y del puerto
** Personalizaciones
+
El resultado varía según la configuración de su sitio.  Compruebe la configuración del puerto y consulte las notas de la versión para conocer los cambios específicos del RCF que haya instalado.



. Copia la configuración actual en ejecución a la configuración de inicio para que sea persistente.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. Reinicia el switch:
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Repite estos pasos en el conmutador cs2.


.¿Que sigue?
Una vez que hayas instalado el RCF en tus conmutadores, link:configure-verify-ssh-9808.html["Verifica SSH para la recopilación de registros"].
