---
permalink: switch-cisco-9808/configure-upgrade-rcf-9808.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 'Actualizas la versión del archivo de configuración de referencia (RCF) en tus switches Cisco Nexus 9808 para admitir nuevo hardware, una nueva versión de ONTAP o para alinearla con una nueva versión de NX-OS en la configuración de tu sistema AFX 2K.' 
---
= Actualizar la versión de RCF - Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Actualizas la versión del archivo de configuración de referencia (RCF) en tus switches Cisco Nexus 9808 para admitir nuevo hardware, una nueva versión de ONTAP o para alinearla con una nueva versión de NX-OS en la configuración de tu sistema AFX 2K.


NOTE: No actualices ni cambies tu versión de RCF a una versión no compatible.

.Antes de empezar
* Debes haber leído la página link:configure-install-upgrade-rcf-overview-9808.html["Descripción general de la instalación o actualización de RCF"].
* Debes estar conectado a los conmutadores mediante la consola serie o haber conservado la información de configuración básica. Esto se debe a que el procedimiento de actualización de RCF requiere que borres los ajustes del conmutador y realices una configuración básica.
* Asegúrate de tener una copia de seguridad actualizada de la configuración del conmutador.
* Comprueba que tu clúster funcione correctamente, es decir, que no haya errores en los registros ni problemas similares.
* Debes tener la versión actual de RCF.
* Necesitas una configuración de arranque en el RCF que refleje las imágenes de arranque deseadas.
+
Si necesita cambiar la configuración de arranque para que refleje las imágenes de arranque actuales, debe hacerlo antes de volver a aplicar el RCF para que se instancie la versión correcta en futuros reinicios.



.Acerca de esta tarea
* La actualización del RCF en ambos conmutadores es un procedimiento no disruptivo.
+
** No es necesario que haya ningún enlace entre conmutadores (ISL) operativo durante este procedimiento. Esto es así por diseño porque los cambios en la versión de RCF pueden afectar temporalmente la conectividad del ISL. Para garantizar un funcionamiento ininterrumpido del clúster, este procedimiento te indica migrar todas las LIF del clúster al conmutador asociado operativo mientras realizas los pasos en el conmutador de destino.
** Este procedimiento te indica que actualices el RCF del primer conmutador (cs1) y luego repitas los pasos para el segundo conmutador (cs2).


* Este procedimiento requiere el uso de comandos de ONTAP y de los conmutadores Cisco Nexus 9000 Series Switches, los pasos indican qué CLI estás usando para introducir los comandos.
* Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:
+
** Los nombres de los dos switches de Cisco son cs1 y cs2.
** Los nombres de los nodos son node1-01, node1-02, node1-03 y node1-04.
** Los nombres del clúster LIF son:
+
*** node1-01_clus1 y node1-01_clus2 para node1-01
*** node1-02_clus1 y node1-02_clus2 para node1-02
*** node1-03_clus1 y node1-03_clus2 para node1-03
*** node1-04_clus1 y node1-04_clus2 para node1-04


** El `cluster1::*>` El indicador muestra el nombre del clúster.






[[step-1-prepare-for-the-upgrade]]
== Paso 1: Prepárese para la actualización

Introduce los comandos para los siguientes pasos desde la CLI de ONTAP.

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
[source, cli]
----
system node autosupport invoke -node * -type all -message MAINT=xh
----
+
donde _x_ es la duración de la ventana de mantenimiento en horas.

. Cambie el nivel de privilegio a avanzado, ingresando *y* cuando se le solicite continuar:
+
[source, cli]
----
set -privilege advanced
----
+
Aparece el indicador avanzado (*>).

. Muestra los puertos en cada nodo que están conectados a los conmutadores:
+
[source, cli]
----
network device-discovery show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/5       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/14      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/7       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/16      N9K-C9808
            e2a    cs1(FOXXXXXXXXX)          Ethernet1/3       N9K-C9808
            e2b    cs2(FOXXXXXXXXX)          Ethernet1/12      N9K-C9808
node1-01/lldp
            e10a   cs1 (ec:bb:78:9e:c7:e8)   Ethernet1/5       -
            e10b   cs2 (ec:bb:78:9e:c8:0c)   Ethernet1/14      -
            e8a    cs1 (ec:bb:78:9e:c7:f0)   Ethernet1/7       -
            e8b    cs2 (ec:bb:78:9e:c8:14)   Ethernet1/16      -
            e1a    cs1 (ec:bb:78:9e:c7:d8)   Ethernet1/1       -
            e1b    cs2 (ec:bb:78:9e:c7:fc)   Ethernet1/10      -
            e2a    cs1 (ec:bb:78:9e:c7:e0)   Ethernet1/3       -
            e2b    cs2 (ec:bb:78:9e:c8:04)   Ethernet1/12      -
node1-02/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/6       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/15      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/8       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/17      N9K-C9808
            e2a    cs1(FOXXXXXXXXXX)         Ethernet1/2       N9K-C9808
            e2b    cs2(FOX3005Q66Q)          Ethernet1/13      N9K-C9808
node1-02/lldp
            e10a   cs1 (ec:bb:78:9e:c7:ec)   Ethernet1/6       -
            e10b   cs2 (ec:bb:78:9e:c8:10)   Ethernet1/15      -
            e8a    cs1 (ec:bb:78:9e:c7:f4)   Ethernet1/8       -
            e8b    cs2 (ec:bb:78:9e:c8:18)   Ethernet1/17      -
            e1a    cs1 (ec:bb:78:9e:c7:dc)   Ethernet1/2       -
            e1b    cs2 (ec:bb:78:9e:c8:00)   Ethernet1/11      -
            e2a    cs1 (ec:bb:78:9e:c7:e4)   Ethernet1/4       -
            e2b    cs2 (ec:bb:78:9e:c8:08)   Ethernet1/13      -
.
.
.
----
====
. Consulta el estado administrativo y operativo de cada puerto.
+
.. *Puertos de clúster*
+
... Verifique que todos los puertos del clúster estén activos y en buen estado:
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-02
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-03

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false
----
====
... Verifique que todas las interfaces del clúster (LIF) estén en el puerto principal:
+
[source, cli]
----
network interface show -role cluster
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network           Current      Current Is
Vserver     Interface          Admin/Oper Address/Mask      Node         Port    Home
----------- ------------------ ---------- ----------------- ------------ ------- ----
Cluster
            node1-01_clus1     up/up      169.254.3.4/23     node1-01    e2a     true
            node1-01_clus2     up/up      169.254.3.5/23     node1-01    e2b     true
            node1-02_clus1     up/up      169.254.3.8/23     node1-02    e2a     true
            node1-02_clus2     up/up      169.254.3.9/23     node1-02    e2b     true
            node1-03_clus1     up/up      169.254.1.3/23     node1-03    e2a     true
            node1-03_clus2     up/up      169.254.1.1/23     node1-03    e2b     true
            node1-04_clus1     up/up      169.254.1.6/23     node1-04    e2a     true
            node1-04_clus2     up/up      169.254.1.7/23     node1-04    e2b     true
----
====
... Verifique que el clúster muestre información para ambos conmutadores:
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs2(FDOXXXXXXXX)            cluster-network    10.228.137.233   N9K-C9808
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(3)(F)
    Version Source: CDP/ISDP


cs1(FOXXXXXXXXX)            cluster-network    10.228.137.234   N9K-C9808
     Serial Number: FOXXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(3)(F)
    Version Source: CDP/ISDP
----
====


.. *Puertos HA*
+
... Verifique que todos los puertos HA estén activos con un estado saludable:
+
[source, cli]
----
ha interconnect status show -node <node-name>
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====
... Comprueba que todos los puertos HA estén correctamente configurados y que el tipo de interconexión sea RoCE:
+
[source, cli]
----
ha interconnect config show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect config show*
  (system ha interconnect config show)
                       Node: node1-01
          Interconnect Type: RoCE
            Local System ID: 542023071
          Partner System ID: 542022984
       Connection Initiator: local
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.111     0x0
e1b-18  169.254.18.242     0x0



                       Node: node1-02
          Interconnect Type: RoCE
            Local System ID: 542022984
          Partner System ID: 542023071
       Connection Initiator: partner
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.208     0x0
e1b-18  169.254.18.169     0x0
.
.
.
----
====


.. *Puertos de almacenamiento*
+
... Verifique que todos los puertos de almacenamiento se encuentren en buen estado:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-02
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-03
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-04
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
----
====


.. *Puertos para estantes de almacenamiento*
+
... Verifique que todos los puertos del estante de almacenamiento estén activos con un estado saludable:
+
[source, cli]
----
storage shelf port show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.0
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false
----
====
... Verifique que todos los puertos del estante de almacenamiento estén activos con un estado saludable:
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 cs1(FOXXXXXXXXX)
1.1   1  connected       Ethernet1/15/1 cs2(FDOXXXXXXXX)
1.1   2  connected       Ethernet1/17/2 cs1(FOXXXXXXXXX)
1.1   3  connected       Ethernet1/15/2 cs2(FDOXXXXXXXX)
1.1   4  connected       Ethernet1/17/3 cs1(FOXXXXXXXXX)
1.1   5  connected       Ethernet1/15/3 cs2(FDOXXXXXXXX)
1.1   6  connected       Ethernet1/17/4 cs1(FOXXXXXXXXX)
1.1   7  connected       Ethernet1/15/4 cs2(FDOXXXXXXXX)
1.1   8  connected       Ethernet1/19/1 cs1(FOXXXXXXXXX)
1.1   9  connected       Ethernet1/17/1 cs2(FDOXXXXXXXX)
1.1   10 connected       Ethernet1/19/2 cs1(FOXXXXXXXXX)
1.1   11 connected       Ethernet1/17/2 cs2(FDOXXXXXXXX)
1.1   12 connected       Ethernet1/19/3 cs1(FOXXXXXXXXX)
1.1   13 connected       Ethernet1/17/3 cs2(FDOXXXXXXXX)
1.1   14 connected       Ethernet1/19/4 cs1(FOXXXXXXXXX)
1.1   15 connected       Ethernet1/17/4 cs2(FDOXXXXXXXX)
----
====




. Desactiva la reversión automática en las LIF del clúster. Las LIF del clúster se transfieren al conmutador del clúster asociado y permanecen allí mientras realizas este procedimiento en el conmutador de destino:
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----




[[step-2-configure-ports]]
== Paso 2: Configurar puertos

. Mediante la interfaz de línea de comandos (CLI) del switch, en el switch cs1, apaga los puertos conectados a todos los puertos de los nodos para cada tarjeta de línea.
+
El siguiente ejemplo muestra los comandos para desactivar todos los puertos de la tarjeta de línea 1 `e1`, `e1-1/1-18`, `e1/19/1-4`, `e1/20/1-4` ......... `e1/35/1-4`. Repite los comandos para cada tarjeta de línea del conmutador.

+
[listing, subs="+quotes"]
----
cs1# *config terminal*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-18*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-4,e1/23/1-4,e1/24/1-4,e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-4,e1/31/1-4,e1/32/1-4,e1/33/1-4,e1/34/1-4,e1/35/1-4*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
+

CAUTION: Asegúrate de apagar *todos* los puertos conectados para evitar cualquier problema de conexión a la red. Consulta el artículo de base de conocimientos link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["Nodo fuera de quórum al migrar la LIF del clúster durante la actualización del sistema operativo del switch"^] para más detalles.

. Mediante la CLI de ONTAP, comprueba que las LIF del clúster se hayan conmutado a los puertos alojados en el switch cs1. Esto puede tardar unos segundos.
+
[source, cli]
----
network interface show -role cluster
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e2a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e2b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e2a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e2b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e2a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e2b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e2a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e2b     true

8 entries were displayed.
----
====
. Usando la CLI de ONTAP, verifica que el clúster esté en buen estado:
+
[source, cli]
----
cluster show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------  -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false
----
====
. Si aún no lo has hecho, utilizando la CLI del conmutador, guarda una copia de la configuración actual del conmutador copiando el resultado del siguiente comando en un archivo de texto:
+
`show running-config`

+
.. Utiliza el comando  `show diff running-config` para comparar con el archivo RCF guardado en el bootflash. De lo contrario, utiliza una herramienta de comparación de terceros.


. Guarde los detalles de configuración básicos en el `write_erase.cfg` archivo en la memoria flash de arranque.
+
[NOTE]
====
Asegúrese de configurar lo siguiente:

** Nombre de usuario y contraseña
** Dirección IP de gestión
** Puerta de enlace predeterminada
** Cambiar nombre


====
+
[CAUTION]
====
Si el  `write_erase.cfg` archivo ya existe, cámbiale el nombre a  `write_erase_old.cfg`, así:

`cs1# move bootflash:write_erase.cfg write_erase_old.cfg`

====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

+
Consulta el artículo de base de conocimientos link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Cómo borrar la configuración de un switch de interconexión Cisco manteniendo la conectividad remota"^] para más detalles.

. Usando la CLI del switch, verifica que el archivo  `write_erase.cfg` esté rellenado como se espera:
+
`show file bootflash:write_erase.cfg`

. Usando la CLI del switch, ejecuta el comando  `write erase` para borrar la configuración guardada actual:
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Usando la CLI del switch, copia la configuración básica guardada anteriormente en la configuración de inicio.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. Usando la CLI del switch, reinicia el switch:
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Una vez que la dirección IP de administración vuelva a ser accesible, inicie sesión en el switch a través de SSH.
+
Es posible que necesites actualizar las entradas del archivo host relacionadas con las claves SSH.

. Usando la CLI del conmutador, copia el RCF en la bootflash del conmutador cs1 usando uno de los siguientes protocolos de transferencia: FTP, TFTP, SFTP o SCP.
+
Para obtener más información sobre los comandos de Cisco, consulta la guía correspondiente en las link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^] guides.

+
`copy <protocol>: bootflash: vrf management`

+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo muestra cómo se utiliza TFTP para copiar un RCF a la memoria flash de arranque del switch cs1:

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *RCF-v10.1-NX9808-CL1-ST1.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Usando la CLI del switch, aplica el RCF previamente descargado en la bootflash.
+
Para obtener más información sobre los comandos de Cisco, consulta la guía correspondiente en las link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^] guides.

+
Este ejemplo muestra el RCF `RCF-v10.1-NX9808-CL1-ST1.txt` instalándose en el switch cs1:

+
[listing, subs="+quotes"]
----
cs1# *copy RCF-v10.1-NX9808-CL1-ST1.txt running-config echo-commands*
----
+
[CAUTION]
====
Asegúrese de leer detenidamente las secciones *Notas de instalación*, *Notas importantes* y *banner* de su RCF. Debe leer y seguir estas instrucciones para garantizar la configuración y el funcionamiento adecuados del conmutador.

====
. Usando la CLI del conmutador, verifica que el RCF sea la versión más reciente correcta:
+
`show running-config`

+
Al comprobar la salida para verificar que tiene el RCF correcto, asegúrese de que la siguiente información sea correcta:

+
** El estandarte de RCF
** Configuración del nodo y del puerto
** Personalizaciones
+
El resultado varía según la configuración de su sitio.  Compruebe la configuración del puerto y consulte las notas de la versión para conocer los cambios específicos del RCF que haya instalado.



. Vuelva a aplicar cualquier personalización anterior a la configuración del switch.
+
Si tus conmutadores ejecutan RCF 10.1 o una versión posterior, puedes link:configure-install-upgrade-rcf-overview-9808.html#change-port-speed-configuration["cambia la configuración de la velocidad del puerto"] si es necesario.

. Mediante la CLI del switch, después de verificar que las versiones de RCF, las adiciones personalizadas y la configuración del switch son correctas, copia el archivo  `running-config` al archivo  `startup-config`.
+
Para más información sobre los comandos de Cisco, consulta la guía correspondiente en las  https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^] guides.

+
`cs1# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. Utilizando la interfaz de línea de comandos (CLI) del switch, reinicia el switch cs1. Puedes ignorar las alertas de «`cluster switch health monitor`» y los eventos de «`cluster ports down`» que se reporten en los nodos mientras el switch se reinicia.
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Usando la CLI de ONTAP, verifica el estado de todos los puertos del clúster.
+
.. *Puertos de clúster*
+
... Verifique que los puertos del clúster estén activos y en buen estado en todos los nodos del clúster:
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-02
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-03
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false
----
====
... Verifique el estado del switch desde el clúster.
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/5       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/14      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/7       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/16      N9K-C9808
            e2a    cs1(FOXXXXXXXXX)          Ethernet1/3       N9K-C9808
            e2b    cs2(FOXXXXXXXXX)          Ethernet1/12      N9K-C9808
node1-02/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/6       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/15      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/8       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/17      N9K-C9808
            e2a    cs1(FOXXXXXXXXXX)         Ethernet1/2       N9K-C9808
            e2b    cs2(FOX3005Q66Q)          Ethernet1/13      N9K-C9808
.
.
.
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs2(FDOXXXXXXXX)           cluster-network    10.228.137.233    N9K-C9808
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.6(3)(F)
    Version Source: CDP/ISDP

cs1(FOXXXXXXXXX)           cluster-network    10.228.137.234    N9K-C9808
     Serial Number: FOXXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.6(3)(F)
    Version Source: CDP/ISDP
----
====


.. *Puertos HA*
+
... Verifique que todos los puertos HA estén activos con un estado saludable:
+
[source, cli]
----
ha interconnect status show -node <node-name>
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====
... Comprueba que todos los puertos HA estén correctamente configurados y que el tipo de interconexión sea RoCE:
+
[source, cli]
----
ha interconnect config show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect config show*
  (system ha interconnect config show)
                       Node: node1-01
          Interconnect Type: RoCE
            Local System ID: 542023071
          Partner System ID: 542022984
       Connection Initiator: local
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.111     0x0
e1b-18  169.254.18.242     0x0



                       Node: node1-02
          Interconnect Type: RoCE
            Local System ID: 542022984
          Partner System ID: 542023071
       Connection Initiator: partner
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.208     0x0
e1b-18  169.254.18.169     0x0
.
.
.
----
====


.. *Puertos de almacenamiento*
+
... Verifique que todos los puertos de almacenamiento se encuentren en buen estado:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-02
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-03
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-04
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
----
====


.. *Puertos para estantes de almacenamiento*
+
... Verifique que todos los puertos del estante de almacenamiento estén activos con un estado saludable:
+
[source, cli]
----
storage shelf port show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.0
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false
----
====
... Verifique el estado de conexión de todos los puertos del estante de almacenamiento:
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 cs1(FOXXXXXXXXX)
1.1   1  connected       Ethernet1/15/1 cs2(FDOXXXXXXXX)
1.1   2  connected       Ethernet1/17/2 cs1(FOXXXXXXXXX)
1.1   3  connected       Ethernet1/15/2 cs2(FDOXXXXXXXX)
1.1   4  connected       Ethernet1/17/3 cs1(FOXXXXXXXXX)
1.1   5  connected       Ethernet1/15/3 cs2(FDOXXXXXXXX)
1.1   6  connected       Ethernet1/17/4 cs1(FOXXXXXXXXX)
1.1   7  connected       Ethernet1/15/4 cs2(FDOXXXXXXXX)
1.1   8  connected       Ethernet1/19/1 cs1(FOXXXXXXXXX)
1.1   9  connected       Ethernet1/17/1 cs2(FDOXXXXXXXX)
1.1   10 connected       Ethernet1/19/2 cs1(FOXXXXXXXXX)
1.1   11 connected       Ethernet1/17/2 cs2(FDOXXXXXXXX)
1.1   12 connected       Ethernet1/19/3 cs1(FOXXXXXXXXX)
1.1   13 connected       Ethernet1/17/3 cs2(FDOXXXXXXXX)
1.1   14 connected       Ethernet1/19/4 cs1(FOXXXXXXXXX)
1.1   15 connected       Ethernet1/17/4 cs2(FDOXXXXXXXX)
----
====




. Usando la CLI de ONTAP, verifica que el clúster esté en buen estado:
+
[source, cli]
----
cluster show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health   Eligibility   Epsilon
----------------- -------- ------------- -------
node1-01          true     true          false
node1-02          true     true          false
node1-03          true     true          true
node1-04          true     true          false

4 entries were displayed.
----
====
. Repita los pasos 4 a 18 en el interruptor cs2.
. Usando la CLI de ONTAP, activa la reversión automática en las LIF del clúster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----




[[step-3-verify-the-cluster-network-configuration-and-cluster-health]]
== Paso 3: Verifique la configuración de red y el estado del clúster.

. Usando la interfaz de línea de comandos (CLI) del switch, verifica que los puertos del switch conectados a los puertos del clúster estén *up*.
+
[source, cli]
----
show interface brief
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason                 Speed     Port
Interface                                                                    Ch #
--------------------------------------------------------------------------------
Eth1/1          1       eth  trunk  up      none                     400G(D) --
Eth1/2          1       eth  trunk  up      none                     400G(D) --
Eth1/3          1       eth  trunk  up      none                     400G(D) --
Eth1/4          1       eth  trunk  up      none                     400G(D) --
Eth1/5          1       eth  trunk  up      none                     400G(D) --
Eth1/6          1       eth  trunk  up      none                     400G(D) --
Eth1/7          1       eth  trunk  up      none                     400G(D) --
Eth1/8          1       eth  trunk  up      none                     400G(D) --
Eth1/9          1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/10         1       eth  trunk  up      none                     400G(D) --
Eth1/11         1       eth  trunk  up      none                     400G(D) --
Eth1/12         1       eth  trunk  up      none                     400G(D) --
Eth1/13         1       eth  trunk  up      none                     400G(D) --
Eth1/14         1       eth  trunk  up      none                     400G(D) --
Eth1/15         1       eth  trunk  up      none                     400G(D) --
Eth1/16         1       eth  trunk  up      none                     400G(D) --
Eth1/17         1       eth  trunk  up      none                     400G(D) --
Eth1/18         1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/19/1       1       eth  trunk  up      none                     100G(D) --
Eth1/19/2       1       eth  trunk  up      none                     100G(D) --
Eth1/19/3       1       eth  trunk  up      none                     100G(D) --
Eth1/19/4       1       eth  trunk  up      none                     100G(D) --
Eth1/20/1       1       eth  trunk  up      none                     100G(D) --
Eth1/20/2       1       eth  trunk  up      none                     100G(D) --
Eth1/20/3       1       eth  trunk  up      none                     100G(D) --
Eth1/20/4       1       eth  trunk  up      none                     100G(D) --
.
.
.
Eth1/30/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/30/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/30/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/30/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/36         1       eth  trunk  down    XCVR not inserted        auto(D) 1

------------------------------------------------------------------------------------
Port-channel VLAN    Type Mode   Status  Reason                    Speed   Protocol
								                                                           Interface
------------------------------------------------------------------------------------
Po1          1       eth  trunk  down    No operational members    auto(D)  lacp
Po998        1       eth  access down    Administratively down     auto(I)  none
Po999        1       eth  access down    Administratively down     auto(I)  none
----
====
. Usando la CLI del switch, verifica que los nodos esperados sigan conectados:
+
[source, cli]
----
show cdp neighbors
----
+
[source, cli]
----
show lldp neighbors
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                  Eth1/3         179    H         AFX-2K          e7a
cs2                  Eth1/4         123    H         AFX-2K          e7a
cs1                  Eth1/5         179    H         AFX-2K          e10a
cs2                  Eth1/6         123    H         AFX-2K          e10a
cs1                  Eth1/7         179    H         AFX-2K          e11a
cs2                  Eth1/8         123    H         AFX-2K          e11a
cs1                  Eth1/12        179    H         AFX-2K          e7b
cs2                  Eth1/13        123    H         AFX-2K          e7b
cs1                  Eth1/14        179    H         AFX-2K          e10b
cs2                  Eth1/15        123    H         AFX-2K          e10b
cs1                  Eth1/16        179    H         AFX-2K          e11b
cs2                  Eth1/17        123    H         AFX-2K          e11b

cs1# *show lldp neighbors*
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID            Local Intf      Hold-time  Capability  Port ID
cs1                    Eth1/1          121        S           e1a
cs2                    Eth1/2          121        S           e1a
cs1                    Eth1/3          121        S           e7a
cs2                    Eth1/4          121        S           e7a
cs1                    Eth1/5          121        S           e10a
cs2                    Eth1/6          121        S           e10a
cs1                    Eth1/7          121        S           e11a
cs2                    Eth1/8          121        S           e11a
cs1                    Eth1/10         121        S           e1b
cs2                    Eth1/11         121        S           e1b
cs1                    Eth1/12         121        S           e7b
cs2                    Eth1/13         121        S           e7b
cs1                    Eth1/14         121        S           e10b
cs2                    Eth1/15         121        S           e10b
cs1                    Eth1/16         121        S           e11b
cs2                    Eth1/17         121        S           e11b
952551000983           Eth1/19/1       120        S           e1a
952551000983           Eth1/19/2       120        S           e3a
952551000983           Eth1/19/3       120        S           e1a
952551000983           Eth1/19/4       120        S           e3a
952551000983           Eth1/20/1       120        S           e2a
952551000983           Eth1/20/2       120        S           e4a
952551000983           Eth1/20/3       120        S           e2a
952551000983           Eth1/20/4       120        S           e4a
.
.
.
----
====
. Usando la CLI del conmutador, verifica que los nodos del clúster estén en las VLAN del clúster correctas usando los siguientes comandos:
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show vlan brief*

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Po998, Po999, Eth1/1
                                                Eth1/2, Eth1/3, Eth1/4, Eth1/5
                                                Eth1/6, Eth1/7, Eth1/8, Eth1/9
                                                Eth1/10, Eth1/11, Eth1/12
                                                Eth1/13, Eth1/14, Eth1/15
                                                Eth1/16, Eth1/17, Eth1/18
                                                Eth1/36, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
.
.

                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
17   VLAN0017                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
                                                Eth1/20/2, Eth1/20/3, Eth1/20/4
                                                Eth1/21/1, Eth1/21/2, Eth1/21/3
.
.
                                                Eth1/30/4, Eth1/31/1, Eth1/31/2
                                                Eth1/31/3, Eth1/31/4, Eth1/32/1
                                                Eth1/32/2, Eth1/32/3, Eth1/32/4
                                                Eth1/33/1, Eth1/33/2, Eth1/33/3
                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
18   VLAN0018                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
.
.
                                                Eth1/30/1, Eth1/30/2, Eth1/30/3
                                                Eth1/30/4, Eth1/31/1, Eth1/31/2
                                                Eth1/31/3, Eth1/31/4, Eth1/32/1
                                                Eth1/32/2, Eth1/32/3, Eth1/32/4
                                                Eth1/33/1, Eth1/33/2, Eth1/33/3
                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
30   VLAN0030                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
                                                Eth1/20/2, Eth1/20/3, Eth1/20/4
.
.
                                                Eth1/33/1, Eth1/33/2, Eth1/33/3
                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
40   VLAN0040                         active    Po1, Eth1/1, Eth1/2, Eth1/3
                                                Eth1/4, Eth1/5, Eth1/6, Eth1/7
                                                Eth1/8, Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/36, Eth1/19/1
                                                Eth1/19/2, Eth1/19/3, Eth1/19/4
                                                Eth1/20/1, Eth1/20/2, Eth1/20/3
                                                Eth1/20/4, Eth1/21/1, Eth1/21/2
                                                Eth1/21/3, Eth1/21/4, Eth1/22/1
                                                Eth1/22/2, Eth1/22/3, Eth1/22/4
                                                Eth1/23/1, Eth1/23/2, Eth1/23/3
                                                Eth1/23/4, Eth1/24/1, Eth1/24/2
                                                Eth1/24/3, Eth1/24/4, Eth1/25/1
                                                Eth1/25/2, Eth1/25/3, Eth1/25/4
                                                Eth1/26/1, Eth1/26/2, Eth1/26/3
                                                Eth1/26/4, Eth1/27/1, Eth1/27/2
                                                Eth1/27/3, Eth1/27/4, Eth1/28/1
.
.
                                                Eth1/34/2, Eth1/34/3, Eth1/34/4
                                                Eth1/35/1, Eth1/35/2, Eth1/35/3
                                                Eth1/35/4

cs1# *show interface trunk*

--------------------------------------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
--------------------------------------------------------------------------------

Eth1/1        1       trunking      --
Eth1/2        1       trunking      --
Eth1/3        1       trunking      --
Eth1/4        1       trunking      --
Eth1/5        1       trunking      --
Eth1/6        1       trunking      --
Eth1/7        1       trunking      --
Eth1/8        1       trunking      --
Eth1/9        1       trunking      --
Eth1/10       1       trunking      --
.
.
.
Eth1/30/1     1       trunking      --
Eth1/30/2     1       trunking      --
Eth1/30/3     1       trunking      --
Eth1/30/4     1       trunking      --
Eth1/31/1     1       trunking      --
Eth1/31/2     1       trunking      --
Eth1/31/3     1       trunking      --
Eth1/31/4     1       trunking      --
Eth1/32/1     1       trunking      --
Eth1/32/2     1       trunking      --
Eth1/32/3     1       trunking      --
Eth1/32/4     1       trunking      --
Eth1/33/1     1       trunking      --
Eth1/33/2     1       trunking      --
Eth1/33/3     1       trunking      --
Eth1/33/4     1       trunking      --
Eth1/34/1     1       trunking      --
Eth1/34/2     1       trunking      --
Eth1/34/3     1       trunking      --
Eth1/34/4     1       trunking      --
Eth1/35/1     1       trunking      --
Eth1/35/2     1       trunking      --
Eth1/35/3     1       trunking      --
Eth1/35/4     1       trunking      --
Eth1/36       1       trnk-bndl     Po1
Po1           1       not-trunking  --


--------------------------------------------------------------------------------
Port          Vlans Allowed on Trunk
--------------------------------------------------------------------------------
Eth1/1        1,17-18,30,40
Eth1/2        1,17-18,30,40
Eth1/3        1,17-18,30,40
Eth1/4        1,17-18,30,40
Eth1/5        1,17-18,30,40
Eth1/6        1,17-18,30,40
Eth1/7        1,17-18,30,40
Eth1/8        1,17-18,30,40
Eth1/9        1,17-18,30,40
Eth1/10       1,17-18,30,40
Eth1/11       1,17-18,30,40
.
.
.
Eth1/30/1     1,17-18,30,40
Eth1/30/2     1,17-18,30,40
Eth1/30/3     1,17-18,30,40
Eth1/30/4     1,17-18,30,40
Eth1/31/1     1,17-18,30,40
Eth1/31/2     1,17-18,30,40
Eth1/31/3     1,17-18,30,40
Eth1/31/4     1,17-18,30,40
Eth1/32/1     1,17-18,30,40
Eth1/32/2     1,17-18,30,40
Eth1/32/3     1,17-18,30,40
Eth1/32/4     1,17-18,30,40
Eth1/33/1     1,17-18,30,40
Eth1/33/2     1,17-18,30,40
Eth1/33/3     1,17-18,30,40
Eth1/33/4     1,17-18,30,40
Eth1/34/1     1,17-18,30,40
Eth1/34/2     1,17-18,30,40
Eth1/34/3     1,17-18,30,40
Eth1/34/4     1,17-18,30,40
Eth1/35/1     1,17-18,30,40
Eth1/35/2     1,17-18,30,40
Eth1/35/3     1,17-18,30,40
Eth1/35/4     1,17-18,30,40
Eth1/36       1,40
Po1           1,40


--------------------------------------------------------------------------------
Port          Vlans Err-disabled on Trunk
--------------------------------------------------------------------------------
Eth1/1        none
Eth1/2        none
Eth1/3        none
Eth1/4        none
Eth1/5        none
Eth1/6        none
Eth1/7        none
Eth1/8        none
Eth1/9        none
Eth1/10       none
.
.
.
Eth1/30/1     none
Eth1/30/2     none
Eth1/30/3     none
Eth1/30/4     none
Eth1/31/1     none
Eth1/31/2     none
Eth1/31/3     none
Eth1/31/4     none
Eth1/32/1     none
Eth1/32/2     none
Eth1/32/3     none
Eth1/32/4     none
Eth1/33/1     none
Eth1/33/2     none
Eth1/33/3     none
Eth1/33/4     none
Eth1/34/1     none
Eth1/34/2     none
Eth1/34/3     none
Eth1/34/4     none
Eth1/35/1     none
Eth1/35/2     none
Eth1/35/3     none
Eth1/35/4     none
Eth1/36       none
Po1           none


--------------------------------------------------------------------------------
Port          STP Forwarding
--------------------------------------------------------------------------------
Eth1/1        1,17-18,30,40
Eth1/2        1,17-18,30,40
Eth1/3        1,17-18,30,40
Eth1/4        1,17-18,30,40
Eth1/5        1,17-18,30,40
Eth1/6        1,17-18,30,40
Eth1/7        1,17-18,30,40
Eth1/8        1,17-18,30,40
Eth1/9        none
Eth1/10       1,17-18,30,40
.
.
.
Eth1/30/1     none
Eth1/30/2     none
Eth1/30/3     none
Eth1/30/4     none
Eth1/31/1     none
Eth1/31/2     none
Eth1/31/3     none
Eth1/31/4     none
Eth1/32/1     none
Eth1/32/2     none
Eth1/32/3     none
Eth1/32/4     none
Eth1/33/1     none
Eth1/33/2     none
Eth1/33/3     none
Eth1/33/4     none
Eth1/34/1     none
Eth1/34/2     none
Eth1/34/3     none
Eth1/34/4     none
Eth1/35/1     none
Eth1/35/2     none
Eth1/35/3     none
Eth1/35/4     none
Eth1/36       none
Po1           none


--------------------------------------------------------------------------------
Port          Vlans in spanning tree forwarding state and not pruned
--------------------------------------------------------------------------------
Eth1/1        Feature VTP is not enabled 1,17-18,30,40
Eth1/2        Feature VTP is not enabled 1,17-18,30,40
Eth1/3        Feature VTP is not enabled 1,17-18,30,40
Eth1/4        Feature VTP is not enabled 1,17-18,30,40
Eth1/5        Feature VTP is not enabled 1,17-18,30,40
Eth1/6        Feature VTP is not enabled 1,17-18,30,40
Eth1/7        Feature VTP is not enabled 1,17-18,30,40
Eth1/8        Feature VTP is not enabled 1,17-18,30,40
Eth1/9        Feature VTP is not enabled 1,17-18,30,40
Eth1/10       Feature VTP is not enabled 1,17-18,30,40
.
.
.
Eth1/30/1     Feature VTP is not enabled none
Eth1/30/2     Feature VTP is not enabled none
Eth1/30/3     Feature VTP is not enabled none
Eth1/30/4     Feature VTP is not enabled none
Eth1/31/1     Feature VTP is not enabled none
Eth1/31/2     Feature VTP is not enabled none
Eth1/31/3     Feature VTP is not enabled none
Eth1/31/4     Feature VTP is not enabled none
Eth1/32/1     Feature VTP is not enabled none
Eth1/32/2     Feature VTP is not enabled none
Eth1/32/3     Feature VTP is not enabled none
Eth1/32/4     Feature VTP is not enabled none
Eth1/33/1     Feature VTP is not enabled none
Eth1/33/2     Feature VTP is not enabled none
Eth1/33/3     Feature VTP is not enabled none
Eth1/33/4     Feature VTP is not enabled none
Eth1/34/1     Feature VTP is not enabled none
Eth1/34/2     Feature VTP is not enabled none
Eth1/34/3     Feature VTP is not enabled none
Eth1/34/4     Feature VTP is not enabled none
Eth1/35/1     Feature VTP is not enabled none
Eth1/35/2     Feature VTP is not enabled none
Eth1/35/3     Feature VTP is not enabled none
Eth1/35/4     Feature VTP is not enabled none
Eth1/36       Feature VTP is not enabled none
Po1           Feature VTP is not enabled none
----
====
+

NOTE: Para obtener detalles específicos sobre el uso de puertos y VLAN, consulte la sección de notas importantes y el banner en su RCF.

. Usando la CLI del conmutador, verifica que el ISL entre cs1 y cs2 funciona:
+
[source, cli]
----
show port-channel summary
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SD)     Eth      LACP      Eth1/36(D)
998   Po998(SD)   Eth      NONE      --
999   Po999(SD)   Eth      NONE      --
----
====
. Mediante la CLI de ONTAP, comprueba que las LIF del clúster hayan vuelto a su puerto de origen:
+
[source, cli]
----
network interface show -role cluster
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e2a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e2b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e2a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e2b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e2a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e2b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e2a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e2b     true
----
====
+
Si alguna LIF del clúster no ha regresado a sus puertos de origen, reviértala manualmente desde el nodo local:

+
`network interface revert -vserver vserver_name -lif <lif-name>`

. Usando la CLI de ONTAP, verifica que el clúster esté en buen estado:
+
[source, cli]
----
cluster show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------- -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false
----
====
. Mediante la CLI de ONTAP, comprueba la conectividad de las interfaces del clúster remoto:
+
.. Puedes usar el `network interface check cluster-connectivity show` comando para mostrar los detalles de una comprobación de accesibilidad para la conectividad del clúster:
+
[source, cli]
----
network interface check cluster-connectivity show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*

                                  Source           Destination     Packet
Node   Date                       LIF              LIF             Loss
------ -------------------------- ---------------- --------------- -----------
node1-01
       6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1   none
       6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus1   none


node1-02
       6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1   none
       6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2   none
.
.
.
----
====
.. Alternativamente, puede utilizar el `cluster ping-cluster -node <node-name>` comando para comprobar la conectividad:
+
[source, cli]
----
cluster ping-cluster -node <node-name>
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node1-04
Getting addresses from network interface table...
Cluster node1-01_clus1 169.254.36.44 node1-01 e7a
Cluster node1-01_clus2 169.254.7.5   node1-01 e7b
Cluster node1-02_clus1 169.254.197.206 node1-02 e7a
Cluster node1-02_clus2 169.254.195.186 node1-02 e7b
Cluster node1-03_clus1 169.254.192.49 node1-03 e7a
Cluster node1-03_clus2 169.254.182.76 node1-03 e7b
Cluster node1-04_clus1 169.254.59.49 node1-04 e7a
Cluster node1-04_clus2 169.254.62.244 node1-04 e7b
Local = 169.254.59.49 169.254.62.244
Remote = 169.254.36.44 169.254.7.5 169.254.197.206 169.254.195.186 169.254.192.49 169.254.182.76
Cluster Vserver Id = 4294967293
Ping status:
............
Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)
................................................
Detected 9000 byte MTU on 12 path(s):
    Local 169.254.59.49 to Remote 169.254.182.76
    Local 169.254.59.49 to Remote 169.254.192.49
    Local 169.254.59.49 to Remote 169.254.195.186
    Local 169.254.59.49 to Remote 169.254.197.206
    Local 169.254.59.49 to Remote 169.254.36.44
    Local 169.254.59.49 to Remote 169.254.7.5
    Local 169.254.62.244 to Remote 169.254.182.76
    Local 169.254.62.244 to Remote 169.254.192.49
    Local 169.254.62.244 to Remote 169.254.195.186
    Local 169.254.62.244 to Remote 169.254.197.206
    Local 169.254.62.244 to Remote 169.254.36.44
    Local 169.254.62.244 to Remote 169.254.7.5
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----
====




.¿Que sigue?
Una vez que hayas actualizado el RCF en tus conmutadores, link:configure-verify-ssh-9808.html["Verifica SSH para la recopilación de registros"].
