---
permalink: switch-cisco-9808/configure-review-cabling-config-requirements-9808.html 
sidebar: sidebar 
keywords: 9808 cabling setup, 9808 switches configuration, nx-os 
summary: Si vas a instalar nuevos conmutadores Cisco Nexus 9808 como parte de la instalación de un nuevo sistema AFX 2K, vas a sustituir un módulo supervisor o vas a restablecer un conmutador a los ajustes predeterminados de fábrica, debes revisar los siguientes requisitos de cableado y configuración. 
---
= Revisa los requisitos de cableado y configuración - Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vas a instalar conmutadores Cisco Nexus 9808 como parte de la instalación de un nuevo sistema AFX 2K, vas a sustituir un módulo supervisor o vas a restablecer un conmutador a los ajustes predeterminados de fábrica, debes revisar los siguientes requisitos de cableado y configuración.



[[hard-code-the-speed-on-breakout-ports]]
== Fija la velocidad en los puertos breakout

Debes configurar de forma fija los puertos del switch (4x100GbE) para 100GbE. Si no configuras la velocidad de forma fija, los puertos no se activarán y permanecerán en un estado de desactivación por error.

Por ejemplo, para configurar de forma fija 100GbE en los puertos de derivación 19-35, haz lo siguiente en el modo de configuración. El ejemplo muestra los comandos que se aplican al primer switch (cs1). Repite estos comandos para el segundo switch.

[listing, subs="+quotes"]
----
(cs1)# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
(cs1)(config)# *interface e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-4,e1/23/1-4,e1/24/1-4,e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-4,e1/31/1-4,e1/32/1-4,e1/33/1-4,e1/34/1-4,e1/35/1-4*
(cs1)(config-if)# *speed 100000*
(cs1)(config-if)# *no negotiate auto*
(cs1)(config-if)# *exit*
(cs1)(config)# *exit*
(cs1)# *copy running-config startup-config*
----
.¿Que sigue?
Una vez que cumplas con los requisitos de cableado y configuración, link:configure-install-nxos-9808.html["instalar el NX-OS"].
