---
permalink: switch-cisco-9808/install-complete-afx-setup-9808.html 
sidebar: sidebar 
keywords: switches, complete system setup, Cisco Nexus, 9808 switches, AFX 
summary: Después de completar los procedimientos de configuración del switch Cisco Nexus 9808, vas al sitio de documentación del sistema AFX para encender los estantes de almacenamiento y los controladores en tu sistema AFX 2K, verificar la conectividad del switch y completar la configuración del sistema AFX. 
---
= Completa la configuración del sistema AFX - Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de completar los procedimientos de configuración del switch Cisco Nexus 9808, vas al sitio de documentación del sistema AFX para encender los estantes de almacenamiento y los controladores en tu sistema AFX 2K, verificar la conectividad del switch y completar la configuración del sistema AFX.

.Antes de empezar
* Debes haber completado los procedimientos de configuración del conmutador en el link:configure-switch-workflow-9808.html["configura el flujo de trabajo del conmutador"].
* Cada conmutador debe estar conectado a una consola o debes tener acceso remoto a cada conmutador.


.Paso
. Completa los pasos para encender y configurar tu sistema AFX 2K usando el procedimiento de link:https://docs.netapp.com/us-en/ontap-afx/install-afx-2k/power-on-hardware.html["Enciende tu sistema de almacenamiento AFX 2K"^].


.¿Que sigue?
Después de que hayas encendido las estanterías de almacenamiento y los controladores y hayas completado la configuración del sistema AFX 2K, ya puedes usar tu sistema AFX.
