---
sidebar: sidebar 
permalink: switch-cisco-9808/reference-documentation-9808.html 
keywords: shared storage cluster switch 
summary: Para la instalación y configuración del switch Cisco Nexus 9808 como parte de un nuevo sistema AFX 2K o para el mantenimiento de switches existentes, puedes consultar la documentación correspondiente de los switches Cisco y la documentación de sistemas de NetApp. 
---
= Documentación de referencia - Cisco Nexus 9808
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para la instalación y configuración del switch Cisco Nexus 9808 como parte de un nuevo sistema AFX 2K o para el mantenimiento de switches existentes, puedes consultar la documentación correspondiente de los switches Cisco y la documentación de sistemas de NetApp.


NOTE: Para obtener instrucciones paso a paso sobre cómo instalar y configurar tus conmutadores como parte de un nuevo sistema AFX 2K, consulta la link:install-configure-switches-in-afx-workflow-9808.html["Instalar y configurar conmutadores en un flujo de trabajo de un sistema AFX"].



[[cisco-switch-documentation]]
== Documentación de los switches Cisco

Para instalar y configurar tus conmutadores Cisco Nexus 9808 como parte de un nuevo sistema AFX 2K, puedes consultar los siguientes documentos de Cisco para familiarizarte con las notas de la versión de los conmutadores, la información de seguridad, las opciones de instalación, la configuración inicial del software y las referencias de comandos.

Después de instalar y configurar tus switches, puedes consultar la documentación correspondiente de Cisco para mantener tus switches.

Todos estos documentos están disponibles en la página link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Soporte para switches Cisco Nexus serie 9000"^].

[cols="1,2,3"]
|===
| Tipo de tarea | Título del documento de Cisco | Descripción 


 a| 
Instalar y configurar
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html["Notas de lanzamiento de Cisco Nexus serie 9000 NX-OS"^](Seleccione las notas correspondientes a la versión de NX-OS instalada en sus switches)
 a| 
Describe las características, errores y limitaciones de la serie Cisco Nexus 9000.



 a| 
Instalar y configurar
 a| 
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch["Información sobre cumplimiento normativo y seguridad para la serie Cisco Nexus 9000"^]
 a| 
Proporciona información sobre cumplimiento normativo, seguridad y requisitos legales de organismos internacionales para los switches de la serie Nexus 9000.



 a| 
Instalar y configurar
 a| 
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/hw/9800/9808/nx-os/cisco-nexus-9808-nx-os-mode-switch-hardware-installation-guide/m-8000-modular-overview-ph2.html?linkclickid=aisrch["Guía de instalación del hardware del conmutador Cisco Nexus 9808 en modo NX-OS"^]
 a| 
Proporciona información detallada sobre los requisitos del sitio, detalles del hardware del switch y opciones de instalación.



 a| 
Instalar y configurar
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html["Guías de configuración de software para switches Cisco Nexus serie 9000"^](Seleccione la guía correspondiente a la versión de NX-OS instalada en sus switches)
 a| 
Proporciona la información de configuración inicial del switch que necesita antes de poder configurarlo para el funcionamiento de ONTAP .



 a| 
Instalar, configurar y mantener
 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^]
 a| 
Proporciona enlaces a las diversas referencias de comandos proporcionadas por Cisco.



 a| 
Instalar y configurar
 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/upgrade/cisco-nexus-9000-nx-os-software-upgrade-downgrade-guide-101x.html["Guía de actualización y degradación de software NX-OS de la serie Cisco Nexus 9000"^](Seleccione la guía correspondiente a la versión de NX-OS instalada en sus switches)
 a| 
Proporciona información sobre cómo degradar el software del switch a uno compatible con ONTAP , si fuera necesario.



 a| 
Mantener
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-system-message-guides-list.html["Referencia de mensajes del sistema NX-OS de Cisco Nexus serie 9000"^]
 a| 
Describe los mensajes del sistema para los switches Cisco Nexus serie 9000, aquellos que son informativos y otros que podrían ayudar a diagnosticar problemas con los enlaces, el hardware interno o el software del sistema.

|===


[[netapp-systems-documentation]]
== NetApp documentación de sistemas

Para instalar y configurar tus conmutadores Cisco Nexus 9808 como parte de un nuevo sistema AFX 2K, puedes consultar los siguientes documentos y recursos de sistemas de NetApp para que te familiarices con los sistemas AFX, las versiones de ONTAP compatibles, las configuraciones de hardware compatibles y los requisitos de instalación del sistema.

[cols="1,2,3"]
|===
| Tipo de tarea | Título del documento de ONTAP | Descripción 


 a| 
Instalar y configurar
 a| 
link:https://docs.netapp.com/us-en/ontap-afx/index.html["Documentación de los sistemas AFX"^]
 a| 
Describe cómo instalar el hardware de NetApp .



 a| 
Instalar y configurar
 a| 
link:https://docs.netapp.com/us-en/ontap-family/["Documentación de ONTAP"^]
 a| 
Proporciona información detallada sobre todos los aspectos de las versiones de ONTAP .



 a| 
Instalar y configurar
 a| 
link:https://hwu.netapp.com["NetApp Hardware Universe"^]
 a| 
Proporciona información sobre la configuración y compatibilidad del hardware de NetApp .



 a| 
Instalar y configurar
 a| 
link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"^]
 a| 
Ofrece más información sobre los requisitos de instalación del sistema de almacenamiento.

|===