---
permalink: switch-cisco-9336c-fx2-shared/configure-switch-overview-9336c-shared.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Descripción general de la instalación y la configuración de los switches compartidos Cisco Nexus 9336C-FX2 
---
= Descripción general de la instalación y la configuración de los switches compartidos Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El switch compartido Cisco Nexus 9336C-FX2 forma parte de la plataforma Cisco Nexus 9000 y se puede instalar en un armario rack de sistema de NetApp. Los switches compartidos permiten combinar la funcionalidad de clúster y almacenamiento en una configuración de switch compartido, ya que admiten el uso de archivos de configuración de referencia de almacenamiento y clúster compartidos.



== Información general de configuración inicial

Para configurar un switch Cisco Nexus 9336C-FX2 en sistemas que ejecutan ONTAP, siga estos pasos:

. link:cable-9336c-shared.html["Complete la hoja de cálculo de cableado"].
+
Utilice las imágenes de cableado para completar el cableado entre las controladoras y los switches.

. link:install-9336c-shared.html["Instale el interruptor"].
. link:setup-and-configure-9336c-shared.html["Configure el switch"].
. link:install-switch-and-passthrough-panel-9336c-shared.html["Instale el switch en el armario de NetApp"].
+
En función de la configuración, podrá instalar el switch y el panel de paso a través de Cisco Nexus 9336C-FX2 en un armario de NetApp con los soportes estándar que se incluyen con el switch.

. link:prepare-nxos-rcf-9336c-shared.html["Prepare la instalación de NX-OS y RCF"].
. link:install-nxos-software-9336c-shared.html["Instale el software NX-OS"].
. link:install-nxos-rcf-9336c-shared.html["Instale el archivo de configuración RCF"].
+
Instale el RCF después de configurar por primera vez el conmutador Nexus 9336C-FX2. También puede utilizar este procedimiento para actualizar la versión de RCF.





== Información adicional

Antes de iniciar la instalación o el mantenimiento, asegúrese de revisar lo siguiente:

* link:configure-reqs-9336c-shared.html["Requisitos de configuración"]
* link:components-9336c-shared.html["Componentes y números de pieza"]
* link:required-documentation-9336c-shared.html["Documentación requerida"]

