---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/install-9336c-shared.html 
keywords:  
summary:  
---
= Instalar switches compartidos Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Siga estas instrucciones para configurar los switches compartidos Cisco Nexus 9336C-FX2.

.Antes de empezar
Asegúrese de tener lo siguiente:

* Documentación requerida del switch compartido, documentación del controlador y documentación de ONTAP .  Verlink:required-documentation-9336c-shared.html["Requisitos de documentación para los switches compartidos Cisco Nexus 9336C-FX2"] y https://docs.netapp.com/us-en/ontap/index.html["Documentación de NetApp ONTAP"^] .
* Licencias aplicables, información de red y configuración, y cables.
* Hojas de trabajo de cableado completadas. Verlink:cable-9336c-shared.html["Complete la hoja de trabajo de cableado del Cisco Nexus 9336C-FX2"] .  Para obtener más información sobre el cableado, consulte el https://hwu.netapp.com["Hardware Universe"] .


.Pasos
. Instale en rack los switches, controladores y estantes de almacenamiento NS224 NVMe.
+
Ver ellink:../switch-cisco-9336c-fx2/install-switch-and-passthrough-panel-9336c-cluster.html["Instrucciones de estantería"] para aprender cómo instalar el switch en un armario NetApp .

. Encienda los conmutadores, controladores y estantes de almacenamiento NS224 NVMe.


.¿Que sigue?
Opcionalmente, puedes link:install-switch-and-passthrough-panel-9336c-shared.html["Instalar un conmutador Cisco Nexus 9336C-FX2 en un gabinete NetApp"]. De lo contrario, vaya a link:setup-and-configure-9336c-shared.html["Configura el interruptor"].
