---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/install-9336c-shared.html 
keywords:  
summary:  
---
= Instale los switches compartidos Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Siga estas instrucciones para configurar los switches compartidos Cisco Nexus 9336C-FX2.

.Lo que necesitará
* Se requiere documentación de los switches compartidos, documentación de la controladora y documentación de ONTAP. Consulte link:required-documentation-9336c-shared.html["Requisitos de documentación de los switches compartidos Cisco Nexus 9336C-FX2"] y.. https://["Documentación de ONTAP de NetApp"^].
* Las licencias aplicables, la información de configuración y red, y los cables.
* Hojas de datos de cableado completadas. Consulte link:cable-9336c-shared.html["Rellene la hoja de trabajo del cableado Cisco Nexus 9336C-FX2"]. Para obtener más información sobre el cableado, consulte https://["Hardware Universe"].


.Pasos
. Monte en rack los switches, las controladoras y las bandejas de almacenamiento NVMe NS224.
+
Consulte https://["Instrucciones de la estantería"] Para obtener más información sobre cómo montar en rack el switch en un armario NetApp.

. Encienda los switches, las controladoras y las bandejas de almacenamiento NVMe NS224.


.El futuro
Vaya a. https://["Configurar el switch compartido Cisco Nexus 9336C-FX2"].
