---
permalink: switch-cisco-9336c-fx2-shared/install-nxos-rcf-9336c-shared.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: Puede instalar RCF después de configurar el switch Nexus 9336C-FX2 por primera vez. También puede utilizar este procedimiento para actualizar su versión de RCF. 
---
= Instalar el archivo de configuración de referencia (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede instalar el archivo de configuración de referencia (RCF) después de configurar el switch Nexus 9336C-FX2 por primera vez.

Antes de comenzar, complete el procedimiento enlink:prepare-nxos-rcf-9336c-shared.html["Prepárese para instalar NX-OS y RCF."] .

.Antes de empezar
Verifique las siguientes instalaciones y conexiones:

* Una conexión de consola al conmutador.  La conexión a la consola es opcional si tiene acceso remoto al switch.
* Los switches cs1 y cs2 están encendidos y la configuración inicial del switch está completa (la dirección IP de administración y SSH están configuradas).
* Se ha instalado la versión deseada de NX-OS.
* Las conexiones de enlace entre conmutadores (ISL) están conectadas.
* Los puertos del clúster de nodos ONTAP no están conectados.


.Configuración RCF disponible
* *ClusterStorageRCF*: admite un clúster particionado más dos zonas de almacenamiento en los conmutadores (Cluster-Storage RCF 1._xx_).




== Paso 1: Instale el RCF en los interruptores

. Inicie sesión para cambiar cs1 usando SSH o mediante una consola serial.
. Copie el RCF al bootflash del conmutador cs1 utilizando uno de los siguientes protocolos de transferencia: FTP, TFTP, SFTP o SCP.
+
Para obtener más información sobre los comandos de Cisco , consulte la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo muestra cómo se utiliza TFTP para copiar un RCF a la memoria flash de arranque del switch cs1:

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Aplique el RCF descargado previamente a la memoria flash de arranque.
+
Para obtener más información sobre los comandos de Cisco , consulte la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo muestra el archivo RCF. `Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt` Instalando en el switch cs1:

[listing]
----
cs1# copy Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt running-config echo-commands
----
====
. Examine la salida del banner de `show banner motd` dominio. Debe leer y seguir estas instrucciones para garantizar la configuración y el funcionamiento adecuados del conmutador.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Nexus N9K-C9336C-FX2
* Filename : Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt
* Date     : 10-23-2020
* Version  : v1.6
*
* Port Usage:
* Ports  1- 3: Breakout mode (4x10G) Intra-Cluster Ports, int e1/1/1-4, e1/2/1-4
, e1/3/1-4
* Ports  4- 6: Breakout mode (4x25G) Intra-Cluster/HA Ports, int e1/4/1-4, e1/5/
1-4, e1/6/1-4
* Ports  7-34: 40/100GbE Intra-Cluster/HA Ports, int e1/7-34
* Ports 35-36: Intra-Cluster ISL Ports, int e1/35-36
*
* Dynamic breakout commands:
* 10G: interface breakout module 1 port <range> map 10g-4x
* 25G: interface breakout module 1 port <range> map 25g-4x
*
* Undo breakout commands and return interfaces to 40/100G configuration in confi
g mode:
* no interface breakout module 1 port <range> map 10g-4x
* no interface breakout module 1 port <range> map 25g-4x
* interface Ethernet <interfaces taken out of breakout mode>
* inherit port-profile 40-100G
* priority-flow-control mode auto
* service-policy input HA
* exit
*
******************************************************************************
----
====
. Verifique que el archivo RCF sea la versión más reciente correcta:
+
`show running-config`

+
Al comprobar la salida para verificar que tiene el RCF correcto, asegúrese de que la siguiente información sea correcta:

+
** El estandarte de RCF
** Configuración del nodo y del puerto
** Personalizaciones
+
El resultado varía según la configuración de su sitio.  Compruebe la configuración del puerto y consulte las notas de la versión para conocer los cambios específicos del RCF que haya instalado.



. Registre cualquier adición personalizada entre el actual `running-config` archivo y el archivo RCF en uso.
. Después de verificar que las versiones de RCF y la configuración del interruptor sean correctas, copie el `running-config` archivo al `startup-config` archivo.
+
[listing]
----
cs1# copy running-config startup-config [########################################] 100% Copy complete
----
. Guarde los detalles de configuración básicos en el `write_erase.cfg` archivo en la memoria flash de arranque.
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

. Para RCF versión 1.12 y posteriores, ejecute los siguientes comandos:
+
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1280" >> bootflash:write_erase.cfg`

+
Consulte el artículo de la base de conocimientoslink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Cómo borrar la configuración de un switch de interconexión Cisco manteniendo la conectividad remota"^] Para obtener más detalles.

. Verifique que el `write_erase.cfg` El archivo se ha rellenado según lo previsto:
+
`show file bootflash:write_erase.cfg`

. Ejecute el comando write erase para borrar la configuración guardada actual:
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copie la configuración básica guardada previamente en la configuración de inicio.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. Reiniciar interruptor cs1.
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Repita los pasos 1 al 13 en el interruptor cs2.
. Conecte los puertos del clúster de todos los nodos del clúster ONTAP a los conmutadores cs1 y cs2.




== Paso 2: Verifique las conexiones del interruptor

. Verifique que los puertos del switch conectados a los puertos del clúster estén *activos*.
+
`show interface brief`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
.
.
Eth1/1/1      1       eth  access up      none                    10G(D) --
Eth1/1/2      1       eth  access up      none                    10G(D) --
Eth1/7        1       eth  trunk  up      none                   100G(D) --
Eth1/8        1       eth  trunk  up      none                   100G(D) --
.
.
----
====
. Verifique que los nodos del clúster se encuentren en sus VLAN de clúster correctas utilizando los siguientes comandos:
+
`show vlan brief`

+
`show interface trunk`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show vlan brief*

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Eth1/1, Eth1/2, Eth1/3
                                                Eth1/4, Eth1/5, Eth1/6, Eth1/7
                                                Eth1/8, Eth1/35, Eth1/36
                                                Eth1/9/1, Eth1/9/2, Eth1/9/3
                                                Eth1/9/4, Eth1/10/1, Eth1/10/2
                                                Eth1/10/3, Eth1/10/4
17   VLAN0017                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9/1, Eth1/9/2, Eth1/9/3
                                                Eth1/9/4, Eth1/10/1, Eth1/10/2
                                                Eth1/10/3, Eth1/10/4
18   VLAN0018                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9/1, Eth1/9/2, Eth1/9/3
                                                Eth1/9/4, Eth1/10/1, Eth1/10/2
                                                Eth1/10/3, Eth1/10/4
31   VLAN0031                         active    Eth1/11, Eth1/12, Eth1/13
                                                Eth1/14, Eth1/15, Eth1/16
                                                Eth1/17, Eth1/18, Eth1/19
                                                Eth1/20, Eth1/21, Eth1/22
32   VLAN0032                         active    Eth1/23, Eth1/24, Eth1/25
                                                Eth1/26, Eth1/27, Eth1/28
                                                Eth1/29, Eth1/30, Eth1/31
                                                Eth1/32, Eth1/33, Eth1/34
33   VLAN0033                         active    Eth1/11, Eth1/12, Eth1/13
                                                Eth1/14, Eth1/15, Eth1/16
                                                Eth1/17, Eth1/18, Eth1/19
                                                Eth1/20, Eth1/21, Eth1/22
34   VLAN0034                         active    Eth1/23, Eth1/24, Eth1/25
                                                Eth1/26, Eth1/27, Eth1/28
                                                Eth1/29, Eth1/30, Eth1/31
                                                Eth1/32, Eth1/33, Eth1/34

cs1# *show interface trunk*

-----------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
-----------------------------------------------------
Eth1/1        1       trunking      --
Eth1/2        1       trunking      --
Eth1/3        1       trunking      --
Eth1/4        1       trunking      --
Eth1/5        1       trunking      --
Eth1/6        1       trunking      --
Eth1/7        1       trunking      --
Eth1/8        1       trunking      --
Eth1/9/1      1       trunking      --
Eth1/9/2      1       trunking      --
Eth1/9/3      1       trunking      --
Eth1/9/4      1       trunking      --
Eth1/10/1     1       trunking      --
Eth1/10/2     1       trunking      --
Eth1/10/3     1       trunking      --
Eth1/10/4     1       trunking      --
Eth1/11       33      trunking      --
Eth1/12       33      trunking      --
Eth1/13       33      trunking      --
Eth1/14       33      trunking      --
Eth1/15       33      trunking      --
Eth1/16       33      trunking      --
Eth1/17       33      trunking      --
Eth1/18       33      trunking      --
Eth1/19       33      trunking      --
Eth1/20       33      trunking      --
Eth1/21       33      trunking      --
Eth1/22       33      trunking      --
Eth1/23       34      trunking      --
Eth1/24       34      trunking      --
Eth1/25       34      trunking      --
Eth1/26       34      trunking      --
Eth1/27       34      trunking      --
Eth1/28       34      trunking      --
Eth1/29       34      trunking      --
Eth1/30       34      trunking      --
Eth1/31       34      trunking      --
Eth1/32       34      trunking      --
Eth1/33       34      trunking      --
Eth1/34       34      trunking      --
Eth1/35       1       trnk-bndl     Po1
Eth1/36       1       trnk-bndl     Po1
Po1           1       trunking      --

------------------------------------------------------
Port          Vlans Allowed on Trunk
------------------------------------------------------
Eth1/1        1,17-18
Eth1/2        1,17-18
Eth1/3        1,17-18
Eth1/4        1,17-18
Eth1/5        1,17-18
Eth1/6        1,17-18
Eth1/7        1,17-18
Eth1/8        1,17-18
Eth1/9/1      1,17-18
Eth1/9/2      1,17-18
Eth1/9/3      1,17-18
Eth1/9/4      1,17-18
Eth1/10/1     1,17-18
Eth1/10/2     1,17-18
Eth1/10/3     1,17-18
Eth1/10/4     1,17-18
Eth1/11       31,33
Eth1/12       31,33
Eth1/13       31,33
Eth1/14       31,33
Eth1/15       31,33
Eth1/16       31,33
Eth1/17       31,33
Eth1/18       31,33
Eth1/19       31,33
Eth1/20       31,33
Eth1/21       31,33
Eth1/22       31,33
Eth1/23       32,34
Eth1/24       32,34
Eth1/25       32,34
Eth1/26       32,34
Eth1/27       32,34
Eth1/28       32,34
Eth1/29       32,34
Eth1/30       32,34
Eth1/31       32,34
Eth1/32       32,34
Eth1/33       32,34
Eth1/34       32,34
Eth1/35       1
Eth1/36       1
Po1           1
..
..
..
..
..
----
====
+

NOTE: Para obtener detalles específicos sobre el uso de puertos y VLAN, consulte la sección de notas importantes y el banner en su RCF.

. Verifique que el ISL entre cs1 y cs2 sea funcional:
+
`show port-channel summary`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)        Eth1/36(P)
cs1#
----
====




== Paso 3: Configura tu clúster ONTAP

NetApp recomienda utilizar System Manager para configurar nuevos clústeres.

System Manager proporciona un flujo de trabajo simple y fácil para la configuración del clúster, incluyendo la asignación de una dirección IP de administración de nodos, la inicialización del clúster, la creación de una capa local, la configuración de protocolos y el aprovisionamiento de almacenamiento inicial.

Ir a https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Configurar ONTAP en un nuevo clúster con el Administrador del sistema"] Para obtener instrucciones de configuración.

.¿Que sigue?
Una vez instalado RCF, puedes link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
