---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= Migrar desde una configuración conmutada con almacenamiento de conexión directa
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede migrar desde una configuración con switch con almacenamiento de conexión directa agregando dos nuevos switches compartidos.

.Switches compatibles
Se admiten los siguientes switches:

* Nexus 9336C-FX2
* Nexus 3232C


Las versiones ONTAP y NX-OS compatibles con este procedimiento se encuentran en la página Cisco Ethernet Switches. Consulte https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco"].

.Puertos de conexión
Los switches utilizan los siguientes puertos para conectarse a los nodos:

* Nexus 9336C-FX2:
+
** Puertos 1- 3: Modo de arranque (4 x 10 G) puertos intra-clúster, int e1/1/1-4, e1/2/1-4, e1/3/1-4
** Puertos 4- 6: Modo de arranque (4x25G) puertos Intra-Cluster/ha, int e1/4/1-4, e1/5/1-4, e1/6/1-4
** Puertos 7-34: Puertos intra-clúster/alta disponibilidad de 40 GbE, int e1/7-34


* Nexus 3232C:
+
** Puertos 1-30: 10/40/100 GbE


* Los switches utilizan los siguientes puertos de enlace entre switches (ISL):
+
** Puertos E1/35-36: Nexus 9336C-FX2
** Puertos e1/31-32: Nexus 3232C




La https://hwu.netapp.com["Hardware Universe"] contiene información sobre el cableado compatible para todos los switches de clúster.

.Lo que necesitará
* Asegúrese de completar las siguientes tareas:
+
** Se configuraron algunos puertos en los switches Nexus 9336C-FX2 a 100 GbE.
** Conectividad 100 GbE planificada, migrada y documentada desde nodos a switches Nexus 9336C-FX2.
** Migre de forma no disruptiva otros switches de clúster Cisco de un clúster ONTAP a los switches de red Cisco Nexus 9336C-FX2.


* La red de switches existente está correctamente configurada y funciona.
* Todos los puertos se encuentran en el estado *up* para garantizar operaciones no disruptivas.
* Los switches Nexus 9336C-FX2 están configurados y funcionan con la versión adecuada del archivo de configuración de referencia (RCF) y de NX-OS instalado.
* La configuración de red existente tiene lo siguiente:
+
** Un clúster de NetApp redundante y totalmente funcional mediante switches Cisco anteriores.
** Conectividad de la administración y acceso de consola a los switches Cisco anteriores y a los nuevos.
** Todas las LIF del clúster en el estado *up* con las LIF del clúster se encuentran en sus puertos de inicio.
** Puertos ISL habilitados y cableado entre los otros switches Cisco y entre los nuevos switches.




.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la nomenclatura de conmutador y nodo siguiente:

* Los switches de clúster existentes de Cisco Nexus 3232C son _c1_ y _c2_.
* Los nuevos switches Nexus 9336C-FX2 son _sh1_ y _sh2_.
* Los nodos son _1_ y _2_.
* Las LIF del clúster son _1_clus1_ y _1_clus2_ en el nodo 1, y _2_clus1_ y _2_clus2_ en el nodo 2, respectivamente.
* El interruptor c2 se sustituye primero por el interruptor sh2 y, a continuación, el interruptor c1 se sustituye por el interruptor sh1.


.Pasos
. Si se habilita AutoSupport en este clúster, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
Donde x es la duración de la ventana de mantenimiento en horas.

. Compruebe el estado administrativo y operativo de cada puerto del clúster.
. Compruebe que todos los puertos del clúster tengan el estado correcto:
+
`network port show –role cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[step4]]Compruebe que todas las interfaces de clúster (LIF) estén en el puerto de inicio:
+
`network interface show -role cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[step5]]Compruebe que el clúster muestre información de los dos switches del clúster:
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[step6]]deshabilite la reversión automática en las LIF del clúster.
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[step7]]apague el interruptor c2.
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[paso8]]Compruebe que las LIF del clúster han migrado a los puertos alojados en el switch del clúster sh1:
+
`network interface show -role cluster`

+
Esto puede tardar unos segundos.

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[step9]]sustituya el interruptor c2 por el nuevo interruptor sh2 y vuelva a conectar el nuevo interruptor.
. Compruebe que los puertos están de nuevo en sh2. *Tenga en cuenta* que los LIF siguen en el conmutador c1.
. Apague el interruptor c1.
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[paso 12]]Compruebe que las LIF del clúster han migrado a los puertos alojados en el switch del clúster sh2. Esto puede tardar unos segundos.
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[step13]]sustituya el interruptor c1 por el nuevo interruptor sh1 y vuelva a conectar el nuevo interruptor.
. Compruebe que los puertos están de nuevo en sh1. *Nota* que los LIF están todavía en el conmutador c2.
. Habilite la reversión automática en las LIF del clúster:
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[paso16]]Compruebe que el clúster esté en buen estado:
+
`cluster show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====


.El futuro
Después de migrar tus switches, puedes link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
