---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html 
keywords:  
summary:  
---
= Migrar desde un clúster sin conmutador con almacenamiento de conexión directa
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede migrar desde un clúster sin conmutadores con almacenamiento de conexión directa agregando dos nuevos conmutadores compartidos.

El procedimiento que utilice dependerá de si dispone de dos puertos de red de clúster dedicados en cada controlador o de un único puerto de clúster en cada controlador.  El proceso documentado funciona para todos los nodos que utilizan puertos ópticos o Twinax, pero no es compatible con este conmutador si los nodos utilizan puertos RJ45 10Gb BASE-T integrados para los puertos de red del clúster.

La mayoría de los sistemas requieren dos puertos de red de clúster dedicados en cada controlador. Ver https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco"] Para más información.

Si tiene un entorno de clúster sin conmutación de dos nodos existente, puede migrar a un entorno de clúster conmutado de dos nodos mediante conmutadores Cisco Nexus 9336C-FX2 para poder escalar más allá de dos nodos en el clúster.



== Requisitos de revisión

Asegúrese de que:

* Para la configuración sin interruptor de dos nodos:
+
** La configuración sin interruptor de dos nodos está correctamente configurada y funcionando.
** Los nodos ejecutan ONTAP 9.8 o posterior.
** Todos los puertos del clúster están en estado *activo*.
** Todas las interfaces lógicas del clúster (LIF) están en estado *activo* y en sus puertos *de origen*.


* Para la configuración del conmutador Cisco Nexus 9336C-FX2:
+
** Ambos switches tienen conectividad de red de gestión.
** Existe acceso mediante consola a los conmutadores del clúster.
** Las conexiones de conmutador nodo a nodo y de conmutador a conmutador Nexus 9336C-FX2 utilizan cables Twinax o de fibra.
** NetApp https://hwu.netapp.com["Hardware Universe"] Contiene más información sobre el cableado.
** Los cables de enlace entre conmutadores (ISL) están conectados a los puertos 1/35 y 1/36 en ambos conmutadores 9336C-FX2.


* Se ha completado la personalización inicial de los switches 9336C-FX2.  De modo que:
+
** Los switches 9336C-FX2 ejecutan la última versión del software.
** Se han aplicado archivos de configuración de referencia (RCF) a los conmutadores.
** Cualquier personalización del sitio, como SMTP, SNMP y SSH, se configura en los nuevos conmutadores.






== Migrar los interruptores

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de nodos y conmutadores de clúster:

* Los nombres de los conmutadores 9336C-FX2 son _cs1_ y _cs2_.
* Los nombres de los SVM del clúster son _node1_ y _node2_.
* Los nombres de los LIF son _node1_clus1_ y _node1_clus2_ en el nodo 1, y _node2_clus1_ y _node2_clus2_ en el nodo 2 respectivamente.
* El indicador cluster1::*> indica el nombre del clúster.
* Los puertos del clúster utilizados en este procedimiento son _e3a_ y _e3b_, según el controlador AFF A400 .  El https://hwu.netapp.com["Hardware Universe"] Contiene la información más reciente sobre los puertos de clúster reales para sus plataformas.




=== Paso 1: Migrar desde un clúster sin conmutador con conexión directa

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=xh` .
+
donde x es la duración de la ventana de mantenimiento en horas.




NOTE: El mensaje de AutoSupport notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante la ventana de mantenimiento.

. [[step2]]Cambie el nivel de privilegio a avanzado, ingresando "y" cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el indicador avanzado (*>).

. Deshabilite todos los puertos orientados a nodos (excepto los puertos ISL) en ambos conmutadores de clúster nuevos cs1 y cs2.  No debe deshabilitar los puertos ISL.
+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos orientados al nodo del 1 al 34 están deshabilitados en el switch cs1:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *shutdown*
----
====


. [[step4]]Verifique que el ISL y los puertos físicos en el ISL entre los dos switches 9336C-FX2 cs1 y cs2 estén activos en los puertos 1/35 y 1/36:
+
`show port-channel summary`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos ISL están activos en el switch cs1:

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
El siguiente ejemplo muestra que los puertos ISL están activos en el switch cs2:

[listing, subs="+quotes"]
----
       cs2# *show port-channel summary*
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====


. [[step5]]Mostrar la lista de dispositivos vecinos:
+
`show cdp neighbors`

+
Este comando proporciona información sobre los dispositivos conectados al sistema.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo enumera los dispositivos vecinos en el switch cs1:

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
El siguiente ejemplo enumera los dispositivos vecinos en el switch cs2:

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====


. [[step6]]Verificar que todos los puertos del clúster estén activos:
+
`network port show - ipspace Cluster`

+
Cada puerto debe mostrarse activo en Enlace y saludable en Estado de salud.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
====


. [[step7]]Verificar que todas las LIF del clúster estén activas y operativas:
+
`network interface show - vserver Cluster`

+
Cada clúster LIF debería mostrar verdadero para `Is Home` y tener un estado Admin/Oper de activo/activo.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
====


. [[step8]]Verificar que la reversión automática esté habilitada en todas las LIF del clúster:
+
`network interface show - vserver Cluster -fields auto-revert`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
====


. [[step9]]Desconecte el cable del puerto de clúster e3a en el nodo1 y luego conecte e3a al puerto 1 en el conmutador de clúster cs1, utilizando el cableado apropiado compatible con los conmutadores 9336C-FX2.
+
NetApp https://hwu.netapp.com["Hardware Universe"] Contiene más información sobre el cableado.

. Desconecte el cable del puerto de clúster e3a en el nodo 2 y, luego, conecte e3a al puerto 2 en el conmutador de clúster cs1, utilizando el cableado adecuado compatible con los conmutadores 9336C-FX2.
. Habilite todos los puertos orientados a nodos en el conmutador de clúster cs1.
+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos 1/1 a 1/34 están habilitados en el switch cs1:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *no shutdown*
----
====


. [[step12]]Verifique que todas las LIF del clúster estén *activas*, operativas y se muestren como verdaderas para `Is Home` :
+
`network interface show - vserver Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que todas las LIF están *activas* en los nodos 1 y 2 y que `Is Home` Los resultados son *verdaderos*:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
====


. [[step13]]Mostrar información sobre el estado de los nodos en el clúster:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra información sobre el estado y la elegibilidad de los nodos del clúster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====


. [[step14]]Desconecte el cable del puerto de clúster e3b en el nodo1 y luego conecte e3b al puerto 1 en el conmutador de clúster cs2, utilizando el cableado apropiado compatible con los conmutadores 9336C-FX2.
. Desconecte el cable del puerto de clúster e3b en el nodo 2 y, luego, conecte e3b al puerto 2 en el conmutador de clúster cs2, utilizando el cableado adecuado compatible con los conmutadores 9336C-FX2.
. Habilite todos los puertos orientados a nodos en el conmutador de clúster cs2.
+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos 1/1 a 1/34 están habilitados en el switch cs2:

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-34*
cs2(config-if-range)# *no shutdown*
----
====


. [[step17]]Verificar que todos los puertos del clúster estén activos:
+
`network port show - ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que todos los puertos del clúster están activos en los nodos 1 y 2:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
====


. [[step18]]Verificar que todas las interfaces muestren verdadero para `Is Home` :
+
`network interface show - vserver Cluster`

+

NOTE: Esto podría tardar varios minutos en completarse.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que todas las LIF están *activas* en los nodos 1 y 2 y que `Is Home` Los resultados son ciertos:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
====


. [[step19]]Verificar que ambos nodos tengan una conexión a cada interruptor:
+
`show cdp neighbors`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra los resultados correspondientes para ambos interruptores:

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step20]]Muestra información sobre los dispositivos de red detectados en tu clúster:
+
`network device-discovery show -protocol cdp`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
====


. [[step21]]Verifique que la configuración de almacenamiento del par HA 1 (y del par HA 2) sea correcta y no presente errores:
+
`system switch ethernet show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====


. [[step22]]Verifique que la configuración esté desactivada:
+
`network options switchless-cluster show`

+

NOTE: El comando podría tardar varios minutos en completarse.  Espere el anuncio de que "la duración de la batería está a punto de expirar (3 minutos)".

+
El `false` El resultado del siguiente ejemplo muestra que la configuración está desactivada:

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====


. [[step23]]Verificar el estado de los nodos miembros del clúster:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra información sobre el estado y la elegibilidad de los nodos del clúster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step25]] Vuelva a cambiar el nivel de privilegios a administrador:
+
`set -privilege admin`





=== Paso 2: Configurar el interruptor compartido

Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los nombres de los dos conmutadores compartidos son _sh1_ y _sh2_.
* Los nodos son _nodo1_ y _nodo2_.



NOTE: El procedimiento requiere el uso de comandos ONTAP y comandos de switches Cisco Nexus serie 9000; se utilizan comandos ONTAP a menos que se indique lo contrario.

. Verifique que la configuración de almacenamiento del par HA 1 (y del par HA 2) sea correcta y no contenga errores:
+
`system switch ethernet show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Verifique que los puertos del nodo de almacenamiento estén en buen estado y operativos:
+
`storage port show -port-type ENET`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
====


. [[step3]]Mueva el par HA 1, los puertos de la ruta A del NSM224 al rango de puertos sh1 11-22.
. Instale un cable desde el par HA 1, nodo1, ruta A al rango de puertos sh1 11-22.  Por ejemplo, la ruta del puerto de almacenamiento A en un AFF A400 es e0c.
. Instale un cable desde el par HA 1, nodo2, ruta A al rango de puertos sh1 11-22.
. Verifique que los puertos del nodo estén en buen estado y operativos:
+
`storage port show -port-type ENET`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Compruebe que no haya problemas con el conmutador de almacenamiento o el cableado del clúster:
+
`system health alert show -instance`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. Mueva los puertos de la ruta B del par HA 1, NSM224 al rango de puertos sh2 11-22.
. Instale un cable desde el par HA 1, nodo1, ruta B al rango de puertos sh2 11-22.  Por ejemplo, el puerto de almacenamiento de la ruta B en un AFF A400 es e5b.
. Instale un cable desde el par HA 1, nodo2, ruta B al rango de puertos sh2 11-22.
. Verifique que los puertos del nodo estén en buen estado y operativos:
+
`storage port show -port-type ENET`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Verifique que la configuración de almacenamiento del par HA 1 sea correcta y no presente errores:
+
`system switch ethernet show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Reconfigurar los puertos de almacenamiento secundario (controlador) no utilizados en el par HA 1 de almacenamiento a red.  Si se conectaron directamente más de un NS224, habrá puertos que deberán reconfigurarse.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage port modify –node [node name] –port [port name] –mode network
----
====
+
Para colocar puertos de almacenamiento en un dominio de difusión:

+
** `network port broadcast-domain create`(para crear un nuevo dominio, si fuera necesario)
** `network port broadcast-domain add-ports`(para agregar puertos a un dominio existente)


. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.¿Que sigue?
Después de migrar tus switches, puedes link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
