---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= Migrar desde una configuración conmutada con almacenamiento de conexión directa
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede migrar desde una configuración conmutada con almacenamiento de conexión directa agregando dos nuevos conmutadores compartidos.

.Interruptores compatibles
Se admiten los siguientes conmutadores:

* Nexus 9336C-FX2
* Nexus 3232C


Las versiones de ONTAP y NX-OS compatibles con este procedimiento se encuentran en la página de switches Ethernet de Cisco . Ver https://mysupport.netapp.com/site/info/cisco-ethernet-switch["conmutadores Ethernet de Cisco"] .

.Puertos de conexión
Los conmutadores utilizan los siguientes puertos para conectarse a los nodos:

* Nexus 9336C-FX2:
+
** Puertos 1-3: Modo Breakout (4x10G) Puertos intraclúster, int e1/1/1-4, e1/2/1-4, e1/3/1-4
** Puertos 4-6: Modo Breakout (4x25G) Puertos intraclúster/HA, int e1/4/1-4, e1/5/1-4, e1/6/1-4
** Puertos 7-34: Puertos intraclúster/HA 40/100GbE, int e1/7-34


* Nexus 3232C:
+
** Puertos 1-30: 10/40/100 GbE


* Los conmutadores utilizan los siguientes puertos de enlace entre conmutadores (ISL):
+
** Puertos int e1/35-36: Nexus 9336C-FX2
** Puertos e1/31-32: Nexus 3232C




El https://hwu.netapp.com["Hardware Universe"] Contiene información sobre el cableado compatible para todos los conmutadores del clúster.

.Lo que necesitarás
* Asegúrese de haber completado las siguientes tareas:
+
** Se configuraron algunos de los puertos de los switches Nexus 9336C-FX2 para que funcionen a 100 GbE.
** Se planificó, migró y documentó la conectividad 100 GbE desde los nodos a los conmutadores Nexus 9336C-FX2.
** Migramos sin interrupciones otros switches de clúster de Cisco desde un clúster ONTAP a switches de red Cisco Nexus 9336C-FX2.


* La red de conmutación existente está configurada y funcionando correctamente.
* Todos los puertos están en estado *activo* para garantizar un funcionamiento sin interrupciones.
* Los switches Nexus 9336C-FX2 están configurados y funcionando con la versión correcta de NX-OS instalada y el archivo de configuración de referencia (RCF) aplicado.
* La configuración de red existente presenta lo siguiente:
+
** Un clúster NetApp redundante y totalmente funcional que utiliza ambos switches Cisco antiguos.
** Conectividad de gestión y acceso a la consola tanto para los switches Cisco antiguos como para los nuevos.
** Todas las LIF del clúster en estado *activo* están en sus puertos de inicio.
** Puertos ISL habilitados y cableados entre los otros switches de Cisco y entre los nuevos switches.




.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los switches de clúster Cisco Nexus 3232C existentes son _c1_ y _c2_.
* Los nuevos switches Nexus 9336C-FX2 son _sh1_ y _sh2_.
* Los nodos son _nodo1_ y _nodo2_.
* Los LIF del clúster son _node1_clus1_ y _node1_clus2_ en el nodo 1, y _node2_clus1_ y _node2_clus2_ en el nodo 2 respectivamente.
* El interruptor c2 se reemplaza primero por el interruptor sh2 y luego el interruptor c1 se reemplaza por el interruptor sh1.


.Pasos
. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
Donde x es la duración del período de mantenimiento en horas.

. Verifique el estado administrativo y operativo de cada puerto del clúster.
. Verifique que todos los puertos del clúster estén activos y en buen estado:
+
`network port show –role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[step4]]Verifique que todas las interfaces del clúster (LIF) estén en el puerto principal:
+
`network interface show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[step5]]Verifique que el clúster muestre información para ambos conmutadores del clúster:
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[step6]]Deshabilitar la reversión automática en los LIF del clúster.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[step7]]Apague el interruptor c2.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[step8]]Verificar que las LIF del clúster se hayan migrado a los puertos alojados en el switch del clúster sh1:
+
`network interface show -role cluster`

+
Esto podría tardar unos segundos.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[step9]]Reemplace el interruptor c2 con el nuevo interruptor sh2 y vuelva a cablear el nuevo interruptor.
. Verifique que los puertos estén de nuevo operativos en sh2.  *Nota*: Los LIF todavía están en el interruptor c1.
. Apague el interruptor c1.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[step12]]Verifique que las LIF del clúster se hayan migrado a los puertos alojados en el switch del clúster sh2. Esto podría tardar unos segundos.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[step13]]Reemplace el interruptor c1 con el nuevo interruptor sh1 y vuelva a cablear el nuevo interruptor.
. Verifique que los puertos estén de nuevo operativos en sh1.  *Nota*: Los LIF todavía están en el interruptor c2.
. Habilitar la reversión automática en los LIF del clúster:
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[step16]]Verificar que el clúster esté en buen estado:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====


.¿Que sigue?
Después de migrar tus switches, puedes link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
