---
permalink: switch-cisco-9336c-fx2-shared/reset-switch-9336c-shared.html 
sidebar: sidebar 
keywords: 9336C-FX2 reset switch to factory defaults, 9336C-FX2 switches configuration, efos 
summary: Antes de configurar su conmutador Cisco Nexus 9336C-FX2, revise la siguiente información. 
---
= Restablecer el conmutador compartido 9336C-FX2 a los valores predeterminados de fábrica
:allow-uri-read: 


[role="lead"]
Para restablecer el conmutador compartido 9336C-FX2 a los valores predeterminados de fábrica, debe borrar la configuración del conmutador 9336C-FX2.

.Acerca de esta tarea
* Debes estar conectado al switch mediante la consola serie.
* Esta tarea restablece la configuración de la red de administración.


.Pasos
. Borrar la configuración existente:
+
`write erase`

+
[listing, subs="+quotes"]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
. Recargue el software del conmutador:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----
+
El sistema se reinicia y entra en el asistente de configuración. Durante el arranque, si recibe el mensaje “¿Desea cancelar el aprovisionamiento automático y continuar con la configuración normal?” (sí/no)[n]”, debe responder *sí* para continuar.



.¿Qué sigue?
Después de reiniciar los interruptores, puedeslink:configure-switch-overview-9336c-shared.html["reconfigurar"] los que necesiten.
