---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/setup-and-configure-9336c-shared.html 
keywords:  
summary:  
---
= Configurar los switches compartidos Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Siga estas instrucciones para configurar los switches compartidos Cisco Nexus 9336C-FX2.

.Antes de empezar
Asegúrese de tener lo siguiente:

* Documentación requerida del switch compartido, documentación del controlador y documentación de ONTAP .  Verlink:required-documentation-9336c-shared.html["Requisitos de documentación para los switches compartidos Cisco Nexus 9336C-FX2"] y https://docs.netapp.com/us-en/ontap/index.html["Documentación de NetApp ONTAP"^] .
* Licencias aplicables, información de red y configuración, y cables.
* Hojas de trabajo de cableado completadas. Verlink:cable-9336c-shared.html["Complete la hoja de trabajo de cableado del Cisco Nexus 9336C-FX2"] .  Para obtener más información sobre el cableado, consulte el https://hwu.netapp.com["Hardware Universe"] .


.Pasos
. [[step3]]Realice una configuración inicial de los interruptores.
+
Para la configuración, necesitará el número y tipo adecuados de cables y conectores de cable para sus conmutadores.

+
Dependiendo del tipo de switch que esté configurando inicialmente, deberá conectarse al puerto de consola del switch con el cable de consola incluido; también deberá proporcionar información de red específica.

. Encienda el interruptor.
+
Proporcione las respuestas correspondientes a las siguientes preguntas de configuración inicial cuando encienda el switch por primera vez.

+
La política de seguridad de su sitio define las respuestas y los servicios que se deben habilitar.

+
.. ¿Interrumpir el aprovisionamiento automático y continuar con la configuración normal?  (sí/no)
+
Responda con *sí*.  El valor predeterminado es no.

.. ¿Desea implementar un estándar de contraseñas seguras?  (sí/no)
+
Responda con *sí*.  La respuesta predeterminada es sí.

.. Introduzca la contraseña de administrador.
+
La contraseña predeterminada es admin; debes crear una contraseña nueva y segura.

+
Una contraseña débil puede ser rechazada.

.. ¿Desea acceder al cuadro de diálogo de configuración básica?  (sí/no)
+
Responda con *sí* en la configuración inicial del switch.

.. ¿Crear otra cuenta de inicio de sesión?  (sí/no)
+
La respuesta depende de las políticas de su sitio web sobre administradores alternativos.  El valor predeterminado es no.

.. ¿Configurar la cadena de comunidad SNMP de solo lectura?  (sí/no)
+
Responda con *no*.  El valor predeterminado es no.

.. ¿Configurar la cadena de comunidad SNMP de lectura y escritura?  (sí/no)
+
Responda con *no*.  El valor predeterminado es no.

.. Introduzca el nombre del interruptor.
+
El nombre del interruptor está limitado a 63 caracteres alfanuméricos.

.. ¿Continuar con la configuración de administración fuera de banda (mgmt0)?  (sí/no)
+
Responda con *sí* (la opción predeterminada) a esa pregunta.  En la solicitud de dirección IPv4 de mgmt0, ingrese su dirección IP: ip_address

.. ¿Configurar la puerta de enlace predeterminada?  (sí/no)
+
Responda con *sí*.  En el prompt Dirección IPv4 de la puerta de enlace predeterminada: ingrese su puerta de enlace predeterminada.

.. ¿Configurar opciones IP avanzadas?  (sí/no)
+
Responda con *no*.  El valor predeterminado es no.

.. ¿Habilitar el servicio telnet?  (sí/no)
+
Responda con *no*.  El valor predeterminado es no.

.. ¿Habilitar el servicio SSH?  (sí/no)
+
Responda con *sí*.  La respuesta predeterminada es sí.

+

NOTE: Se recomienda utilizar SSH al usar Ethernet Switch Health Monitor (CSHM) por sus funciones de recopilación de registros.  También se recomienda SSHv2 para mayor seguridad.

.. [[step14]]Ingrese el tipo de clave SSH que desea generar (dsa/rsa/rsa1).  El valor predeterminado es rsa.
.. Ingrese el número de bits de clave (1024-2048).
.. ¿Configurar el servidor NTP?  (sí/no)
+
Responda con *no*.  El valor predeterminado es no.

.. Configurar la capa de interfaz predeterminada (L3/L2):
+
Responda con *L2*.  El valor predeterminado es L2.

.. Configurar el estado predeterminado de la interfaz del puerto del switch (apagado/abierto):
+
Responda con *noshut*.  El valor predeterminado es noshut.

.. Configurar el perfil del sistema CoPP (estricto/moderado/permisivo/denso):
+
Responda con *estricto*.  El valor predeterminado es estricto.

.. ¿Desea editar la configuración?  (sí/no)
+
En este punto debería ver la nueva configuración.  Revise y realice los cambios necesarios en la configuración que acaba de ingresar.  Responda con "no" cuando se le solicite si está satisfecho con la configuración.  Responda con *sí* si desea editar su configuración.

.. ¿Usar esta configuración y guardarla?  (sí/no)
+
Responda con *sí* para guardar la configuración.  Esto actualiza automáticamente las imágenes de kickstart y del sistema.



. Verifique las opciones de configuración que seleccionó en la pantalla que aparece al final de la configuración y asegúrese de guardar la configuración.
+

NOTE: Si no guarda la configuración en este paso, ninguno de los cambios tendrá efecto la próxima vez que reinicie el switch.

. Compruebe la versión en los conmutadores de red del clúster y, si es necesario, descargue la versión del software compatible con NetApp en los conmutadores desde https://software.cisco.com/download/home["Descarga de software de Cisco"^] página.


.¿Que sigue?
Una vez que hayas configurado tus interruptores, podrás link:prepare-nxos-rcf-9336c-shared.html["Prepárese para instalar NX-OS y RCF"].
