---
permalink: switch-cisco-9364d-gx2a/configure-install-nxos-9364d.html 
sidebar: sidebar 
keywords: procedure, install, nx-os, software, nexus, cluster, switch, install the nx-os software - cisco nexus 9364d-gx2a 
summary: 'Instalas el sistema operativo NX-OS en tu(s) switch Cisco Nexus 9364D-GX2A como parte de la instalación de un nuevo sistema AFX 1K o AFX 2K, de la sustitución de un switch o del restablecimiento de un switch a los valores predeterminados de fábrica.' 
---
= Instala NX-OS - Cisco Nexus 9364D-GX2A
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Instalas el sistema operativo NX-OS en tu(s) switch Cisco Nexus 9364D-GX2A como parte de la instalación de un nuevo sistema AFX 1K o AFX 2K, de la sustitución de un switch o del restablecimiento de un switch a los valores predeterminados de fábrica.

.Antes de empezar
* Los conmutadores deben estar encendidos y debes haber completado el procedimiento link:configure-complete-initial-setup-9364d.html["Completa la configuración inicial del conmutador"].
* Si vas a instalar NX-OS en uno o varios switches como parte de la instalación de un nuevo sistema AFX o de la sustitución de un switch, verifica que la versión de NX-OS en tus switches sea la versión actual compatible con NetApp.
+
** Si tus conmutadores tienen la versión actual compatible con NetApp, no necesitas instalar el NX-OS. Debes instalar el RCF. Empieza por link:configure-install-upgrade-rcf-overview-9364d.html["Instalar o actualizar la descripción general de RCF"].
** Si tus conmutadores no tienen la versión actual compatible con NetApp, sigue este procedimiento para instalar el NX-OS.


* Si vas a instalar el NX-OS en un switch como parte de una sustitución del switch o de un restablecimiento a los ajustes predeterminados de fábrica, verifica que tu clúster esté completamente funcional, es decir, que no haya errores en los registros ni problemas similares.



NOTE: Si estás instalando el NX-OS como parte de la instalación de un nuevo sistema AFX, puedes omitir este requisito porque los controladores de tu sistema AFX aún no están encendidos en este punto de la instalación y configuración de tu sistema AFX.

.Acerca de esta tarea
* La versión de ONTAP que se ejecuta en tu sistema AFX determina las versiones de NX-OS compatibles con tus switches.
+
** Para los switches en un sistema AFX 1K, que ejecuten cualquier versión compatible de ONTAP, se admite NX-OS 10.4.2 y versiones posteriores.
** Para los switches en un sistema AFX 2K que ejecutan ONTAP 9.19.1GA o posterior, se admite NX-OS 10.6 y posteriores.
+
Para consultar la lista actual de versiones de NX-OS compatibles, visita la link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco de NetApp"^] página.



* Este procedimiento solo requiere el uso de comandos de los switches Cisco Nexus 9000 Series.
* En los ejemplos de este procedimiento, el primer switch se llama cs1 y el segundo switch se llama cs2.
* Si has instalado conmutadores como parte de una nueva instalación del sistema AFX 1K o AFX 2K, este procedimiento te indica cómo instalar NX-OS en el primer conmutador (cs1) y luego te pide que repitas los pasos para el segundo conmutador (cs2).
* Los ejemplos que se muestran en este procedimiento son para sistemas AFX 1K con switches que ejecutan RCF 10.0. Si tienes un sistema AFX 2K, la entrada y la salida pueden variar.




[[step-1-prepare-to-install-the-nx-os]]
== Paso 1: prepárate para instalar NX-OS

Prepárate para instalar el NX-OS en los conmutadores asegurándote de que tienes acceso a un servidor con la versión compatible de NX-OS, descargando el NX-OS, conectándote a la red de gestión para la transferencia de archivos y luego comprobando la conectividad con el servidor.

.Pasos
. Debes tener acceso a un servidor HTTP, FTP o TFTP. El acceso a uno de estos servidores te permite descargar una versión compatible de NX-OS.
. Descarga la versión correcta de NX-OS para los conmutadores desde la  https://software.cisco.com/download/home["Descarga de software de Cisco"^] página.
. Conecta el conmutador a la red de gestión (para la transferencia de archivos).
. Comprueba la conectividad con el servidor que aloja el NX-OS mediante el comando ping.
+
`ping <IP address>`

+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo verifica que el switch puede alcanzar el servidor en la dirección IP 172.19.2.1:

[listing, subs="+quotes"]
----
cs1# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====




[[step-2-install-the-nx-os]]
== Paso 2: instalar el NX-OS

Instalas el NX-OS en el primer switch (cs1) instalando y verificando la versión de NX-OS, actualizando y verificando la imagen EPLD, y luego repites estos pasos en el segundo switch (cs2) si estás instalando el NX-OS como parte de una nueva instalación del sistema AFX.

. Copia las imágenes de NX-OS y EPLD en el primer switch.
+
Usas este comando dos veces: la primera vez para copiar la versión de NX-OS y la segunda vez para copiar la versión de EPLD.

+
`copy <protocol>: bootflash: vrf management`

+
.Mostrar ejemplo
[%collapsible]
====
El ejemplo usa sftp.

[listing, subs="+quotes"]
----
cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.10.4.2.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *root*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
root@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.10.4.2.bin  /bootflash/nxos.10.4.2.bin
/code/nxos.10.4.2.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.

cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.10.4.2.F.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.10.4.2.F.img  /bootflash/n9000-epld.10.4.2.F.img
/code/n9000-epld.10.4.2.F.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. Verifica la versión de NX-OS que se está ejecutando:
+
`show version`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.4(1) [Feature Release]
  Host NXOS: version 10.4(1)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-cs.10.4.1.F.bin
  NXOS compile time:  11/30/2023 12:00:00 [12/14/2023 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9332D-GX2B Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs2
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun  5 15:55:08 2025
  Reason: Reset Requested by CLI command reload
  System version: 10.4(1)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs2#
----
====
. Instale la imagen NX-OS.
+
La instalación del archivo de imagen provoca que este se cargue cada vez que se reinicie el switch.

+
`install all nxos bootflash:nxos.<version number>.bin`

+
.Mostrar ejemplo
[%collapsible]
====
El ejemplo usa la versión 10.4.2 de NX-OS.

[listing, subs="+quotes"]
----
cs2# *install all nxos bootflash:nxos.10.4.2.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.10.4.2.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.10.4.2.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.10.4.2.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  Bootable  Impact          Install-type  Reason
------  --------  --------------- ------------  ---------
  1     yes       Disruptive      Reset         Default upgrade is not hitless



Images will be upgraded according to following table:

Module   Image    Running-Version(pri:alt)                 New-Version         Upg-Required
------- --------- ---------------------------------------- ------------------- ------------
  1      nxos     10.4(1)                                  10.4(2)             Yes
  1      bios     xx.xx.:xx.xx                             xxx                 No


Switch will be reloaded for disruptive upgrade.

Do you want to continue with the installation (y/n)? [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS

Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. Comprueba la nueva versión de NX-OS después de que el conmutador se haya reiniciado:
+
`show version`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.4(2) [Feature Release]
  Host NXOS: version 10.4(2)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-cs.10.4.2.F.bin
  NXOS compile time:  11/30/2023 12:00:00 [12/14/2023 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9332D-GX2B Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs2
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun  5 15:55:08 2025
  Reason: Reset Requested by CLI command reload
  System version: 10.4(2)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs2#
----
====
. Actualiza la imagen EPLD con los siguientes comandos:
+
`show version module 1 epld`

+
`install epld bootflash:n9000-epld.<version>.img module all`

+
Una vez ejecutado el último comando, el switch se reinicia.

+
.Mostrar ejemplo
[%collapsible]
====
El ejemplo usa la versión 10.4.2.F de EPLD

[listing, subs="+quotes"]
----
cs2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                        0x7
IO   FPGA                        0x17
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2

cs2# *install epld bootflash:n9000-epld.10.4.2.F.img module all*
Compatibility check:
Module        Type         Upgradable        Impact    Reason
------  ------------------ ----------------- --------- -----------
     1         SUP         Yes       disruptive  Module Upgradable

Retrieving EPLD versions.... Please wait.
Images will be upgraded according to following table:
Module  Type   EPLD              Running-Version   New-Version  Upg-Required
------- ------ ----------------- ----------------- ------------ ------------
     1  SUP    MI FPGA           0x07              0x07         No
     1  SUP    IO FPGA           0x17              0x19         Yes
     1  SUP    MI FPGA2          0x02              0x02         No
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] *y*

Proceeding to upgrade Modules.

Starting Module 1 EPLD Upgrade

Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sectors)
Module 1 EPLD upgrade is successful.
Module   Type  Upgrade-Result
-------- ----- --------------
     1   SUP   Success

EPLDs upgraded.

Module 1 EPLD upgrade is successful.
----
====
. Después de que el conmutador se reinicie, inicia sesión y verifica que la nueva versión de EPLD se haya cargado correctamente:
+
`show version module 1 epld`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                        0x7
IO   FPGA                        0x19
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
----
====
. Si vas a instalar el NX-OS como parte de la instalación de un nuevo sistema AFX, repite estos pasos para instalar las imágenes de NX-OS y EPLD en el switch cs2.


.¿Que sigue?
Después de que hayas instalado NX-OS en tus conmutadores, instala RCF comenzando con el link:configure-install-upgrade-rcf-overview-9364d.html["Instalar o actualizar la descripción general de RCF"].
