---
sidebar: sidebar 
permalink: switch-cisco-9364d-gx2a/configure-reqs-9364d-cluster.html 
keywords: shared storage cluster switch 
summary: A partir de ONTAP 9.9.1, puede utilizar los conmutadores Cisco Nexus 9364d-gx2a para combinar la funcionalidad de almacenamiento y clúster en un escenario de conmutador compartido. 
---
= Requisitos de red para los conmutadores Cisco Nexus 9364D-GX2A
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del conmutador Cisco Nexus 9364D-GX2A, asegúrese de revisar los requisitos de cableado y red.



== Requisitos de red

Necesita la siguiente información de red para todas las configuraciones de los switches.

* Subred IP para el tráfico de red de gestión
* Nombres de host y direcciones IP para cada una de las controladoras del sistema de almacenamiento y todos los switches aplicables
* La mayoría de los controladores del sistema de almacenamiento se administran a través de la interfaz e0M conectándose al puerto de servicio Ethernet (ícono de llave inglesa).
* Consulte la https://hwu.netapp.com["Hardware Universe"^] para obtener la información más reciente.




== Requisitos de cableado

* Tiene el número y tipo adecuados de cables y conectores de cable para los conmutadores. Consulte https://hwu.netapp.com["Hardware Universe"^].
* Según el tipo de conmutador que esté configurando inicialmente, debe conectarse al puerto de la consola del conmutador con el cable de consola incluido.

