= Nuevo soporte de conmutador
:allow-uri-read: 




== Nuevo soporte de conmutador

[cols="25h,~,~"]
|===
| Interruptores | Descripción | Comienzo disponible 


 a| 
Conmutador Cisco de 32 puertos 400 GbE (X190300-CS-PI y X190300-PE)
 a| 
Compatibilidad con conmutadores Cisco 9332D-GX2B intra-clúster/HA/almacenamiento.
 a| 
ONTAP 9.17.1



 a| 
Conmutador Cisco de 64 puertos 400 GbE (X190310-CS-PI)
 a| 
Compatibilidad con conmutadores Cisco 9364D-GX2A intra-clúster/HA/almacenamiento.
 a| 
ONTAP 9.17.1



 a| 
Conmutador de clúster y almacenamiento Cisco Nexus 9336C-FX2-T de 12 puertos 10/25/40/100 GbE (X190212-CS-PE y X190212-CS-PI)
 a| 
Admite configuraciones de clúster de 10/25/40/100 GbE y configuraciones de almacenamiento de 100 GbE (almacenamiento conectado a conmutador).
 a| 
ONTAP 9.10.1



 a| 
Conmutador de clúster y almacenamiento Cisco Nexus 9336C-FX2-T de 12 puertos 10/25/40/100 GbE (X190212-CS-PE y X190212-CS-PI)
 a| 
Admite configuraciones de clúster de 10/25/40/100 GbE y configuraciones de almacenamiento de 100 GbE (almacenamiento conectado a conmutador).
 a| 
ONTAP 9.10.1



 a| 
Switch NVIDIA de 16 puertos (X190006-PE y X190006-PI) de 100GbE Gb
 a| 
Compatibilidad con switch de interconexión de clúster y switch de almacenamiento NVIDIA SN2100, incluida la compatibilidad con configuraciones IP de MetroCluster.
 a| 
ONTAP 9.10.1



 a| 
Switch Cisco de 36 puertos (X190200-CS-PE y X190200-CS-PI) de 100GbE Gb
 a| 
Admite una infraestructura compartida (clúster, alta disponibilidad y almacenamiento conectado a switches) en la misma pareja de switches Cisco Nexus 9336C-FX2, incluida la compatibilidad con configuraciones de IP de MetroCluster.
 a| 
ONTAP 9.9.1



 a| 
Switch Cisco 100GbE de 36 puertos (X190200-CS-PE y X190200-CS-PI), (X190210-FE-PE y X190210-FE-PI)
 a| 
Soporte del switch de interconexión de clúster Nexus 9336C-FX2 de Cisco y los switches de almacenamiento para sistemas de almacenamiento AFF y ASA, así como para la conectividad de datos de interfaz.
 a| 
ONTAP 9.8



 a| 
Conmutador Broadcom BES-53248 (X190005 y X190005R)
 a| 
Compatibilidad con switches de interconexión de clúster BES-53248 de Broadcom para controladoras AFF/FAS con puertos 10/25GbE y 40/100GbE.
 a| 
ONTAP 9.8



 a| 
Switch Cisco de 36 puertos (X190200) y switch Cisco de 100GbE 100GbE Gb con 32 puertos (X190100 y X190100R)
 a| 
Compatibilidad con switches de almacenamiento Nexus 3232C de Cisco para conectar bandejas de unidades NVMe de NS224 TB sistemas de almacenamiento AFF y ASA:

* ASA A800/AFF A800 de AFF
* ASA A700/AFF de AFF
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8

|===