---
sidebar: sidebar 
permalink: switch-cisco-9332d-gx2b/configure-reqs-9332d-cluster.html 
keywords: shared storage cluster switch 
summary: A partir de ONTAP 9.9.1, puede utilizar los conmutadores Cisco Nexus 9332D-GX2B para combinar la funcionalidad de almacenamiento y clúster en un escenario de conmutador compartido. 
---
= Requisitos de red para los conmutadores Cisco Nexus 9332D-GX2B
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del conmutador Cisco Nexus 9332D-GX2B, asegúrese de revisar los requisitos de cableado y red.



== Requisitos de red

Necesita la siguiente información de red para todas las configuraciones del conmutador.

* Subred IP para la gestión del tráfico de red
* Nombres de host y direcciones IP para cada uno de los controladores del sistema de almacenamiento y todos los conmutadores aplicables
* La mayoría de los controladores del sistema de almacenamiento se administran a través de la interfaz e0M conectándose al puerto de servicio Ethernet (ícono de llave inglesa).




== Requisitos de cableado

* Tienes el número y tipo adecuados de cables y conectores de cable para tus switches. Consulta el link:https://hwu.netapp.com["Hardware Universe"^].
* Dependiendo del tipo de conmutador que esté configurando inicialmente, deberá conectarse al puerto de consola del conmutador con el cable de consola incluido.


.Información relacionada
* Consulte el https://hwu.netapp.com["Hardware Universe"^] Para obtener la información más reciente.
* Consulta link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"^] para obtener más información sobre los requisitos de instalación del switch.

