---
sidebar: sidebar 
permalink: switch-cisco-9332d-gx2b/install-prepare-9332d.html 
keywords: shared storage cluster switch 
summary: Antes de instalar los conmutadores Cisco Nexus 9332D-GX2B como parte de la instalación de un nuevo sistema AFX 1K o AFX 2K, deberías familiarizarte con los aspectos relacionados con el conmutador y su instalación consultando la documentación correspondiente de los conmutadores Cisco y de los sistemas ONTAP, conociendo las versiones de RCF compatibles con los sistemas AFX y valorando el uso de Smart Call Home. 
---
= Prepárate para instalar los switches - Cisco Nexus 9332D-GX2B
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de instalar los conmutadores Cisco Nexus 9332D-GX2B como parte de la instalación de un nuevo sistema AFX 1K o AFX 2K, deberías familiarizarte con los aspectos relacionados con el conmutador y su instalación consultando la documentación correspondiente de los conmutadores Cisco y de los sistemas ONTAP, conociendo las versiones de RCF compatibles con los sistemas AFX y valorando el uso de Smart Call Home.



[[step-1-review-the-cisco-switch-documentation]]
=== Paso 1: Consulta la documentación del conmutador Cisco

Deberías revisar los siguientes documentos de instalación y configuración de Cisco para que te familiarices con las notas de la versión del switch, la información de seguridad, las opciones de instalación, la configuración inicial del software y las referencias de comandos.

Todos los documentos de Cisco están disponibles en la página link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Soporte para switches Cisco Nexus serie 9000"^].

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html["Notas de lanzamiento de Cisco Nexus serie 9000 NX-OS"^](Seleccione las notas correspondientes a la versión de NX-OS instalada en sus switches)
* link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch["Información sobre cumplimiento normativo y seguridad para la serie Cisco Nexus 9000"^]
* link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9332d-gx2b/cisco-nexus-9332d-gx2b-nx-os-mode-switch-hardware-installation-guide.html["Guía de instalación del hardware del conmutador de modo NX-OS Cisco Nexus 9332D-GX2B"^]
* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html["Guías de configuración de software para switches Cisco Nexus serie 9000"^](Seleccione la guía correspondiente a la versión de NX-OS instalada en sus switches)
* link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Referencia de comandos de Cisco Nexus serie 9000 NX-OS"^] Ofrece enlaces a las distintas guías de referencia de comandos proporcionadas por Cisco.




[[step-2-review-the-netapp-systems-documentation]]
=== Paso 2: Revisa la documentación de los sistemas NetApp

Deberías revisar la siguiente documentación de sistemas de NetApp para que te familiarices con la instalación del sistema AFX 1K o AFX 2K, la información sobre las versiones de ONTAP y los requisitos de configuración y compatibilidad del hardware.

* link:https://docs.netapp.com/us-en/ontap-afx/index.html["Documentación de los sistemas AFX"^] Explica cómo instalar el hardware de NetApp.
* link:https://docs.netapp.com/us-en/ontap-family/["Documentación de ONTAP"^] Ofrece información detallada sobre todos los aspectos de las versiones de ONTAP.
* link:https://hwu.netapp.com["Hardware Universe"^] Ofrece información sobre la configuración y compatibilidad del hardware de NetApp.
* link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"^] Ofrece más información sobre los requisitos de instalación del sistema de almacenamiento.




[[step-3-understand-the-supported-rcf-versions]]
=== Paso 3: conoce las versiones de RCF compatibles

La versión de ONTAP que se ejecuta en tu sistema AFX y la versión de NX-OS en tus switches determinan las versiones de RCF compatibles para tus switches. Las versiones de RCF tienen configuraciones de velocidad de puerto preestablecidas que determinan cuántos puertos del switch están en modo breakout (4x100GbE) y en modo no breakout.

[NOTE]
====
Para consultar la lista actualizada de versiones de RCF compatibles, visita la link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco de NetApp"^] página.

La información sobre los puertos del switch también se puede consultar en https://hwu.netapp.com["NetApp Hardware Universe"^].

====
* Si tienes un sistema AFX 1K, RCF 10.0 y versiones posteriores son compatibles.
* Si tienes un sistema AFX 2K, RCF 10.1 y versiones posteriores son compatibles.
* RCF 10.0 consta de un único archivo y es compatible con conmutadores compartidos, `Cluster-HA-Storage AFX RCF_10.0`.
+
Por ejemplo, la siguiente tabla muestra las agrupaciones predefinidas de los puertos del switch, sus velocidades de puerto y su uso para este archivo RCF.

+
[cols="1,2"]
|===
| Cambiar grupos de puertos del switch | Velocidades y uso de los puertos 


 a| 
Ethernet1/1/1-4 a Ethernet1/30/1-4
 a| 
Modo 4x100GbE para conexiones de clúster, alta disponibilidad y almacenamiento



 a| 
Ethernet1/31, Ethernet1/32
 a| 
400GbE ISL

|===
* RCF 10.1 cuenta con distintos archivos para diferentes casos de uso en los sistemas AFX 1K y AFX 2K. Dependiendo de cómo planees usar los switches en la configuración de tu sistema AFX 1K o AFX 2K (compartido, solo almacenamiento o solo clúster y HA), eliges el archivo RCF correspondiente.
+
Por ejemplo, si utilizas tus switches como switches compartidos en un sistema AFX 2K, usas el archivo RCF adecuado para ese caso de uso. El archivo RCF adecuado podría llamarse de forma similar a  `RCF-v10.1-NX9332D-GX2B-CL1-ST1-100GBR15-400G15.txt`. La siguiente tabla muestra los grupos predefinidos de los puertos del switch, sus velocidades de puerto y el uso para este archivo RCF.

+
[cols="1,2"]
|===
| Cambiar grupos de puertos del switch | Velocidades y uso de los puertos 


 a| 
Ethernet1/1/1-4 a Ethernet1/15/1-4
 a| 
Modo 4x100GbE para conexiones intra-clúster, HA y con los estantes de almacenamiento



 a| 
Ethernet1/16 a Ethernet1/30
 a| 
Modo 400GbE para conexiones intra-clúster, HA y de almacenamiento



 a| 
Ethernet1/31, Ethernet1/32
 a| 
Conexiones ISL intra-clúster de 400GbE

|===
+
[NOTE]
====
Puedes modificar los grupos predefinidos para ajustar el número de puertos del switch en el modo breakout (4x100GbE) y en el modo 400GbE cuando necesites adaptar una configuración de velocidad de puerto diferente para tu sistema AFX.

Harás esto más adelante, como parte del procedimiento de instalación de RCF.

====




[[step-4-consider-using-smart-call-home]]
=== Paso 4: plantéate utilizar Smart Call Home

ONTAP admite el control del estado de los switches Ethernet (CSHM) para supervisar los switches del clúster AFX, así como la capacidad de recopilar registros de diagnóstico de los switches.

Smart Call Home de Cisco es una opción que ofrece soporte proactivo y te ayuda a resolver cualquier problema que pueda surgir con los switches.

Puedes encontrar más información sobre Smart Call Home en la documentación de link:configure-smart-call-9332d.html["Configura Smart Call Home"].

.¿Que sigue?
Después de que hayas preparado todo para instalar tus switches, link:install-switches-9332d.html["instalar los interruptores"].
