---
permalink: switch-cisco-9332d-gx2b/install-upgrade-rcf-overview-cluster.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9332d-gx2b 
summary: Puede instalar el RCF después de configurar el conmutador Nexus 9332D-GX2B por primera vez. También puede utilizar este procedimiento para actualizar su versión de RCF. 
---
= Descripción general de la instalación o actualización del archivo de configuración de referencia (RCF).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Instale el archivo de configuración de referencia (RCF) después de configurar el conmutador Nexus 9332D-GX2B por primera vez. Actualiza tu versión RCF cuando tienes una versión existente del archivo RCF instalado en tu conmutador.

Consulte el artículo de la base de conocimientoslink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Cómo borrar la configuración de un switch de interconexión Cisco manteniendo la conectividad remota"^] Para obtener más información sobre la instalación o actualización de su RCF.

.Configuración RCF disponible
* *Cluster-HA-Storage*: admite tráfico compartido de clúster/HA/almacenamiento en puertos (NX9332D-GX2B-RCF-v10.0-Shared.txt).


Para obtener detalles específicos sobre el uso de puertos y VLAN, consulte la sección de notas importantes y el banner en su RCF.

.Documentación sugerida
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco (NSS)"^]
+
Consulte la tabla de compatibilidad de switches para conocer las versiones compatibles de ONTAP y RCF en el sitio de soporte de NetApp .  Tenga en cuenta que puede haber dependencias de comandos entre la sintaxis de comandos en RCF y la sintaxis que se encuentra en versiones específicas de NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Switches Cisco Nexus serie 9000"^]
+
Consulte las guías de software y actualización correspondientes disponibles en el sitio web de Cisco para obtener documentación completa sobre los procedimientos de actualización y degradación de los switches de Cisco .



.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los nombres de los dos switches de Cisco son cs1 y cs2.
* Los nombres de los nodos son node1-01, node1-02, node1-03 y node1-04.
* Los nombres del clúster LIF son node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 y node1-04_clus2.
* El `cluster1::*>` El indicador muestra el nombre del clúster.


Ver el https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para verificar los puertos correctos en su plataforma.


NOTE: Los resultados del comando pueden variar dependiendo de las diferentes versiones de ONTAP.

.Comandos utilizados
El procedimiento requiere el uso de comandos ONTAP y comandos de switches Cisco Nexus serie 9000; se utilizan comandos ONTAP a menos que se indique lo contrario.

.¿Que sigue?
Después de haber revisado el procedimiento de instalación o actualización de RCF,link:install-rcf-software-9332d-cluster.html["instalar el RCF"] olink:upgrade-rcf-software-9332d-cluster.html["Mejora tu RCF"] según sea necesario.
