---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Descripción general de la configuración de software de los switches de clúster Cisco Nexus 9336C-FX2 
---
= Flujo de trabajo de instalación de software para los switches de clúster Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar y configurar el software para un switch Cisco Nexus 9336C-FX2 y para instalar o actualizar el archivo de configuración de referencia (RCF), siga estos pasos:

. link:install-nxos-overview-9336c-cluster.html["Prepárese para instalar el software NX-OS y RCF"].
+
Se deben instalar el software Cisco NX-OS y los archivos de configuración de referencia (RCF) en los switches de clúster de Cisco Nexus 9336C-FX2.

. link:install-nxos-software-9336c-cluster.html["Instale o actualice el software NX-OS"].
+
Descargue e instale o actualice el software NX-OS en el switch de clúster Cisco Nexus 9336C-FX2.

. link:install-nxos-rcf-9336c-cluster.html["Instale o actualice el RCF"].
+
Instale o actualice el RCF después de configurar por primera vez el switch Cisco Nexus 9336C-FX2. También puede utilizar este procedimiento para actualizar la versión de RCF.

. link:configure-ssh.html["Habilite SSH"].
+
Si utiliza el monitor de estado del switch Ethernet (CSHM) y las funciones de recopilación de registros, habilite SSH en los switches.


