---
permalink: switch-cisco-9336c-fx2/configure-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: La función de recogida de registros de control de estado del switch de clúster se utiliza para recoger archivos de registro relacionados con el switch en ONTAP. Debe asegurarse de que ha configurado su entorno mediante la CLI del switch de clúster BES-53248, tal y como se describe a continuación. 
---
= Habilite la función de recogida de registros
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar la función de recopilación de registros para recoger archivos de registro relacionados con switches en ONTAP.

Compruebe que ha configurado su entorno mediante el conmutador de clúster 9336C-FX2 *CLI*.

.Pasos
. Cree una contraseña para la función de recogida de registros de monitor de estado del switch Ethernet:
+
`system switch ethernet log setup-password`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. Habilite la función de recopilación de registros del monitor de estado del switch Ethernet:
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Espere 10 minutos y compruebe que se complete la recopilación de registros:

+
`system switch ethernet log show`

+

CAUTION: Si alguno de estos comandos devuelve un error o si la recogida de registros no se completa, póngase en contacto con el soporte de NetApp.


