---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2/configure-reqs-9336c-cluster.html 
keywords: shared storage cluster switch 
summary: A partir de ONTAP 9.9.1, puede utilizar los conmutadores Cisco Nexus 9336C-FX2 para combinar la funcionalidad de almacenamiento y clúster en un escenario de conmutador compartido. 
---
= Requisitos de configuración para los conmutadores de clúster Cisco Nexus 9336C-FX2 y 9336C-FX2-T
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento de los conmutadores Cisco Nexus 9336C-FX2 y 9336C-FX2-T, asegúrese de revisar la configuración y los requisitos de red.



== Compatibilidad con ONTAP

[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
A partir de ONTAP 9.9.1, puede utilizar los switches Cisco Nexus 9336C-FX2 para combinar la funcionalidad de almacenamiento y clúster en una configuración de switch compartido.

Si desea crear clústeres ONTAP con más de dos nodos, necesitará dos conmutadores de red compatibles.


NOTE: El monitor de estado del switch Ethernet no es compatible con ONTAP 9.13.1P8 y versiones anteriores ni con 9.14.1P3 y versiones anteriores ni con NX-OS versión 10.3(4a)(M).

--
.ONTAP 9.10.1 y posteriores
--
Además, a partir de ONTAP 9.10.1, puede utilizar los conmutadores Cisco Nexus 9336C-FX2-T para combinar la funcionalidad de almacenamiento y clúster en una configuración de conmutador compartido.

Si desea crear clústeres ONTAP con más de dos nodos, necesitará dos conmutadores de red compatibles.

--
====


== Requisitos de configuración

Asegúrese de que:

* Tiene la cantidad y el tipo de cables y conectores de cables adecuados para sus conmutadores. Ver el https://hwu.netapp.com["Hardware Universe"^] .
* Dependiendo del tipo de conmutador que esté configurando inicialmente, deberá conectarse al puerto de consola del conmutador con el cable de consola incluido.




== Requisitos de red

Necesita la siguiente información de red para todas las configuraciones del conmutador.

* Subred IP para la gestión del tráfico de red
* Nombres de host y direcciones IP para cada uno de los controladores del sistema de almacenamiento y todos los conmutadores aplicables
* La mayoría de los controladores del sistema de almacenamiento se administran a través de la interfaz e0M conectándose al puerto de servicio Ethernet (ícono de llave inglesa). En los sistemas AFF A800 y AFF A700s , la interfaz e0M utiliza un puerto Ethernet dedicado.
* Consulte el https://hwu.netapp.com["Hardware Universe"^] Para obtener la información más reciente.


Para obtener más información sobre la configuración inicial de su switch, consulte la siguiente guía: https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Guía de instalación y actualización de Cisco Nexus 9336C-FX2"^] .

.¿Qué sigue?
Después de revisar los requisitos de configuración, puede confirmar su link:components-9336c-cluster.html["componentes y números de pieza"].
