---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2/configure-reqs-9336c-cluster.html 
keywords: shared storage cluster switch 
summary: Desde ONTAP 9.9.1, puede utilizar los switches Cisco Nexus 9336C-FX2 para combinar las funciones de almacenamiento y clúster en un escenario de switch compartido. 
---
= Requisitos de configuración para los conmutadores de clúster Cisco Nexus 9336C-FX2 y 9336C-FX2-T
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento de los conmutadores Cisco Nexus 9336C-FX2 y 9336C-FX2-T, asegúrese de revisar la configuración y los requisitos de red.



== Soporte de ONTAP

[role="tabbed-block"]
====
.ONTAP 9.9.1 y versiones posteriores
--
Desde ONTAP 9.9.1, puede utilizar los switches Cisco Nexus 9336C-FX2 para combinar la funcionalidad de almacenamiento y clúster en una configuración de switch compartido.

Si desea crear clústeres de ONTAP con más de dos nodos, necesita dos switches de red compatibles.


NOTE: El monitor de estado del switch Ethernet no admite ONTAP 9.13.1P8 y versiones anteriores y 9.14.1P3 y anteriores o NX-OS versión 10,3(4a)(M).

--
.ONTAP 9.10.1 y posteriores
--
Además, a partir de ONTAP 9.10.1, puede utilizar los conmutadores Cisco Nexus 9336C-FX2-T para combinar la funcionalidad de almacenamiento y clúster en una configuración de conmutador compartido.

Si desea crear clústeres de ONTAP con más de dos nodos, necesita dos switches de red compatibles.

--
====


== Requisitos de configuración

Asegúrese de que:

* Tiene el número y tipo adecuados de cables y conectores de cable para los conmutadores. Consulte https://hwu.netapp.com["Hardware Universe"^].
* Según el tipo de conmutador que esté configurando inicialmente, debe conectarse al puerto de la consola del conmutador con el cable de consola incluido.




== Requisitos de red

Necesita la siguiente información de red para todas las configuraciones de los switches.

* Subred IP para el tráfico de red de gestión
* Nombres de host y direcciones IP para cada una de las controladoras del sistema de almacenamiento y todos los switches aplicables
* La mayoría de las controladoras del sistema de almacenamiento se gestionan a través de la interfaz e0M mediante la conexión al puerto de servicio Ethernet (icono de llave inglesa). En los sistemas A800 y AFF A700 de AFF, la interfaz e0M utiliza un puerto Ethernet dedicado.
* Consulte la https://hwu.netapp.com["Hardware Universe"^] para obtener la información más reciente.


Para obtener más información acerca de la configuración inicial del switch, consulte la siguiente guía: https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Guía de instalación y actualización de Cisco Nexus 9336C-FX2"^].

.¿Qué sigue?
Después de revisar los requisitos de configuración, puede confirmar sulink:components-9336c-cluster.html["componentes y números de pieza"] .
