---
permalink: switch-cisco-9336c-fx2/CSHM_log_collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: La función de recogida de registros de control de estado del switch de clúster se utiliza para recoger archivos de registro relacionados con el switch en ONTAP. Debe asegurarse de configurar el entorno usando la CLI del switch de clúster 9336c-FX2, tal como se detalla a continuación. 
---
= Recopilación de registro de supervisión del estado del switch Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar la función de recopilación de registros para recoger archivos de registro relacionados con switches en ONTAP.
El monitor de estado del switch Ethernet (CSHM) es responsable de garantizar el estado operativo de los conmutadores de red del clúster y de almacenamiento y de recopilar registros del switch para fines de depuración. Este procedimiento lo guía a través del proceso de configuración e inicio de la recopilación de registros detallados de *Soporte* desde el switch e inicia una recopilación por hora de datos *Periódicos* que es recopilada por AutoSupport.

.Antes de empezar
* Compruebe que ha configurado su entorno mediante el conmutador de clúster 9336C-FX2 *CLI*.
* La monitorización del estado del interruptor debe estar activada para el interruptor. Verifique esto asegurándose de que el `Is Monitored:` el campo se establece en *true* en la salida del `system switch ethernet show` comando.


.Pasos
. Cree una contraseña para la función de recogida de registros de monitor de estado del switch Ethernet:
+
`system switch ethernet log setup-password`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. Para iniciar la recopilación de registros, ejecute el siguiente comando, sustituyendo EL DISPOSITIVO por el conmutador utilizado en el comando anterior. Esto inicia ambos tipos de recopilación de registros: Los registros detallados de *Support* y una recopilación horaria de datos *Periódicos*.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Espere 10 minutos y compruebe que se complete la recopilación de registros:

+
`system switch ethernet log show`

+

CAUTION: Si alguno de estos comandos devuelve un error o si la recogida de registros no se completa, póngase en contacto con el soporte de NetApp.



.Resolución de problemas
Si se encuentra con alguno de los siguientes estados de error informados por la función de recopilación de registros (visible en la salida de `system switch ethernet log show`), pruebe los pasos de depuración correspondientes:

|===


| *Estado de error de recopilación de registros* | *Resolución* 


 a| 
*Las claves RSA no están presentes*
 a| 
Vuelva a generar las claves SSH de ONTAP. Póngase en contacto con el soporte de NetApp.



 a| 
*error de contraseña de cambio*
 a| 
Verifique las credenciales, pruebe la conectividad SSH y vuelva a generar las claves SSH de ONTAP. Revise la documentación del switch o póngase en contacto con el soporte de NetApp para obtener instrucciones.



 a| 
*Las claves ECDSA no están presentes para FIPS*
 a| 
Si el modo FIPS está activado, es necesario generar claves ECDSA en el conmutador antes de volver a intentarlo.



 a| 
*registro preexistente encontrado*
 a| 
Elimine el archivo de recopilación de registros anterior del conmutador.



 a| 
*error de registro de volcado del interruptor*
 a| 
Asegúrese de que el usuario del conmutador tiene permisos de recopilación de registros. Consulte los requisitos previos anteriores.

|===