---
permalink: switch-cisco-9336c-fx2/replace-storage-switch-9336c-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: 'La sustitución de un switch Nexus 9336C-FX2 defectuoso en una red de clúster es un procedimiento no disruptivo \(NDU\).' 
---
= Sustituya un switch de almacenamiento Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer determinada información de configuración, las conexiones de puertos y los requisitos de cableado cuando sustituye los switches de almacenamiento Cisco Nexus 9336C-FX2.

.Lo que necesitará
Debe verificar que existen las siguientes condiciones antes de instalar el software NX-OS y los RCF en un switch de almacenamiento Cisco Nexus 9336C-FX2:

* Su sistema es compatible con los switches de almacenamiento Cisco Nexus 9336C-FX2.
* Debe haber consultado la tabla de compatibilidad de switches de la página Cisco Ethernet Switch para ver las versiones ONTAP, NX-OS y RCF admitidas.
* Debe haber hecho referencia a las guías de software y actualización adecuadas disponibles en el sitio web de Cisco. Switches Cisco Nexus serie 3000
* Debe haber descargado los RCF correspondientes.
* La configuración de red existente debe tener las siguientes características:
+
** La página Cisco Ethernet Switches tiene las versiones más recientes de RCF y NX-OS en sus switches.
** Debe haber conectividad de gestión en ambos switches.


* El switch Cisco Nexus 9336C-FX2 de sustitución debe tener las siguientes características:
+
** La conectividad de la red de gestión debe ser funcional.
** El acceso de la consola al interruptor de sustitución debe estar en su lugar.
** Se deben cargar en el conmutador las imágenes del sistema operativo RCF y NX-OS adecuadas.
** La configuración inicial del interruptor debe estar completa.




.Acerca de esta tarea
Este procedimiento sustituye al segundo switch de almacenamiento Nexus 9336C-FX2 S2 con el nuevo switch 9336C-FX NS2. Los dos nodos son 1 y 2.

Pasos a completar:

* Confirmar que el interruptor que se va a sustituir es S2.
* Desconectar los cables del interruptor S2.
* Vuelva a conectar los cables al conmutador NS2.
* Verifique todas las configuraciones del dispositivo en el conmutador NS2.
+

NOTE: Puede haber dependencias entre la sintaxis de comandos en las versiones RCF y NX-OS.



.Pasos
. Si se habilita AutoSupport en este clúster, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ es la duración de la ventana de mantenimiento en horas.

. Compruebe el estado de los puertos del nodo de almacenamiento para asegurarse de que exista conexión al switch de almacenamiento S1:
+
`storage port show -port-type ENET`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. Verifique que el interruptor de almacenamiento S1 esté disponible:
+
`network device-discovery show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
node1/cdp
           e3a   S1                        Ethernet1/1 NX9336C
           e4a   node2                     e4a         AFF-A700
           e4e   node2                     e4e         AFF-A700
node1/lldp
           e3a   S1                        Ethernet1/1 -
           e4a   node2                     e4a         -
           e4e   node2                     e4e         -
node2/cdp
           e3a   S1                        Ethernet1/2 NX9336C
           e4a   node1                     e4a         AFF-A700
           e4e   node1                     e4e         AFF-A700
node2/lldp
           e3a   S1                        Ethernet1/2 -
           e4a   node1                     e4a         -
           e4e   node1                     e4e         -
storage::*>
----
====
. Ejecute el programa `lldp neighbors` comando en el switch de trabajo para confirmar que puede ver tanto los nodos como todas las bandejas:
+
`show lldp neighbors`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
node1            Eth1/1       121          S             e3a
node2            Eth1/2       121          S             e3a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. Compruebe los puertos de la bandeja en el sistema de almacenamiento:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   S1
3.20    1   -             -
3.20    2   Ethernet1/6   S1
3.20    3   -             -
3.30    0   Ethernet1/7   S1
3.20    1   -             -
3.30    2   Ethernet1/8   S1
3.20    3   -             -
storage::*>
----
====
. Retire todos los cables conectados al interruptor de almacenamiento S2.
. Vuelva a conectar todos los cables al interruptor de sustitución NS2.
. Vuelva a comprobar el estado de los puertos del nodo de almacenamiento:
+
`storage port show -port-type ENET`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. Compruebe que ambos conmutadores estén disponibles:
+
`network device-discovery show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/cdp
          e3a  S1                         Ethernet1/1 NX9336C
          e4a  node2                      e4a         AFF-A700
          e4e  node2                      e4e         AFF-A700
          e7b   NS2                       Ethernet1/1 NX9336C
node1/lldp
          e3a  S1                         Ethernet1/1 -
          e4a  node2                      e4a         -
          e4e  node2                      e4e         -
          e7b  NS2                        Ethernet1/1 -
node2/cdp
          e3a  S1                         Ethernet1/2 NX9336C
          e4a  node1                      e4a         AFF-A700
          e4e  node1                      e4e         AFF-A700
          e7b  NS2                        Ethernet1/2 NX9336C
node2/lldp
          e3a  S1                         Ethernet1/2 -
          e4a  node1                      e4a         -
          e4e  node1                      e4e         -
          e7b  NS2                        Ethernet1/2 -
storage::*>
----
====
. Compruebe los puertos de la bandeja en el sistema de almacenamiento:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     S1
3.20    1     Ethernet1/5     NS2
3.20    2     Ethernet1/6     S1
3.20    3     Ethernet1/6     NS2
3.30    0     Ethernet1/7     S1
3.20    1     Ethernet1/7     NS2
3.30    2     Ethernet1/8     S1
3.20    3     Ethernet1/8     NS2
storage::*>
----
====
. Si ha suprimido la creación automática de casos, vuelva a habilitarla invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


