---
permalink: switch-cisco-9336c-fx2/reset-switch-9336c.html 
sidebar: sidebar 
keywords: 9336C-FX2 reset switch to factory defaults, 9336C-FX2 switches configuration, efos 
summary: Antes de configurar su conmutador Cisco Nexus 9336C-FX2, revise la siguiente información. 
---
= Restablecer los interruptores de clúster 9336C-FX2 y 9336C-FX2-T a los valores predeterminados de fábrica
:allow-uri-read: 


[role="lead"]
Para restablecer los interruptores del clúster 9336C-FX2 y 9336C-FX2-T a los valores predeterminados de fábrica, debe borrar la configuración de los interruptores 9336C-FX2 y 9336C-FX2-T.

.Acerca de esta tarea
* Debe estar conectado al conmutador mediante la consola serie.
* Esta tarea restablece la configuración de la red de gestión.


.Pasos
. Borrar la configuración existente:
+
`write erase`

+
[listing, subs="+quotes"]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
. Recargue el software del conmutador:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----
+
El sistema se reinicia y entra en el asistente de configuración.  Durante el arranque, si recibe el mensaje “¿Desea cancelar el aprovisionamiento automático y continuar con la configuración normal?”  (sí/no)[n]”, debe responder *sí* para continuar.


