---
permalink: switch-cisco-9336c-fx2/setup-worksheet-9336c-cluster.html 
sidebar: sidebar 
keywords: document, support, platform, complete, blank, cabling, worksheet, guide, cisco, nexus, cisco nexus 9336c-fx2 cabling worksheet - cisco nexus 9336-fx2-t 
summary: Si desea documentar las plataformas compatibles, debe completar la hoja de trabajo de cableado en blanco utilizando como guía la hoja de trabajo de cableado de muestra completada. 
---
= Complete la hoja de trabajo de cableado de Cisco Nexus 9336C-FX2 o 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea documentar las plataformas compatibles, descargue un PDF de esta página y complete la hoja de trabajo de cableado.

La hoja de cálculo de cableado de muestra proporciona ejemplos de asignaciones de puertos recomendadas desde los conmutadores a los controladores.  La hoja de trabajo en blanco proporciona una plantilla que puede utilizar para configurar su clúster.

* <<Hoja de trabajo de cableado de muestra 9336C-FX2>>
* <<Hoja de cableado en blanco 9336C-FX2>>
* <<Hoja de trabajo de cableado de muestra 9336C-FX2-T (12 puertos)>>
* <<Hoja de cableado en blanco 9336C-FX2-T (12 puertos)>>




== Hoja de trabajo de cableado de muestra 9336C-FX2

La definición de puerto de muestra en cada par de conmutadores es la siguiente:

[cols="1, 1, 1, 1"]
|===
2+| Interruptor de clúster A 2+| Interruptor de clúster B 


| Puerto de conmutación | Uso de nodos y puertos | Puerto de conmutación | Uso de nodos y puertos 


 a| 
1
 a| 
4x10GbE nodo 1
 a| 
1
 a| 
4x10GbE nodo 1



 a| 
2
 a| 
4x10GbE nodo 2
 a| 
2
 a| 
4x10GbE nodo 2



 a| 
3
 a| 
4x10GbE nodo 3
 a| 
3
 a| 
4x10GbE nodo 3



 a| 
4
 a| 
4 nodos 4x25GbE
 a| 
4
 a| 
4 nodos 4x25GbE



 a| 
5
 a| 
4x25GbE nodo 5
 a| 
5
 a| 
4x25GbE nodo 5



 a| 
6
 a| 
4x25GbE nodo 6
 a| 
6
 a| 
4x25GbE nodo 6



 a| 
7
 a| 
Nodo 7 de 40/100 GbE
 a| 
7
 a| 
Nodo 7 de 40/100 GbE



 a| 
8
 a| 
Nodo 8 de 40/100 GbE
 a| 
8
 a| 
Nodo 8 de 40/100 GbE



 a| 
9
 a| 
Nodo 9 de 40/100 GbE
 a| 
9
 a| 
Nodo 9 de 40/100 GbE



 a| 
10
 a| 
Nodo 10 de 40/100 GbE
 a| 
10
 a| 
Nodo 10 de 40/100 GbE



 a| 
11
 a| 
Nodo 11 de 40/100 GbE
 a| 
11
 a| 
Nodo 11 de 40/100 GbE



 a| 
12
 a| 
Nodo 12 de 40/100 GbE
 a| 
12
 a| 
Nodo 12 de 40/100 GbE



 a| 
13
 a| 
Nodo 13 de 40/100 GbE
 a| 
13
 a| 
Nodo 13 de 40/100 GbE



 a| 
14
 a| 
Nodo 14 de 40/100 GbE
 a| 
14
 a| 
Nodo 14 de 40/100 GbE



 a| 
15
 a| 
Nodo 15 de 40/100 GbE
 a| 
15
 a| 
Nodo 15 de 40/100 GbE



 a| 
16
 a| 
Nodo 16 de 40/100 GbE
 a| 
16
 a| 
Nodo 16 de 40/100 GbE



 a| 
17
 a| 
Nodo 17 de 40/100 GbE
 a| 
17
 a| 
Nodo 17 de 40/100 GbE



 a| 
18
 a| 
Nodo 18 de 40/100 GbE
 a| 
18
 a| 
Nodo 18 de 40/100 GbE



 a| 
19
 a| 
Nodo 19 de 40/100 GbE
 a| 
19
 a| 
Nodo 19 de 40/100 GbE



 a| 
20
 a| 
Nodo 20 de 40/100 GbE
 a| 
20
 a| 
Nodo 20 de 40/100 GbE



 a| 
21
 a| 
Nodo 21 de 40/100 GbE
 a| 
21
 a| 
Nodo 21 de 40/100 GbE



 a| 
22
 a| 
Nodo 22 de 40/100 GbE
 a| 
22
 a| 
Nodo 22 de 40/100 GbE



 a| 
23
 a| 
Nodo 23 de 40/100 GbE
 a| 
23
 a| 
Nodo 23 de 40/100 GbE



 a| 
24
 a| 
Nodo 24 de 40/100 GbE
 a| 
24
 a| 
Nodo 24 de 40/100 GbE



 a| 
25 a 34
 a| 
Reservado
 a| 
25 a 34
 a| 
Reservado



 a| 
35
 a| 
ISL 100GbE al puerto 35 del switch B
 a| 
35
 a| 
ISL 100GbE al puerto 35 del switch A



 a| 
36
 a| 
ISL 100GbE al puerto 36 del switch B
 a| 
36
 a| 
ISL 100GbE al puerto 36 del switch A

|===


== Hoja de cableado en blanco 9336C-FX2

Puede utilizar la hoja de trabajo de cableado en blanco para documentar las plataformas que se admiten como nodos en un clúster.  La sección _Conexiones de clúster admitidas_ de https://hwu.netapp.com["Hardware Universe"^] Define los puertos del clúster utilizados por la plataforma.

[cols="1, 1, 1, 1"]
|===
2+| Interruptor de clúster A 2+| Interruptor de clúster B 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25 a 34
 a| 
Reservado
 a| 
25 a 34
 a| 
Reservado



 a| 
35
 a| 
ISL 100GbE al puerto 35 del switch B
 a| 
35
 a| 
ISL 100GbE al puerto 35 del switch A



 a| 
36
 a| 
ISL 100GbE al puerto 36 del switch B
 a| 
36
 a| 
ISL 100GbE al puerto 36 del switch A

|===


== Hoja de trabajo de cableado de muestra 9336C-FX2-T (12 puertos)

La definición de puerto de muestra en cada par de conmutadores es la siguiente:

[cols="1, 1, 1, 1"]
|===
2+| Interruptor de clúster A 2+| Interruptor de clúster B 


| Puerto de conmutación | Uso de nodos y puertos | Puerto de conmutación | Uso de nodos y puertos 


 a| 
1
 a| 
4x10GbE nodo 1
 a| 
1
 a| 
4x10GbE nodo 1



 a| 
2
 a| 
4x10GbE nodo 2
 a| 
2
 a| 
4x10GbE nodo 2



 a| 
3
 a| 
4x10GbE nodo 3
 a| 
3
 a| 
4x10GbE nodo 3



 a| 
4
 a| 
4 nodos 4x25GbE
 a| 
4
 a| 
4 nodos 4x25GbE



 a| 
5
 a| 
4x25GbE nodo 5
 a| 
5
 a| 
4x25GbE nodo 5



 a| 
6
 a| 
4x25GbE nodo 6
 a| 
6
 a| 
4x25GbE nodo 6



 a| 
7
 a| 
Nodo 7 de 40/100 GbE
 a| 
7
 a| 
Nodo 7 de 40/100 GbE



 a| 
8
 a| 
Nodo 8 de 40/100 GbE
 a| 
8
 a| 
Nodo 8 de 40/100 GbE



 a| 
9
 a| 
Nodo 9 de 40/100 GbE
 a| 
9
 a| 
Nodo 9 de 40/100 GbE



 a| 
10
 a| 
Nodo 10 de 40/100 GbE
 a| 
10
 a| 
Nodo 10 de 40/100 GbE



 a| 
11 al 34
 a| 
Requiere licencia
 a| 
11 al 34
 a| 
Requiere licencia



 a| 
35
 a| 
ISL 100GbE al puerto 35 del switch B
 a| 
35
 a| 
ISL 100GbE al puerto 35 del switch A



 a| 
36
 a| 
ISL 100GbE al puerto 36 del switch B
 a| 
36
 a| 
ISL 100GbE al puerto 36 del switch A

|===


== Hoja de cableado en blanco 9336C-FX2-T (12 puertos)

Puede utilizar la hoja de trabajo de cableado en blanco para documentar las plataformas que se admiten como nodos en un clúster.  La sección _Conexiones de clúster admitidas_ de https://hwu.netapp.com["Hardware Universe"^] Define los puertos del clúster utilizados por la plataforma.

[cols="1, 1, 1, 1"]
|===
2+| Interruptor de clúster A 2+| Interruptor de clúster B 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11 al 34
 a| 
Requiere licencia
 a| 
11 al 34
 a| 
Requiere licencia



 a| 
35
 a| 
ISL 100GbE al puerto 35 del switch B
 a| 
35
 a| 
ISL 100GbE al puerto 35 del switch A



 a| 
36
 a| 
ISL 100GbE al puerto 36 del switch B
 a| 
36
 a| 
ISL 100GbE al puerto 36 del switch A

|===
Ver el https://hwu.netapp.com/Switch/Index["Hardware Universe"] Para obtener más información sobre los puertos del switch.

.¿Qué sigue?
Una vez que hayas completado tus hojas de trabajo de cableado, podrás link:install-switch-9336c-cluster.html["instalar el interruptor"].
