---
permalink: switch-bes-53248/components-bes53248.html 
sidebar: sidebar 
keywords: cluster-mode,supported versions,switches supported,cluster network,efos 
summary: Para la instalación y el mantenimiento del interruptor BES-53248, asegúrese de revisar la lista de componentes y números de pieza. 
---
= Componentes y números de pieza para los interruptores de clúster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del interruptor BES-53248, asegúrese de revisar la lista de componentes y números de pieza.

La siguiente tabla enumera el número de pieza, la descripción y las versiones mínimas de EFOS y ONTAP para los componentes del conmutador de clúster BES-53248, incluidos los detalles del kit de riel de montaje en rack.


NOTE: Se requiere una versión mínima de EFOS *3.10.0.3* para los números de pieza *X190005-B* y *X190005R-B*.

[cols="20,40,20,20"]
|===
| Número de pieza | Descripción | Versión mínima de EFOS | Versión mínima de ONTAP 


 a| 
X190005-B
 a| 
BES-53248-B/IX8, CLSW, 16PT10/25GB, PTSX (PTSX = Escape del lado de babor)
 a| 
3.10.0.3
 a| 
9,8



 a| 
X190005R-B
 a| 
BES-53248-B/IX8, CLSW, 16PT10/25GB, PSIN (PSIN = entrada del lado de babor)
 a| 
3.10.0.3
 a| 
9,8



 a| 
X190005
 a| 
BES-53248, CLSW, 16Pt10/25GB, PTSX, BRDCM SUPP
 a| 
3.4.4.6
 a| 
9.5P8



 a| 
X190005R
 a| 
BES-53248, CLSW, 16Pt10/25GB, PSIN, BRDCM SUPP
 a| 
3.4.4.6
 a| 
9.5P8



 a| 
X-RAIL-4POST-190005
 a| 
Kit de rieles para montaje en rack Ozeki de 4 postes y 19 pulgadas
 a| 
N/A
 a| 
N/A

|===

IMPORTANT: Tenga en cuenta la siguiente información con respecto a los tipos de máquinas:

[cols="50,50"]
|===
| Tipo de máquina | Versión mínima de EFOS 


 a| 
BES-53248A1
| 3.4.4.6 


 a| 
BES-53248A2
| 3.10.0.3 


 a| 
BES-53248A3
| 3.10.0.3 
|===
Puedes determinar el tipo específico de tu máquina utilizando el siguiente comando: `show version`

.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show version*

Switch: cs1

System Description............................. EFOS, 3.10.0.3, Linux 5.4.2-b4581018, 2016.05.00.07
Machine Type................................... *_BES-53248A3_*
Machine Model.................................. BES-53248
Serial Number.................................. QTWCU225xxxxx
Part Number.................................... 1IX8BZxxxxx
Maintenance Level.............................. a3a
Manufacturer................................... QTMC
Burned In MAC Address.......................... C0:18:50:F4:3x:xx
Software Version............................... 3.10.0.3
Operating System............................... Linux 5.4.2-b4581018
Network Processing Device...................... BCM56873_A0
.
.
.
----
====
.¿Qué sigue?
Una vez que haya confirmado sus componentes y números de pieza, puede revisar el link:required-documentation-bes53248.html["documentación requerida"].
