---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 'Siga estos pasos para instalar el software Ethernet Fabric OS (EFOS) en el conmutador de clúster BES-53248.' 
---
= Instale el software EFOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos pasos para instalar el software Ethernet Fabric OS (EFOS) en el conmutador de clúster BES-53248.

El software EFOS incluye un conjunto de funciones y protocolos de red avanzados para el desarrollo de sistemas de infraestructura Ethernet e IP.  Esta arquitectura de software es adecuada para cualquier dispositivo de organización de red que utilice aplicaciones que requieran una inspección o separación exhaustiva de paquetes.



== Prepárese para la instalación

.Antes de empezar
* Este procedimiento solo es adecuado para instalaciones nuevas.
* Descargue el software Broadcom EFOS correspondiente a sus conmutadores de clúster desde https://www.broadcom.com/support/bes-switch["Compatibilidad con conmutadores Ethernet Broadcom"^] sitio.
* Asegurar ellink:configure-install-initial.html["El conmutador de clúster BES-53248 está configurado"] .




== Instala el software

Utilice uno de los siguientes métodos para instalar el software EFOS:

* <<Método 1: Instalar EFOS>>. Úselo en la mayoría de los casos.
* <<Método 2: Instalar EFOS en modo ONIE>>. Utilizar si una versión de EFOS cumple con la norma FIPS y la otra no.




=== Método 1: Instalar EFOS

Siga los siguientes pasos para instalar el software EFOS.

.Pasos
. Inicie sesión en el puerto de consola serie del switch o conéctese mediante SSH.
. Utilice el `ping` comando para verificar la conectividad con el servidor que aloja EFOS, las licencias y el archivo RCF.
+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo verifica que el switch está conectado al servidor en la dirección IP 172.19.2.1:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Descarga el archivo de imagen al switch.
+
Consulte la siguiente tabla para obtener información sobre los protocolos de copia compatibles:

+
|===


| *Protocolo* | *Requisito previo* 


 a| 
Protocolo trivial de transferencia de archivos (TFTP)
 a| 
Ninguno



 a| 
Protocolo de transferencia de archivos SSH (SFTP)
 a| 
Su paquete de software debe admitir la administración segura.



 a| 
FTP
 a| 
Se requiere contraseña



 a| 
XMODEM
 a| 
Ninguno



 a| 
YMODEM
 a| 
Ninguno



 a| 
ZMODEM
 a| 
Ninguno



 a| 
Protocolo de copia segura (SCP)
 a| 
Su paquete de software debe admitir la administración segura.



 a| 
HTTP
 a| 
Las transferencias de archivos mediante CLI son compatibles con determinadas plataformas cuando está disponible una utilidad WGET nativa.



 a| 
HTTPS
 a| 
Las transferencias de archivos mediante CLI son compatibles con determinadas plataformas cuando está disponible una utilidad WGET nativa.

|===
+
Copiar el archivo de imagen a la imagen activa significa que, al reiniciar, esa imagen establecerá la versión de EFOS en ejecución.  La imagen anterior permanece disponible como copia de seguridad.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Muestra las imágenes de arranque para la configuración activa y de respaldo:
+
`show bootvar`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. Reinicia el switch:
+
`reload`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. Vuelva a iniciar sesión y verifique la nueva versión del software EFOS:
+
`show version`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Finalice la instalación. Siga estos cuatro pasos para reconfigurar el conmutador:
+
.. link:configure-licenses.html["Instalar licencias"]
.. link:configure-install-rcf.html["Instala el archivo RCF"]
.. link:configure-ssh.html["Habilitar SSH"]
.. link:../switch-cshm/config-overview.html["Configurar la monitorización del estado del switch"]


. Repita los pasos del 1 al 7 en el interruptor asociado.




=== Método 2: Instalar EFOS en modo ONIE

Puede realizar los siguientes pasos si una versión de EFOS cumple con FIPS y la otra no cumple con FIPS.  Estos pasos se pueden utilizar para instalar la imagen EFOS 3.7.xx compatible o no compatible con FIPS desde ONIE si el switch no arranca.

.Pasos
. Conéctese a una consola que esté conectada al puerto serie del conmutador.
. Inicie el switch en modo de instalación ONIE.
+
Durante el arranque, seleccione ONIE cuando vea la indicación.

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
Después de seleccionar *ONIE*, el interruptor se carga y le presenta varias opciones.  Seleccione *Instalar sistema operativo*.

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
El switch arranca en modo de instalación ONIE.

. Detenga la detección ONIE y configure la interfaz Ethernet.
+
Cuando aparezca el siguiente mensaje, pulse *Enter* para abrir la consola ONIE:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: La detección ONIE continúa y se imprimen mensajes en la consola.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configure la interfaz Ethernet del puerto de administración del switch y agregue la ruta mediante `ifconfig eth0 <ipAddress> netmask <netmask> up` y `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Verifique que el servidor que aloja el archivo de instalación de ONIE sea accesible:
+
`ping`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Instala el nuevo software del switch:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
El software se instala y luego reinicia el switch.  Deje que el switch se reinicie normalmente en la nueva versión de EFOS.

. Inicie sesión y verifique que el nuevo software del switch esté instalado:
+
`show bootvar`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. Finalice la instalación. El switch se reinicia sin ninguna configuración aplicada y se restablece a los valores predeterminados de fábrica. Siga estos cinco pasos para reconfigurar el conmutador:
+
.. link:configure-install-initial.html["Configurar interruptor"]
.. link:configure-licenses.html["Instalar licencias"]
.. link:configure-install-rcf.html["Instala el archivo RCF"]
.. link:configure-ssh.html["Habilitar SSH"]
.. link:../switch-cshm/config-overview.html["Configurar la monitorización del estado del switch"]


. Repita los pasos del 1 al 8 en el interruptor asociado.


.¿Qué sigue?
Una vez instalado el software EFOS, podrá link:configure-licenses.html["Instala tus licencias"].
