---
permalink: switch-bes-53248/configure-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: La función de recogida de registros de control de estado del switch de clúster se utiliza para recoger archivos de registro relacionados con el switch en ONTAP. Debe asegurarse de que ha configurado su entorno mediante la CLI del switch de clúster BES-53248, tal y como se describe a continuación. 
---
= Habilite la función de recogida de registros
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar la función de recogida de registros, que se utiliza para recoger archivos de registro relacionados con el switch en ONTAP.

Asegúrese de que ha configurado su entorno mediante la CLI del switch de clúster BES-53248.



== Para ONTAP 9.8 y posterior

Habilite la función de recogida de registros mediante los comandos:

`system switch ethernet log setup-password` y.. `system switch ethernet log enable-collection`

.Pasos
. Introduzca: `system switch ethernet log setup-password`
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
. Introduzca: `system switch ethernet log enable-collection`
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
====




== Para versiones de parches ONTAP 9.5P15, 9.6P11, 9.7P8 y posteriores

Habilite la función de recogida de registros mediante los comandos:

`system cluster-switch log setup-password` y.. `system cluster-switch log enable-collection`

.Pasos
. Introduzca: `system cluster-switch log setup-password`
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
. Introduzca: `system cluster-switch log enable-collection`
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.
----
====



NOTE: El comando log Collect no está disponible en este momento. Consulte link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1225042["Error 1225042"^] para obtener más detalles.


CAUTION: Si alguno de estos comandos devuelve un error, póngase en contacto con el soporte de NetApp.

.El futuro
Si va a actualizar el switch, vaya a. link:replace-verify.html["Verificar la configuración de actualización"].
