---
permalink: switch-bes-53248/configure-install-initial.html 
sidebar: sidebar 
keywords: switches initial setup,initial setup,efos download 
summary: Puede utilizar este procedimiento para realizar la instalación inicial del conmutador de clúster BES-53248. 
---
= Configurar el conmutador de clúster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos pasos para realizar una configuración inicial del conmutador de clúster BES-53248.

.Antes de empezar
* El hardware se instala según se describe enlink:install-hardware-bes53248.html["Instala el hardware"] .
* Has revisado lo siguiente:
+
** link:configure-reqs-bes53248.html["Requisitos de configuración"]
** link:components-bes53248.html["Componentes y números de pieza"]
** link:required-documentation-bes53248.html["Requisitos de documentación"]




.Acerca de los ejemplos
Los ejemplos de los procedimientos de configuración utilizan la siguiente nomenclatura de interruptores y nodos:

* Los nombres de los switches NetApp son `cs1` y `cs2` .  La actualización comienza en el segundo switch, _cs2._
* Los nombres de los clústeres LIF son `node1_clus1` y `node1_clus2` para el nodo 1, y `node2_clus1` y `node2_clus2` para el nodo 2.
* El nombre del espacio IP es Cluster.
* El `cluster1::>` El indicador muestra el nombre del clúster.
* Los puertos del clúster en cada nodo se llaman `e0a` y `e0b` .  Ver el https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^] para los puertos de clúster reales compatibles con su plataforma.
* Los enlaces entre conmutadores (ISL) compatibles con los conmutadores NetApp son los puertos 0/55 y 0/56.
* Las conexiones de nodo compatibles con los switches NetApp son los puertos 0/1 a 0/16 con licencia predeterminada.
* Los ejemplos utilizan dos nodos, pero puede haber hasta 24 nodos en un clúster.


.Pasos
. Conecte el puerto serie a un host o a otro puerto serie.
. Conecte el puerto de administración (el puerto RJ-45 con forma de llave inglesa en el lado izquierdo del switch) a la misma red donde se encuentra su servidor TFTP.
. En la consola, configure los ajustes de serie del host:
+
** 115200 baudios
** 8 bits de datos
** 1 bit de parada
** paridad: ninguna
** Control de flujo: ninguno


. Inicia sesión en el switch como `admin` y pulse *Enter* cuando se le solicite una contraseña.  El nombre del interruptor predeterminado es *routing*.  Cuando se le solicite, ingrese `enable` .  Esto le da acceso al modo EXEC privilegiado para la configuración del switch.
+
[listing, subs="+quotes"]
----
User: *admin*
Password:
(Routing)> *enable*
Password:
(Routing)#
----
. Cambie el nombre del interruptor a *cs2*.
+
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
(cs2)#
----
. Para configurar una dirección IPv4 o IPv6 estática de administración para el puerto de servicio del switch:


[role="tabbed-block"]
====
.IPv4
--
El puerto de servicio está configurado para usar DHCP de forma predeterminada.  La dirección IP, la máscara de subred y la dirección de puerta de enlace predeterminada se asignan automáticamente.

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip <ip-address> <netmask> <gateway>*
----
--
.IPv6
--
El puerto de servicio está configurado para usar DHCP de forma predeterminada.  La dirección IP, la máscara de subred y la dirección de puerta de enlace predeterminada se asignan automáticamente.

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ipv6 <address>*
(cs2)# *serviceport ipv6 <gateway>*
----
--
====
. [[step7]]Verifique los resultados utilizando el comando:
+
`show serviceport`

+
[listing, subs="+quotes"]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
. Configurar el dominio y el servidor de nombres:
+
[source, cli]
----
ip domain name <domain_name>
ip name server <server_name>
----
+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ip domain name company.com*
(cs2)(Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2)(Config)# *exit*
(cs2)#
----
. Configure el servidor NTP.


[role="tabbed-block"]
====
.EFOS 3.10.0.3 y versiones posteriores
--
Configurar la zona horaria y la sincronización horaria (NTP):

[source, cli]
----
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 y versiones anteriores
--
Configurar la zona horaria y la sincronización horaria (SNTP):

[source, cli]
----
sntp client mode <client_mode>
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *sntp client mode unicast*
(cs2)(Config)# *sntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step10]]Configure la hora manualmente si no configuró un servidor NTP en el paso anterior.


[role="tabbed-block"]
====
.EFOS 3.10.0.3 y versiones posteriores
--
Configure la hora manualmente.

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 y versiones anteriores
--
Configure la hora manualmente.

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *no sntp client mode*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step11]]Guarde la configuración en ejecución en la configuración de inicio:
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----


.¿Que sigue?
Una vez que hayas configurado tus interruptores, podrás link:configure-efos-software.html["Instale el software EFOS"].
