---
permalink: switch-bes-53248/configure-reqs-bes53248.html 
sidebar: sidebar 
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches 
summary: Puede utilizar la tabla de asignación de puertos del conmutador de clúster BES-53248 como guía para configurar su clúster. 
---
= Requisitos de configuración para los conmutadores de clúster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del switch BES-53248, asegúrese de revisar los requisitos de soporte y configuración de EFOS y ONTAP .



== Soporte para EFOS y ONTAP

Consulta el link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] y el link:https://mysupport.netapp.com/site/info/broadcom-cluster-switch["Matriz de compatibilidad de conmutadores Broadcom"^] para información sobre la compatibilidad de EFOS y ONTAP con los switches BES-53248. El soporte de EFOS y ONTAP puede variar según el tipo de máquina específico del switch BES-53248. Para detalles de todos los tipos de máquina del switch BES-52348, consulta link:components-bes53248.html["Componentes y números de pieza para los interruptores de clúster BES-53248"]. Consulta link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"]^ para más información sobre los requisitos de instalación del switch.



== Requisitos de configuración

Para configurar un clúster, necesita el número y tipo adecuados de cables y conectores de cable para los conmutadores del clúster.  Dependiendo del tipo de conmutador de clúster que esté configurando inicialmente, deberá conectarse al puerto de consola del conmutador con el cable de consola incluido.



=== Asignaciones de puertos de conmutador de clúster

Puede utilizar la tabla de asignaciones de puertos del conmutador de clúster BES-53248 compatible con Broadcom como guía para configurar su clúster.

[cols="1,2"]
|===
| Puertos de conmutación | Uso de puertos 


 a| 
01-16
 a| 
Nodos de puerto de clúster 10/25GbE, configuración base



 a| 
17-48
 a| 
Nodos de puerto de clúster 10/25GbE, con licencias



 a| 
49-54
 a| 
Nodos de puerto de clúster 40/100GbE, con licencias, añadidos de derecha a izquierda



 a| 
55-56
 a| 
Puertos ISL (Inter-Switch Link) de clúster 100GbE, configuración base

|===
Consulta el link:https://hwu.netapp.com/Switch/Index["Hardware Universe"] para más información sobre los puertos del switch. Consulta link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"^] para más información sobre los requisitos de instalación del switch.



=== restricción de velocidad del grupo de puertos

* En los conmutadores de clúster BES-53248, los 48 puertos 10/25GbE (SFP28/SFP+) se combinan en 12 grupos de 4 puertos de la siguiente manera: Puertos 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44 y 45-48.
* La velocidad del puerto SFP28/SFP+ debe ser la misma (10GbE o 25GbE) en todos los puertos del grupo de 4 puertos.




=== Requisitos adicionales

* Si compras licencias adicionales, consulta link:configure-licenses.html["Activar puertos con licencias nuevas"] para saber cómo activarlas.
* Si SSH está activo, deberá volver a habilitarlo manualmente después de ejecutar el comando. `erase startup-config` y reiniciar el conmutador.


.¿Qué sigue?
Después de revisar los requisitos de configuración, puede confirmar su link:components-bes53248.html["componentes y números de pieza"].
