---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 'Siga estos pasos para instalar el software Ethernet Fabric OS (EFOS) en el conmutador de clúster BES-53248.' 
---
= Instale el software del EFOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos pasos para instalar el software Ethernet Fabric OS (EFOS) en el conmutador de clúster BES-53248.

El software EFOS incluye un conjunto de funciones y protocolos de red avanzados para desarrollar sistemas Ethernet e infraestructura IP. Esta arquitectura de software es adecuada para cualquier dispositivo de organización de red que utilice aplicaciones que requieran una inspección o separación exhaustiva de paquetes.



== Preparación de la instalación

.Antes de empezar
* Este procedimiento solo es adecuado para instalaciones nuevas.
* Descargue el software Broadcom EFOS aplicable para los switches de su clúster de la https://www.broadcom.com/support/bes-switch["Compatibilidad con switches Ethernet Broadcom"^] sitio.
* Asegúrese de que el link:configure-install-initial.html["El conmutador de clúster BES-53248 está configurado"].




== Instale el software

Utilice uno de los siguientes métodos para instalar el software EFOS:

* <<Método 1: Instalar EFOS>>. Utilizado en la mayoría de los casos.
* <<Método 2: Instale EFOS en modo ONIE>>. Se utiliza si una versión de EFOS es compatible con FIPS y la otra versión de EFOS no es compatible con FIPS.




=== Método 1: Instalar EFOS

Realice los siguientes pasos para instalar el software EFOS.

.Pasos
. Inicie sesión en el puerto de la consola de serie del switch o conéctese mediante SSH.
. Utilice la `ping` Comando para verificar la conectividad con el servidor que aloja EFOS, licencias y el archivo RCF.
+
.Muestra el ejemplo
[%collapsible]
====
En este ejemplo se comprueba que el conmutador está conectado al servidor en la dirección IP 172.19.2.1:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Descargue el archivo de imagen en el switch.
+
Consulte la siguiente tabla para obtener información sobre los protocolos de copia admitidos:

+
|===


| *Protocolo* | *Requisitos* 


 a| 
Protocolo trivial de transferencia de archivos (TFTP)
 a| 
Ninguno



 a| 
Protocolo de transferencia de archivos SSH (SFTP)
 a| 
Su paquete de software debe admitir una gestión segura



 a| 
FTP
 a| 
Se requiere contraseña



 a| 
XMÓDEM
 a| 
Ninguno



 a| 
YMODEM
 a| 
Ninguno



 a| 
ZMODEM
 a| 
Ninguno



 a| 
Protocolo de copia segura (SCP)
 a| 
Su paquete de software debe admitir una gestión segura



 a| 
HTTP
 a| 
Las transferencias de archivos basadas en CLI se admiten en plataformas seleccionadas cuando hay disponible una utilidad WGET nativa



 a| 
HTTPS
 a| 
Las transferencias de archivos basadas en CLI se admiten en plataformas seleccionadas cuando hay disponible una utilidad WGET nativa

|===
+
Copiar el archivo de imagen en la imagen activa significa que al reiniciar, esa imagen establece la versión EFOS en ejecución. La imagen anterior sigue estando disponible como copia de seguridad.

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Mostrar las imágenes de arranque para la configuración activa y de copia de seguridad:
+
`show bootvar`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. Reinicie el switch:
+
`reload`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. Vuelva a iniciar sesión y compruebe la nueva versión del software EFOS:
+
`show version`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Complete la instalación.
Siga estos cinco pasos para volver a configurar el switch:
+
.. link:configure-licenses.html["Instale licencias"]
.. link:configure-install-rcf.html["Instale el archivo RCF"]
.. link:configure-ssh.html["Habilite SSH"]
.. link:CSHM_log_collection.html["Habilite la recogida de registros"]
.. link:CSHM_snmpv3.html["Configure SNMPv3 para la supervisión"]


. Repita los pasos 1 a 7 en el conmutador asociado.




=== Método 2: Instale EFOS en modo ONIE

Puede realizar los siguientes pasos si una versión de EFOS es compatible con FIPS y la otra versión de EFOS no es compatible con FIPS. Estos pasos se pueden utilizar para instalar la imagen EFOS 3.7.x.x no compatible con FIPS o FIPS desde ONIE si el conmutador no arranca.

.Pasos
. Conéctese a una consola que esté conectada al puerto serie del switch.
. Arranque el interruptor en el modo DE instalación ONIE.
+
Durante el arranque, seleccione ONIE cuando vea la solicitud.

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
Después de seleccionar *ONIE*, el interruptor se carga y le presenta varias opciones. Seleccione *instalar OS*.

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
El interruptor se inicia EN el modo DE instalación ONIE.

. Detenga EL descubrimiento DE ONIE y configure la interfaz Ethernet.
+
Cuando aparezca el siguiente mensaje, pulse *Intro* para invocar LA consola ONIE:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: El descubrimiento de ONIE continúa y los mensajes se imprimen en la consola.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configure la interfaz Ethernet del puerto de gestión del switch y agregue la ruta mediante `ifconfig eth0 <ipAddress> netmask <netmask> up` y.. `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Compruebe que se puede acceder al servidor que aloja el archivo DE instalación ONIE:
+
`ping`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Instale el nuevo software del conmutador:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
El software se instala y, a continuación, reinicia el conmutador. Deje que el interruptor se reinicie normalmente en la nueva versión de EFOS.

. Inicie sesión y compruebe que el nuevo software del conmutador está instalado:
+
`show bootvar`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. Complete la instalación.
El conmutador se reinicia sin aplicar ninguna configuración y se restablece a los valores predeterminados de fábrica. Siga estos seis pasos para volver a configurar el switch:
+
.. link:configure-install-initial.html["Configurar el switch"]
.. link:configure-licenses.html["Instale licencias"]
.. link:configure-install-rcf.html["Instale el archivo RCF"]
.. link:configure-ssh.html["Habilite SSH"]
.. link:CSHM_log_collection.html["Habilite la recogida de registros"]
.. link:CSHM_snmpv3.html["Configure SNMPv3 para la supervisión"]


. Repita los pasos 1 a 8 en el conmutador asociado.


.¿Qué sigue?
Una vez instalado el software EFOS, podrá link:configure-licenses.html["Instala tus licencias"].
