---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: El modelo base de switch de clúster BES-53248 tiene licencia para 16 puertos de 10 GbE o 25 GbE y dos puertos de 100 GbE. Es posible añadir puertos nuevos si se adquieren más licencias. 
---
= Instale licencias para switches de clúster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El modelo base de switch de clúster BES-53248 tiene licencia para 16 puertos de 10 GbE o 25 GbE y dos puertos de 100 GbE. Puede añadir puertos nuevos si compra más licencias.


CAUTION: Para EFOS 3,12 y posterior, siga los pasos de instalación en link:efos-install-rcf-license-file.html["Instale el archivo de configuración de referencia (RCF) y el archivo de licencia"].



== Revisar las licencias disponibles

Las siguientes licencias están disponibles para su uso en el conmutador de clúster BES-53248:

[cols="1,2,3"]
|===
| Tipo de licencia | Detalles de licencia | Versión de firmware admitida 


 a| 
SW-BES-53248A2-8P-2P
 a| 
Clave de licencia Broadcom 8PT-10G25G + 2PT-40G100G, X190005/R
 a| 
EFOS 3.4.4.6 y posterior



 a| 
SW-BES-53248A2-8P-1025G
 a| 
Clave de licencia 10G25G de 8 puertos Broadcom, X190005/R
 a| 
EFOS 3.4.4.6 y posterior



 a| 
SW-BES53248A2-6P-40-100G
 a| 
Clave de licencia de Broadcom 6 puertos 40G100G, X190005/R
 a| 
EFOS 3.4.4.6 y posterior

|===


== Licencias heredadas

En la siguiente tabla se enumeran las licencias heredadas que estaban disponibles para su uso en el conmutador de clúster BES-53248:

[cols="1,2,3"]
|===
| Tipo de licencia | Detalles de licencia | Versión de firmware admitida 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Clave de licencia Broadcom 8P 10-25,2P40-100, X190005/R.
 a| 
EFOS 3.4.3.3 y posterior



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Clave de licencia Broadcom 16P 10-25,4P40-100, X190005/R.
 a| 
EFOS 3.4.3.3 y posterior



 a| 
SW-BES-53248A1-G1-24P-LIC
 a| 
Clave de licencia Broadcom 24P 10-25,6P40-100, X190005/R.
 a| 
EFOS 3.4.3.3 y posterior



 a| 
SW-BES54248-40-100G-LIC
 a| 
Clave de licencia Broadcom 6Port 40G100G, X190005/R.
 a| 
EFOS 3.4.4.6 y posterior



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
Clave de licencia Broadcom de 8 puertos 10G25G, X190005/R.
 a| 
EFOS 3.4.4.6 y posterior



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
Clave de licencia Broadcom 16Port 10G25G, X190005/R.
 a| 
EFOS 3.4.4.6 y posterior



 a| 
SW-BES53248-24P-1025G-LIC
 a| 
Clave de licencia Broadcom 24Port 10G25G, X190005/R.
 a| 
EFOS 3.4.4.6 y posterior

|===

NOTE: No se requiere una licencia para la configuración base.



== Instale los archivos de licencia

Siga estos pasos para instalar licencias para switches de clúster BES-53248.

.Pasos
. Conecte el switch de clúster a la red de gestión.
. Utilice la `ping` Comando para verificar la conectividad con el servidor que aloja EFOS, licencias y el archivo RCF.
+
.Muestra el ejemplo
[%collapsible]
====
En este ejemplo se comprueba que el conmutador está conectado al servidor en la dirección IP 172.19.2.1:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Compruebe el uso actual de la licencia en el conmutador cs2:
+
`show license`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. Instale el archivo de licencia.
+
Repita este paso para cargar más licencias y usar diferentes números de índice de claves.

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo, se usa SFTP para copiar un archivo de licencia en un índice de claves 1.

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. Mostrar toda la información de licencia actual y anotar el estado de la licencia antes de reiniciar el conmutador cs2:
+
`show license`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. Mostrar todos los puertos con licencia:
+
`show port all | exclude Detach`

+
Los puertos de los archivos de licencia adicionales no se muestran hasta que se haya reiniciado el conmutador.

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. Reinicie el switch:
+
`reload`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. Compruebe que la nueva licencia está activa y tenga en cuenta que se ha aplicado:
+
`show license`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. Compruebe que todos los puertos nuevos estén disponibles:
+
`show port all | exclude Detach`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: Al instalar licencias adicionales, debe configurar las nuevas interfaces manualmente. No vuelva a aplicar un RCF a un interruptor de producción en funcionamiento existente.



== Solucione problemas de instalación

Cuando se produzcan problemas al instalar una licencia, ejecute los siguientes comandos de depuración antes de ejecutar `copy` comando de nuevo.

Comandos de depuración que se utilizarán: `debug transfer` y.. `debug license`

.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
Cuando ejecute el `copy` con el `debug transfer` y.. `debug license` opciones habilitadas, se devuelve la salida del registro.

.Muestra el ejemplo
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
Compruebe lo siguiente en la salida de depuración:

* Compruebe que el número de serie coincide con: `Serial number QTFCU38290012 matched.`
* Compruebe que el modelo del interruptor coincide con: `Model BES-53248 matched.`
* Compruebe que el índice de licencia especificado no se haya utilizado anteriormente. Cuando ya se utiliza un índice de licencia, se devuelve el siguiente error: `License file /mnt/download//license.dat.1 already exists.`
* Una licencia de puerto no es una licencia de función. Por lo tanto, se espera la siguiente declaración: `Feature not found in license file with index = 1.`


Utilice la `copy` comando para realizar una copia de seguridad de licencias de puerto en el servidor:

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: Si necesita degradar el software del conmutador de la versión 3.4.4.6, se eliminarán las licencias. Este es el comportamiento esperado.

Debe instalar una licencia anterior adecuada antes de volver a una versión anterior del software.



== Activar puertos con licencia nueva

Para activar los puertos con licencia nueva, debe editar la última versión del RCF y anular el comentario de los detalles del puerto correspondientes.

La licencia predeterminada activa los puertos 0/1 a 0/16 y 0/55 a 0/56, mientras que los puertos recién licenciados estarán entre los puertos 0/17 a 0/54, dependiendo del tipo y el número de licencias disponibles. Por ejemplo, para activar la licencia SW-BES54248-40-100G-LIC, debe anular el comentario de la siguiente sección en el RCF:

.Muestra el ejemplo
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: Para los puertos de alta velocidad entre 0/49 y 0/54 inclusive, quite el comentario de cada puerto pero sólo descomente una línea *velocidad* en el RCF para cada uno de estos puertos, ya sea: *Velocidad 100G full-duplex* o *velocidad 40G full-duplex* como se muestra en el ejemplo. Para puertos de baja velocidad entre 0/17 y 0/48 incluidos, quite la Marca de comentario de toda la sección de 8 puertos cuando se haya activado una licencia apropiada.

.El futuro
Una vez instaladas las licencias, puedes link:configure-install-rcf.html["instalar el archivo de configuración de referencia (RCF)"] o link:upgrade-rcf.html["actualizar el RCF"].
