---
permalink: switch-bes-53248/configure-software-overview-bes53248.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch 
summary: Revise la descripción general del software. 
---
= Flujo de trabajo de instalación de software para conmutadores BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar y configurar el software para un conmutador de clúster BES-53248, siga estos pasos:

. link:configure-efos-software.html["Instale el software del EFOS"].
+
Descargue e instale el software Ethernet Fabric OS (EFOS) en el switch de clúster BES-53248.

. link:configure-licenses.html["Instale licencias para switches de clúster BES-53248"].
+
Opcionalmente, añada nuevos puertos comprando e instalando más licencias. El modelo de base de switches tiene licencia para 16 puertos de 10 GbE o 25 GbE y dos puertos de 100 GbE.

. link:configure-install-rcf.html["Instalación del archivo de configuración de referencia (RCF)"].
+
Instale o actualice el RCF en el conmutador de clúster BES-53248 y, a continuación, compruebe los puertos para obtener una licencia adicional después de aplicar el RCF.

. link:configure-ssh.html["Habilite SSH en switches de clúster BES-53248"].
+
Si utiliza el monitor de estado del switch Ethernet (CSHM) y las funciones de recopilación de registros, habilite SSH en los switches.

. link:reset-switch-bes-53248.html["Restablecer el interruptor a los valores predeterminados de fábrica"].
+
Borre la configuración del conmutador de clúster BES-53248.


