---
permalink: switch-bes-53248/configure-ssh.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, bes, enable ssh on bes-53248 cluster switches - bes-53248 switches 
summary: 'SSH es un requisito cuando se utilizan las funciones de recopilación de registros y Monitor de estado del conmutador de clúster \(CSHM\). Para habilitar SSH en los switches de clúster BES-53248, primero debe generar las claves SSH y, a continuación, habilitar SSH.' 
---
= Habilite SSH en switches de clúster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utiliza las funciones de recogida de registros y el monitor de estado del switch Ethernet (CSHM), debe generar las claves SSH y, a continuación, habilitar SSH en los switches del clúster.

.Pasos
. Compruebe que SSH está desactivado:
+
`show ip ssh`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Disabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Disabled
SCP server Administrative Mode: ............... Disabled
----
====
+
** Si SSH no está deshabilitado, deshabilítelo de la siguiente manera:
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *ip ssh server disable*
(switch)# *ip scp server disable*
----
====
+

WARNING: Asegúrese de deshabilitar SSH antes de modificar las claves, de lo contrario, se informará una advertencia en el conmutador.



. En el modo de configuración, genere las claves SSH:
+
`crypto key generate`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *config*

(switch) (Config)# *crypto key generate rsa*

Do you want to overwrite the existing RSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate dsa*

Do you want to overwrite the existing DSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate ecdsa 521*

Do you want to overwrite the existing ECDSA keys? (y/n): *y*
----
====
. En el modo de configuración, configure la autorización AAA para la recopilación de registros de ONTAP :
+
`aaa authorization commands "noCmdAuthList" none`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) (Config)# *aaa authorization commands "noCmdAuthList" none*
(switch) (Config)# *exit*
----
====
. Vuelva a habilitar SSH/SCP.
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *ip ssh server enable*
(switch)# *ip scp server enable*
(switch)# *ip ssh pubkey-auth*
----
====
. Guarde estos cambios en la configuración de inicio:
+
`write memory`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Cifrar las claves SSH (solo para *FIPS-mode*):
+

CAUTION: En el modo FIPS, se requiere que las claves se cifren con una frase de acceso por motivos de seguridad. En ausencia de una clave cifrada, la aplicación no se inicia. Las claves se crean y cifran mediante los siguientes comandos:

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) *configure*
(switch) (Config)# *crypto key encrypt write rsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *crypto key encrypt write dsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch)(Config)# *crypto key encrypt write ecdsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *end*
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Reinicie el switch:
+
`reload`

. Compruebe que SSH está habilitado:
+
`show ip ssh`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Enabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Enabled
SCP server Administrative Mode: ............... Enabled
----
====


.El futuro
link:../switch-cshm/config-overview.html["Configure la supervisión de estado del switch"].
