---
permalink: switch-bes-53248/configure-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: La función de recogida de registros de control de estado del switch de clúster se utiliza para recoger archivos de registro relacionados con el switch en ONTAP. Debe asegurarse de que ha configurado su entorno mediante la CLI del switch de clúster BES-53248, tal y como se describe a continuación. 
---
= Habilite la función de recogida de registros
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar la función de recopilación de registros para recoger archivos de registro relacionados con switches en ONTAP.


IMPORTANT: Para habilitar la función de recopilación de registros, debe ejecutar ONTAP versión 9.12.1 y posteriores, y EFOS 3.8.0.2 y posteriores.

Asegúrese de haber configurado su entorno utilizando el conmutador de clúster BES-53248 *CLI*.

.Pasos
. Habilite la función de recogida de registros del monitor de estado del switch de Ethernet para recoger archivos de registro relacionados con switches con los siguientes comandos:
+
`system switch ethernet log setup-password` y..

+
`system switch ethernet log enable-collection`

+
.. Introduzca: `system switch ethernet log setup-password`
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
.. Introduzca: `system switch ethernet log enable-collection`
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system  switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
====


. Inicie la función de recopilación de registros del switch:
+
`system switch ethernet log collect -device *`

+
Espere 10 minutos y compruebe que la recopilación del registro se ha realizado correctamente mediante el comando:

+
`system switch ethernet log show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> system switch ethernet log show
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------
1      cs1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete
2      cs2 (b8:ce:f6:19:1b:96)      4/29/2022 03:07:42   complete
----

CAUTION: Si alguno de estos comandos devuelve un error, póngase en contacto con el soporte de NetApp.

.El futuro
Si va a actualizar el switch, vaya a. link:replace-verify.html["Verificar la configuración de actualización"].

====

