---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: El modelo base del conmutador de clúster BES-53248 tiene licencia para 16 puertos 10GbE o 25GbE y dos puertos 100GbE.  Se pueden añadir nuevos puertos adquiriendo más licencias. 
---
= Instale las licencias para los conmutadores de clúster BES-53248.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El modelo base del conmutador de clúster BES-53248 tiene licencia para 16 puertos 10GbE o 25GbE y dos puertos 100GbE.  Puedes añadir nuevos puertos comprando más licencias.


CAUTION: Para EFOS 3.12 y versiones posteriores, siga los pasos de instalación enlink:efos-install-rcf-license-file.html["Instale el archivo de configuración de referencia (RCF) y el archivo de licencia."] .



== Revisar las licencias disponibles

Las siguientes licencias están disponibles para su uso en el conmutador de clúster BES-53248:

[cols="1,2,3"]
|===
| Tipo de licencia | Detalles de la licencia | Versión de firmware compatible 


 a| 
SW-BES-53248A2-8P-2P
 a| 
Clave de licencia Broadcom 8PT-10G25G + 2PT-40G100G, X190005/R
 a| 
EFOS 3.4.4.6 y versiones posteriores



 a| 
SW-BES-53248A2-8P-1025G
 a| 
Clave de licencia Broadcom de 8 puertos 10G25G, X190005/R
 a| 
EFOS 3.4.4.6 y versiones posteriores



 a| 
SW-BES53248A2-6P-40-100G
 a| 
Clave de licencia Broadcom de 6 puertos 40G100G, X190005/R
 a| 
EFOS 3.4.4.6 y versiones posteriores

|===


== Licencias heredadas

La siguiente tabla enumera las licencias heredadas que estaban disponibles para su uso en el conmutador de clúster BES-53248:

[cols="1,2,3"]
|===
| Tipo de licencia | Detalles de la licencia | Versión de firmware compatible 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Clave de licencia Broadcom 8P 10-25,2P40-100, X190005/R
 a| 
EFOS 3.4.3.3 y posteriores



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Clave de licencia Broadcom 16P 10-25,4P40-100, X190005/R
 a| 
EFOS 3.4.3.3 y posteriores



 a| 
SW-BES-53248A1-G1-24P-LIC
 a| 
Clave de licencia Broadcom 24P 10-25,6P40-100, X190005/R
 a| 
EFOS 3.4.3.3 y posteriores



 a| 
SW-BES54248-40-100G-LIC
 a| 
Clave de licencia Broadcom 6Port 40G100G, X190005/R
 a| 
EFOS 3.4.4.6 y versiones posteriores



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
Clave de licencia Broadcom 8Port 10G25G, X190005/R
 a| 
EFOS 3.4.4.6 y versiones posteriores



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
Clave de licencia Broadcom de 16 puertos 10G25G, X190005/R
 a| 
EFOS 3.4.4.6 y versiones posteriores



 a| 
SW-BES53248-24P-1025G-LIC
 a| 
Clave de licencia Broadcom de 24 puertos 10G/25G, X190005/R
 a| 
EFOS 3.4.4.6 y versiones posteriores

|===

NOTE: No se requiere licencia para la configuración básica.



== Instalar archivos de licencia

Siga estos pasos para instalar las licencias para los conmutadores de clúster BES-53248.

.Pasos
. Conecte el conmutador del clúster a la red de administración.
. Utilice el `ping` comando para verificar la conectividad con el servidor que aloja EFOS, las licencias y el archivo RCF.
+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo verifica que el switch está conectado al servidor en la dirección IP 172.19.2.1:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Compruebe el uso actual de la licencia en el switch cs2:
+
`show license`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. Instale el archivo de licencia.
+
Repita este paso para cargar más licencias y utilizar diferentes números de índice de clave.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo utiliza SFTP para copiar un archivo de licencia a un índice de clave 1.

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. Muestra toda la información de licencia actual y anota el estado de la licencia antes de reiniciar el switch cs2:
+
`show license`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. Mostrar todos los puertos con licencia:
+
`show port all | exclude Detach`

+
Los puertos de los archivos de licencia adicionales no se muestran hasta que se reinicia el switch.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. Reinicia el switch:
+
`reload`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. Compruebe que la nueva licencia esté activa y observe que se ha aplicado:
+
`show license`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. Compruebe que todos los puertos nuevos estén disponibles:
+
`show port all | exclude Detach`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: Al instalar licencias adicionales, deberá configurar manualmente las nuevas interfaces.  No vuelva a aplicar un RCF a un interruptor de producción que ya esté en funcionamiento.



== Solucionar problemas de instalación

Si surgen problemas al instalar una licencia, ejecute los siguientes comandos de depuración antes de ejecutar el programa. `copy` Orden de nuevo.

Comandos de depuración a utilizar: `debug transfer` y `debug license`

.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
Cuando ejecutas el `copy` comando con el `debug transfer` y `debug license` Si se habilitan las opciones, se devuelve el registro de salida.

.Mostrar ejemplo
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
Compruebe lo siguiente en la salida de depuración:

* Compruebe que el número de serie coincide: `Serial number QTFCU38290012 matched.`
* Compruebe que el modelo del interruptor coincida: `Model BES-53248 matched.`
* Compruebe que el índice de licencia especificado no se haya utilizado previamente.  Cuando ya se está utilizando un índice de licencia, se devuelve el siguiente error: `License file /mnt/download//license.dat.1 already exists.`
* Una licencia de puerto no es una licencia de funcionalidad.  Por lo tanto, se espera la siguiente declaración: `Feature not found in license file with index = 1.`


Utilice el `copy` comando para realizar una copia de seguridad de las licencias de puerto en el servidor:

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: Si necesita degradar el software del switch desde la versión 3.4.4.6, las licencias se eliminarán.  Este es el comportamiento esperado.

Debe instalar una licencia anterior apropiada antes de volver a una versión anterior del software.



== Activar los puertos recién licenciados

Para activar los puertos recién licenciados, debe editar la última versión del RCF y descomentar los detalles del puerto correspondiente.

La licencia predeterminada activa los puertos 0/1 a 0/16 y 0/55 a 0/56, mientras que los puertos recién licenciados estarán entre los puertos 0/17 y 0/54 dependiendo del tipo y la cantidad de licencias disponibles.  Por ejemplo, para activar la licencia SW-BES54248-40-100G-LIC, debe descomentar la siguiente sección en el RCF:

.Mostrar ejemplo
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: Para los puertos de alta velocidad entre 0/49 y 0/54 inclusive, descomente cada puerto, pero solo descomente una línea *speed* en el RCF para cada uno de estos puertos, ya sea: *speed 100G full-duplex* o *speed 40G full-duplex* como se muestra en el ejemplo.  Para puertos de baja velocidad entre 0/17 y 0/48 inclusive, descomente toda la sección de 8 puertos cuando se haya activado una licencia apropiada.

.¿Que sigue?
Una vez instaladas las licencias, puedes link:configure-install-rcf.html["instalar el archivo de configuración de referencia (RCF)"] o link:upgrade-rcf.html["actualizar el RCF"].
