---
permalink: switch-bes-53248/index.html 
sidebar: sidebar 
keywords: broadcom, support, bes, cluster, switch, broadcam-supported bes-53248 cluster switches 
summary: Para la instalación y mantenimiento del switch BES-53248, asegúrese de revisar la compatibilidad con el SO, los números de pieza, los requisitos de configuración y los requisitos de documentación. 
---
= Descripción general y requisitos: Conmutadores BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y mantenimiento del switch BES-53248, asegúrese de revisar la compatibilidad con el SO, los números de pieza, los requisitos de configuración y los requisitos de documentación.



== Compatibilidad con el sistema operativo (SO)

El conmutador BES-53248 admite lo siguiente:

* *EFOS firmware 3.4.4.6 y posterior*. El switch BES-53248 se ejecuta en un sistema operativo Broadcom integrado conocido como Ethernet Fabric OS (EFOS). La compatibilidad con puertos de clúster de 40/100 GbE comienza con el firmware EFOS versión 3.4.4.6 y posteriores.
* *ONTAP 9.5P8 y posterior*. Los switches de clúster BES-53248 compatibles con Broadcom están diseñados para funcionar en clústeres con diferentes tamaños de dos a 24 nodos en ONTAP 9.5P8 y versiones posteriores.




== Cambiar números de pieza de componente

En la siguiente tabla se enumeran el número de pieza y la descripción de los componentes del switch de clúster BES-53248, incluido el kit de raíl para montaje en rack, los ventiladores y las fuentes de alimentación.

[cols="1,2"]
|===
| Número de pieza | Descripción 


 a| 
X190005
 a| 
BES-53248, CLSW, 16Pt10/25GB, PTSX, SOPORTE de BRDCM (PTSX = escape lateral del puerto)



 a| 
X190005R
 a| 
BES-53248, CLSW, 16Pt10/25GB, PSIN, SOPORTE de BRDCM (PSIN = entrada lateral del puerto)



 a| 
X-RAIL-4POST-190005
 a| 
Kit de rieles para montaje en rack Ozeki 4 post 19"



 a| 
X-FAN-190005-R.
 a| 
Ventilador, toma lateral de la lumbrera X190005



 a| 
X-FAN-190005-F
 a| 
Ventilador, escape lateral de la lumbrera X190005



 a| 
X-PSU-190005-R
 a| 
Fuente de alimentación, toma lateral de la lumbrera X190005

Flujo de aire de admisión del lado del puerto (aire de retroceso): El aire frío entra en el chasis a través del extremo del puerto del pasillo frío y sale por los módulos de ventilador y fuente de alimentación del pasillo caliente.



 a| 
X-PSU-190005-F
 a| 
Fuente de alimentación, escape lateral de la lumbrera X190005

Flujo de aire de escape del lado del puerto (aire estándar): El aire frío entra en el chasis a través del ventilador y los módulos de alimentación del pasillo frío y sale por el extremo del puerto del chasis en el pasillo caliente. El color azul indica el flujo de aire de escape del puerto. Esta es la opción más común.

|===


== Requisitos de configuración

Para configurar el clúster, necesita el número y el tipo de cables y conectores de cables adecuados para los switches de clúster. Según el tipo de switch de clúster que se esté configurando inicialmente, debe conectarse al puerto de la consola del switch con el cable de consola incluido y necesita información de red específica.

.Asignaciones de puertos del switch del clúster
Puede utilizar la tabla de asignaciones de puertos de conmutador de clúster BES-53248 compatible con Broadcom como guía para configurar su clúster.

[cols="1,2"]
|===
| Puertos del switch | Uso de puertos 


 a| 
01-16
 a| 
Configuración base de nodos de puertos de clúster de 10 GbE



 a| 
17-48
 a| 
Nodos de puertos de clúster de 10 GbE, con licencias



 a| 
49-54
 a| 
Nodos de puertos de clúster de 100 GbE, con licencias, añadidos de derecha a izquierda



 a| 
55-56
 a| 
Puertos de enlace entre switches (ISL) de clúster de 100 GbE, configuración base

|===
.Limitación de velocidad del grupo de puertos
En los switches de clúster BES-53248, los puertos de 48 10 GbE (SFP28/SFP+) se combinan en 12 grupos de puertos de 4 de la siguiente manera: Puertos 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44, y 45-48.

La velocidad del puerto SFP28/SFP+ debe ser la misma (10 GbE o 25 GbE) en todos los puertos del grupo de 4 puertos.



== Requisitos de documentación

Necesita documentación específica sobre los switches y las controladoras para configurar su switch de clúster BES-53248 y su clúster de ONTAP.



=== Documentación de Broadcom

Para configurar el switch de clúster BES-53248, necesita los siguientes documentos disponibles en el sitio de soporte de Broadcom: https://www.broadcom.com/support/bes-switch["Línea de producto de conmutador Ethernet Broadcom"^]

[cols="1,2"]
|===
| Título del documento | Descripción 


 a| 
_EFOS Guía del administrador v3.4.3_
 a| 
Proporciona ejemplos de cómo utilizar el conmutador BES-53248 en una red típica.



 a| 
_Referencia de comandos de la CLI del EFOS v3.4.3_
 a| 
Describe los comandos de la interfaz de línea de comandos (CLI) que utiliza para ver y configurar el software BES-53248.



 a| 
_Guía de puesta en marcha del EFOS v3.4.3_
 a| 
Proporciona información detallada acerca del conmutador BES-53248.



 a| 
_EFOS SNMP Reference Guide v3.4.3_
 a| 
Proporciona ejemplos de cómo utilizar el conmutador BES-53248 en una red típica.



 a| 
_EFOS escala parámetros y valores v3.4.3_
 a| 
Describe los parámetros de escala predeterminados con los que se suministra y valida el software EFOS en las plataformas compatibles.



 a| 
_EFOS Especificaciones funcionales v3.4.3_
 a| 
Describe las especificaciones del software EFOS en las plataformas compatibles.



 a| 
_Notas de publicación de EFOS v3.4.3_
 a| 
Proporciona información específica de la versión sobre el software BES-53248.



 a| 
_Matriz de compatibilidad de redes de administración y redes de clúster_
 a| 
Proporciona información sobre la compatibilidad de red. La matriz está disponible en el sitio de descarga del conmutador BES-53248 en https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Switches de clúster Broadcom"^].

|===


=== Documentación de los sistemas ONTAP y artículos de la base de conocimientos

Para configurar un sistema ONTAP, necesita los siguientes documentos en el sitio de soporte de NetApp en http://mysupport.netapp.com/["mysupport.netapp.com"^] O el sitio de la base de conocimientos (KB) en https://kb.netapp.com/["kb.netapp.com"^].

[cols="1,2"]
|===
| Nombre | Descripción 


 a| 
https://hwu.netapp.com/Home/Index["Hardware Universe de NetApp"^]
 a| 
Describe los requisitos de alimentación y del sitio para todo el hardware de NetApp, incluidos los armarios de sistema, y proporciona información sobre los conectores y las opciones de cables relevantes que se deben usar junto con sus números de pieza.



 a| 
Específicos del controlador _instrucciones de instalación y configuración_
 a| 
Describe cómo instalar el hardware de NetApp.



 a| 
ONTAP 9
 a| 
Proporciona información detallada sobre todos los aspectos de la versión 9 de ONTAP.



 a| 
_Cómo añadir licencias de puerto adicionales para el conmutador BES-53248 compatible con Broadcom_
 a| 
Proporciona información detallada sobre cómo agregar licencias de puerto. Vaya a la https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["Artículo de base de conocimientos"^].

|===