---
permalink: switch-bes-53248/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: two-node switchless clusters, migrating to a two-node switched BES-53248 cluster environment,BES-53248 switches, migrating two-node switched clusters,2-node 
summary: Si tiene un clúster de dos nodos sin conmutadores, puede migrar, sin interrupciones, a un clúster de dos nodos con conmutadores que incluya conmutadores de clúster BES-53248 compatibles con Broadcom. 
---
= Migrar a un entorno de clúster NetApp conmutado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene un entorno de clúster _sin conmutador_ existente de dos nodos, puede migrar a un entorno de clúster _con conmutador_ de dos nodos utilizando conmutadores de clúster BES-53248 compatibles con Broadcom, lo que le permite escalar más allá de dos nodos en el clúster.

El proceso de migración funciona para todos los puertos de nodos del clúster que utilizan puertos ópticos o Twinax, pero no es compatible con este conmutador si los nodos utilizan puertos RJ45 10GBASE-T integrados para los puertos de red del clúster.



== Requisitos de revisión

Revise los siguientes requisitos para el entorno del clúster.

* Tenga en cuenta que la mayoría de los sistemas requieren dos puertos de red de clúster dedicados en cada controlador.
* Asegúrese de que el conmutador de clúster BES-53248 esté configurado como se describe enlink:replace-switch-reqs.html["Reemplazar requisitos"] antes de iniciar este proceso de migración.
* Para la configuración sin conmutador de dos nodos, asegúrese de que:
+
** La configuración sin interruptor de dos nodos está correctamente configurada y funcionando.
** Los nodos ejecutan ONTAP 9.5P8 y versiones posteriores.  La compatibilidad con puertos de clúster 40/100 GbE comienza con la versión de firmware EFOS 3.4.4.6 y posteriores.
** Todos los puertos del clúster están en estado *activo*.
** Todas las interfaces lógicas del clúster (LIF) están en estado *activo* y en sus puertos de inicio.


* Para la configuración del conmutador de clúster BES-53248 compatible con Broadcom, asegúrese de lo siguiente:
+
** El conmutador de clúster BES-53248 es completamente funcional en ambos conmutadores.
** Ambos switches tienen conectividad de red de gestión.
** Existe acceso mediante consola a los conmutadores del clúster.
** Las conexiones de conmutador a nodo y de conmutador a conmutador BES-53248 utilizan cables Twinax o de fibra.
+
El https://hwu.netapp.com/Home/Index["_Universo de hardware de NetApp_"^] Contiene información sobre la compatibilidad con ONTAP , el firmware EFOS compatible y el cableado a los switches BES-53248.



* Los cables de enlace entre conmutadores (ISL) están conectados a los puertos 0/55 y 0/56 en ambos conmutadores BES-53248.
* La personalización inicial de ambos switches BES-53248 está completa, de modo que:
+
** Los conmutadores BES-53248 ejecutan la última versión del software.
** Los switches BES-53248 tienen licencias de puerto opcionales instaladas, si se compran.
** Los archivos de configuración de referencia (RCF) se aplican a los conmutadores.


* Cualquier personalización del sitio (SMTP, SNMP y SSH) se configura en los nuevos conmutadores.


.Restricciones de velocidad del grupo de puertos
* Los 48 puertos 10/25GbE (SFP28/SFP+) se combinan en 12 grupos de 4 puertos de la siguiente manera: Puertos 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44 y 45-48.
* La velocidad del puerto SFP28/SFP+ debe ser la misma (10GbE o 25GbE) en todos los puertos del grupo de 4 puertos.
* Si las velocidades en un grupo de 4 puertos son diferentes, los puertos del conmutador no funcionarán correctamente.




== Migrar al entorno de clúster

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de nodos y conmutadores de clúster:

* Los nombres de los conmutadores BES-53248 son `cs1` y `cs2` .
* Los nombres de los SVM del clúster son `node1` y `node2` .
* Los nombres de los LIF son `node1_clus1` y `node1_clus2` en el nodo 1, y `node2_clus1` y `node2_clus2` en el nodo 2 respectivamente.
* El `cluster1::*>` El indicador muestra el nombre del clúster.
* Los puertos del clúster utilizados en este procedimiento son `e0a` y `e0b` .
+
El https://hwu.netapp.com/Home/Index["_Universo de hardware de NetApp_"^] Contiene la información más reciente sobre los puertos de clúster reales para sus plataformas.





=== Paso 1: Prepararse para la migración

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
donde x es la duración de la ventana de mantenimiento en horas.

+

NOTE: El mensaje de AutoSupport notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante la ventana de mantenimiento.

+
El siguiente comando suprime la creación automática de casos durante dos horas:

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. Cambie el nivel de privilegio a avanzado, ingresando *y* cuando se le solicite continuar:
+
`set -privilege advanced`

+
La solicitud avanzada(`*>` ) aparece.





=== Paso 2: Configurar puertos y cableado

. Deshabilite todos los puertos orientados al nodo activados (que no sean puertos ISL) en ambos conmutadores del nuevo clúster cs1 *y* cs2.
+

NOTE: No debe deshabilitar los puertos ISL.

+
El siguiente ejemplo muestra que los puertos orientados al nodo del 1 al 16 están deshabilitados en el switch cs1:

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. Verifique que el enlace ISL y los puertos físicos del enlace ISL entre los dos conmutadores BES-53248 cs1 y cs2 estén activos:
+
`show port-channel`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos ISL están activos en el switch cs1:

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
El siguiente ejemplo muestra que los puertos ISL están activos en el switch cs2:

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Mostrar la lista de dispositivos vecinos:
+
`show isdp neighbors`

+
Este comando proporciona información sobre los dispositivos conectados al sistema.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo enumera los dispositivos vecinos en el switch cs1:

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
El siguiente ejemplo enumera los dispositivos vecinos en el switch cs2:

[listing, subs="+quotes"]
----
(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
====
. Verifique que todos los puertos del clúster estén activos:
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy
----
====
. Verifique que todas las LIF del clúster estén activas y operativas:
+
`network interface show -vserver Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. Desactive la reversión automática en los LIF del clúster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. Desconecte el cable del puerto de clúster e0a en el nodo 1 y, luego, conecte e0a al puerto 1 en el conmutador de clúster cs1, utilizando el cableado adecuado compatible con los conmutadores BES-53248.
+
El https://hwu.netapp.com/Home/Index["_Universo de hardware de NetApp_"^] Contiene más información sobre el cableado.

. Desconecte el cable del puerto de clúster e0a en el nodo 2 y, luego, conecte e0a al puerto 2 en el conmutador de clúster cs1, utilizando el cableado adecuado compatible con los conmutadores BES-53248.
. Habilite todos los puertos orientados a nodos en el conmutador de clúster cs1.
+
El siguiente ejemplo muestra que los puertos del 1 al 16 están habilitados en el switch cs1:

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *no shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. Verifique que todos los puertos del clúster estén activos:
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. Verifique que todas las LIF del clúster estén activas y operativas:
+
`network interface show -vserver Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true
----
====
. Mostrar información sobre el estado de los nodos en el clúster:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra información sobre el estado y la elegibilidad de los nodos del clúster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. Desconecte el cable del puerto de clúster e0b en el nodo 1 y, luego, conecte e0b al puerto 1 en el conmutador de clúster cs2, utilizando el cableado adecuado compatible con los conmutadores BES-53248.
. Desconecte el cable del puerto de clúster e0b en el nodo 2 y, luego, conecte e0b al puerto 2 en el conmutador de clúster cs2, utilizando el cableado adecuado compatible con los conmutadores BES-53248.
. Habilite todos los puertos orientados a nodos en el conmutador de clúster cs2.
+
El siguiente ejemplo muestra que los puertos del 1 al 16 están habilitados en el switch cs2:

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)# *exit*
----
. Verifique que todos los puertos del clúster estén activos:
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====




=== Paso 3: Verificar la configuración

. Habilitar la reversión automática en los LIF del clúster.
+
[listing, subs="+quotes"]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true
----
. En el switch cs2, apague y reinicie todos los puertos del clúster para activar una reversión automática de todas las LIF del clúster que no estén en sus puertos de origen.
+
[listing, subs="+quotes"]
----
cs2> *enable*
cs2# *configure*
cs2(config)# *interface 0/1-0/16*
cs2(config-if-range)# *shutdown*

(Wait for 5-10 seconds before re-enabling the ports)

cs2(config-if-range)# *no shutdown*

(After executing the no shutdown command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)

cs2(config-if-range)# *exit*
cs2(config)# *exit*
cs2#
----
. Verifique que las LIF del clúster hayan vuelto a sus puertos de origen (esto podría tardar un minuto):
+
`network interface show -vserver Cluster`

+
Si alguna de las LIF del clúster no ha vuelto a su puerto de origen, vuelva a configurarla manualmente. Debe conectarse a cada consola del sistema LIF o SP/ BMC de administración de nodos del nodo local propietario del LIF:

+
`network interface revert -vserver Cluster -lif *`

. Verifique que todas las interfaces muestren `true` para `Is Home` :
+
`network interface show -vserver Cluster`

+

NOTE: Esto podría tardar varios minutos en completarse.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true
----
====
. Verifique que ambos nodos tengan una conexión a cada conmutador:
+
`show isdp neighbors`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra los resultados correspondientes para ambos interruptores:

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform -- Port ID
-------------- ------------ --------- ------------ ----------- ----------
node1          0/1          175       H            FAS2750     e0a
node2          0/2          157       H            FAS2750     e0a
cs2            0/55         178       R            BES-53248   0/55
cs2            0/56         178       R            BES-53248   0/56


(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform    Port ID
-------------- ------------ --------- ------------ ----------- ------------
node1          0/1          137       H            FAS2750     e0b
node2          0/2          179       H            FAS2750     e0b
cs1            0/55         175       R            BES-53248   0/55
cs1            0/56         175       R            BES-53248   0/56
----
====
. Muestra información sobre los dispositivos de red detectados en su clúster:
+
`network device-discovery show -protocol cdp`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
====
. Verifique que la configuración esté desactivada:
+
`network options switchless-cluster show`

+

NOTE: El comando podría tardar varios minutos en completarse.  Espere el anuncio de "tiempo de vida de 3 minutos a expirar".

+
El `false` El resultado del siguiente ejemplo muestra que la configuración está desactivada:

+
[listing, subs="+quotes"]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: *false*
----
. Verifique el estado de los nodos miembros del clúster:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra información sobre el estado y la elegibilidad de los nodos del clúster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step10]]Cambie el nivel de privilegios de nuevo a administrador:
+
`set -privilege admin`

. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
+
Para obtener más información, consulte: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["Artículo de la base de conocimientos de NetApp : Cómo suprimir la creación automática de casos durante las ventanas de mantenimiento programadas"^]



.¿Que sigue?
Después de migrar tus switches, puedes link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
