---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610, CN1610 replacing, migrate from CN1610 
summary: Para reemplazar los conmutadores de clúster CN1610 existentes en un clúster con conmutadores de clúster BES-53248 compatibles con Broadcom, debe realizar una secuencia específica de tareas. 
---
= Migrar los conmutadores de clúster CN1610 a conmutadores de clúster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para migrar los conmutadores de clúster CN1610 de un clúster a conmutadores de clúster BES-53248 compatibles con Broadcom, revise los requisitos de migración y luego siga el procedimiento de migración.

Se admiten los siguientes conmutadores de clúster:

* CN1610
* BES-53248




== Requisitos de revisión

Verifique que su configuración cumple con los siguientes requisitos:

* Algunos de los puertos de los switches BES-53248 están configurados para funcionar a 10GbE.
* Se ha planificado, migrado y documentado la conectividad 10GbE desde los nodos a los conmutadores de clúster BES-53248.
* El clúster está funcionando correctamente (no debería haber errores en los registros ni problemas similares).
* La personalización inicial de los switches BES-53248 está completa, de modo que:
+
** Los switches BES-53248 ejecutan la última versión recomendada del software EFOS.
** Se han aplicado archivos de configuración de referencia (RCF) a los conmutadores.
** Cualquier personalización del sitio, como DNS, NTP, SMTP, SNMP y SSH, se configura en los nuevos conmutadores.






=== Conexiones de nodos

Los conmutadores del clúster admiten las siguientes conexiones de nodo:

* NetApp CN1610: puertos 0/1 a 0/12 (10GbE)
* BES-53248: puertos 0/1-0/16 (10GbE/25GbE)
+

NOTE: Se pueden activar puertos adicionales mediante la compra de licencias de puerto.





=== Puertos ISL

Los conmutadores del clúster utilizan los siguientes puertos de enlace entre conmutadores (ISL):

* NetApp CN1610: puertos 0/13 a 0/16 (10GbE)
* BES-53248: puertos 0/55-0/56 (100GbE)


El link:https://hwu.netapp.com/Home/Index["_Universo de hardware de NetApp_"^] Contiene información sobre la compatibilidad de ONTAP , el firmware EFOS compatible y el cableado a los conmutadores de clúster BES-53248. Ver link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"^] para obtener más información sobre los requisitos de instalación del conmutador.



=== Cableado ISL

El cableado ISL apropiado es el siguiente:

* *Inicio:* Para CN1610 a CN1610 (SFP+ a SFP+), cuatro cables de fibra óptica o cobre de conexión directa SFP+.
* *Final:* Para BES-53248 a BES-53248 (QSFP28 a QSFP28), dos transceptores ópticos QSFP28/cables de conexión directa de fibra o cobre.




== Migrar los interruptores

Siga este procedimiento para migrar los conmutadores de clúster CN1610 a conmutadores de clúster BES-53248.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los ejemplos utilizan dos nodos, cada uno de los cuales despliega dos puertos de interconexión de clúster de 10 GbE: `e0a` y `e0b` .
* Los resultados de los comandos pueden variar según las diferentes versiones del software ONTAP .
* Los interruptores CN1610 que se deben reemplazar son `CL1` y `CL2` .
* Los interruptores BES-53248 que reemplazan a los interruptores CN1610 son `cs1` y `cs2` .
* Los nodos son `node1` y `node2` .
* El interruptor CL2 se reemplaza primero por cs2, seguido de CL1 por cs1.
* Los switches BES-53248 vienen precargados con las versiones compatibles del archivo de configuración de referencia (RCF) y del sistema operativo Ethernet Fabric (EFOS) con cables ISL conectados en los puertos 55 y 56.
* Los nombres de los clústeres LIF son `node1_clus1` y `node1_clus2` para el nodo 1, y `node2_clus1` y `node2_clus2` para el nodo 2.


.Acerca de esta tarea
Este procedimiento cubre el siguiente escenario:

* El clúster comienza con dos nodos conectados a dos conmutadores de clúster CN1610.
* El interruptor CN1610 CL2 se reemplaza por el interruptor BES-53248 cs2:
+
** Desactive los puertos de los nodos del clúster.  Todos los puertos deben apagarse simultáneamente para evitar la inestabilidad del clúster.
** Desconecte los cables de todos los puertos del clúster en todos los nodos conectados a CL2 y, a continuación, utilice cables compatibles para volver a conectar los puertos al nuevo conmutador del clúster cs2.


* El interruptor CN1610 CL1 se reemplaza por el interruptor BES-53248 cs1:
+
** Desactive los puertos de los nodos del clúster.  Todos los puertos deben apagarse simultáneamente para evitar la inestabilidad del clúster.
** Desconecte los cables de todos los puertos del clúster en todos los nodos conectados a CL1 y, a continuación, utilice cables compatibles para volver a conectar los puertos al nuevo conmutador del clúster cs1.





NOTE: No se necesita ningún enlace entre conmutadores (ISL) operativo durante este procedimiento. Esto es así por diseño porque los cambios de versión de RCF pueden afectar la conectividad de ISL temporalmente. Para garantizar un funcionamiento ininterrumpido del clúster, el siguiente procedimiento migra todas las LIF del clúster al conmutador asociado operativo mientras se realizan los pasos en el conmutador de destino.



=== Paso 1: Prepararse para la migración

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
donde x es la duración de la ventana de mantenimiento en horas.

+

NOTE: El mensaje de AutoSupport notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante la ventana de mantenimiento.

+
El siguiente comando suprime la creación automática de casos durante dos horas:

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. Cambie el nivel de privilegio a avanzado, ingresando *y* cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el indicador avanzado (*>).





=== Paso 2: Configurar puertos y cableado

. En los nuevos switches, confirme que el enlace ISL está cableado y funciona correctamente entre los switches cs1 y cs2:
+
`show port-channel`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos ISL están *activos* en el switch cs1:

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
El siguiente ejemplo muestra que los puertos ISL están *activos* en el switch cs2:

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Muestra los puertos del clúster en cada nodo conectado a los conmutadores del clúster existentes:
+
`network device-discovery show -protocol cdp`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cuántas interfaces de interconexión de clúster se han configurado en cada nodo para cada conmutador de interconexión de clúster:

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    CL2                       0/2               CN1610
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    CL2                       0/1               CN1610
----
====
. Determinar el estado administrativo u operativo de cada interfaz de clúster.
+
.. Verifique que todos los puertos del clúster estén `up` con un `healthy` estado:
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
.. Verifique que todas las interfaces del clúster (LIF) estén en sus puertos de origen:
+
`network interface show -vserver Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====


. Verifique que el clúster muestre información para ambos conmutadores del clúster:


[role="tabbed-block"]
====
.ONTAP 9.8 y posteriores
--
A partir de ONTAP 9.8, utilice el siguiente comando: `system switch ethernet show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
.ONTAP 9.7 y versiones anteriores
--
Para ONTAP 9.7 y versiones anteriores, utilice el comando: `system cluster-switch show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
====
. [[step5]]Deshabilitar la reversión automática en los LIF del clúster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. En el conmutador de clúster CL2, apague los puertos conectados a los puertos de clúster de los nodos para realizar la conmutación por error de las LIF del clúster:
+
[listing, subs="+quotes"]
----
(CL2)# *configure*
(CL2)(Config)# *interface 0/1-0/16*
(CL2)(Interface 0/1-0/16)# *shutdown*
(CL2)(Interface 0/1-0/16)# *exit*
(CL2)(Config)# *exit*
(CL2)#
----
. Verifique que las LIF del clúster hayan conmutado por error a los puertos alojados en el conmutador del clúster CL1. Esto podría tardar unos segundos.
+
`network interface show -vserver Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0a     false
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0a     false
----
====
. Verifique que el clúster esté en buen estado:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Traslade todos los cables de conexión de los nodos del clúster del antiguo switch CL2 al nuevo switch cs2.
. Confirme el estado de las conexiones de red migradas a cs2:
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Todos los puertos del clúster que se movieron deberían ser `up` .

. Comprobar la información de los vecinos en los puertos del clúster:
+
`network device-discovery show -protocol cdp`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    cs2                       0/1               BES-53248
----
====
. Confirme que las conexiones de los puertos del switch son correctas desde la perspectiva del switch cs2:
+
[listing, subs="+quotes"]
----
cs2# *show interface all*
cs2# *show isdp neighbors*
----
. En el conmutador de clúster CL1, apague los puertos conectados a los puertos de clúster de los nodos para realizar la conmutación por error de las LIF del clúster:
+
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/1-0/16*
(CL1)(Interface 0/1-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
+
Todas las LIF del clúster conmutan por error al conmutador cs2.

. Verifique que los LIF del clúster hayan conmutado por error a los puertos alojados en el conmutador cs2. Esto podría tardar unos segundos:
+
`network interface show -vserver Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0b     false
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0b     false
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. Verifique que el clúster esté en buen estado:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Traslade los cables de conexión del nodo del clúster desde CL1 al nuevo conmutador cs1.
. Confirme el estado de las conexiones de red migradas a cs1:
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Todos los puertos del clúster que se movieron deberían ser `up` .

. Comprobar la información de los vecinos en los puertos del clúster:
+
`network device-discovery show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====
. Confirme que las conexiones de los puertos del switch son correctas desde la perspectiva del switch cs1:
+
[listing, subs="+quotes"]
----
cs1# *show interface all*
cs1# *show isdp neighbors*
----
. Verifique que el enlace ISL entre cs1 y cs2 siga operativo:
+
`show port-channel`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos ISL están *activos* en el switch cs1:

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
El siguiente ejemplo muestra que los puertos ISL están *activos* en el switch cs2:

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Elimine los conmutadores CN1610 reemplazados de la tabla de conmutadores del clúster, si no se eliminan automáticamente:


[role="tabbed-block"]
====
.ONTAP 9.8 y posteriores
--
A partir de ONTAP 9.8, utilice el siguiente comando: `system switch ethernet delete -device _device-name_`

[listing]
----
cluster::*> system switch ethernet delete -device CL1
cluster::*> system switch ethernet delete -device CL2
----
--
.ONTAP 9.7 y versiones anteriores
--
Para ONTAP 9.7 y versiones anteriores, utilice el comando: `system cluster-switch delete -device _device-name_`

[listing]
----
cluster::*> system cluster-switch delete -device CL1
cluster::*> system cluster-switch delete -device CL2
----
--
====


=== Paso 3: Verificar la configuración

. Habilitar la reversión automática en los LIF del clúster.
+
[listing, subs="+quotes"]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true
----
. En el switch cs2, apague y reinicie todos los puertos del clúster para activar una reversión automática de todas las LIF del clúster que no estén en sus puertos de origen.
+
[listing, subs="+quotes"]
----
cs2> *enable*
cs2# *configure*
cs2(config)# *interface 0/1-0/16*
cs2(config-if-range)# *shutdown*

(Wait for 5-10 seconds before re-enabling the ports)

cs2(config-if-range)# *no shutdown*

(After executing the no shutdown command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)

cs2(config-if-range)# *exit*
cs2(config)# *exit*
cs2#
----
. Verifique que las LIF del clúster hayan vuelto a sus puertos de origen (esto podría tardar un minuto):
+
`network interface show -vserver Cluster`

+
Si alguna de las LIF del clúster no ha vuelto a su puerto de origen, vuelva a configurarla manualmente. Debe conectarse a cada consola del sistema LIF o SP/ BMC de administración de nodos del nodo local propietario del LIF:

+
`network interface revert -vserver Cluster -lif *`

. Verifique que el clúster esté en buen estado:
+
`cluster show`

. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step6]]Si suprimió la creación automática de casos, vuelva a habilitarla invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing, subs="+quotes"]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----


.¿Que sigue?
Después de migrar tus switches, puedes link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
