---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610, CN1610 replacing, migrate from CN1610 
summary: Para sustituir los switches de clúster CN1610 existentes en un clúster con switches de clúster BES-53248 compatibles con Broadcom, debe realizar una secuencia específica de tareas. 
---
= Migrar switches de clúster CN1610 a switches de clúster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para migrar los switches de clúster CN1610 de un clúster a switches de clúster BES-53248 compatibles con Broadcom, revise los requisitos de migración y siga el procedimiento de migración.

Se admiten los siguientes switches de clúster:

* CN1610
* BES-53248




== Revise los requisitos

Compruebe que la configuración cumple los siguientes requisitos:

* Algunos de los puertos de los switches BES-53248 están configurados para funcionar a 10GbE o 40GbE.
* Se ha planificado, migrado y documentado la conectividad 10GbE y 40GbE desde los nodos a los switches de clúster BES-53248.
* El clúster está funcionando completamente (no debería haber errores en los registros o problemas similares).
* Se ha completado la personalización inicial de los interruptores BES-53248, de modo que:
+
** Los conmutadores BES-53248 ejecutan la última versión recomendada del software EFOS.
** Los archivos de configuración de referencia (RCF) se han aplicado a los conmutadores.
** La personalización de cualquier sitio, como DNS, NTP, SMTP, SNMP, Y SSH, se configuran en los nuevos switches.






=== Conexiones de nodos

Los switches de clúster admiten las siguientes conexiones de nodo:

* NetApp CN1610: Puertos 0/1 a 0/12 (10GbE)
* BES-53248: Puertos 0/1-0/16 (10GbE/25GbE)
+

NOTE: Los puertos adicionales se pueden activar si se compran licencias de puertos.





=== Puertos ISL

Los switches de clúster utilizan los siguientes puertos de enlace entre switches (ISL):

* NetApp CN1610: Puertos 0/13 a 0/16 (10GbE)
* BES-53248: Puertos 0/55-0/56 (100GbE)


La https://hwu.netapp.com/Home/Index["_Hardware Universe_ de NetApp"^] Contiene información acerca de la compatibilidad con ONTAP, el firmware EFOS compatible y el cableado para switches de clúster BES-53248.



=== Cableado ISL

El cableado ISL adecuado es el siguiente:

* *Principio:* para CN1610 a CN1610 (SFP+ a SFP+), cuatro cables de conexión directa de cobre o fibra óptica SFP+.
* *Final:* para BES-53248 a BES-53248 (QSFP28 a QSFP28), dos transceptores ópticos QSFP28/fibra o cables de conexión directa de cobre.




== Migrar los switches

Siga este procedimiento para migrar switches de clúster CN1610 a switches de clúster BES-53248.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la nomenclatura de conmutador y nodo siguiente:

* En los ejemplos, se utilizan dos nodos, cada uno de los cuales implementa dos puertos de interconexión de clúster de 10 GbE: `e0a` y.. `e0b`.
* Los resultados del comando pueden variar en función de las diferentes versiones del software ONTAP.
* Los switches CN1610 que se van a sustituir son `CL1` y.. `CL2`.
* Los switches BES-53248 para reemplazar los switches CN1610 son `cs1` y.. `cs2`.
* Los nodos son `node1` y.. `node2`.
* El interruptor CL2 se sustituye primero por cs2, seguido por CL1 por cs1.
* Los switches BES-53248 están precargados con las versiones compatibles de archivo de configuración de referencia (RCF) y SO Ethernet Fabric (EFOS) con cables ISL conectados en los puertos 55 y 56.
* Los nombres de LIF del clúster son `node1_clus1` y.. `node1_clus2` para los nodos 1, y. `node2_clus1` y.. `node2_clus2` para el 2.


.Acerca de esta tarea
Este procedimiento cubre el siguiente caso:

* El clúster comienza con dos nodos conectados a dos switches de clúster CN1610.
* El conmutador CN1610 CL2 se sustituye por el conmutador BES-53248 cs2:
+
** Desconecte los cables de todos los puertos del clúster de todos los nodos conectados a CL2 y, a continuación, utilice cables admitidos para volver a conectar los puertos al nuevo switch del clúster cs2.


* El conmutador CN1610 CL1 se sustituye por el conmutador BES-53248 cs1:
+
** Desconecte los cables de todos los puertos del clúster de todos los nodos conectados a CL1 y, a continuación, utilice cables admitidos para volver a conectar los puertos al nuevo switch del clúster cs1.





NOTE: Durante este procedimiento no se necesita ningún enlace entre switches (ISL) operativo. Esto se debe a que los cambios en la versión de RCF pueden afectar temporalmente a la conectividad ISL. Para garantizar operaciones de clúster no disruptivas, el siguiente procedimiento migra todas las LIF del clúster al switch de partner operativo mientras realiza los pasos del switch de destino.



=== Paso 1: Preparación para la migración

. Si se habilita AutoSupport en este clúster, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
donde x es la duración de la ventana de mantenimiento en horas.

+

NOTE: El mensaje de AutoSupport notifica al soporte técnico de esta tarea de mantenimiento para que la creación automática de casos se suprima durante la ventana de mantenimiento.

+
El siguiente comando suprime la creación automática de casos durante dos horas:

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. Cambie el nivel de privilegio a avanzado, introduciendo *y* cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el mensaje avanzado (*>).





=== Paso 2: Configure los puertos y el cableado

. En los switches nuevos, confirme que el cableado ISL está en buen estado entre los switches CS1 y CS2:
+
`show port-channel summary`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/55(P)   Eth1/56(P)

cs2# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/55(P)   Eth1/56(P)
----
====
. Muestre los puertos de clúster en cada nodo que están conectados a los switches de clúster existentes:
+
`network device-discovery show -protocol cdp`

+
.Muestra el ejemplo
[%collapsible]
====
El ejemplo siguiente muestra cuántas interfaces de interconexión de clúster se han configurado en cada nodo para cada switch de interconexión de clúster:

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL2                       0/2               CN1610
            e0b    CL1                       0/2               CN1610
node1      /cdp
            e0a    CL2                       0/1               CN1610
            e0b    CL1                       0/1               CN1610
----
====
. Determinar el estado administrativo u operativo de cada interfaz de clúster.
+
.. Verifique que todos los puertos del clúster sean `up` con un `healthy` estado:
+
`network port show -ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
.. Compruebe que todas las interfaces del clúster (LIF) están en sus puertos de inicio:
+
`network interface show -vserver Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====


. Compruebe que el clúster muestra información de ambos switches de clúster:


[role="tabbed-block"]
====
.ONTAP 9.8 y posteriores
--
A partir de ONTAP 9,8, utilice el comando: `system switch ethernet show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
.ONTAP 9.7 y anteriores
--
Para ONTAP 9,7 y versiones anteriores, utilice el comando: `system cluster-switch show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
====
. [[step5]]Deshabilite la reversión automática en las LIF del clúster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. En el switch de clúster CL1, apague los puertos conectados a los puertos de clúster de los nodos:
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16*
(CL1)(Interface 0/13-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Compruebe que las LIF del clúster han migrado a los puertos alojados en el switch de clúster CL1. Esto puede tardar unos segundos.
+
`network interface show -vserver Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     false
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     false
----
====
. Compruebe que el clúster esté en buen estado:
+
`cluster show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Mueva todos los cables de conexión de nodos de clúster del switch antiguo CS2 al nuevo switch de CS2.
. Confirme el estado de las conexiones de red movidas a CS2:
+
`network port show -ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Todos los puertos de clúster que se han movido deben ser `up`.

. Compruebe la información de cercanía en los puertos de clúster:
+
`network device-discovery show -protocol cdp`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    cs1                       0/2               BES-53248
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    cs1                       0/1               BES-53248
----
====
. Confirme las conexiones del puerto del switch desde la perspectiva del switch CS2 mediante los comandos:
+
[listing, subs="+quotes"]
----
cs2# *show interface brief*
cs2# *show cdp neighbors*
----
. En el switch de clúster CL2, apague los puertos conectados a los puertos de clúster de los nodos.
+
[listing, subs="+quotes"]
----
(CL2)# *configure*
(CL2)(Config)# *interface 0/1-0/16*
(CL2)(Interface 0/1-0/16)# *shutdown*
(CL2)(Interface 0/13-0/16)# *exit*
(CL2)(Config)# *exit*
(CL2)#
----
+
Todos los LIF del clúster se mueven al switch CS2.

. Comprobar que las LIF del clúster han migrado a los puertos alojados en el switch cs2. Esto puede tardar unos segundos:
+
`network interface show -vserver Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. Compruebe que el clúster esté en buen estado:
+
`cluster show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Mueva los cables de conexión de nodo de clúster de CL1 al nuevo switch de CS1.
. Confirme el estado de las conexiones de red movidas a CS1:
+
`network port show -ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Todos los puertos de clúster que se han movido deben ser `up`.

. Compruebe la información de cercanía en los puertos de clúster:
+
`network device-discovery show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs2                       0/1               BES-53248
            e0b    cs1                       0/1               BES-53248
node2      /cdp
            e0a    cs2                       0/2               BES-53248
            e0b    cs1                       0/2               BES-53248
----
====
. Confirme las conexiones del puerto del switch desde la perspectiva del switch CS1 mediante los comandos:
+
[listing, subs="+quotes"]
----
cs1# *show interface brief*
cs1# *show cdp neighbors*
----
. Compruebe que el ISL entre CS1 y CS2 aún está operativo:
+
`show port-channel summary`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/55(P)   Eth1/56(P)

cs2# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/55(P)   Eth1/56(P)
----
====
. Extraiga los interruptores CN1610 sustituidos si no se retiran automáticamente:


[role="tabbed-block"]
====
.ONTAP 9.8 y posteriores
--
A partir de ONTAP 9,8, utilice el comando: `system switch ethernet delete -device _device-name_`

[listing]
----
cluster::*> system switch ethernet delete -device CL2
cluster::*> system switch ethernet delete -device CL1
----
--
.ONTAP 9,4 y anteriores
--
Para ONTAP 9,4 y versiones anteriores, utilice el comando: `system cluster-switch delete -device _device-name_`

[listing]
----
cluster::*> system cluster-switch delete -device CL2
cluster::*> system cluster-switch delete -device CL1
----
--
====


=== Paso 3: Verificar la configuración

. Habilite la reversión automática en las LIF del clúster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert true*
----
. Compruebe que las LIF del clúster han vuelto a sus puertos raíz (esto puede tardar un minuto):
+
`network interface show -vserver Cluster`

+
Si los LIF del clúster no han cambiado a su puerto de inicio, los revierte manualmente:

+
`network interface revert -vserver Cluster -lif *`

. Compruebe que el clúster esté en buen estado:
+
`cluster show`

. Haga ping en las interfaces de clúster remoto para verificar la conectividad:
+
`cluster ping-cluster -node <name>`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69  node1     e0a
Cluster node1_clus2 169.254.49.125  node1     e0b
Cluster node2_clus1 169.254.47.194  node2     e0a
Cluster node2_clus2 169.254.19.183  node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. Cree una contraseña para la función de recopilación de registros de monitor de estado del switch Ethernet.
+

IMPORTANT: Para habilitar la función de recopilación de registros, debe ejecutar ONTAP 9.12.1 y versiones posteriores, y EFOS 3.8.0.2 y versiones posteriores.

+
`system switch ethernet log setup-password`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. Habilite la función de recopilación de registros del monitor de estado del switch Ethernet:
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration?
{y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Espere 10 minutos y compruebe que se complete la recopilación de registros:

+
`system switch ethernet log show`

+

CAUTION: Si alguno de estos comandos devuelve un error o si la recogida de registros no se completa, póngase en contacto con el soporte de NetApp.

. Si ha suprimido la creación automática de casos, vuelva a habilitarla invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing, subs="+quotes"]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----


.El futuro
Una vez finalizada la migración, es posible que tenga que instalar el archivo de configuración necesario para admitir el Monitor de estado del conmutador de clúster (CSHM) para los switches de clúster BES-53248. Consulte link:configure-health-monitor.html["Instale el archivo de configuración del Monitor de estado del conmutador de clúster (CSHM)"] y.. link:configure-log-collection.html["Habilite la función de recogida de registros"].
