---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610, CN1610 replacing, migrate from CN1610 
summary: Para sustituir los switches de clúster CN1610 existentes en un clúster con switches de clúster BES-53248 compatibles con Broadcom, debe realizar una secuencia específica de tareas. 
---
= Migrar switches de clúster CN1610 a switches de clúster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para migrar los switches de clúster CN1610 de un clúster a switches de clúster BES-53248 compatibles con Broadcom, revise los requisitos de migración y siga el procedimiento de migración.

Se admiten los siguientes switches de clúster:

* CN1610
* BES-53248




== Revise los requisitos

Compruebe que la configuración cumple los siguientes requisitos:

* Algunos de los puertos de los conmutadores BES-53248 están configurados para funcionar a 10GbE.
* La conectividad 10GbE desde los nodos a los switches de clúster BES-53248 se ha planificado, migrado y documentado.
* El clúster está funcionando completamente (no debería haber errores en los registros o problemas similares).
* Se ha completado la personalización inicial de los interruptores BES-53248, de modo que:
+
** Los conmutadores BES-53248 ejecutan la última versión recomendada del software EFOS.
** Los archivos de configuración de referencia (RCF) se han aplicado a los conmutadores.
** La personalización de cualquier sitio, como DNS, NTP, SMTP, SNMP, Y SSH, se configuran en los nuevos switches.






=== Conexiones de nodos

Los switches de clúster admiten las siguientes conexiones de nodo:

* NetApp CN1610: Puertos 0/1 a 0/12 (10GbE)
* BES-53248: Puertos 0/1-0/16 (10GbE/25GbE)
+

NOTE: Los puertos adicionales se pueden activar si se compran licencias de puertos.





=== Puertos ISL

Los switches de clúster utilizan los siguientes puertos de enlace entre switches (ISL):

* NetApp CN1610: Puertos 0/13 a 0/16 (10GbE)
* BES-53248: Puertos 0/55-0/56 (100GbE)


La https://hwu.netapp.com/Home/Index["_Hardware Universe_ de NetApp"^] Contiene información acerca de la compatibilidad con ONTAP, el firmware EFOS compatible y el cableado para switches de clúster BES-53248.



=== Cableado ISL

El cableado ISL adecuado es el siguiente:

* *Principio:* para CN1610 a CN1610 (SFP+ a SFP+), cuatro cables de conexión directa de cobre o fibra óptica SFP+.
* *Final:* para BES-53248 a BES-53248 (QSFP28 a QSFP28), dos transceptores ópticos QSFP28/fibra o cables de conexión directa de cobre.




== Migrar los switches

Siga este procedimiento para migrar switches de clúster CN1610 a switches de clúster BES-53248.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la nomenclatura de conmutador y nodo siguiente:

* En los ejemplos, se utilizan dos nodos, cada uno de los cuales implementa dos puertos de interconexión de clúster de 10 GbE: `e0a` y.. `e0b`.
* Los resultados del comando pueden variar en función de las diferentes versiones del software ONTAP.
* Los switches CN1610 que se van a sustituir son `CL1` y.. `CL2`.
* Los switches BES-53248 para reemplazar los switches CN1610 son `cs1` y.. `cs2`.
* Los nodos son `node1` y.. `node2`.
* El interruptor CL2 se sustituye primero por cs2, seguido por CL1 por cs1.
* Los switches BES-53248 están precargados con las versiones compatibles de archivo de configuración de referencia (RCF) y SO Ethernet Fabric (EFOS) con cables ISL conectados en los puertos 55 y 56.
* Los nombres de LIF del clúster son `node1_clus1` y.. `node1_clus2` para los nodos 1, y. `node2_clus1` y.. `node2_clus2` para el 2.


.Acerca de esta tarea
Este procedimiento cubre el siguiente caso:

* El clúster comienza con dos nodos conectados a dos switches de clúster CN1610.
* El conmutador CN1610 CL2 se sustituye por el conmutador BES-53248 cs2:
+
** Apague los puertos de los nodos del clúster. Todos los puertos deben apagarse simultáneamente para evitar la inestabilidad del clúster.
** Desconecte los cables de todos los puertos del clúster de todos los nodos conectados a CL2 y, a continuación, utilice cables admitidos para volver a conectar los puertos al nuevo switch del clúster cs2.


* El conmutador CN1610 CL1 se sustituye por el conmutador BES-53248 cs1:
+
** Apague los puertos de los nodos del clúster. Todos los puertos deben apagarse simultáneamente para evitar la inestabilidad del clúster.
** Desconecte los cables de todos los puertos del clúster de todos los nodos conectados a CL1 y, a continuación, utilice cables admitidos para volver a conectar los puertos al nuevo switch del clúster cs1.





NOTE: Durante este procedimiento no se necesita ningún enlace entre switches (ISL) operativo. Esto se debe a que los cambios en la versión de RCF pueden afectar temporalmente a la conectividad ISL. Para garantizar operaciones de clúster no disruptivas, el siguiente procedimiento migra todas las LIF del clúster al switch de partner operativo mientras realiza los pasos del switch de destino.



=== Paso 1: Preparación para la migración

. Si se habilita AutoSupport en este clúster, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
donde x es la duración de la ventana de mantenimiento en horas.

+

NOTE: El mensaje de AutoSupport notifica al soporte técnico de esta tarea de mantenimiento para que la creación automática de casos se suprima durante la ventana de mantenimiento.

+
El siguiente comando suprime la creación automática de casos durante dos horas:

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. Cambie el nivel de privilegio a avanzado, introduciendo *y* cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el mensaje avanzado (*>).





=== Paso 2: Configure los puertos y el cableado

. En los switches nuevos, confirme que el cableado ISL está en buen estado entre los switches CS1 y CS2:
+
`show port-channel`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestra que los puertos ISL están *up* en el switch cs1:

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
El siguiente ejemplo muestra que los puertos ISL están *up* en el conmutador cs2:

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Muestre los puertos de clúster en cada nodo que están conectados a los switches de clúster existentes:
+
`network device-discovery show -protocol cdp`

+
.Muestra el ejemplo
[%collapsible]
====
El ejemplo siguiente muestra cuántas interfaces de interconexión de clúster se han configurado en cada nodo para cada switch de interconexión de clúster:

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    CL2                       0/2               CN1610
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    CL2                       0/1               CN1610
----
====
. Determinar el estado administrativo u operativo de cada interfaz de clúster.
+
.. Verifique que todos los puertos del clúster sean `up` con un `healthy` estado:
+
`network port show -ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
.. Compruebe que todas las interfaces del clúster (LIF) están en sus puertos de inicio:
+
`network interface show -vserver Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====


. Compruebe que el clúster muestra información de ambos switches de clúster:


[role="tabbed-block"]
====
.ONTAP 9.8 y posteriores
--
A partir de ONTAP 9,8, utilice el comando: `system switch ethernet show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
.ONTAP 9.7 y anteriores
--
Para ONTAP 9,7 y versiones anteriores, utilice el comando: `system cluster-switch show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
====
. [[step5]]Deshabilite la reversión automática en las LIF del clúster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. En el switch de clúster CL2, apague los puertos conectados a los puertos de clúster de los nodos para conmutar las LIF de clúster:
+
[listing, subs="+quotes"]
----
(CL2)# *configure*
(CL2)(Config)# *interface 0/1-0/16*
(CL2)(Interface 0/1-0/16)# *shutdown*
(CL2)(Interface 0/1-0/16)# *exit*
(CL2)(Config)# *exit*
(CL2)#
----
. Compruebe que las LIF del clúster han conmutado al nodo de respaldo a los puertos alojados en el switch del clúster CL1. Esto puede tardar unos segundos.
+
`network interface show -vserver Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0a     false
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0a     false
----
====
. Compruebe que el clúster esté en buen estado:
+
`cluster show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Mueva todos los cables de conexión de nodos de clúster del switch antiguo CL2 al nuevo switch de CS2.
. Confirme el estado de las conexiones de red movidas a CS2:
+
`network port show -ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Todos los puertos de clúster que se han movido deben ser `up`.

. Compruebe la información de cercanía en los puertos de clúster:
+
`network device-discovery show -protocol cdp`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    cs2                       0/1               BES-53248
----
====
. Confirme que las conexiones de puertos del switch sean correctas desde la perspectiva del switch CS2:
+
[listing, subs="+quotes"]
----
cs2# *show port all*
cs2# *show isdp neighbors*
----
. En el switch de clúster CL1, apague los puertos conectados a los puertos de clúster de los nodos para conmutar las LIF de clúster:
+
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/1-0/16*
(CL1)(Interface 0/1-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
+
Todos los LIF del clúster realizan la conmutación al respaldo al switch CS2.

. Compruebe que los LIF de clúster han conmutado al nodo de respaldo a los puertos alojados en el switch CS2. Esto puede tardar unos segundos:
+
`network interface show -vserver Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0b     false
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0b     false
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. Compruebe que el clúster esté en buen estado:
+
`cluster show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. Mueva los cables de conexión de nodo de clúster de CL1 al nuevo switch de CS1.
. Confirme el estado de las conexiones de red movidas a CS1:
+
`network port show -ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
Todos los puertos de clúster que se han movido deben ser `up`.

. Compruebe la información de cercanía en los puertos de clúster:
+
`network device-discovery show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====
. Confirme que las conexiones de puertos del switch sean correctas desde la perspectiva del switch CS1:
+
[listing, subs="+quotes"]
----
cs1# *show port all*
cs1# *show isdp neighbors*
----
. Compruebe que el ISL entre CS1 y CS2 aún está operativo:
+
`show port-channel`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestra que los puertos ISL están *up* en el switch cs1:

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
El siguiente ejemplo muestra que los puertos ISL están *up* en el conmutador cs2:

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Elimine los switches CN1610 sustituidos de la tabla de switches del clúster si no se eliminan automáticamente:


[role="tabbed-block"]
====
.ONTAP 9.8 y posteriores
--
A partir de ONTAP 9,8, utilice el comando: `system switch ethernet delete -device _device-name_`

[listing]
----
cluster::*> system switch ethernet delete -device CL1
cluster::*> system switch ethernet delete -device CL2
----
--
.ONTAP 9.7 y anteriores
--
Para ONTAP 9,7 y versiones anteriores, utilice el comando: `system cluster-switch delete -device _device-name_`

[listing]
----
cluster::*> system cluster-switch delete -device CL1
cluster::*> system cluster-switch delete -device CL2
----
--
====


=== Paso 3: Verificar la configuración

. Habilite la reversión automática en las LIF del clúster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert true*
----
. Compruebe que las LIF del clúster han vuelto a sus puertos raíz (esto puede tardar un minuto):
+
`network interface show -vserver Cluster`

+
Si los LIF del clúster no han cambiado a su puerto de inicio, los revierte manualmente:

+
`network interface revert -vserver Cluster -lif *`

. Compruebe que el clúster esté en buen estado:
+
`cluster show`

. Haga ping en las interfaces de clúster remoto para verificar la conectividad:
+
`cluster ping-cluster -node <name>`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69  node1     e0a
Cluster node1_clus2 169.254.49.125  node1     e0b
Cluster node2_clus1 169.254.47.194  node2     e0a
Cluster node2_clus2 169.254.19.183  node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. Si ha suprimido la creación automática de casos, vuelva a habilitarla invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing, subs="+quotes"]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----


.El futuro
link:../switch-cshm/config-overview.html["Configure la supervisión de estado del switch"].
