---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610, CN1610 replacing, migrate from CN1610 
summary: Para sustituir los switches de clúster CN1610 existentes en un clúster con switches de clúster BES-53248 compatibles con Broadcom, debe realizar una secuencia específica de tareas. 
---
= Migrar switches de clúster CN1610 a switches de clúster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para migrar los switches de clúster CN1610 de un clúster a switches de clúster BES-53248 compatibles con Broadcom, revise los requisitos de migración y siga el procedimiento de migración.

Se admiten los siguientes switches de clúster:

* CN1610
* BES-53248




== Revise los requisitos

Revise la información de configuración, las conexiones de puertos y los requisitos de cableado.



=== Conexiones de nodos

Los switches de clúster admiten las siguientes conexiones de nodo:

* NetApp CN1610: Puertos 0/1 a 0/12 (10 GbE)
* BES-53248: Puertos 0/1-0/16 (10/25 GbE)
+

NOTE: Los puertos adicionales se pueden activar si se compran licencias de puertos.





=== Puertos ISL

Los switches de clúster utilizan los siguientes puertos de enlace entre switches (ISL):

* NetApp CN1610: Puertos 0/13 a 0/16 (10 GbE)
* BES-53248: Puertos 0/55-0/56 (100 GbE)


La https://hwu.netapp.com/Home/Index["_Hardware Universe_ de NetApp"^] Contiene información acerca de la compatibilidad con ONTAP, el firmware EFOS compatible y el cableado para switches de clúster BES-53248.



=== Cableado ISL

El cableado ISL adecuado es el siguiente:

* *Principio:* para CN1610 a CN1610 (SFP+ a SFP+), cuatro cables de conexión directa de cobre o fibra óptica SFP+.
* *Interim:* para CN1610 a BES-53248 (SFP+ a SFP28), cuatro cables de conexión directa de fibra o de cobre óptico SFP+ 10G.
* *Final:* para BES-53248 a BES-53248 (QSFP28 a QSFP28), dos transceptores ópticos QSFP28/fibra o cables de conexión directa de cobre.




== Migrar los switches

Siga este procedimiento para migrar switches de clúster CN1610 a switches de clúster BES-53248.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la nomenclatura de conmutador y nodo siguiente:

* En los ejemplos, se utilizan dos nodos, cada uno de los cuales implementa dos puertos de interconexión de clúster de 10 GbE: `e0a` y.. `e0b`.
* Los resultados del comando pueden variar en función de las diferentes versiones del software ONTAP.
* Los switches CN1610 que se van a sustituir son `CL1` y.. `CL2`.
* Los switches BES-53248 para reemplazar los switches CN1610 son `cs1` y.. `cs2`.
* Los nodos son `node1` y.. `node2`.
* El interruptor CL2 se sustituye primero por cs2, seguido por CL1 por cs1.
* Los switches BES-53248 están precargados con las versiones compatibles de archivo de configuración de referencia (RCF) y SO Ethernet Fabric (EFOS) con cables ISL conectados en los puertos 55 y 56.
* Los nombres de LIF del clúster son `node1_clus1` y.. `node1_clus2` para los nodos 1, y. `node2_clus1` y.. `node2_clus2` para el 2.


.Acerca de esta tarea
Este procedimiento cubre el siguiente caso:

* El clúster comienza con dos nodos conectados a dos switches de clúster CN1610.
* El conmutador CN1610 CL2 se sustituye por el conmutador BES-53248 cs2:
+
** Desconecte los cables de todos los puertos del clúster de todos los nodos conectados a CL2 y, a continuación, utilice cables admitidos para volver a conectar los puertos al nuevo switch del clúster cs2.
** Desconecte los cables entre los puertos ISL CL1 y CL2 y, a continuación, utilice los cables admitidos para volver a conectar los puertos de CL1 a cs2.


* El conmutador CN1610 CL1 se sustituye por el conmutador BES-53248 cs1:
+
** Desconecte los cables de todos los puertos del clúster de todos los nodos conectados a CL1 y, a continuación, utilice cables admitidos para volver a conectar los puertos al nuevo switch del clúster cs1.
** Desconecte los cables entre los puertos ISL CL1 y cs2 y, a continuación, utilice los cables admitidos para volver a conectar los puertos de cs1 a cs2.






=== Paso 1: Preparación para la migración

. Si se habilita AutoSupport en este clúster, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
donde x es la duración de la ventana de mantenimiento en horas.

+

NOTE: El mensaje de AutoSupport notifica al soporte técnico de esta tarea de mantenimiento para que la creación automática de casos se suprima durante la ventana de mantenimiento.

+
El siguiente comando suprime la creación automática de casos durante dos horas:

+
[listing]
----
cluster1::*> system node autosupport invoke -node \* -type all -message MAINT=2h
----
. Cambie el nivel de privilegio a avanzado, introduciendo *y* cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el mensaje avanzado (*>).

. Compruebe que la reversión automática está habilitada en todas las LIF del clúster:
+
`network interface show -vserver Cluster -fields auto-revert`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
----
====
. Muestra información sobre los dispositivos de la configuración:
+
`network device-discovery show -protocol cdp`

+
.Muestra el ejemplo
[%collapsible]
====
El ejemplo siguiente muestra cuántas interfaces de interconexión de clúster se han configurado en cada nodo para cada switch de interconexión de clúster:

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL2                       0/2               CN1610
            e0b    CL1                       0/2               CN1610
node1      /cdp
            e0a    CL2                       0/1               CN1610
            e0b    CL1                       0/1               CN1610
----
====
. Determinar el estado administrativo u operativo de cada interfaz de clúster.
+
.. Muestre los atributos de puerto de red del clúster:
+
`network port show -ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
.. Mostrar información acerca de las interfaces lógicas:
+
`network interface show -vserver Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====


. Compruebe que las licencias de puerto, RCF e imagen EFOS adecuados están instaladas en los nuevos conmutadores BES-53248 según sea necesario para sus requisitos, y realice cualquier personalización esencial del sitio, como usuarios y contraseñas, direcciones de red, etc.
. Hacer ping en las interfaces de clúster remoto:
+
`cluster ping-cluster -node node-name`

+
.Muestra el ejemplo
[%collapsible]
====
En el ejemplo siguiente se muestra cómo hacer ping a las interfaces de clúster remoto:

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69  node1     e0a
Cluster node1_clus2 169.254.49.125  node1     e0b
Cluster node2_clus1 169.254.47.194  node2     e0a
Cluster node2_clus2 169.254.19.183  node2     e0b

Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)

RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====




=== Paso 2: Configure los puertos y el cableado

. Apague los puertos ISL 13 a 16 en el switch CN1610 activo CL1:
+
`shutdown`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo, se muestra cómo apagar los puertos ISL 13 a 16 en el switch CN1610 CL1:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16*
(CL1)(Interface 0/13-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Cree un ISL temporal entre CN1610 CL1 y BES-53248 cs2 nuevos. El ISL se define únicamente en cs2, ya que el ISL existente en CL1 se puede reutilizar.
+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se crea un ISL temporal en cs2 (puertos 13-16) que se conecta al ISL existente en CL1 (puertos 13-16).

[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2) (Config)# *port-channel name 1/2 temp-isl-cn1610*
(cs2) (Config)# *interface 0/13-0/16*
(cs2) (Interface 0/13-0/16)# *no spanning-tree edgeport*
(cs2) (Interface 0/13-0/16)# *addport 1/2*
(cs2) (Interface 0/13-0/16)# *exit*
(cs2) (Config)# *interface lag 2*
(cs2) (Interface lag 2)# *mtu 9216*
(cs2) (Interface lag 2)# *port-channel load-balance 7*
(cs2) (Config)# *exit*

(cs2)# *show port-channel 1/2*
Local Interface................................ 1/2
Channel Name................................... temp-isl-cn1610
Link State..................................... Down
Admin Mode..................................... Enabled
Type........................................... Static
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr     Device/        Port      Port
Ports   Timeout        Speed     Active
------- -------------- --------- -------
0/13    actor/long     10G Full  False
        partner/long
0/14    actor/long     10G Full  False
        partner/long
0/15    actor/long     10G Full  False
        partner/long
0/16    actor/long     10G Full  False
        partner/long
----
====
. En todos los nodos, quite los cables conectados al conmutador CL2 CN1610.
+
A continuación, debe volver a conectar los puertos desconectados de todos los nodos al nuevo conmutador BES-53248 cs2. Consulte la https://hwu.netapp.com/Home/Index["_Hardware Universe_ de NetApp"^] para ver las opciones de cableado aprobadas.

. Quite cuatro cables ISL de los puertos 13 a 16 en el conmutador CL2 CN1610.
+
Debe conectar el cableado autorizado adecuado al puerto de conexión 0/13 a 0/16 en el nuevo conmutador BES-53248 cs2, a los puertos 13 a 16 del conmutador CN1610 existente CL1.

. Traiga ISL 13 a 16 en el conmutador CL1 CN1610 activo.
+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestra el proceso de puesta en marcha de los puertos ISL 13 a 16 en CL1:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16*
(CL1)(Interface 0/13-0/16,3/1)# *no shutdown*
(CL1)(Interface 0/13-0/16,3/1)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Verifique que los ISL estén "up" en el switch CN1610 CL1:
+
`show port-channel`

+
La `Link State` Debe ser "arriba", `Type` Debe ser "estático", y. `Port Active` Debe ser "True" en los puertos 0/13 a 0/16:

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(CL2)# *show port-channel 3/1*
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7


(Enhanced hashing mode)
Mbr      Device/        Port        Port
Ports    Timeout        Speed       Active
-------- -------------- ----------- --------
0/13     actor/long     10 Gb Full  True
         partner/long
0/14     actor/long     10 Gb Full  True
         partner/long
0/15     actor/long     10 Gb Full  True
         partner/long
0/16     actor/long     10 Gb Full  True
         partner/long
----
====
. Compruebe que los puertos ISL están activos en el switch BES-53248:
+
`show port-channel`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/2*

Local Interface................................ 1/2
Channel Name................................... temp-isl-cn1610
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Port-channel Min-links......................... 1
Load Balance Option............................ 7

(Src/Dest MAC, VLAN, EType, incoming port)

Mbr     Device/       Port      Port
Ports   Timeout       Speed     Active
------- ------------- --------- -------
0/13    actor/long    10G Full  True
        partner/long
0/14    actor/long    10G Full  True
        partner/long
0/15    actor/long    10G Full  True
        partner/long
0/16    actor/long    10G Full  True
        partner/long
----
====
. Compruebe que todos los puertos de interconexión de clúster se hayan revertido a sus puertos principales:
+
`network interface show -vserver Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. Compruebe que todos los puertos del clúster estén conectados:
+
`network port show -ipspace Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestra el resultado del comando anterior, comprobando que todas las interconexiones del clúster están en funcionamiento:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. Hacer ping en las interfaces de clúster remoto:
+
`cluster ping-cluster -node _node-name_`

+
.Muestra el ejemplo
[%collapsible]
====
En el ejemplo siguiente se muestra cómo hacer ping a las interfaces de clúster remoto:

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69  node1     e0a
Cluster node1_clus2 169.254.49.125  node1     e0b
Cluster node2_clus1 169.254.47.194  node2     e0a
Cluster node2_clus2 169.254.19.183  node2     eob
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. En todos los nodos, quite los cables conectados al conmutador CL1 CN1610.
+
A continuación, debe volver a conectar los puertos desconectados de todos los nodos al nuevo conmutador BES-53248 cs1. Consulte la https://hwu.netapp.com/Home/Index["_Hardware Universe_ de NetApp"^] para ver las opciones de cableado aprobadas.

. Quite cuatro cables ISL de los puertos 13 a 16 en el switch BES-53248 cs2.
. Retire el canal de puerto temporal 2 de cs2.
+
.Muestra el ejemplo
[%collapsible]
====
En el ejemplo siguiente se quita Port-Channel 2 y se copia el archivo de configuración de ejecución en el archivo de configuración de inicio:

[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2) (Config)# *deleteport 1/2 all*
(cs2) (Config)# *interface 0/13-0/16*
(cs2) (Interface 0/13-0/16)# *spanning-tree edgeport*
​​​​​(cs2) (Interface 0/13-0/16)# *exit*
(cs2) (Config)# *exit*
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully .
----
====
. Compruebe el estado del puerto del nodo del clúster:
+
`network port show -ipspace Cluster`

+
En el siguiente ejemplo, se verifica que todos los puertos de interconexión del clúster en los nodos 1 y 2 `up`:

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====




=== Paso 3: Verificar la configuración

. Compruebe que la interfaz se encuentra ahora en casa:
+
`network interface show -vserver Cluster`

+
.Muestra el ejemplo
[%collapsible]
====
En el ejemplo siguiente se muestra el estado de las interfaces de interconexión de clúster son `up` y.. `Is home` para 1 y 2:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current   Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node      Port    Home
----------- ------------ ---------- ------------------ --------- ------- ------
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1     e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1     e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2     e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2     e0b     true
----
====
. Haga ping a las interfaces remotas del clúster y, a continuación, realice una comprobación del servidor de llamadas de procedimiento remoto:
+
`cluster ping-cluster -node _node-name_`

+
.Muestra el ejemplo
[%collapsible]
====
En el ejemplo siguiente se muestra cómo hacer ping a las interfaces de clúster remoto:

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69  node1     e0a
Cluster node1_clus2 169.254.49.125  node1     e0b
Cluster node2_clus1 169.254.47.194  node2     e0a
Cluster node2_clus2 169.254.19.183  node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. Muestra la información sobre los dispositivos de la configuración:
+
`network device-discovery show -protocol cdp`

+
.Muestra el ejemplo
[%collapsible]
====
Los siguientes ejemplos muestran los nodos 1 y 2 se han migrado de CN1610 CL2 y CL1 a BES-53248 cs2 y cs1:

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs2                       0/1               BES-53248
            e0b    cs1                       0/1               BES-53248
node2      /cdp
            e0a    cs2                       0/2               BES-53248
            e0b    cs1                       0/2               BES-53248
----
====
. Extraiga los interruptores CN1610 sustituidos si no se retiran automáticamente:
+
`system cluster-switch delete -device _device-name_`

+
.Muestra el ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo quitar los switches CN1610:

[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch delete –device CL2*
cluster::*> *system cluster-switch delete –device CL1*
----
====
. Si ha suprimido la creación automática de casos, vuelva a habilitarla invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing, subs="+quotes"]
----
cluster::*> *system node autosupport invoke -node \* -type all -message MAINT=END*
----


.El futuro
Una vez finalizada la migración, es posible que tenga que instalar el archivo de configuración necesario para admitir el Monitor de estado del conmutador de clúster (CSHM) para los switches de clúster BES-53248. Consulte link:configure-health-monitor.html["Instale el archivo de configuración del Monitor de estado del conmutador de clúster (CSHM)"] y.. link:configure-log-collection.html["Habilite la función de recogida de registros"].
