---
permalink: switch-bes-53248/replace-verify.html 
sidebar: sidebar 
keywords: command, verify, operational, bes, cluster, switch, upgrade, verify the configuration after a cluster switch upgrade - bes-53428 switches 
summary: Puede utilizar los comandos proporcionados aquí para verificar que todo esté operativo después de una actualización del conmutador de clúster BES-53248. 
---
= Verifique la red del clúster ONTAP después de una actualización del software EFOS o RCF de los conmutadores del clúster BES-53248.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar los siguientes comandos para verificar el estado de la red del clúster ONTAP después de una actualización del software EFOS o RCF para los conmutadores de clúster BES-53248.

.Pasos
. Muestra información sobre los puertos de red del clúster mediante el siguiente comando:
+
[source, cli]
----
network port show -ipspace Cluster
----
+
`Link`debe tener el valor `up` y `Health Status` debe ser `healthy` .

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra el resultado del comando:

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. Para cada LIF, verifique que `Is Home` es `true` y `Status Admin/Oper` es `up` en ambos nodos, utilizando el comando:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.217.125/16 node1         e0a     true
            node1_clus2  up/up    169.254.205.88/16  node1         e0b     true
            node2_clus1  up/up    169.254.252.125/16 node2         e0a     true
            node2_clus2  up/up    169.254.110.131/16 node2         e0b     true
----
====
. Verifique que el `Health Status` de cada nodo es `true` usando el comando:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====


.¿Que sigue?
Una vez que haya confirmado la actualización de su software EFOS o RCF, podrá link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
