---
permalink: switch-bes-53248/required-documentation-bes53248.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: Necesitas documentación específica del switch y del controlador para configurar tu modo clúster. 
---
= Requisitos de documentación para los conmutadores de clúster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación del switch BES-53248, asegúrate de revisar la documentación específica del switch y del controlador.



== Documentación de Broadcom

Para configurar el switch de clúster BES-53248, necesitas los siguientes documentos disponibles en el Broadcom Support Site: link:https://www.broadcom.com/support/bes-switch["Línea de productos de conmutadores Ethernet de Broadcom"^].

[cols="1,2"]
|===
| Título del documento | Descripción 


 a| 
_Guía del administrador de EFOS v3.4.3_
 a| 
Proporciona ejemplos de cómo utilizar el switch BES-53248 en una red típica.



 a| 
_Referencia de comandos de la CLI de EFOS v3.4.3_
 a| 
Describe los comandos de la interfaz de línea de comandos (CLI) que se utilizan para ver y configurar el software BES-53248.



 a| 
_Guía de inicio rápido de EFOS v3.4.3_
 a| 
Proporciona información detallada sobre el conmutador BES-53248.



 a| 
_Guía de referencia SNMP de EFOS v3.4.3_
 a| 
Proporciona ejemplos de cómo utilizar el switch BES-53248 en una red típica.



 a| 
_Parámetros y valores de escalado de EFOS v3.4.3_
 a| 
Describe los parámetros de escalado predeterminados con los que se entrega y valida el software EFOS en las plataformas compatibles.



 a| 
_Especificaciones funcionales de EFOS v3.4.3_
 a| 
Describe las especificaciones del software EFOS en las plataformas compatibles.



 a| 
_Notas de la versión 3.4.3 de EFOS_
 a| 
Proporciona información específica de la versión del software BES-53248.



 a| 
_Matriz de compatibilidad de redes de clúster y redes de administración_
 a| 
Proporciona información sobre la compatibilidad de red. La matriz está disponible en el sitio de descargas del switch BES-53248 en link:https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["conmutadores de clúster Broadcom"^].

|===


== Documentación de sistemas ONTAP y artículos de la base de conocimientos

Para configurar un sistema ONTAP, necesitas los siguientes documentos del sitio de soporte de NetApp en link:http://mysupport.netapp.com/["mysupport.netapp.com"^] o del sitio de la base de conocimientos (KB) en link:https://kb.netapp.com/["kb.netapp.com"^].

[cols="1,2"]
|===
| Nombre | Descripción 


 a| 
https://hwu.netapp.com/Home/Index["Hardware Universe"^]
 a| 
Describe los requisitos de alimentación y emplazamiento para todo el hardware de NetApp , incluidos los armarios del sistema, y ​​proporciona información sobre los conectores y opciones de cable pertinentes que se deben utilizar junto con sus números de pieza.



 a| 
Instrucciones de instalación y configuración específicas del controlador
 a| 
Describe cómo instalar el hardware de NetApp .



 a| 
link:https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^]
 a| 
Proporciona información detallada sobre todos los aspectos de la versión ONTAP 9.



 a| 
_Cómo agregar licencias de puertos adicionales para el switch BES-53248 compatible con Broadcom_
 a| 
Proporciona información detallada sobre cómo agregar licencias de puertos. Consulta este link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["Artículo de la base de conocimientos"^].

|===