---
permalink: switch-bes-53248/required-documentation-bes53248.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: Necesita documentación específica sobre los switches y la controladora para configurar la configuración de Cluster-Mode. 
---
= Requisitos de documentación para los switches de clúster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y mantenimiento del conmutador BES-53248, asegúrese de revisar la documentación específica del conmutador y del controlador.



== Documentación de Broadcom

Para configurar el switch de clúster BES-53248, necesita los siguientes documentos disponibles en el sitio de soporte de Broadcom: https://["Línea de producto de conmutador Ethernet Broadcom"^]

[cols="1,2"]
|===
| Título del documento | Descripción 


 a| 
_EFOS Guía del administrador v3.4.3_
 a| 
Proporciona ejemplos de cómo utilizar el conmutador BES-53248 en una red típica.



 a| 
_Referencia de comandos de la CLI del EFOS v3.4.3_
 a| 
Describe los comandos de la interfaz de línea de comandos (CLI) que utiliza para ver y configurar el software BES-53248.



 a| 
_Guía de puesta en marcha del EFOS v3.4.3_
 a| 
Proporciona información detallada acerca del conmutador BES-53248.



 a| 
_EFOS SNMP Reference Guide v3.4.3_
 a| 
Proporciona ejemplos de cómo utilizar el conmutador BES-53248 en una red típica.



 a| 
_EFOS escala parámetros y valores v3.4.3_
 a| 
Describe los parámetros de escala predeterminados con los que se suministra y valida el software EFOS en las plataformas compatibles.



 a| 
_EFOS Especificaciones funcionales v3.4.3_
 a| 
Describe las especificaciones del software EFOS en las plataformas compatibles.



 a| 
_Notas de publicación de EFOS v3.4.3_
 a| 
Proporciona información específica de la versión sobre el software BES-53248.



 a| 
_Matriz de compatibilidad de redes de administración y redes de clúster_
 a| 
Proporciona información sobre la compatibilidad de red. La matriz está disponible en el sitio de descarga del conmutador BES-53248 en https://["Switches de clúster Broadcom"^].

|===


== Documentación de los sistemas ONTAP y artículos de la base de conocimientos

Para configurar un sistema ONTAP, necesita los siguientes documentos en el sitio de soporte de NetApp en http://["mysupport.netapp.com"^] O el sitio de la base de conocimientos (KB) en https://["kb.netapp.com"^].

[cols="1,2"]
|===
| Nombre | Descripción 


 a| 
https://["Hardware Universe de NetApp"^]
 a| 
Describe los requisitos de alimentación y del sitio para todo el hardware de NetApp, incluidos los armarios de sistema, y proporciona información sobre los conectores y las opciones de cables relevantes que se deben usar junto con sus números de pieza.



 a| 
Específicos del controlador _instrucciones de instalación y configuración_
 a| 
Describe cómo instalar el hardware de NetApp.



 a| 
ONTAP 9
 a| 
Proporciona información detallada sobre todos los aspectos de la versión 9 de ONTAP.



 a| 
_Cómo añadir licencias de puerto adicionales para el conmutador BES-53248 compatible con Broadcom_
 a| 
Proporciona información detallada sobre cómo agregar licencias de puerto. Vaya a la https://["Artículo de base de conocimientos"^].

|===