---
permalink: switch-bes-53248/reset-switch-bes-53248.html 
sidebar: sidebar 
keywords: BES-53248 reset switch to factory defaults, BES-53248 switches configuration, efos 
summary: Antes de configurar su switch Broadcom BES-53248, revise la siguiente información. 
---
= Restablecer el interruptor del clúster BES-53248 a los valores predeterminados de fábrica
:allow-uri-read: 


[role="lead"]
Para restablecer el interruptor del clúster BES-53248 a los valores predeterminados de fábrica, debe borrar la configuración del interruptor BES-53248.

.Acerca de esta tarea
* Debes estar conectado al switch mediante la consola serie.
* Esta tarea restablece la configuración de la red de administración.


.Pasos
. Cambie al símbolo del sistema con privilegios elevados.
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)#
----
. Borre la configuración de inicio.
+
`erase startup-config`

+
[listing, subs="+quotes"]
----
(cs2)# *erase startup-config*

Are you sure you want to clear the configuration? (y/n) *y*
----
. Reinicia el switch.
+
[listing, subs="+quotes"]
----
(cs2)# *reload*
Are you sure you would like to reset the system? (y/n) *y*
----



NOTE: Si el sistema pregunta si desea guardar la configuración no guardada o modificada antes de reiniciar el switch, seleccione *No*.

. [[step4]] Espere a que el switch se recargue y luego inicie sesión en el switch.
+
El usuario predeterminado es “admin” y no se ha establecido ninguna contraseña.  Se muestra un mensaje similar al siguiente:

+
[listing]
----
(Routing)>
----

