---
permalink: switch-bes-53248/upgrade-switch-overview.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch 
summary: Antes de configurar conmutadores de clúster BES-53248, revise una descripción general del proceso y la nomenclatura. 
---
= Descripción general del proceso de actualización de los switches de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos pasos para actualizar el software EFOS y los archivos de configuración de referencia (RCF) en los switches de cluster Broadcom BES-54328, según corresponda.

. link:upgrade-efos-software.html["Actualice su versión de EFOS"]
+
Descargue e instale el software Ethernet Fabric OS (EFOS) en el switch de clúster BES-53248.

. link:upgrade-rcf.html["Actualice su versión de RCF"]
+
Actualice el RCF en el switch de clúster BES-53248 y, a continuación, verifique los puertos para obtener una licencia adicional después de aplicar el RCF.

. link:replace-verify.html["Compruebe la red del clúster de ONTAP después de actualizar"]
+
Compruebe el estado de la red de cluster ONTAP después de actualizar el software de EFOS o RCF para los switches de cluster BES-53248.


