---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: 'Siga estos pasos para actualizar el software Ethernet Fabric OS (EFOS) en el conmutador de clúster BES-53248.' 
---
= Actualizar el software EFOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos pasos para actualizar el software EFOS en el conmutador de clúster BES-53248.

El software EFOS incluye un conjunto de funciones y protocolos de red avanzados para el desarrollo de sistemas de infraestructura Ethernet e IP.  Esta arquitectura de software es adecuada para cualquier dispositivo de organización de red que utilice aplicaciones que requieran una inspección o separación exhaustiva de paquetes.



== Prepárate para la actualización

.Antes de empezar
* Descargue el software Broadcom EFOS correspondiente a sus conmutadores de clúster desde https://www.broadcom.com/support/bes-switch["Compatibilidad con conmutadores Ethernet Broadcom"^] sitio.
* Revise las siguientes notas relativas a las versiones de EFOS.


[]
====
*Tenga en cuenta lo siguiente:*

* Al actualizar de EFOS 3.4.xx a EFOS 3.7.xx o posterior, el switch debe estar ejecutando EFOS 3.4.4.6 (o una versión 3.4.xx posterior).  Si está ejecutando una versión anterior a esa, actualice primero el switch a EFOS 3.4.4.6 (o una versión 3.4.xx posterior) y luego actualice el switch a EFOS 3.7.xx o posterior.
* La configuración para EFOS 3.4.xx y 3.7.xx o posterior es diferente.  Cambiar la versión de EFOS de 3.4.xx a 3.7.xx o posterior, o viceversa, requiere que el switch se restablezca a los valores predeterminados de fábrica y que se (re)apliquen los archivos RCF para la versión de EFOS correspondiente.  Este procedimiento requiere acceso a través del puerto de consola serie.
* A partir de la versión 3.7.xx de EFOS o posterior, está disponible una versión no compatible con FIPS y una versión compatible con FIPS.  Se aplican pasos diferentes al pasar de una versión no compatible con FIPS a una versión compatible con FIPS o viceversa.  Cambiar la versión de EFOS de una versión no compatible con FIPS a una versión compatible con FIPS o viceversa restablecerá el switch a los valores predeterminados de fábrica.  Este procedimiento requiere acceso a través del puerto de consola serie.


====
|===


| *Procedimiento* | *Versión actual de EFOS * | *Nueva versión de EFOS* | *Pasos de alto nivel* 


 a| 
Pasos para actualizar EFOS entre dos versiones (no) compatibles con FIPS
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
Actualizar la nueva imagen EFOS usando<<Método 1: Actualizar EFOS>> .  La información de configuración y licencia se conserva.



 a| 
3.4.4.6 (o posterior 3.4.xx)
 a| 
Versión 3.7.xx o posterior no compatible con FIPS
 a| 
Actualizar EFOS usando<<Método 1: Actualizar EFOS>> .  Restablezca el switch a los valores predeterminados de fábrica y aplique el archivo RCF para EFOS 3.7.xx o posterior.



.2+| Versión 3.7.xx o posterior no compatible con FIPS  a| 
3.4.4.6 (o posterior 3.4.xx)
 a| 
Reduzca la versión de EFOS utilizando<<Método 1: Actualizar EFOS>> .  Restablezca el switch a los valores predeterminados de fábrica y aplique el archivo RCF para EFOS 3.4.xx



 a| 
Versión 3.7.xx o posterior no compatible con FIPS
 a| 
Actualizar la nueva imagen EFOS usando<<Método 1: Actualizar EFOS>> .  La información de configuración y licencia se conserva.



 a| 
3.7.xx o posterior compatible con FIPS
 a| 
3.7.xx o posterior compatible con FIPS
 a| 
Actualizar la nueva imagen EFOS usando<<Método 1: Actualizar EFOS>> .  La información de configuración y licencia se conserva.



 a| 
Pasos para actualizar a/desde una versión EFOS compatible con FIPS
 a| 
No cumple con la norma FIPS
 a| 
Cumple con la norma FIPS
 a| 
Actualización de la imagen EFOS mediante<<Método 2: Actualizar EFOS mediante la instalación de ONIE OS>> .  Se perderá la configuración del switch y la información de la licencia.



 a| 
Cumple con la norma FIPS
 a| 
No cumple con la norma FIPS

|===
[IMPORTANT]
====
Para comprobar si su versión de EFOS cumple o no con la normativa FIPS, utilice la siguiente herramienta: `show fips status` dominio.  En los siguientes ejemplos, *IP_switch_a1* utiliza EFOS compatible con FIPS y *IP_switch_a2* utiliza EFOS no compatible con FIPS.

* En el conmutador IP_switch_a1 (EFOS compatible con FIPS):
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* En el conmutador IP_switch_a2 (EFOS no compatible con FIPS):
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== Actualiza el software

Utilice uno de los siguientes métodos:

* <<Método 1: Actualizar EFOS>>. Utilizar en la mayoría de los casos (véase la tabla anterior).
* <<Método 2: Actualizar EFOS mediante la instalación de ONIE OS>>. Utilizar si una versión de EFOS cumple con la norma FIPS y la otra no.



NOTE: Actualice EFOS en un conmutador a la vez para garantizar el funcionamiento continuo de la red del clúster.



=== Método 1: Actualizar EFOS

Siga los siguientes pasos para actualizar el software EFOS.


IMPORTANT: Tenga en cuenta que después de actualizar los conmutadores de clúster BES-53248 de EFOS 3.3.xx o 3.4.xx a EFOS 3.7.0.4 o 3.8.0.2, los enlaces entre conmutadores (ISL) y los canales de puerto se marcan en el estado *Inactivo*.  Este es el comportamiento esperado y puede continuar con la actualización sin problemas, a menos que tenga problemas con la reversión automática de LIF.  Consulte el artículo de la base de conocimientos: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["El switch de clúster BES-53248 NDU no se actualizó a EFOS 3.7.0.4 ni a versiones posteriores."^] Para obtener más detalles.

.Pasos
. Conecte el conmutador de clúster BES-53248 a la red de administración.
. Utilice el `ping` comando para verificar la conectividad con el servidor que aloja EFOS, las licencias y el archivo RCF.
+
Este ejemplo verifica que el switch está conectado al servidor en la dirección IP 172.19.2.1:

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Desactive la reversión automática en los LIF del clúster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Muestra las imágenes de arranque para la configuración activa y de respaldo:
+
`show bootvar`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6              3.7.0.4        3.7.0.4

----
====
. Descarga el archivo de imagen al switch.
+
Copiar el archivo de imagen a la imagen de respaldo significa que cuando reinicia, esa imagen establece la versión de EFOS en ejecución, completando la actualización.

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk backup*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. Muestra las imágenes de arranque para la configuración activa y de respaldo:
+
`show bootvar`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4    3.7.0.4             3.7.0.4       3.10.0.3
----
====
. Inicie el sistema desde la configuración de respaldo:
+
`boot system backup`

+
[listing, subs="+quotes"]
----
(cs2)# *boot system backup*
Activating image backup ..
----
. Muestra las imágenes de arranque para la configuración activa y de respaldo:
+
`show bootvar`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1    3.10.0.3    3.10.0.3            3.10.0.3       3.10.0.3
----
====
. Guarde la configuración en ejecución en la configuración de inicio:
+
`write memory`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.

Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. Reinicia el switch:
+
`reload`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. Vuelva a iniciar sesión y verifique la nueva versión del software EFOS:
+
`show version`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Repita los pasos 5 a 11 en el interruptor cs1.
. Habilitar la reversión automática en los LIF del clúster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Verifique que los LIF del clúster hayan vuelto a su puerto de origen:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
Para obtener más detalles, consultelink:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Revierte un LIF a su puerto de origen"] .





=== Método 2: Actualizar EFOS mediante la instalación de ONIE OS

Puede realizar los siguientes pasos si una versión de EFOS cumple con FIPS y la otra no cumple con FIPS.  Estos pasos se pueden utilizar para actualizar la imagen EFOS 3.7.xx no compatible con FIPS o compatible con FIPS desde ONIE si el switch no arranca.


NOTE: Esta funcionalidad solo está disponible para EFOS 3.7.xx o posterior que no cumpla con FIPS.


CAUTION: Si actualiza EFOS utilizando la instalación de ONIE OS, la configuración se restablece a los valores predeterminados de fábrica y las licencias se eliminan.  Debe configurar el switch e instalar las licencias y un RCF compatible para que el switch vuelva a funcionar con normalidad.

.Pasos
. Desactive la reversión automática en los LIF del clúster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Inicie el switch en modo de instalación ONIE.
+
Durante el arranque, seleccione ONIE cuando vea el indicador:

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Después de seleccionar *ONIE*, el interruptor se carga y le presenta varias opciones.  Seleccione *Instalar sistema operativo*.

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
El switch arranca en modo de instalación ONIE.

. Detenga la detección ONIE y configure la interfaz Ethernet.
+
Cuando aparezca el siguiente mensaje, pulse *Enter* para abrir la consola ONIE:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: La detección ONIE continúa y se imprimen mensajes en la consola.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configure la interfaz Ethernet y agregue la ruta usando `ifconfig eth0 <ipAddress> netmask <netmask> up` y `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Verifique que el servidor que aloja el archivo de instalación de ONIE sea accesible:
+
`ping`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Instala el nuevo software del switch:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
El software se instala y luego reinicia el switch.  Deje que el switch se reinicie normalmente en la nueva versión de EFOS.

. Verifique que el nuevo software del switch esté instalado:
+
`show bootvar`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. Finalice la instalación.  El switch se reinicia sin ninguna configuración aplicada y se restablece a los valores predeterminados de fábrica.  Complete los siguientes pasos para reconfigurar el conmutador:
+
.. link:configure-licenses.html["Instalar licencias"]
.. link:configure-install-rcf.html["Instala el RCF"]
.. link:configure-ssh.html["Habilitar SSH"]
.. link:CSHM_log_collection.html["Habilitar la recopilación de registros"]
.. link:CSHM_snmpv3.html["Configure SNMPv3 para la monitorización"]


. Repita los pasos 2 a 8 en el interruptor cs1.
. Habilitar la reversión automática en los LIF del clúster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Verifique que los LIF del clúster hayan vuelto a su puerto de origen:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
Para obtener más detalles, consultelink:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Revierte un LIF a su puerto de origen"] .


