---
permalink: switch-cisco-3132q-v/cn1610-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Antes de configurar los switches Cisco Nexus 3132q-v, revise una descripción general del proceso y la nomenclatura. 
---
= Requisitos de migración
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Los conmutadores Cisco Nexus 3132Q-V se pueden utilizar como conmutadores de clúster en su clúster AFF o FAS . Los conmutadores de clúster le permiten crear clústeres ONTAP con más de dos nodos.

[NOTE]
====
El procedimiento requiere el uso de comandos ONTAP y comandos de switches Cisco Nexus serie 3000; se utilizan comandos ONTAP a menos que se indique lo contrario.

====
Para obtener más información, consulte:

* https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["Página de descripción de NetApp CN1601 y CN1610"^]
* https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Página de descripción del switch Ethernet de Cisco"^]
* http://hwu.netapp.com["Hardware Universe"^]




== Requisitos CN1610

Se admiten los siguientes conmutadores de clúster:

* NetApp CN1610
* Cisco Nexus 3132Q-V


Los conmutadores del clúster admiten las siguientes conexiones de nodo:

* NetApp CN1610: puertos 0/1 a 0/12 (10 GbE)
* Cisco Nexus 3132Q-V: puertos e1/1-30 (40/100 GbE)


Los conmutadores del clúster utilizan los siguientes puertos de enlace entre conmutadores (ISL):

* NetApp CN1610: puertos 0/13 a 0/16 (10 GbE)
* Cisco Nexus 3132Q-V: puertos e1/31-32 (40/100 GbE)
+
Ellink:https://hwu.netapp.com/["Hardware Universe"^] Contiene información sobre el cableado compatible con los switches Nexus 3132Q-V:

* Los nodos con conexiones de clúster de 10 GbE requieren cables de conexión de fibra óptica QSFP a SFP+ o cables de conexión de cobre QSFP a SFP+.
* Los nodos con conexiones de clúster de 40/100 GbE requieren módulos ópticos QSFP/QSFP28 compatibles con cables de fibra óptica o cables de cobre de conexión directa QSFP/QSFP28.


El cableado ISL apropiado es el siguiente:

* Inicio: Para CN1610 a CN1610 (SFP+ a SFP+), cuatro cables de fibra óptica o cobre de conexión directa SFP+
* Provisional: Para CN1610 a Nexus 3132Q-V (QSFP a cuatro SFP+ breakout), un cable de fibra óptica o cobre QSFP a SFP+ breakout
* Final: Para Nexus 3132Q-V a Nexus 3132Q-V (QSFP28 a QSFP28), dos cables de fibra óptica o cobre de conexión directa QSFP28


Los cables twinax de NetApp no ​​son compatibles con los switches Cisco Nexus 3132Q-V.

Si su configuración actual de CN1610 utiliza cables twinax de NetApp para conexiones de nodo de clúster a conmutador o conexiones ISL y desea continuar utilizando twinax en su entorno, necesita adquirir cables twinax de Cisco .  Como alternativa, puede utilizar cables de fibra óptica tanto para las conexiones ISL como para las conexiones entre el nodo del clúster y el conmutador.

.Acerca de los ejemplos utilizados
Los ejemplos de este procedimiento describen la sustitución de switches CN1610 por switches Cisco Nexus 3132Q-V.  Puedes utilizar estos pasos (con modificaciones) para otros switches Cisco más antiguos.

El procedimiento también utiliza la siguiente nomenclatura de interruptores y nodos:

* Los resultados del comando pueden variar dependiendo de las diferentes versiones de ONTAP.
* Los interruptores CN1610 que se reemplazarán son *CL1* y *CL2*.
* Los switches Nexus 3132Q-V que reemplazan a los switches CN1610 son *C1* y *C2*.
* *n1_clus1* es la primera interfaz lógica de clúster (LIF) conectada al conmutador de clúster 1 (CL1 o C1) para el nodo *n1*.
* *n1_clus2* es el primer LIF de clúster conectado al conmutador de clúster 2 (CL2 o C2) para el nodo *n1*.
* *n1_clus3* es la segunda LIF conectada al conmutador de clúster 2 (CL2 o C2) para el nodo *n1*.
* *n1_clus4* es la segunda LIF conectada al conmutador de clúster 1 (CL1 o C1) para el nodo *n1*.
* El número de puertos 10 GbE y 40/100 GbE se define en los archivos de configuración de referencia (RCF) disponibles en el https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Descarga del archivo de configuración de referencia del switch de red en clúster de Cisco"^] página.
* Los nodos son *n1*, *n2*, *n3* y *n4*.


Los ejemplos de este procedimiento utilizan cuatro nodos:

* Dos nodos utilizan cuatro puertos de interconexión de clúster 10 GbE: *e0a*, *e0b*, *e0c* y *e0d*.
* Los otros dos nodos utilizan dos puertos de interconexión de clúster de 40 GbE: *e4a* y *e4e*.
+
Ellink:https://hwu.netapp.com/["Hardware Universe"^] Enumera los puertos de clúster reales en sus plataformas.



.¿Que sigue?
link:cn5596-prepare-to-migrate.html["Prepárate para la migración"].
