---
permalink: switch-cisco-3132q-v/configure-reqs-3132q.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: Para la instalación y el mantenimiento del switch Cisco Nexus 3132Q-V, asegúrese de revisar los requisitos de red y configuración. 
---
= Requisitos de configuración para los switches Cisco Nexus 3132Q-V
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del switch Cisco Nexus 3132Q-V, asegúrese de revisar los requisitos de red y configuración.



== Requisitos de configuración

Para configurar su clúster, necesita el número y tipo adecuados de cables y conectores de cable para sus conmutadores.  Dependiendo del tipo de switch que esté configurando inicialmente, deberá conectarse al puerto de consola del switch con el cable de consola incluido; también deberá proporcionar información de red específica.



== Requisitos de red

Necesitará la siguiente información de red para todas las configuraciones de conmutadores:

* Subred IP para la gestión del tráfico de red.
* Nombres de host y direcciones IP para cada uno de los controladores del sistema de almacenamiento y todos los conmutadores aplicables.
* La mayoría de los controladores del sistema de almacenamiento se administran a través de la interfaz e0M conectándose al puerto de servicio Ethernet (ícono de llave inglesa). En los sistemas AFF A800 y AFF A700 , la interfaz e0M utiliza un puerto Ethernet dedicado.


Consulte el https://hwu.netapp.com["Hardware Universe"^] Para obtener la información más reciente.

.¿Qué sigue?
Después de revisar los requisitos de configuración, puede revisar link:required-documentation-3132q.html["documentación requerida"].
