---
permalink: switch-cisco-3132q-v/replace-cisco-nexus-3132q-v.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3132q-v cluster switches 
summary: 'La sustitución de un switch Cisco Nexus 3132Q-V defectuoso en una red de clúster es un procedimiento no disruptivo (NDO), y debe realizar una secuencia específica de tareas.' 
---
= Sustituya los switches de clúster Cisco Nexus 3132Q-V.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para sustituir un switch Cisco Nexus 3132Q-V defectuoso en una red de clúster. El procedimiento de sustitución es un procedimiento no disruptivo (NDO).



== Revise los requisitos

.Requisitos de switch
Revise la link:switch-requirements.html["Requisitos para sustituir los switches de clúster Cisco Nexus 3132Q-V."].

.Lo que necesitará
* La configuración de clúster y red existente tiene:
+
** La infraestructura de clúster Nexus 3132Q-V es redundante y completamente funcional en ambos switches.
+
La link:http://support.netapp.com/NOW/download/software/cm_switches/["Switch Ethernet de Cisco"^] Page tiene las últimas versiones RCF y NX-OS en sus switches.

** Todos los puertos del clúster están en la `up` estado.
** La conectividad de gestión existe en ambos switches.
** Todas las interfaces lógicas (LIF) del clúster están en la `up` estado y se han migrado.


* Para el interruptor de sustitución Nexus 3132Q-V, asegúrese de que:
+
** La conectividad de la red de gestión en el switch de reemplazo es funcional.
** El acceso de la consola al interruptor de sustitución está en su lugar.
** El conmutador de imagen del sistema operativo RCF y NX-OS deseado se carga en el conmutador.
** Se ha completado la personalización inicial del conmutador.


* http://hwu.netapp.com["Hardware Universe"^]




== Sustituya el interruptor

Este procedimiento sustituye al segundo interruptor de grupo de Nexus 3132Q-V CL2 con el nuevo interruptor C2 3132Q-V.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la nomenclatura de conmutador y nodo siguiente:

* n1_clus1 es la primera interfaz lógica del clúster (LIF) conectada al switch del clúster C1 para el nodo n1.
* n1_clus2 es la primera LIF del clúster conectada al switch de clúster CL2 o C2 para el nodo n1.
* n1_clus3 es la segunda LIF conectada al switch de clúster C2 para el nodo n1.
* n1_clusal 4 es la segunda LIF conectada al switch de clúster CL1, para el nodo n1.
* El número de puertos 10 GbE y 40/100 GbE se define en los archivos de configuración de referencia (RCF) disponibles en la link:https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Descarga del archivo de configuración de referencia del conmutador de red de clúster Cisco®"^] página.
* Los nodos son n1, n2, n3 y n4. - Los ejemplos de este procedimiento emplean cuatro nodos: Dos nodos utilizan cuatro puertos de interconexión de clúster de 10 GB: E0a, e0b, e0c y e0d. Los otros dos nodos utilizan dos puertos de interconexión de clúster de 40 GB: e4a y e4e. Consulte link:https://hwu.netapp.com/["Hardware Universe"^] para los puertos del clúster reales en las plataformas.


.Acerca de esta tarea
Este procedimiento cubre el siguiente caso:

* El clúster comienza con cuatro nodos conectados a dos switches de cluster Nexus 3132Q-V, CL1 y CL2.
* El switch del clúster CL2 debe ser sustituido por C2
+
** En cada nodo, las LIF de clúster conectadas a CL2 se migran a los puertos del clúster conectados a CL1.
** Desconecte el cableado de todos los puertos del CL2 y vuelva a conectar el cableado a los mismos puertos del conmutador C2 de sustitución.
** En cada nodo, sus LIF de clúster migrados se revierten.






=== Paso 1: Prepararse para la sustitución

. Si se habilita AutoSupport en este clúster, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ es la duración de la ventana de mantenimiento en horas.

+
[NOTE]
====
El mensaje de AutoSupport notifica al soporte técnico de esta tarea de mantenimiento para que la creación automática de casos se suprima durante la ventana de mantenimiento.

====
. Muestra información sobre los dispositivos de la configuración:
+
`network device-discovery show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface         Platform
----------- ------ ------------------- ----------------  ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1/1    N3K-C3132Q-V
            e0b    CL2                 Ethernet1/1/1    N3K-C3132Q-V
            e0c    CL2                 Ethernet1/1/2    N3K-C3132Q-V
            e0d    CL1                 Ethernet1/1/2    N3K-C3132Q-V
n2         /cdp
            e0a    CL1                 Ethernet1/1/3    N3K-C3132Q-V
            e0b    CL2                 Ethernet1/1/3    N3K-C3132Q-V
            e0c    CL2                 Ethernet1/1/4    N3K-C3132Q-V
            e0d    CL1                 Ethernet1/1/4    N3K-C3132Q-V
n3         /cdp
            e4a    CL1                 Ethernet1/7      N3K-C3132Q-V
            e4e    CL2                 Ethernet1/7      N3K-C3132Q-V
n4         /cdp
            e4a    CL1                 Ethernet1/8      N3K-C3132Q-V
            e4e    CL2                 Ethernet1/8      N3K-C3132Q-V

12 entries were displayed
----
====
. Determine el estado administrativo u operativo de cada interfaz de clúster:
+
.. Mostrar los atributos del puerto de red:
+
`network port show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
       (network port show)

Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
12 entries were displayed.
----
====
.. Mostrar información acerca de las interfaces lógicas:
+
`network interface show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
       (network interface show)

             Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e0a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e0e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e0a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e0e     true

12 entries were displayed.
----
====
.. Muestre la información sobre los switches del clúster detectados:
+
`system cluster-switch show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                          cluster-network   10.10.1.101      NX3132V
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

CL2                          cluster-network   10.10.1.102      NX3132V
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====


. Compruebe que el RCF y la imagen adecuados están instalados en el nuevo switch Nexus 3132Q-V, según sea necesario, y realice las personalizaciones esenciales del sitio.
+
Debe preparar el interruptor de sustitución en este momento. Si necesita actualizar el RCF y la imagen, debe seguir estos pasos:

+
.. En el sitio de soporte de NetApp, vaya a link:http://support.netapp.com/NOW/download/software/cm_switches/["Switch Ethernet de Cisco"^] página.
.. Anote el conmutador y las versiones de software necesarias en la tabla de esa página.
.. Descargue la versión adecuada del RCF.
.. Haga clic en *CONTINUAR* en la página *Descripción*, acepte el contrato de licencia y, a continuación, siga las instrucciones de la página *Descargar* para descargar el RCF.
.. Descargue la versión adecuada del software Image.


. Migre las LIF asociadas a los puertos del clúster conectados al switch C2:
+
`network interface migrate`

+
.Muestra el ejemplo
[%collapsible]
====
Este ejemplo muestra que la migración LIF se realiza en todos los nodos:

[listing]
----

cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 –destination-node n1 -destination-port e0a
cluster::*> network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 –destination-node n1 -destination-port e0d
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 –destination-node n2 -destination-port e0a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 –destination-node n2 -destination-port e0d
cluster::*> network interface migrate -vserver Cluster -lif n3_clus2 -source-node n3 –destination-node n3 -destination-port e4a
cluster::*> network interface migrate -vserver Cluster -lif n4_clus2 -source-node n4 –destination-node n4 -destination-port e4a
----
====
. Compruebe el estado del clúster:
+
`network interface show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
       (network interface show)

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4a     false
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4a     false
12 entries were displayed.
----
====
. Apague los puertos de interconexión de clúster que estén conectados físicamente al switch CL2:
+
`network port modify`

+
.Muestra el ejemplo
[%collapsible]
====
En este ejemplo, se muestran los puertos especificados que se están apagando en todos los nodos:

[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin false
cluster::*> network port modify -node n1 -port e0c -up-admin false
cluster::*> network port modify -node n2 -port e0b -up-admin false
cluster::*> network port modify -node n2 -port e0c -up-admin false
cluster::*> network port modify -node n3 -port e4e -up-admin false
cluster::*> network port modify -node n4 -port e4e -up-admin false
----
====
. Hacer ping a las interfaces remotas del clúster y realizar una comprobación del servidor RPC:
+
`cluster ping-cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e0a	10.10.0.1
Cluster n1_clus2 n1		e0b	10.10.0.2
Cluster n1_clus3 n1		e0c	10.10.0.3
Cluster n1_clus4 n1		e0d	10.10.0.4
Cluster n2_clus1 n2		e0a	10.10.0.5
Cluster n2_clus2 n2		e0b	10.10.0.6
Cluster n2_clus3 n2		e0c	10.10.0.7
Cluster n2_clus4 n2		e0d	10.10.0.8
Cluster n3_clus1 n4		e0a	10.10.0.9
Cluster n3_clus2 n3		e0e	10.10.0.10
Cluster n4_clus1 n4		e0a	10.10.0.11
Cluster n4_clus2 n4		e0e	10.10.0.12

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11 10.10.0.12
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12

Larger than PMTU communication succeeds on 32 path(s)
RPC status:
8 paths up, 0 paths down (tcp check)
8 paths up, 0 paths down (udp check)
----
====
. Apague los puertos 1/31 y 1/32 de CL1 y el interruptor Nexus 3132Q-V activo:
+
`shutdown`

+
.Muestra el ejemplo
[%collapsible]
====
En este ejemplo, se muestran los puertos ISL 1/31 y 1/32 que se están apagando en el switch CL1:

[listing]
----
(CL1)# configure
(CL1)(Config)# interface e1/31-32
(CL1(config-if-range)# shutdown
(CL1(config-if-range)# exit
(CL1)(Config)# exit
(CL1)#
----
====




=== Paso 2: Configurar puertos

. Retire todos los cables conectados al conmutador Nexus 3132Q-V CL2 y vuelva a conectarlos al conmutador C2 de sustitución en todos los nodos.
. Quite los cables ISL de los puertos e1/31 y e1/32 en CL2 y vuelva a conectarlos a los mismos puertos en el switch de reemplazo C2.
. Traiga los puertos ISL 1/31 y 1/32 en el switch Nexus 3132Q-V CL1:
+
[listing]
----
(CL1)# configure
(CL1)(Config)# interface e1/31-32
(CL1(config-if-range)# no shutdown
(CL1(config-if-range)# exit
(CL1)(Config)# exit
(CL1)#
----
. Verifique que los ISL estén activos en CL1:
+
`show port-channel`

+
Los puertos eth1/31 y eth1/32 deben indicar `(P)`, Lo que significa que los puertos ISL están activos en el canal de puerto.

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
CL1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member 						Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Compruebe que los ISL estén activos en C2:
+
`show port-channel summary`

+
Los puertos eth1/31 y eth1/32 deben indicar `(P)`, Lo que significa que ambos puertos ISL están en el canal de puerto.

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. En todos los nodos, active todos los puertos de interconexión del clúster conectados al switch C2 de Nexus 3132Q-V:
+
`network port modify`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin true
cluster::*> network port modify -node n1 -port e0c -up-admin true
cluster::*> network port modify -node n2 -port e0b -up-admin true
cluster::*> network port modify -node n2 -port e0c -up-admin true
cluster::*> network port modify -node n3 -port e4e -up-admin true
cluster::*> network port modify -node n4 -port e4e -up-admin true
----
====
. Para todos los nodos, revierte todos los LIF de interconexión del clúster migrados:
+
`network interface revert`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n1_clus3
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus3
Cluster::*> network interface revert –vserver Cluster –lif n3_clus2
Cluster::*> network interface revert –vserver Cluster –lif n4_clus2
----
====
. Compruebe que los puertos de interconexión de clúster ahora se han revertido a su origen:
+
`network interface show`

+
.Muestra el ejemplo
[%collapsible]
====
Este ejemplo muestra que todas las LIF se han revertido correctamente porque los puertos enumerados en `Current Port` la columna tiene el estado de `true` en la `Is Home` columna. Si la `Is Home` el valor de columna es `false`, El LIF no se ha revertido.

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
12 entries were displayed.
----
====
. Compruebe que los puertos del clúster están conectados:
+
`network port show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
12 entries were displayed.
----
====
. Hacer ping a las interfaces remotas del clúster y realizar una comprobación del servidor RPC:
+
`cluster ping-cluster`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e0a	10.10.0.1
Cluster n1_clus2 n1		e0b	10.10.0.2
Cluster n1_clus3 n1		e0c	10.10.0.3
Cluster n1_clus4 n1		e0d	10.10.0.4
Cluster n2_clus1 n2		e0a	10.10.0.5
Cluster n2_clus2 n2		e0b	10.10.0.6
Cluster n2_clus3 n2		e0c	10.10.0.7
Cluster n2_clus4 n2		e0d	10.10.0.8
Cluster n3_clus1 n3		e0a	10.10.0.9
Cluster n3_clus2 n3		e0e	10.10.0.10
Cluster n4_clus1 n4		e0a	10.10.0.11
Cluster n4_clus2 n4		e0e	10.10.0.12

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11 10.10.0.12
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12

Larger than PMTU communication succeeds on 32 path(s)
RPC status:
8 paths up, 0 paths down (tcp check)
8 paths up, 0 paths down (udp check)
----
====




=== Paso 3: Verificar la configuración

. Muestra la información sobre los dispositivos de la configuración:
+
** `network device-discovery show`
** `network port show -role cluster`
** `network interface show -role cluster`
** `system cluster-switch show`


+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    C1                 Ethernet1/1/1    N3K-C3132Q-V
            e0b    C2                 Ethernet1/1/1    N3K-C3132Q-V
            e0c    C2                 Ethernet1/1/2    N3K-C3132Q-V
            e0d    C1                 Ethernet1/1/2    N3K-C3132Q-V
n2         /cdp
            e0a    C1                 Ethernet1/1/3    N3K-C3132Q-V
            e0b    C2                 Ethernet1/1/3    N3K-C3132Q-V
            e0c    C2                 Ethernet1/1/4    N3K-C3132Q-V
            e0d    C1                 Ethernet1/1/4    N3K-C3132Q-V
n3         /cdp
            e4a    C1                 Ethernet1/7      N3K-C3132Q-V
            e4e    C2                 Ethernet1/7      N3K-C3132Q-V
n4         /cdp
            e4a    C1                 Ethernet1/8      N3K-C3132Q-V
            e4e    C2                 Ethernet1/8      N3K-C3132Q-V
12 entries were displayed.
----
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
12 entries were displayed.
----
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
12 entries were displayed.
----
[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                          cluster-network   10.10.1.101      NX3132V
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

CL2                          cluster-network   10.10.1.102      NX3132V
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP
C2                          cluster-network    10.10.1.103      NX3132V
     Serial Number: FOX000003
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

3 entries were displayed.
----
====
. Retire el interruptor Nexus 3132Q-V sustituido si no se ha retirado automáticamente:
+
`system cluster-switch delete`

+
[listing]
----
cluster::*> system cluster-switch delete –device CL2
----
. Compruebe que se supervisan los switches de clúster adecuados:
+
`system cluster-switch show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                          cluster-network    10.10.1.101      NX3132V
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.103      NX3132V
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. Habilite la función de recogida de registro de supervisión del estado del switch para recopilar archivos de registro relacionados con el switch:
+
`system cluster-switch log setup-password`

+
`system cluster-switch log enable-collection`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> system cluster-switch log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
C1
C2

cluster::*> system cluster-switch log setup-password

Enter the switch name: C1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log setup-password

Enter the switch name: C2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster::*>
----
====
+

NOTE: Si alguno de estos comandos devuelve un error, póngase en contacto con el soporte de NetApp.

. Si ha suprimido la creación automática de casos, vuelva a habilitarla invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


