---
permalink: switch-cisco-3132q-v/reset-switch-3132q-v.html 
sidebar: sidebar 
keywords: 3132Q-V reset switch to factory defaults, 3132Q-V2 switches configuration, efos 
summary: Antes de configurar su conmutador Cisco Nexus 3132Q-V, revise la siguiente información. 
---
= Restablecer el interruptor del clúster 3132Q-V a los valores predeterminados de fábrica
:allow-uri-read: 


[role="lead"]
Para restablecer el interruptor del clúster 3132Q-V a los valores predeterminados de fábrica, debe borrar la configuración del interruptor 3132Q-V.

.Acerca de esta tarea
* Debes estar conectado al switch mediante la consola serie.
* Esta tarea restablece la configuración de la red de administración.


.Pasos
. Borrar la configuración existente:
+
`write erase`

+
[listing, subs="+quotes"]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
. Recargue el software del conmutador:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----
+
El sistema se reinicia y entra en el asistente de configuración. Durante el arranque, si recibe el mensaje “¿Desea cancelar el aprovisionamiento automático y continuar con la configuración normal?” (sí/no)[n]”, debe responder *sí* para continuar.



.¿Qué sigue?
Tras reiniciar el interruptor, puedeslink:install-overview-cisco-3132qv.html["reconfigurar"] Lo adaptaremos a sus necesidades.
