---
permalink: switch-cisco-3132q-v/switch-requirements.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3132q-v cluster switches 
summary: Debe tener en cuenta cierta información de configuración, conexiones de puertos y requisitos de cableado cuando reemplace los conmutadores de clúster Cisco Nexus 3132Q-V. 
---
= Requisitos para la sustitución de switches de clúster Cisco Nexus 3132Q-V
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Asegúrese de comprender los requisitos de configuración, las conexiones de puertos y los requisitos de cableado cuando reemplace los conmutadores del clúster.



== Requisitos de Cisco Nexus 3132Q-V

* El switch de clúster Cisco Nexus 3132Q-V es compatible.
* El número de puertos 10 GbE y 40 GbE se define en los archivos de configuración de referencia (RCF) disponibles enlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Descarga del archivo de configuración de referencia del switch de red en clúster de Cisco"^] .
* Los conmutadores del clúster utilizan los puertos Inter-Switch Link (ISL) e1/31-32.
* Ellink:https://hwu.netapp.com["Hardware Universe"^] Contiene información sobre el cableado compatible con los switches Nexus 3132Q-V:
+
** Los nodos con conexiones de clúster de 10 GbE requieren módulos ópticos QSFP con cables de fibra de ruptura o cables de cobre de ruptura QSFP a SFP+.
** Los nodos con conexiones de clúster de 40 GbE requieren módulos ópticos QSFP/QSFP28 compatibles con cables de fibra o cables de conexión directa de cobre QSFP/QSFP28.
** Los conmutadores del clúster utilizan el cableado ISL apropiado: 2 cables de fibra o cobre de conexión directa QSFP28.


* En el Nexus 3132Q-V, puede operar los puertos QSFP como modos Ethernet de 40 Gb o Ethernet de 4x10 Gb.
+
Por defecto, hay 32 puertos en el modo Ethernet de 40 Gb.  Estos puertos Ethernet de 40 Gb están numerados según una convención de nomenclatura de 2 tuplas.  Por ejemplo, el segundo puerto Ethernet de 40 Gb está numerado como 1/2.  El proceso de cambiar la configuración de Ethernet de 40 Gb a Ethernet de 10 Gb se llama _breakout_ y el proceso de cambiar la configuración de Ethernet de 10 Gb a Ethernet de 40 Gb se llama _breakin_.  Cuando se divide un puerto Ethernet de 40 Gb en puertos Ethernet de 10 Gb, los puertos resultantes se numeran utilizando una convención de nomenclatura de 3 tuplas.  Por ejemplo, los puertos de ruptura del segundo puerto Ethernet de 40 Gb están numerados como 1/2/1, 1/2/2, 1/2/3 y 1/2/4.

* En el lado izquierdo del Nexus 3132Q-V hay un conjunto de cuatro puertos SFP+ multiplexados al primer puerto QSFP.
+
Por defecto, el RCF está estructurado para usar el primer puerto QSFP.

+
Puedes activar cuatro puertos SFP+ en lugar de un puerto QSFP para Nexus 3132Q-V utilizando el siguiente método: `hardware profile front portmode sfp-plus` dominio.  De forma similar, puede restablecer el Nexus 3132Q-V para que utilice un puerto QSFP en lugar de cuatro puertos SFP+ mediante el siguiente procedimiento: `hardware profile front portmode qsfp` dominio.

* Debes haber configurado algunos de los puertos del Nexus 3132Q-V para que funcionen a 10 GbE o 40 GbE.
+
Puedes configurar los seis primeros puertos en modo 4x10 GbE utilizando el `interface breakout module 1 port 1-6 map 10g-4x` dominio.  De forma similar, puede reagrupar los seis primeros puertos QSFP+ de la configuración breakout utilizando el `no interface breakout module 1 port 1-6 map 10g-4x` dominio.

* Debes haber realizado la planificación, la migración y leído la documentación requerida sobre la conectividad de 10 GbE y 40 GbE desde los nodos a los conmutadores de clúster Nexus 3132Q-V.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco"^]Contiene información sobre las versiones de ONTAP y NX-OS compatibles con este procedimiento.





== Requisitos del Cisco Nexus 5596

* Se admiten los siguientes conmutadores de clúster:
+
** Nexus 5596
** Nexus 3132Q-V


* El número de puertos 10 GbE y 40 GbE se define en los archivos de configuración de referencia (RCF) disponibles enlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Descarga del archivo de configuración de referencia del switch de red en clúster de Cisco"^] .
* Los conmutadores del clúster utilizan los siguientes puertos para las conexiones a los nodos:
+
** Puertos e1/1-40 (10 GbE): Nexus 5596
** Puertos e1/1-30 (40 GbE): Nexus 3132Q-V


* Los conmutadores del clúster utilizan los siguientes puertos de enlace entre conmutadores (ISL):
+
** Puertos e1/41-48 (10 GbE): Nexus 5596
** Puertos e1/31-32 (40 GbE): Nexus 3132Q-V


* Ellink:https://hwu.netapp.com/["Hardware Universe"^] Contiene información sobre el cableado compatible con los switches Nexus 3132Q-V:
+
** Los nodos con conexiones de clúster de 10 GbE requieren cables de conexión de fibra óptica QSFP a SFP+ o cables de conexión de cobre QSFP a SFP+.
** Los nodos con conexiones de clúster de 40 GbE requieren módulos ópticos QSFP/QSFP28 compatibles con cables de fibra o cables de conexión directa de cobre QSFP/QSFP28.


* Los conmutadores del clúster utilizan el cableado ISL apropiado:
+
** Inicio: Nexus 5596 a Nexus 5596 (SFP+ a SFP+)
+
*** 8 cables SFP+ de fibra o cobre de conexión directa


** Interina: Nexus 5596 a Nexus 3132Q-V (conversión de QSFP a 4xSFP+)
+
*** 1 cable de conexión de fibra óptica o cobre QSFP a SFP+


** Final: Nexus 3132Q-V a Nexus 3132Q-V (QSFP28 a QSFP28)
+
*** 2 cables QSFP28 de fibra o cobre de conexión directa




* En los switches Nexus 3132Q-V, puede operar los puertos QSFP/QSFP28 como modos Ethernet de 40 Gigabit o Ethernet de 4 x 10 Gigabit.
+
Por defecto, hay 32 puertos en el modo Ethernet de 40 Gigabit.  Estos 40 puertos Gigabit Ethernet están numerados según una convención de nomenclatura de 2 tuplas.  Por ejemplo, el segundo puerto Ethernet de 40 Gigabit está numerado como 1/2.  El proceso de cambiar la configuración de Ethernet de 40 Gigabit a Ethernet de 10 Gigabit se llama _breakout_ y el proceso de cambiar la configuración de Ethernet de 10 Gigabit a Ethernet de 40 Gigabit se llama _breakin_.  Cuando se divide un puerto Ethernet de 40 Gigabit en puertos Ethernet de 10 Gigabit, los puertos resultantes se numeran utilizando una convención de nomenclatura de 3 tuplas.  Por ejemplo, los puertos de ruptura del segundo puerto Ethernet de 40 Gigabit están numerados como 1/2/1, 1/2/2, 1/2/3 y 1/2/4.

* En el lado izquierdo de los switches Nexus 3132Q-V hay un conjunto de 4 puertos SFP+ multiplexados a ese puerto QSFP28.
+
Por defecto, el RCF está estructurado para usar el puerto QSFP28.

+

NOTE: Puedes activar 4 puertos SFP+ en lugar de un puerto QSFP para los switches Nexus 3132Q-V utilizando el siguiente método: `hardware profile front portmode sfp-plus` dominio.  De forma similar, puede restablecer los switches Nexus 3132Q-V para que utilicen un puerto QSFP en lugar de 4 puertos SFP+ mediante el siguiente procedimiento: `hardware profile front portmode qsfp` dominio.

* Has configurado algunos de los puertos de los switches Nexus 3132Q-V para que funcionen a 10 GbE o 40 GbE.
+

NOTE: Puedes configurar los seis primeros puertos en modo 4x10 GbE utilizando el `interface breakout module 1 port 1-6 map 10g-4x` dominio.  De forma similar, puede reagrupar los seis primeros puertos QSFP+ de la configuración breakout utilizando el `no interface breakout module 1 port 1-6 map 10g-4x` dominio.

* Usted ha realizado la planificación, la migración y leído la documentación requerida sobre la conectividad de 10 GbE y 40 GbE desde los nodos a los conmutadores de clúster Nexus 3132Q-V.
* Las versiones de ONTAP y NX-OS compatibles con este procedimiento son las siguientes:link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco"^] .




== Requisitos de NetApp CN1610

* Se admiten los siguientes conmutadores de clúster:
+
** NetApp CN1610
** Cisco Nexus 3132Q-V


* Los conmutadores del clúster admiten las siguientes conexiones de nodo:
+
** NetApp CN1610: puertos 0/1 a 0/12 (10 GbE)
** Cisco Nexus 3132Q-V: puertos e1/1-30 (40 GbE)


* Los conmutadores del clúster utilizan los siguientes puertos de enlace entre conmutadores (ISL):
+
** NetApp CN1610: puertos 0/13 a 0/16 (10 GbE)
** Cisco Nexus 3132Q-V: puertos e1/31-32 (40 GbE)


* Ellink:https://hwu.netapp.com/["Hardware Universe"^] Contiene información sobre el cableado compatible con los switches Nexus 3132Q-V:
+
** Los nodos con conexiones de clúster de 10 GbE requieren cables de conexión de fibra óptica QSFP a SFP+ o cables de conexión de cobre QSFP a SFP+.
** Los nodos con conexiones de clúster de 40 GbE requieren módulos ópticos QSFP/QSFP28 compatibles con cables de fibra óptica o cables de cobre de conexión directa QSFP/QSFP28.


* El cableado ISL apropiado es el siguiente:
+
** Inicio: Para CN1610 a CN1610 (SFP+ a SFP+), cuatro cables de fibra óptica o cobre de conexión directa SFP+
** Provisional: Para CN1610 a Nexus 3132Q-V (QSFP a cuatro SFP+ breakout), un cable de fibra óptica o cobre QSFP a SFP+ breakout
** Final: Para Nexus 3132Q-V a Nexus 3132Q-V (QSFP28 a QSFP28), dos cables de fibra óptica o cobre de conexión directa QSFP28


* Los cables twinax de NetApp no ​​son compatibles con los switches Cisco Nexus 3132Q-V.
+
Si su configuración actual de CN1610 utiliza cables twinax de NetApp para conexiones de nodo de clúster a conmutador o conexiones ISL y desea continuar utilizando twinax en su entorno, necesita adquirir cables twinax de Cisco .  Como alternativa, puede utilizar cables de fibra óptica tanto para las conexiones ISL como para las conexiones entre el nodo del clúster y el conmutador.

* En los switches Nexus 3132Q-V, puede operar los puertos QSFP/QSFP28 como modos Ethernet de 40 Gb o Ethernet de 4x 10 Gb.
+
Por defecto, hay 32 puertos en el modo Ethernet de 40 Gb.  Estos puertos Ethernet de 40 Gb están numerados según una convención de nomenclatura de 2 tuplas.  Por ejemplo, el segundo puerto Ethernet de 40 Gb está numerado como 1/2.  El proceso de cambiar la configuración de Ethernet de 40 Gb a Ethernet de 10 Gb se llama _breakout_ y el proceso de cambiar la configuración de Ethernet de 10 Gb a Ethernet de 40 Gb se llama _breakin_.  Cuando se divide un puerto Ethernet de 40 Gb en puertos Ethernet de 10 Gb, los puertos resultantes se numeran utilizando una convención de nomenclatura de 3 tuplas.  Por ejemplo, los puertos de ruptura del segundo puerto Ethernet de 40 Gb están numerados como 1/2/1, 1/2/2, 1/2/3 y 1/2/4.

* En el lado izquierdo de los switches Nexus 3132Q-V hay un conjunto de cuatro puertos SFP+ multiplexados al primer puerto QSFP.
+
Por defecto, el archivo de configuración de referencia (RCF) está estructurado para usar el primer puerto QSFP.

+
Puede habilitar cuatro puertos SFP+ en lugar de un puerto QSFP para los switches Nexus 3132Q-V mediante el uso de `hardware profile front portmode sfp-plus` dominio.  De forma similar, puede restablecer los switches Nexus 3132Q-V para que utilicen un puerto QSFP en lugar de cuatro puertos SFP+ mediante el uso de `hardware profile front portmode qsfp` dominio.

+

NOTE: Cuando utilice los primeros cuatro puertos SFP+, se deshabilitará el primer puerto QSFP de 40 GbE.

* Debes haber configurado algunos de los puertos de los switches Nexus 3132Q-V para que funcionen a 10 GbE o 40 GbE.
+
Puedes configurar los seis primeros puertos en modo 4x10 GbE utilizando el `interface breakout module 1 port 1-6 map 10g-4x` dominio.  De forma similar, puede reagrupar los seis primeros puertos QSFP+ de la configuración _breakout_ utilizando el `no interface breakout module 1 port 1-6 map 10g-4x` dominio.

* Debes haber realizado la planificación, la migración y leído la documentación requerida sobre la conectividad de 10 GbE y 40 GbE desde los nodos a los conmutadores de clúster Nexus 3132Q-V.
* Las versiones de ONTAP y NX-OS compatibles con este procedimiento se enumeran enlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet de Cisco"^] .
* Las versiones de ONTAP y FASTPATH ​​compatibles con este procedimiento se enumeran enlink:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["Switches NetApp CN1601 y CN1610"^] .

