---
permalink: switch-cisco-3232c-storage/install-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: 'SSH es un requisito cuando se utilizan el Monitor de estado del conmutador de clúster (CSHM) y las funciones de recopilación de registros. Para habilitar SSH en los conmutadores de clúster Cisco 3232c, primero genere las claves SSH y luego habilite SSH.' 
---
= Instalar el archivo de configuración de referencia (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Instale el archivo de configuración de referencia (RCF) después de configurar los conmutadores Nexus 3232C por primera vez.

.Antes de empezar
Verifique las siguientes instalaciones y conexiones:

* Una copia de seguridad actualizada de la configuración del switch.
* Un clúster en pleno funcionamiento (sin errores en los registros ni problemas similares).
* El RCF actual.
* Una conexión de consola al switch, esto es necesario cuando se instala el RCF.


.Acerca de esta tarea
El procedimiento requiere el uso de comandos ONTAP y comandos de switches Cisco Nexus serie 3000; se utilizan comandos ONTAP a menos que se indique lo contrario.

Completa el procedimiento en link:prepare-install-cisco-nexus-3232c-storage.html["Prepárese para instalar NX-OS y RCF."] y luego sigue los pasos a continuación.



== Paso 1: Instale el RCF en los interruptores

. Inicia sesión en el switch s2 usando SSH o usando una consola serie.
. Copia el RCF al bootflash del switch s2 usando uno de los siguientes protocolos de transferencia: FTP, TFTP, SFTP o SCP. Para más información sobre los comandos de Cisco, consulta la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Referencia de comandos de Cisco Nexus serie 3000 NX-OS"^].
+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo muestra TFTP siendo usado para copiar un RCF al bootflash en el switch s2:

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Aplique el RCF descargado previamente a la memoria flash de arranque.
+
Para obtener más información sobre los comandos de Cisco , consulte la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Referencia de comandos de Cisco Nexus serie 3000 NX-OS"^] .

+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo muestra el archivo RCF `NX9336C-FX2-RCF-v1.13-1-Storage.txt` siendo instalado en el switch s2:

[listing, subs="+quotes"]
----
s2# *copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
====
+
[NOTE]
====
Asegúrate de leer detenidamente las secciones *Installation notes*, *Important Notes* y *banner* de tu RCF. Debes leer y seguir estas instrucciones para verificar la correcta configuración y funcionamiento del switch.

====
. Examine la salida del banner de `show banner motd` dominio.  Debe leer y seguir las instrucciones que figuran en *Notas importantes* para garantizar la configuración y el funcionamiento correctos del interruptor.
. Verifique que RCF sea la versión más reciente correcta:
+
`show running-config`

+
Al comprobar la salida para verificar que tiene el RCF correcto, asegúrese de que la siguiente información sea correcta:

+
** El estandarte de RCF
** Configuración del nodo y del puerto
** Personalizaciones
+
El resultado varía según la configuración de su sitio.  Compruebe la configuración del puerto y consulte las notas de la versión para conocer los cambios específicos del RCF que haya instalado.



. Vuelva a aplicar cualquier personalización anterior a la configuración del switch.
. Después de verificar que las versiones de RCF y la configuración del interruptor sean correctas, copie el `running-config` archivo al `startup-config` archivo.
+
`s2# copy running-config startup-config [########################################] 100% Copy complete`

. Reinicia el switch s2:
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Repite los pasos 1 a 8 en el switch s1.
. Conecta los puertos de almacenamiento de nodo y los puertos de estantería de almacenamiento de todos los nodos en el clúster ONTAP a los switches s1 y s2.




== Paso 2: Verifique las conexiones del interruptor

. Verifica que los puertos del switch estén *up*.
+
`show interface brief`

. Verifica que los puertos de almacenamiento del nodo y los puertos de la estantería de almacenamiento estén en sus VLAN correctas usando los siguientes comandos:
+
`show vlan brief`

+
`show interface trunk`





== Paso 3: Configura tu clúster ONTAP

NetApp recomienda utilizar System Manager para configurar nuevos clústeres.

System Manager proporciona un flujo de trabajo simple y fácil para la configuración y el establecimiento de un clúster, incluida la asignación de una dirección IP de administración de nodo, la inicialización del clúster, la creación de un nivel local, la configuración de protocolos y el aprovisionamiento de almacenamiento inicial.

Referirse a https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Configurar ONTAP en un nuevo clúster con el Administrador del sistema"] para obtener instrucciones de configuración.

.¿Que sigue?
Una vez instalado RCF, puedes link:configure-ssh-keys.html["verificar la configuración de SSH"].
