---
permalink: switch-cisco-3232c-storage/prepare-install-cisco-nexus-3232c-storage.html 
sidebar: sidebar 
keywords: nx-os software, install, cisco nexus storage switches, 3232c, rcfs 
summary: 'El software Cisco NX-OS y los archivos de configuración de referencia (RCFs) deben instalarse en los switches de almacenamiento Cisco Nexus 3232C.' 
---
= Preparar la instalación del software NX-OS y el archivo de configuración de referencia (RCF).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar el software NX-OS y el archivo de configuración de referencia (RCF), siga este procedimiento.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los nombres de los dos Cisco switches son s1 y s2.
* Los nombres de los nodos son cluster1-01 y cluster1-02.


Consulta el link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para verificar los puertos de red correctos en tus plataformas. Consulta link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["¿Qué información adicional necesito para instalar mi equipo que no está en HWU?"^] para más información sobre los requisitos de instalación del switch.

.Acerca de esta tarea
El procedimiento requiere el uso de comandos ONTAP y comandos de switches Cisco Nexus serie 3000; se utilizan comandos ONTAP a menos que se indique lo contrario.

.Pasos
. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
`system node autosupport invoke -node * -type all -message MAINT=x h`
+
donde _x_ es la duración de la ventana de mantenimiento en horas.

+
[NOTE]
====
El mensaje de AutoSupport notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante la ventana de mantenimiento.

====
. Cambie el nivel de privilegio a avanzado, ingresando *y* cuando se le solicite continuar:
+
`set -privilege advanced`

+
La solicitud avanzada(`*>` ) aparece.

. Muestra cuántas interfaces están configuradas en cada nodo para cada switch:
+
`network device-discovery show -protocol cdp`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e5a    s1                        Eth1/2            N3K-C3232C
            e3b    s2                        Eth1/2            N3K-C3232C
cluster1-01/cdp
            e5a    s1                        Eth1/1            N3K-C3232C
            e3b    s2                        Eth1/1            N3K-C3232C
.
.
----
====
. Comprueba el estado administrativo u operativo de cada puerto de almacenamiento de nodo y de cada puerto de estantería de almacenamiento.
+
.. Muestra los atributos del puerto de almacenamiento del nodo:
+
`storage port show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
.
.
----
====
.. Muestra los atributos del puerto de la estantería de almacenamiento: 
`storage shelf port show`
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*
Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verifica que el control del estado del switch (CSHM) esté activado para los switches para que se monitoreen:
+
`system switch ethernet show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch             Type               Address          Model
  ------------------ ------------------ ---------------- ---------------
  s1                 storage-network    1.0.0.0          N3K-C3232C
     Serial Number: FFFYYYYYYY1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                 storage-network    1.1.0.0           N3K-C3232C
     Serial Number: FEEYYYYYYY2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====




.¿Que sigue?
Después de que te hayas preparado para instalar el software NX-OS y RCF, puedes link:install-nx-os-software-3232c-storage.html["Instalar el software NX-OS"].
