---
permalink: switch-cisco-3232c-storage/replace-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: Puede reemplazar un switch de almacenamiento Cisco Nexus 3232C defectuoso sin interrumpir el servicio realizando una secuencia específica de tareas. 
---
= Reemplazar un switch de almacenamiento Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos pasos para reemplazar un switch de almacenamiento Cisco Nexus 3232C defectuoso. Este es un procedimiento que no produce interrupciones.



== Requisitos de revisión

La configuración de red existente debe tener las siguientes características:

* La página de switches Ethernet de Cisco tiene las últimas versiones de RCF y NX-OS para sus switches.
* Debe existir conectividad de gestión en ambos conmutadores.
+
[NOTE]
====
Asegúrese de que se hayan completado todos los pasos de solución de problemas para confirmar que su interruptor necesita ser reemplazado.

====


El switch de reemplazo Cisco Nexus 3232C debe tener las siguientes características:

* La conectividad de la red de gestión debe funcionar correctamente.
* Debe estar habilitado el acceso a la consola para el interruptor de repuesto.
* La imagen del sistema operativo RCF y NX-OS apropiada debe cargarse en el switch.
* La personalización inicial del interruptor debe estar completa.




== Reemplace el interruptor

Este procedimiento reemplaza el segundo switch de almacenamiento Nexus 3232C s2 por el nuevo switch 3232C ns2. Los dos nodos son cluster1-01 y cluster1-02.



=== Paso 1: confirma que el switch a sustituir es s2

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ es la duración de la ventana de mantenimiento en horas.

+
[NOTE]
====
El mensaje de AutoSupport notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante la ventana de mantenimiento.

====
. Revisa el estado de salud de los puertos del nodo de almacenamiento para asegurarte de que hay conexión con el switch de almacenamiento s1:
+
`storage port show -port-type ENET`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
cluster1-01
                   e5a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
cluster1-02
                   e5a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
====
. Verifica que el switch de almacenamiento s1 está disponible:
+
`network device-discovery show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
cluster1-01/cdp
            e5a    s1                        Ethernet1/1       NX3232C
            e4a    cluster1-02                     e4a               AFF-A700
            e4e    cluster1-02                     e4e               AFF-A700
cluster1-01/lldp
            e5a    s1                        Ethernet1/1       -
            e4a    cluster1-02                     e4a               -
            e4e    cluster1-02                     e4e               -
cluster1-02/cdp
            e3a    s1                        Ethernet1/2       NX3232C
            e4a    cluster1-01                     e4a               AFF-A700
            e4e    cluster1-01                     e4e               AFF-A700
cluster1-02/lldp
            e3a    s1                        Ethernet1/2       -
            e4a    cluster1-01                     e4a               -
            e4e    cluster1-01                     e4e               -
.
.
----
====
. Ejecutar el `show lldp neighbors` Comando en el interruptor de funcionamiento para confirmar que puede ver ambos nodos y todos los estantes:
+
`show lldp neighbors`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
s1# *show lldp neighbors*
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
cluster1-01             Eth1/1          121        S           e5a
cluster1-02             Eth1/2          121        S           e5a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
====




=== Paso 2: Configurar el cableado

. [[cinco]]Verifique los puertos de los estantes en el sistema de almacenamiento:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  s1
3.20   1   -            -
3.20   2   Ethernet1/6  s1
3.20   3   -            -
3.30   0   Ethernet1/7  s1
3.20   1   -            -
3.30   2   Ethernet1/8  s1
3.20   3   -            -
----
====
. Quita todos los cables conectados al switch de almacenamiento s2.
. Vuelve a conectar todos los cables al switch de reemplazo ns2.




=== Paso 3: verifica la configuración de todos los dispositivos en el switch ns2

. Verifique el estado de salud de los puertos del nodo de almacenamiento:
+
`storage port show -port-type ENET`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
cluster1-01
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
cluster1-02
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30

.
.
----
====
. Verifique que ambos interruptores estén disponibles:
+
`network device-discovery show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
cluster1-01/cdp
            e5a    s1                        Ethernet1/1       NX3232C
            e4a    cluster1-02               e4a               AFF-A700
            e4e    cluster1-02               e4e               AFF-A700
            e7b    ns2                       Ethernet1/1       NX3232C
cluster1-01/lldp
            e5a    s1                        Ethernet1/1       -
            e4a    cluster1-02               e4a               -
            e4e    cluster1-02               e4e               -
            e7b    ns2                       Ethernet1/1       -
cluster1-02/cdp
            e5a    s1                        Ethernet1/2       NX3232C
            e4a    cluster1-01               e4a               AFF-A700
            e4e    cluster1-01               e4e               AFF-A700
            e7b    ns2                       Ethernet1/2       NX3232C
cluster1-02/lldp
            e5a    s1                        Ethernet1/2       -
            e4a    cluster1-01               e4a               -
            e4e    cluster1-01               e4e               -
            e7b    ns2                       Ethernet1/2       -
.
.
----
====
. Verifique los puertos de los estantes en el sistema de almacenamiento:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 s1
3.20  1  Ethernet1/5 ns2
3.20  2  Ethernet1/6 s1
3.20  3  Ethernet1/6 ns2
3.30  0  Ethernet1/7 s1
3.20  1  Ethernet1/7 ns2
3.30  2  Ethernet1/8 s1
3.20  3  Ethernet1/8 ns2
.
.
----
====
. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.¿Que sigue?
Después de sustituir el interruptor, puedes link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
