---
permalink: switch-cisco-3232c-storage/setup-switch-3232c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Si aún no dispone de la información de configuración y la documentación necesarias, deberá recopilarlas antes de configurar el clúster y los conmutadores de red de administración. 
---
= Configura el conmutador de almacenamiento 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para instalar y configurar el conmutador Cisco Nexus 3232C.

.Antes de empezar
* Acceso a un servidor HTTP, FTP o TFTP en el sitio de instalación para descargar las versiones aplicables de NX-OS y el archivo de configuración de referencia (RCF).
* Versión aplicable de NX-OS, descargada desde https://software.cisco.com/download/home["Descarga de software de Cisco"^] página.
* Documentación necesaria sobre la red y el switch de red de gestión.
+
Consulta link:required-documentation-3232c-storage.html["Documentación requerida"] para más información.

* Documentación requerida del controlador y documentación de ONTAP .
+
https://netapp.com/us/documenation/index.aspx["Documentación de NetApp"^]

* Licencias aplicables, información de red y configuración, y cables.
* RCFs aplicables de la red de almacenamiento y la red de gestión de NetApp, descargados del NetApp Support Site en http://mysupport.netapp.com/["mysupport.netapp.com"^] para los switches que recibas. Todos los switches de red de almacenamiento y red de gestión de Cisco llegan con la configuración estándar predeterminada de fábrica de Cisco. Estos switches también tienen la versión actual del software NX-OS, pero no tienen los RCFs cargados.


.Pasos
. Instala en el rack los switches de la red de almacenamiento, los switches de la red de gestión y los controladores.
+
[cols="1,2"]
|===
| Si estás instalando tu... | Entonces... 


 a| 
Cisco Nexus 3232C en un gabinete de sistema NetApp
 a| 
Consulta la guía _Installing a Cisco Nexus 3232C switch and pass-through panel in a NetApp cabinet_ para ver las instrucciones para instalar el switch en un armario NetApp.



 a| 
Equipos en un rack de telecomunicaciones
 a| 
Consulte los procedimientos proporcionados en las guías de instalación del hardware del switch y las instrucciones de instalación y configuración de NetApp .

|===
. Conecta la red de almacenamiento y los switches de red de gestión a los controladores usando las hojas de trabajo de cableado completadas.
. Enciende los switches de la red de almacenamiento, la red de gestión y los controladores.
. Realiza una configuración inicial de los switches de red de almacenamiento.
+
Proporcione las respuestas pertinentes a las siguientes preguntas de configuración inicial cuando encienda el switch por primera vez.  La política de seguridad de su sitio define las respuestas y los servicios que se deben habilitar.

+
[cols="1,2"]
|===
| Inmediato | Respuesta 


 a| 
¿Interrumpir el aprovisionamiento automático y continuar con la configuración normal?  (sí/no)
 a| 
Responda con *sí*.  El valor predeterminado es no.



 a| 
¿Desea implementar un estándar de contraseñas seguras?  (sí/no)
 a| 
Responda con *sí*.  La respuesta predeterminada es sí.



 a| 
Introduzca la contraseña de administrador.
 a| 
La contraseña predeterminada es "`admin`"; debe crear una contraseña nueva y segura.  Una contraseña débil puede ser rechazada.



 a| 
¿Desea acceder al cuadro de diálogo de configuración básica?  (sí/no)
 a| 
Responda con *sí* en la configuración inicial del switch.



 a| 
¿Crear otra cuenta de inicio de sesión?  (sí/no)
 a| 
La respuesta depende de las políticas de su sitio web sobre administradores alternativos.  El valor predeterminado es *no*.



 a| 
¿Configurar la cadena de comunidad SNMP de solo lectura?  (sí/no)
 a| 
Responda con *no*.  El valor predeterminado es no.



 a| 
¿Configurar la cadena de comunidad SNMP de lectura y escritura?  (sí/no)
 a| 
Responda con *no*.  El valor predeterminado es no.



 a| 
Introduzca el nombre del interruptor.
 a| 
El nombre del interruptor está limitado a 63 caracteres alfanuméricos.



 a| 
¿Continuar con la configuración de administración fuera de banda (mgmt0)?  (sí/no)
 a| 
Responda con *sí* (la opción predeterminada) a esa pregunta.  En el indicador de dirección IPv4 de mgmt0, ingrese su dirección IP: ip_address.



 a| 
¿Configurar la puerta de enlace predeterminada?  (sí/no)
 a| 
Responda con *sí*.  En el prompt Dirección IPv4 de la puerta de enlace predeterminada: ingrese su puerta de enlace predeterminada.



 a| 
¿Configurar opciones IP avanzadas?  (sí/no)
 a| 
Responda con *no*.  El valor predeterminado es no.



 a| 
¿Habilitar el servicio telnet?  (sí/no)
 a| 
Responda con *no*.  El valor predeterminado es no.



 a| 
¿Servicio SSH habilitado?  (sí/no)
 a| 
Responda con *sí*.  La respuesta predeterminada es sí.


NOTE: Se recomienda utilizar SSH al usar Ethernet Switch Health Monitor (CSHM) por sus funciones de recopilación de registros.  También se recomienda SSHv2 para mayor seguridad.



 a| 
Ingrese el tipo de clave SSH que desea generar (dsa/rsa/rsa1).
 a| 
El valor predeterminado es *rsa*.



 a| 
Ingrese el número de bits de clave (1024-2048).
 a| 
Ingrese el número de bits de clave entre 1024 y 2048.



 a| 
¿Configurar el servidor NTP?  (sí/no)
 a| 
Responda con *no*.  El valor predeterminado es no.



 a| 
Configurar la capa de interfaz predeterminada (L3/L2):
 a| 
Responda con *L2*.  El valor predeterminado es L2.



 a| 
Configurar el estado predeterminado de la interfaz del puerto del switch (apagado/abierto):
 a| 
Responda con *noshut*.  El valor predeterminado es noshut.



 a| 
Configurar el perfil del sistema CoPP (estricto/moderado/permisivo/denso):
 a| 
Responda con *estricto*.  El valor predeterminado es estricto.



 a| 
¿Desea editar la configuración?  (sí/no)
 a| 
En este punto debería ver la nueva configuración.  Revise y realice los cambios necesarios en la configuración que acaba de ingresar.  Responda con *no* cuando se le solicite si está satisfecho con la configuración.  Responda con *sí* si desea editar su configuración.



 a| 
¿Usar esta configuración y guardarla?  (sí/no)
 a| 
Responda con *sí* para guardar la configuración.  Esto actualiza automáticamente las imágenes de kickstart y del sistema.


NOTE: Si no guarda la configuración en este paso, ninguno de los cambios tendrá efecto la próxima vez que reinicie el switch.

|===
. Verifique las opciones de configuración que seleccionó en la pantalla que aparece al final de la configuración y asegúrese de guardar la configuración.
. Comprueba la versión en los switches de red y, si es necesario, descarga la versión del software compatible con NetApp en los switches desde la  https://software.cisco.com/download/home["Descarga de software de Cisco"^] página.


.¿Que sigue?
Después de que hayas configurado tus switches, puedes link:prepare-install-cisco-nexus-3232c-storage.html["Prepárese para instalar NX-OS y RCF."].
