---
permalink: switch-cisco-3232c-storage/upgrade-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: Puede utilizar este procedimiento para actualizar su versión de RCF. 
---
= Actualiza tu archivo de configuración de referencia (RCF).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Actualizas tu versión de RCF cuando tienes una versión existente del archivo RCF instalada en tus switches operativos.

.Antes de empezar
Asegúrese de tener lo siguiente:

* Una copia de seguridad actualizada de la configuración del switch.
* Un clúster en pleno funcionamiento (sin errores en los registros ni problemas similares).
* El RCF actual.
* Si está actualizando su versión de RCF, necesita una configuración de arranque en RCF que refleje las imágenes de arranque deseadas.
+
Si necesitas cambiar la configuración de arranque para reflejar las imágenes de arranque actuales, debes hacerlo antes de volver a aplicar el RCF para que se incluya la versión correcta en futuros reinicios.




CAUTION: Antes de instalar una nueva versión del software del switch y los RCF, debe borrar la configuración del switch y realizar una configuración básica.  Debe estar conectado al switch mediante la consola serie o haber guardado la información de configuración básica antes de borrar la configuración del switch.



== Paso 1: Prepárese para la actualización

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
Donde _x_ es la duración de la ventana de mantenimiento en horas.

. Cambie el nivel de privilegio a avanzado, ingresando *y* cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el indicador avanzado (*>).

. Muestra los puertos en cada nodo que están conectados a los conmutadores:
+
[source, cli]
----
network device-discovery show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
cluster1-01/cdp
            e5a    s1                       Ethernet1/7     N3K-C3232C
            e3b    s2                       Ethernet1/7     N3K-C3232C
cluster1-02/cdp
            e5a    s1                       Ethernet1/8     N3K-C3232C
            e3b    s2                       Ethernet1/8     N3K-C3232C
.
.
----
====
. Comprueba el estado administrativo u operativo de cada puerto de almacenamiento de nodo y de cada puerto de estantería de almacenamiento.
+
.. Verifica que todos los puertos de almacenamiento del nodo estén activos y en buen estado:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
cluster1-02
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
.
.
----
====
.. Verifique que todos los puertos del estante de almacenamiento estén activos con un estado saludable:
+
[source, cli]
----
storage shelf port show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verifica que los switches están siendo monitoreados.
+
[source, cli]
----
system switch ethernet show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====






== Paso 2: actualiza el RCF

. Inicia sesión en el switch s2 usando SSH o usando una consola serie.
. Apaga los puertos conectados a todos los puertos de los nodos.
+
[listing, subs="+quotes"]
----
s2> *enable*
s2# *configure*
s2(config)# *interface e1/1-32*
s2(config-if-range)# *shutdown*
s2(config-if-range)# *exit*
s2(config)# *exit*
----
+

CAUTION: Asegúrese de apagar *todos* los puertos conectados para evitar problemas de conexión de red. Consulte el artículo de la base de conocimientos https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["Nodo fuera de quórum al migrar la LIF del clúster durante la actualización del sistema operativo del switch"^] Para obtener más detalles.

. Si aún no lo ha hecho, guarde una copia de la configuración actual del switch copiando el resultado del siguiente comando en un archivo de texto:
+
`show running-config`

+
.. Registre cualquier adición personalizada entre el actual `running-config` y el archivo RCF en uso (como una configuración SNMP para su organización).
.. Para NX-OS 10.2 y versiones posteriores, utilice el `show diff running-config` comando para comparar con el archivo RCF guardado en la memoria flash de arranque. De lo contrario, utilice una herramienta de comparación o diff de terceros.


. Guarde los detalles de configuración básicos en el `write_erase.cfg` archivo en la memoria flash de arranque.
+
[NOTE]
====
Asegúrese de configurar lo siguiente:

** Nombre de usuario y contraseña
** Dirección IP de gestión
** Puerta de enlace predeterminada
** Cambiar nombre


====
+
`s2# show run | section "switchname" > bootflash:write_erase.cfg`

+
`s2# show run | section "hostname" >> bootflash:write_erase.cfg`

+
`s2# show run | i "username admin password" >> bootflash:write_erase.cfg`

+
`s2# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`s2# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
Consulte el artículo de la base de conocimientoslink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Cómo borrar la configuración de un switch de interconexión Cisco manteniendo la conectividad remota"^] Para obtener más detalles.

. Verifique que el `write_erase.cfg` El archivo se ha rellenado según lo previsto:
+
`*show file bootflash:write_erase.cfg*`

. Emitir el `write erase` comando para borrar la configuración guardada actual:
+
`s2# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copie la configuración básica guardada previamente en la configuración de inicio.
+
`s2# *copy bootflash:write_erase.cfg startup-config*`

. Reinicia el switch:
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Una vez que la dirección IP de administración vuelva a ser accesible, inicie sesión en el switch a través de SSH.
+
Es posible que necesites actualizar las entradas del archivo host relacionadas con las claves SSH.

. Copia el RCF al bootflash del switch s2 usando uno de los siguientes protocolos de transferencia: FTP, TFTP, SFTP o SCP.
+
Para obtener más información sobre los comandos de Cisco, consulta la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html#CommandReferences["Documentación de Cisco Nexus 3000 Series NX-OS"^].

+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo muestra TFTP siendo usado para copiar un RCF al bootflash en el switch s2:

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Aplique el RCF descargado previamente a la memoria flash de arranque.
+
Para más información sobre los comandos de Cisco, consulta la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Documentación de Cisco Nexus 3000 Series"^].

+
Este ejemplo muestra el archivo RCF `NX3232C-RCF-v1.13-1-Storage.txt` instalándose en el switch s2:

+
[listing, subs="+quotes"]
----
s2# *copy NX3232C-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
+
[CAUTION]
====
Asegúrese de leer detenidamente las secciones *Notas de instalación*, *Notas importantes* y *banner* de su RCF. Debe leer y seguir estas instrucciones para garantizar la configuración y el funcionamiento adecuados del conmutador.

====
. Verifique que el archivo RCF sea la versión más reciente correcta:
+
`show running-config`

+
Al comprobar la salida para verificar que tiene el RCF correcto, asegúrese de que la siguiente información sea correcta:

+
** El estandarte de RCF
** Configuración del nodo y del puerto
** Personalizaciones
+
El resultado varía según la configuración de su sitio.  Compruebe la configuración del puerto y consulte las notas de la versión para conocer los cambios específicos del RCF que haya instalado.



. Vuelva a aplicar cualquier personalización anterior a la configuración del switch.
. Después de verificar que las versiones de RCF, las adiciones personalizadas y la configuración del interruptor sean correctas, copie el `running-config` archivo al `startup-config` archivo.
+
Para obtener más información sobre los comandos de Cisco, consulta la guía correspondiente en https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Documentación de Cisco Nexus 9000 Series"^].

+
`s2# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. Reinicia el switch s2. Puedes ignorar las alertas "`cluster switch health monitor`" y los eventos "`cluster ports down`" reportados en los nodos mientras el switch se reinicia.
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Comprueba el estado administrativo u operativo de cada puerto de almacenamiento de nodo y de cada puerto de estantería de almacenamiento.
+
.. Verifique que todos los puertos de almacenamiento se encuentren en buen estado:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
cluster1-02
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
.
.
----
====
.. Verifique que todos los puertos del estante de almacenamiento estén activos con un estado saludable:
+
[source, cli]
----
storage shelf port show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verifica que los switches están siendo monitoreados:
+
[source, cli]
----
system switch ethernet show
----
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch           Type               Address          Model
  ---------------- ------------------ ---------------- ---------------
  s1               storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2               storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====


. Repite los pasos 1 a 16 en el switch s1.




== Paso 3: verifica la red de almacenamiento

Completa los siguientes pasos en cada switch de almacenamiento para verificar que la red de almacenamiento funciona correctamente después de la actualización de RCF.

. Verifica que los puertos del switch estén *up*.
+
[source, cli]
----
show interface brief
----
. Verifica que los puertos de almacenamiento del nodo esperado siguen conectados:
+
[source, cli]
----
show cdp neighbors
----
. Verifica que los puertos de la estantería de almacenamiento previstos siguen conectados:
+
[source, cli]
----
show lldp neighbors
----
. Verifica que los puertos de almacenamiento del nodo y los puertos de la estantería de almacenamiento estén en sus VLAN correctas usando los siguientes comandos:
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----


.¿Que sigue?
Después de actualizar tu RCF, puedeslink:configure-ssh-keys.html["verificar la configuración de SSH"] .
