---
permalink: switch-netapp-cn1610/install-fastpath-rcf-831.html 
sidebar: sidebar 
keywords: fastpath, software, install, netapp cluster switches, rcfs, ontap 
summary: Los pasos de instalación son los mismos tanto para los switches de administración NetApp CN1601 como para los switches de clúster CN1610 que ejecutan ONTAP 8.3.1 o posterior.  Sin embargo, los dos modelos requieren software y RCF diferentes. 
---
= Instale el software FASTPATH ​​y los RCF para ONTAP 8.3.1 y versiones posteriores.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para instalar el software FASTPATH ​​y los RCF para ONTAP 8.3.1 y versiones posteriores.

Los pasos de instalación son los mismos tanto para los switches de administración NetApp CN1601 como para los switches de clúster CN1610 que ejecutan ONTAP 8.3.1 o posterior.  Sin embargo, los dos modelos requieren software y RCF diferentes.



== Requisitos de revisión

.Antes de empezar
Asegúrese de tener lo siguiente:

* Una copia de seguridad actualizada de la configuración del switch.
* Un clúster en pleno funcionamiento (sin errores en los registros ni tarjetas de interfaz de red (NIC) defectuosas o problemas similares).
* Conexiones de puerto totalmente funcionales en el conmutador del clúster.
* Todos los puertos del clúster están configurados.
* Todas las interfaces lógicas del clúster (LIF) están configuradas (no deben haber sido migradas).
* Una vía de comunicación exitosa: ONTAP (privilegio: avanzado) `cluster ping-cluster -node node1` La orden debe indicar que `larger than PMTU communication` Tiene éxito en todos los caminos.
* Una versión compatible de FASTPATH, RCF y ONTAP.
+
Asegúrese de consultar la tabla de compatibilidad del switch en el http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Switches NetApp CN1601 y CN1610"^] Página para las versiones compatibles de FASTPATH, RCF y ONTAP .





== Instala el software FASTPATH

El siguiente procedimiento utiliza la sintaxis de Data ONTAP 8.2 en clúster.  Como resultado, el Vserver del clúster, los nombres de LIF y la salida de la CLI son diferentes a los de Data ONTAP 8.3.

Pueden existir dependencias de comandos entre la sintaxis de comandos en las versiones RCF y FASTPATH.


NOTE: En la versión 1.2 de RCF, el soporte para Telnet se ha deshabilitado explícitamente debido a preocupaciones de seguridad.  Para evitar problemas de conectividad durante la instalación de RCF 1.2, verifique que Secure Shell (SSH) esté habilitado.  El https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["Guía del administrador del switch NetApp CN1610"^] Tiene más información sobre SSH.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los nombres de los dos switches NetApp son cs1 y cs2.
* Los nombres de la interfaz lógica del clúster (LIF) son node1_clus1 y node1_clus2 para el nodo 1, y node2_clus1 y node2_clus2 para el nodo 2.  (Puedes tener hasta 24 nodos en un clúster).
* El nombre de la máquina virtual de almacenamiento (SVM) es Cluster.
* El `cluster1::*>` El indicador muestra el nombre del clúster.
* Los puertos del clúster en cada nodo se denominan e0a y e0b.
+
https://hwu.netapp.com/["Hardware Universe"^]Tiene más información sobre los puertos de clúster reales que son compatibles con su plataforma.

* Los enlaces entre conmutadores (ISL) compatibles son los puertos 0/13 a 0/16.
* Las conexiones de nodo compatibles son los puertos 0/1 a 0/12.




=== Paso 1: Migrar el clúster

. Mostrar información sobre los puertos de red del clúster:
+
`network port show -_ipspace cluster_`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra el tipo de resultado del comando:

[listing]
----
cluster1::> network port show -ipspace cluster
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. Mostrar información sobre los LIF del clúster:
+
`network interface show -_role cluster_`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra las interfaces lógicas del clúster.  En este ejemplo el `-role` Este parámetro muestra información sobre las LIF asociadas a los puertos del clúster:

[listing]
----
cluster1::> network interface show -role cluster
  (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16    node1         e0a     true
            node1_clus2  up/up    10.254.206.128/16  node1         e0b     true
            node2_clus1  up/up    10.254.48.152/16   node2         e0a     true
            node2_clus2  up/up    10.254.42.74/16    node2         e0b     true
4 entries were displayed.
----
====
. En cada nodo respectivo, utilizando una LIF de administración de nodos, migre node1_clus2 a e0a en node1 y node2_clus2 a e0a en node2:
+
`network interface migrate`

+
Debe introducir los comandos en las consolas del controlador que poseen las LIF del clúster correspondiente.

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::> network interface migrate -vserver Cluster -lif node1_clus2 -destination-node node1 -destination-port e0a
cluster1::> network interface migrate -vserver Cluster -lif node2_clus2 -destination-node node2 -destination-port e0a
----
====
+

NOTE: Para este comando, el nombre del clúster distingue entre mayúsculas y minúsculas y el comando debe ejecutarse en cada nodo.  No es posible ejecutar este comando en el clúster general LIF.

. Verifique que la migración se haya realizado correctamente utilizando la `network interface show` comando en un nodo.
+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que clus2 ha migrado al puerto e0a en los nodos node1 y node2:

[listing]
----
cluster1::> **network interface show -role cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16   node1          e0a     true
            node1_clus2  up/up    10.254.206.128/16 node1          e0a     false
            node2_clus1  up/up    10.254.48.152/16  node2          e0a     true
            node2_clus2  up/up    10.254.42.74/16   node2          e0a     false
4 entries were displayed.
----
====
. Cambie el nivel de privilegio a avanzado, ingresando "y" cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el indicador avanzado (*>).

. Desactive el puerto de clúster e0b en ambos nodos:
+
`network port modify -node _node_name_ -port _port_name_ -up-admin false`

+
Debe introducir los comandos en las consolas del controlador que poseen las LIF del clúster correspondiente.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra los comandos para desactivar el puerto e0b en todos los nodos:

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin false
cluster1::*> network port modify -node node2 -port e0b -up-admin false
----
====
. Verifique que el puerto e0b esté cerrado en ambos nodos:
+
`network port show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::*> network port show -role cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
4 entries were displayed.
----
====
. Desactive los puertos Inter-Switch Link (ISL) en cs1.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config)#interface 0/13-0/16
(cs1) (Interface 0/13-0/16)#shutdown
(cs1) (Interface 0/13-0/16)#exit
(cs1) (Config)#exit
----
====
. Realiza una copia de seguridad de la imagen activa actual en cs2.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.5     1.1.0.3            1.1.0.5            1.1.0.5

(cs2) # copy active backup
Copying active to backup
Copy operation successful
----
====




=== Paso 2: Instale el software FASTPATH y RCF

. Verifique la versión en ejecución del software FASTPATH.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. NetApp CN1610, 1.1.0.5, Linux
                                                2.6.21.7
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.1.0.5
Operating System............................... Linux 2.6.21.7
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893

--More-- or (q)uit


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
. Descarga el archivo de imagen al switch.
+
Copiar el archivo de imagen a la imagen activa significa que, al reiniciar, esa imagen establece la versión FASTPATH en ejecución.  La imagen anterior permanece disponible como copia de seguridad.

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) #copy sftp://root@10.22.201.50//tftpboot/NetApp_CN1610_1.2.0.7.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /tftpboot/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Confirma las versiones de la imagen de arranque actual y la siguiente activa:
+
`show bootvar`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.8     1.1.0.8            1.1.0.8            1.2.0.7
----
====
. Instale el RCF compatible con la nueva versión de la imagen en el switch.
+
Si la versión de RCF ya es correcta, active los puertos ISL.

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) #copy tftp://10.22.201.50//CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr

Mode........................................... TFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y


Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
====
+

NOTE: El `.scr` La extensión debe estar incluida en el nombre del archivo antes de ejecutar el script.  Esta extensión es para el sistema operativo FASTPATH.

+
El switch valida automáticamente el script a medida que se descarga en el mismo.  La salida se muestra en la consola.

. Verifique que el script se haya descargado y guardado con el nombre de archivo que le asignó.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) #script list

Configuration Script Name        Size(Bytes)
-------------------------------- -----------
CN1610_CS_RCF_v1.2.scr                  2191

1 configuration script(s) found.
2541 Kbytes free.
----
====
. Aplique el script al interruptor.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.2.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.2.scr' applied.
----
====
. Verifique que los cambios se hayan aplicado al interruptor y, a continuación, guárdelos:
+
`show running-config`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) #show running-config
----
====
. Guarda la configuración en ejecución para que se convierta en la configuración de inicio cuando reinicies el switch.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) #write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Reinicia el switch.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) #reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====




=== Paso 3: Validar la instalación

. Vuelva a iniciar sesión y, a continuación, verifique que el switch esté ejecutando la nueva versión del software FASTPATH.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) #show version

Switch: 1

System Description............................. NetApp CN1610, 1.2.0.7,Linux
                                                3.8.13-4ce360e8
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.2.0.7
Operating System............................... Linux 3.8.13-4ce360e8
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893
CPLD version................................... 0x5


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
+
Una vez completado el reinicio, debe iniciar sesión para verificar la versión de la imagen, ver la configuración en ejecución y buscar la descripción en la interfaz 3/64, que es la etiqueta de versión para RCF.

. Active los puertos ISL en cs1, el switch activo.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config) #interface 0/13-0/16
(cs1) (Interface 0/13-0/16) #no shutdown
(cs1) (Interface 0/13-0/16) #exit
(cs1) (Config) #exit
----
====
. Verifique que los ISL estén operativos:
+
`show port-channel 3/1`

+
El campo Estado de enlace debe indicar `Up` .

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs1) #show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  False
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Habilitar el puerto de clúster e0b en todos los nodos:
+
`network port modify`

+
Debe introducir los comandos en las consolas del controlador que poseen las LIF del clúster correspondiente.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo se activa el puerto e0b en los nodos 1 y 2:

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin true
cluster1::*> network port modify -node node2 -port e0b -up-admin true
----
====
. Verifique que el puerto e0b esté activo en todos los nodos:
+
`network port show -ipspace cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. Verifique que el LIF ahora esté en casa(`true` ) en ambos nodos:
+
`network interface show -_role cluster_`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.66.82/16   node1         e0a     true
            node1_clus2  up/up    169.254.206.128/16 node1         e0b     true
            node2_clus1  up/up    169.254.48.152/16  node2         e0a     true
            node2_clus2  up/up    169.254.42.74/16   node2         e0b     true
4 entries were displayed.
----
====
. Mostrar el estado de los miembros del nodo:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====
. Volver al nivel de privilegios de administrador:
+
`set -privilege admin`

. Repita los pasos anteriores para instalar el software FASTPATH y RCF en el otro switch, cs1.

