---
permalink: switch-netapp-cn1610/install-rcf-file.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: 'Cuando instale un archivo de configuración de referencia (RCF), primero debe migrar las LIF del clúster fuera del switch cs2.  Una vez instalado y validado el RCF, se pueden migrar de nuevo los LIF.' 
---
= Instale un archivo de configuración de referencia en un switch CN1610.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para instalar un archivo de configuración de referencia (RCF).

Antes de instalar un RCF, primero debe migrar las LIF del clúster fuera del switch cs2.  Una vez instalado y validado el RCF, se pueden migrar de nuevo los LIF.



== Requisitos de revisión

.Antes de empezar
Asegúrese de tener lo siguiente:

* Una copia de seguridad actualizada de la configuración del switch.
* Un clúster en pleno funcionamiento (sin errores en los registros ni tarjetas de interfaz de red (NIC) defectuosas o problemas similares).
* Conexiones de puerto totalmente funcionales en el conmutador del clúster.
* Todos los puertos del clúster están configurados.
* Todas las interfaces lógicas del clúster (LIF) están configuradas.
* Una vía de comunicación exitosa: ONTAP (privilegio: avanzado) `cluster ping-cluster -node node1` La orden debe indicar que `larger than PMTU communication` Tiene éxito en todos los caminos.
* Una versión compatible de RCF y ONTAP.
+
Asegúrese de consultar la tabla de compatibilidad del switch en el http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Switches NetApp CN1601 y CN1610"^] Página para las versiones compatibles de RCF y ONTAP .





== Instala el RCF

El siguiente procedimiento utiliza la sintaxis de Data ONTAP 8.2 en clúster.  Como resultado, el Vserver del clúster, los nombres de LIF y la salida de la CLI son diferentes a los de Data ONTAP 8.3.

Pueden existir dependencias de comandos entre la sintaxis de comandos en las versiones RCF y FASTPATH.


NOTE: En la versión 1.2 de RCF, el soporte para Telnet se ha deshabilitado explícitamente debido a preocupaciones de seguridad.  Para evitar problemas de conectividad durante la instalación de RCF 1.2, verifique que Secure Shell (SSH) esté habilitado.  El https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["Guía del administrador del switch NetApp CN1610"^] Tiene más información sobre SSH.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los dos switches NetApp son cs1 y cs2.
* Los dos LIF de clúster son clus1 y clus2.
* Los servidores virtuales son vs1 y vs2.
* El `cluster::*>` El indicador muestra el nombre del clúster.
* Los puertos del clúster en cada nodo se denominan e1a y e2a.
+
https://hwu.netapp.com/["Hardware Universe"^]Tiene más información sobre los puertos de clúster reales que son compatibles con su plataforma.

* Los enlaces entre conmutadores (ISL) compatibles son los puertos 0/13 a 0/16.
* Las conexiones de nodo compatibles son los puertos 0/1 a 0/12.
* Una versión compatible de FASTPATH, RCF y ONTAP.
+
Asegúrese de consultar la tabla de compatibilidad del switch en el http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Switches NetApp CN1601 y CN1610"^] Página para las versiones compatibles de FASTPATH, RCF y ONTAP .





=== Paso 1: Migrar el clúster

. Guarda la información de configuración actual de tu switch:
+
`write memory`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra la configuración actual del switch que se guarda en la configuración de inicio.(`startup-config` ) archivo en switch cs2:

[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. En la consola de cada nodo, migre clus2 al puerto e1a:
+
`network interface migrate`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
====
. En la consola de cada nodo, verifique que la migración se haya realizado correctamente:
+
`network interface show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que clus2 ha migrado al puerto e1a en ambos nodos:

[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
====
. Desactive el puerto e2a en ambos nodos:
+
`network port modify`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra el puerto e2a desactivado en ambos nodos:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Verifique que el puerto e2a esté cerrado en ambos nodos:
+
`network port show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
====
. Desactive los puertos ISL en cs1, el switch NetApp activo.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====




=== Paso 2: Instalar RCF

. Copie el RCF al switch.
+

NOTE: Debes configurar el `.scr` Incluir la extensión como parte del nombre del archivo antes de ejecutar el script.  Esta extensión es la extensión para el sistema operativo FASTPATH.

+
El switch validará automáticamente el script a medida que se descargue en él, y el resultado se mostrará en la consola.

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
====
. Verifique que el script se haya descargado y guardado con el nombre de archivo que le asignó.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
====
. Valide el script.
+

NOTE: El script se valida durante la descarga para verificar que cada línea sea una línea de comando de switch válida.

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
====
. Aplique el script al interruptor.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
====
. Verifique que sus cambios se hayan implementado en el switch.
+
[listing]
----
(cs2) # show running-config
----
+
El ejemplo muestra el `running-config` archivo en el conmutador.  Debe comparar el archivo con el RCF para verificar que los parámetros que configuró sean los esperados.

. Guarde los cambios.
. Configura el `running-config` El archivo debe ser el estándar.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
====
. Reinicie el switch y verifique que el `running-config` El archivo es correcto.
+
Una vez finalizado el reinicio, debe iniciar sesión y ver la `running-config` archivo, y luego busque la descripción en la interfaz 3/64, que es la etiqueta de versión para RCF.

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. Active los puertos ISL en cs1, el switch activo.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
====
. Verifique que los ISL estén operativos:
+
`show port-channel 3/1`

+
El campo Estado de enlace debe indicar `Up` .

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Habilite el puerto de clúster e2a en ambos nodos:
+
`network port modify`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo se activa el puerto e2a en los nodos 1 y 2:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====




=== Paso 3: Validar la instalación

. Verifique que el puerto e2a esté activo en ambos nodos:
+
`network port show -_role cluster_`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
====
. En ambos nodos, revierta el clus2 asociado al puerto e2a:
+
`network interface revert`

+
Es posible que el LIF vuelva a su estado anterior automáticamente, dependiendo de su versión de ONTAP.

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
. Verifique que el LIF ahora esté en casa(`true` ) en ambos nodos:
+
`network interface show -_role cluster_`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. Consulta el estado de los miembros del nodo:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
====
. Copia el `running-config` archivo al `startup-config` Guarde el archivo cuando esté satisfecho con las versiones del software y la configuración del interruptor.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Repita los pasos anteriores para instalar el RCF en el otro switch, cs1.


.¿Que sigue?
link:../switch-cshm/config-overview.html["Configurar la monitorización del estado del switch"]
