---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: Cuando instale el software FASTPATH ​​en sus switches NetApp , debe comenzar la actualización con el segundo switch, cs2. 
---
= Instale el software FASTPATH
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando instale el software FASTPATH ​​en sus switches NetApp , debe comenzar la actualización con el segundo switch, _cs2_.



== Requisitos de revisión

.Antes de empezar
Asegúrese de tener lo siguiente:

* Una copia de seguridad actualizada de la configuración del switch.
* Un clúster en pleno funcionamiento (sin errores en los registros ni tarjetas de interfaz de red (NIC) defectuosas o problemas similares).
* Conexiones de puerto totalmente funcionales en el conmutador del clúster.
* Todos los puertos del clúster están configurados.
* Todas las interfaces lógicas del clúster (LIF) están configuradas (no deben haber sido migradas).
* Una vía de comunicación exitosa: ONTAP (privilegio: avanzado) `cluster ping-cluster -node node1` La orden debe indicar que `larger than PMTU communication` Tiene éxito en todos los caminos.
* Una versión compatible de FASTPATH ​​y ONTAP.
+
Asegúrese de consultar la tabla de compatibilidad del switch en el http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Switches NetApp CN1601 y CN1610"^] Página para las versiones compatibles de FASTPATH ​​y ONTAP .





== Instalar FASTPATH

El siguiente procedimiento utiliza la sintaxis de Data ONTAP 8.2 en clúster.  Como resultado, el Vserver del clúster, los nombres de LIF y la salida de la CLI son diferentes a los de Data ONTAP 8.3.

Pueden existir dependencias de comandos entre la sintaxis de comandos en las versiones RCF y FASTPATH.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los dos switches NetApp son cs1 y cs2.
* Los dos LIF de clúster son clus1 y clus2.
* Los servidores virtuales son vs1 y vs2.
* El `cluster::*>` El indicador muestra el nombre del clúster.
* Los puertos del clúster en cada nodo se denominan e1a y e2a.
+
https://hwu.netapp.com/["Hardware Universe"^]Tiene más información sobre los puertos de clúster reales que son compatibles con su plataforma.

* Los enlaces entre conmutadores (ISL) compatibles son los puertos 0/13 a 0/16.
* Las conexiones de nodo compatibles son los puertos 0/1 a 0/12.




=== Paso 1: Migrar el clúster

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ es la duración de la ventana de mantenimiento en horas.

+

NOTE: El mensaje de AutoSupport notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante la ventana de mantenimiento.

. Inicie sesión en el switch como administrador.  No hay contraseña por defecto.  Al `(cs2) #` Solicite información, ingrese el `enable` dominio.  Repito, no hay contraseña por defecto.  Esto te da acceso al modo EXEC privilegiado, que te permite configurar la interfaz de red.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. En la consola de cada nodo, migre clus2 al puerto e1a:
+
`network interface migrate`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. En la consola de cada nodo, verifique que la migración se haya realizado correctamente:
+
`network interface show`

+
El siguiente ejemplo muestra que clus2 ha migrado al puerto e1a en ambos nodos:

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== Paso 2: Instalar el software FASTPATH

. Desactive el puerto de clúster e2a en ambos nodos:
+
`network port modify`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra el puerto e2a desactivado en ambos nodos:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Verifique que el puerto e2a esté cerrado en ambos nodos:
+
`network port show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. Desactive los puertos Inter-Switch Link (ISL) en cs1, el switch NetApp activo:
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. Realiza una copia de seguridad de la imagen activa actual en cs2.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. Descarga el archivo de imagen al switch.
+
Copiar el archivo de imagen a la imagen activa significa que, al reiniciar, esa imagen establece la versión FASTPATH en ejecución.  La imagen anterior permanece disponible como copia de seguridad.

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Verifique la versión en ejecución del software FASTPATH.
+
`show version`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. Visualice las imágenes de arranque para la configuración activa y de respaldo.
+
`show bootvar`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. Reinicia el switch.
+
`reload`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== Paso 3: Validar la instalación

. Vuelva a iniciar sesión y verifique la nueva versión del software FASTPATH.
+
`show version`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. Active los puertos ISL en cs1, el switch activo.
+
`configure`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. Verifique que los ISL estén operativos:
+
`show port-channel 3/1`

+
El campo Estado de enlace debe indicar `Up` .

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Copia el `running-config` archivo al `startup-config` Guarde el archivo cuando esté satisfecho con las versiones del software y la configuración del interruptor.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. Habilite el segundo puerto del clúster, e2a, en cada nodo:
+
`network port modify`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. Revertir clus2 que está asociado con el puerto e2a:
+
`network interface revert`

+
Es posible que el LIF se revierta automáticamente, dependiendo de su versión del software ONTAP .

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. Verifique que el LIF ahora esté en casa(`true` ) en ambos nodos:
+
`network interface show -_role cluster_`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. Consulte el estado de los nodos:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. Repita los pasos anteriores para instalar el software FASTPATH en el otro switch, cs1.
. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


