---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: Cuando instala el software FASTPATH en sus switches de NetApp, debe comenzar la actualización con el segundo switch cs2. 
---
= Instale el software FASTPATH
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al instalar el software FASTPATH en los switches de NetApp, debe comenzar la actualización con el segundo switch _cs2_.



== Revise los requisitos

.Antes de empezar
Asegúrese de tener lo siguiente:

* Una copia de seguridad actual de la configuración del switch.
* Un clúster que funciona completamente (sin errores en los registros y sin tarjetas de interfaz de red (NIC) del clúster defectuosas o problemas similares).
* Conexiones de puerto completamente funcionales en el switch de clúster.
* Todos los puertos del clúster configurados.
* Toda la configuración de las interfaces lógicas (LIF) del clúster (no debe haberse migrado).
* Una ruta de comunicación correcta: El ONTAP (privilegio: Avanzado) `cluster ping-cluster -node node1` el comando debe indicar que `larger than PMTU communication` se realiza correctamente en todas las rutas.
* Una versión compatible de FASTPATH y ONTAP.
+
Asegúrese de consultar la tabla de compatibilidad de los interruptores en la http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Switches CN1601 y CN1610 de NetApp"^] Página para las versiones DE FASTPATH y ONTAP admitidas.





== Instale FASTPATH

El siguiente procedimiento usa la sintaxis de Clustered Data ONTAP 8.2. Como resultado, los Vserver del clúster, los nombres LIF y la salida de la CLI son distintos a los de Data ONTAP 8.3.

Puede haber dependencias de comandos entre la sintaxis de comandos en las versiones RCF y FASTPATH.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la nomenclatura de conmutador y nodo siguiente:

* Los dos switches de NetApp son cs1 y cs2.
* Las dos LIF de clúster quedan clus1 y clusa2.
* Los vServers son vs1 y vs2.
* La `cluster::*>` prompt indica el nombre del clúster.
* Los puertos de clúster de cada nodo se denominan e1a y e2a.
+
https://hwu.netapp.com/["Hardware Universe"^] dispone de más información sobre los puertos de clúster que admiten su plataforma.

* Los enlaces Inter-Switch (ISL) compatibles son los puertos 0/13 a 0/16.
* Las conexiones de nodos admitidas son los puertos 0/1 a 0/12.




=== Paso 1: Migrar el clúster

. Si se habilita AutoSupport en este clúster, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ es la duración de la ventana de mantenimiento en horas.

+

NOTE: El mensaje de AutoSupport notifica al soporte técnico de esta tarea de mantenimiento para que la creación automática de casos se suprima durante la ventana de mantenimiento.

. Inicie sesión en el switch como admin. De forma predeterminada, no hay ninguna contraseña. En la `(cs2) #` introduzca el `enable` comando. De nuevo, no hay contraseña de forma predeterminada. Esto le permite acceder al modo EXEC privilegiado, que le permite configurar la interfaz de red.
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. En la consola de cada nodo, migre clus2 al puerto e1a:
+
`network interface migrate`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. En la consola de cada nodo, compruebe que la migración tuvo lugar:
+
`network interface show`

+
En el ejemplo siguiente se muestra que clus2 ha migrado al puerto e1a en ambos nodos:

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== Paso 2: Instale el software FASTPATH

. Apague el puerto e2a del clúster en ambos nodos:
+
`network port modify`

+
.Muestra el ejemplo
[%collapsible]
====
En el siguiente ejemplo se muestra el puerto e2a que se está apagando en ambos nodos:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Compruebe que el puerto e2a está apagado en ambos nodos:
+
`network port show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. Apague los puertos de enlace entre switches (ISL) en cs1, el switch activo de NetApp:
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. Realice una copia de seguridad de la imagen activa actual en cs2.
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. Descargue el archivo de imagen en el switch.
+
Copiar el archivo de imagen en la imagen activa significa que cuando se reinicia, esa imagen establece la versión DE FASTPATH en ejecución. La imagen anterior sigue estando disponible como copia de seguridad.

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Compruebe la versión de ejecución del software FASTPATH.
+
`show version`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. Ver las imágenes de arranque para la configuración activa y de copia de seguridad.
+
`show bootvar`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. Reinicie el conmutador.
+
`reload`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== Paso 3: Validar la instalación

. Inicie sesión de nuevo y verifique la nueva versión del software FASTPATH.
+
`show version`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. Conecte los puertos ISL en cs1, el switch activo.
+
`configure`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. Compruebe que los ISL estén operativos:
+
`show port-channel 3/1`

+
El campo Estado del enlace debe indicar `Up`.

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Copie el `running-config` en la `startup-config` archivo cuando esté satisfecho con las versiones de software y la configuración del switch.
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. Habilite el segundo puerto de clúster, e2a, en cada nodo:
+
`network port modify`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. Reversión2 que está asociado al puerto e2a:
+
`network interface revert`

+
Es posible que LIF se revierte automáticamente en función de su versión del software ONTAP.

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. Compruebe que la LIF se encuentra ahora en casa (`true`) en ambos nodos:
+
`network interface show -_role cluster_`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. Vea el estado de los nodos:
+
`cluster show`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. Repita los pasos anteriores para instalar EL software FASTPATH en el otro switch, cs1.
. Si ha suprimido la creación automática de casos, vuelva a habilitarla invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


