---
permalink: switch-netapp-cn1610/migrate-fas22xx-systems.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, fas22xx systems, single, network connection 
summary: Si tiene sistemas FAS22xx en un clúster sin conmutador de dos nodos existente en el que cada módulo de controlador tiene una única conexión 10 GbE directa para la conectividad del clúster, puede utilizar la opción de red de clúster sin conmutador y reemplazar la conectividad directa directa con conexiones de conmutador. 
---
= Migrar a un clúster conmutado de dos nodos en sistemas FAS22xx con una única conexión de red de clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene sistemas FAS22xx en un clúster sin conmutador de dos nodos existente en el que cada módulo de controlador tiene una única conexión 10 GbE directa para la conectividad del clúster, puede utilizar la opción de red de clúster sin conmutador y reemplazar la conectividad directa directa con conexiones de conmutador.



== Requisitos de revisión

.Antes de empezar
Asegúrese de tener lo siguiente:

* Dos conexiones de clúster para migrar de una configuración sin conmutador a una configuración con conmutador.
* El clúster está en buen estado y consta de dos nodos conectados mediante conectividad directa.
* Los nodos ejecutan ONTAP 8.2 o posterior.
* La función de clúster sin conmutador no se puede utilizar con más de dos nodos.
* Todos los puertos del clúster están en el `up` estado.


.Información relacionada
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["Artículo 1010449 de la base de conocimientos de NetApp : Cómo suprimir la creación automática de casos durante las ventanas de mantenimiento programadas"^]



== Migrar los interruptores

Este procedimiento es un procedimiento no disruptivo que elimina la conectividad directa del clúster en un entorno sin conmutador y reemplaza cada conexión al conmutador con una conexión al nodo asociado.



=== Paso 1: Prepararse para la migración

. Cambie el nivel de privilegio a avanzado, ingresando `y` cuando se le solicite continuar:
+
`set -privilege advanced`

+
La solicitud avanzada(`*>` ) aparece.

. Compruebe el estado del clúster de los nodos en la consola del sistema de cualquiera de los nodos:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra información sobre el estado y la elegibilidad de los nodos del clúster:

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. Compruebe el estado del par HA en la consola del sistema de cualquiera de los nodos: `storage failover show`
+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra el estado del nodo 1 y del nodo 2:

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
`x`es la duración del período de mantenimiento en horas.

+

NOTE: El mensaje notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante el período de mantenimiento.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente comando suprime la creación automática de casos durante dos horas:

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====
. Verifique que el estado actual del clúster sin interruptor sea `true` , y luego desactive el modo de clúster sin interruptor:
+
`network options switchless-cluster modify -enabled false`

. Toma el control del nodo objetivo:
+
`storage failover takeover -ofnode _target_node_name_`

+
No importa cuál sea el nodo objetivo.  Cuando se toma el control, el nodo objetivo se reinicia automáticamente y muestra el `Waiting for giveback...` mensaje.

+
El nodo activo ahora está proporcionando datos al nodo asociado (objetivo) que fue tomado por asalto.

. Espere dos minutos después de la toma de control del nodo afectado para confirmar que la toma de control se completó correctamente.
. Con el nodo objetivo mostrando el `Waiting for giveback...` mensaje, apáguelo.
+
El método que utilice para apagar el nodo depende de si utiliza la administración remota a través del procesador de servicio del nodo (SP).

+
|===
| Si SP | Entonces... 


 a| 
Está configurado
 a| 
Inicie sesión en el nodo SP afectado y, a continuación, apague el sistema: `system power off`



 a| 
No está configurado
 a| 
Cuando aparezca el aviso del nodo dañado, pulse `Ctrl-C` y luego responder `y` para detener el nodo.

|===




=== Paso 2: Configurar cables y puertos

. En cada módulo controlador, desconecte el cable que conecta el puerto del clúster 10 GbE al clúster sin conmutador.
. Conecte el puerto de clúster de 10 GbE al conmutador en ambos módulos de controlador.
. Verifique que los puertos del clúster 10 GbE conectados al switch estén configurados para formar parte de la misma VLAN.
+
Si planea conectar los puertos del clúster en cada módulo de controlador a diferentes conmutadores, entonces debe verificar que los puertos en los que se conectan los puertos del clúster en cada conmutador estén configurados para la misma VLAN y que el enlace troncal esté configurado correctamente en ambos conmutadores.

. Devuelve el almacenamiento al nodo de destino:
+
`storage failover giveback -ofnode node2`

. Supervisar el progreso de la operación de devolución:
+
`storage failover show-giveback`

. Una vez finalizada la operación de devolución, confirme que el par HA funciona correctamente y que la toma de control es posible:
+
`storage failover show`

+
.Mostrar ejemplo
[%collapsible]
====
El resultado debería ser similar al siguiente:

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. Verifique que los LIF del puerto del clúster funcionen correctamente:
+
`network interface show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los LIF son `up` en el nodo 1 y el nodo 2 y que los resultados de la columna "Es casa" son `true` :

[listing]
----

cluster::*> network interface show -role cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
node1
            clus1        up/up    192.168.177.121/24  node1        e1a     true
node2
            clus1        up/up    192.168.177.123/24  node2        e1a     true

2 entries were displayed.
----
====
. Compruebe el estado del clúster de los nodos en la consola del sistema de cualquiera de los nodos:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra información sobre el estado y la elegibilidad de los nodos del clúster:

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====


=== Paso 3: Complete el procedimiento

. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. Vuelva a cambiar el nivel de privilegios a administrador:
+
`set -privilege admin`


