---
permalink: switch-netapp-cn1610/migrate-switched-netapp-cn1610.html 
sidebar: sidebar 
keywords: migrate, switchless cluster environment, switched netapp cn1610 
summary: Si tiene un entorno de clúster sin conmutadores de dos nodos existente, puede migrar a un entorno de clúster conmutado de dos nodos utilizando conmutadores de red de clúster CN1610 que le permiten escalar más allá de dos nodos. 
---
= Migrar de un entorno de clúster sin conmutador a un entorno de clúster NetApp CN1610 con conmutador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene un entorno de clúster sin conmutadores de dos nodos existente, puede migrar a un entorno de clúster conmutado de dos nodos utilizando conmutadores de red de clúster CN1610 que le permiten escalar más allá de dos nodos.



== Requisitos de revisión

.Antes de empezar
Asegúrese de tener lo siguiente:

Para una configuración sin conmutador de dos nodos, asegúrese de que:

* La configuración sin interruptor de dos nodos está correctamente configurada y funcionando.
* Los nodos ejecutan ONTAP 8.2 o posterior.
* Todos los puertos del clúster están en el `up` estado.
* Todas las interfaces lógicas del clúster (LIF) se encuentran en el `up` estado y en sus puertos de origen.


Para la configuración del conmutador de clúster CN1610:

* La infraestructura del conmutador de clúster CN1610 es completamente funcional en ambos conmutadores.
* Ambos switches tienen conectividad de red de gestión.
* Existe acceso mediante consola a los conmutadores del clúster.
* Las conexiones de conmutador a nodo y de conmutador a conmutador CN1610 utilizan cables twinax o de fibra óptica.
+
Ellink:https://hwu.netapp.com/["Hardware Universe"^] Contiene más información sobre el cableado.

* Los cables Inter-Switch Link (ISL) están conectados a los puertos 13 a 16 en ambos switches CN1610.
* Se ha completado la personalización inicial de ambos switches CN1610.
+
Cualquier configuración previa del sitio, como SMTP, SNMP y SSH, debe copiarse a los nuevos conmutadores.



.Información relacionada
* link:http://hwu.netapp.com["Hardware Universe"^]
* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 y CN1610"]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["Configuración e instalación de los conmutadores CN1601 y CN1610"^]
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["Artículo 1010449 de la base de conocimientos de NetApp : Cómo suprimir la creación automática de casos durante las ventanas de mantenimiento programadas"^]




== Migrar los interruptores

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de nodos y conmutadores de clúster:

* Los nombres de los conmutadores CN1610 son cs1 y cs2.
* Los nombres de los LIF son clus1 y clus2.
* Los nombres de los nodos son nodo1 y nodo2.
* El `cluster::*>` El indicador muestra el nombre del clúster.
* Los puertos del clúster utilizados en este procedimiento son e1a y e2a.
+
Ellink:https://hwu.netapp.com/["Hardware Universe"^] Contiene la información más reciente sobre los puertos de clúster reales para sus plataformas.





=== Paso 1: Prepararse para la migración

. Cambie el nivel de privilegio a avanzado, ingresando `y` cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el indicador avanzado (*>).

. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ es la duración de la ventana de mantenimiento en horas.

+

NOTE: El mensaje de AutoSupport notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante la ventana de mantenimiento.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente comando suprime la creación automática de casos durante dos horas:

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====




=== Paso 2: Configurar puertos

. Deshabilite todos los puertos orientados a los nodos (excepto los puertos ISL) en ambos conmutadores del nuevo clúster cs1 y cs2.
+
No debe deshabilitar los puertos ISL.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos orientados al nodo del 1 al 12 están deshabilitados en el switch cs1:

[listing]
----

(cs1)> enable
(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
El siguiente ejemplo muestra que los puertos orientados al nodo del 1 al 12 están deshabilitados en el switch cs2:

[listing]
----

(c2)> enable
(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. Verifique que el ISL y los puertos físicos del ISL entre los dos conmutadores del clúster CN1610 cs1 y cs2 sean `up` :
+
`show port-channel`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos ISL son `up` en el interruptor cs1:

[listing]
----

(cs1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
El siguiente ejemplo muestra que los puertos ISL son `up` en el interruptor cs2:

[listing]
----

(cs2)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Mostrar la lista de dispositivos vecinos:
+
`show isdp neighbors`

+
Este comando proporciona información sobre los dispositivos conectados al sistema.

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo enumera los dispositivos vecinos en el switch cs1:

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16
----
El siguiente ejemplo enumera los dispositivos vecinos en el switch cs2:

[listing]
----

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. Muestra la lista de puertos del clúster:
+
`network port show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra los puertos de clúster disponibles:

[listing]
----

cluster::*> network port show -ipspace Cluster
Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false
12 entries were displayed.
----
====
. Verifique que cada puerto del clúster esté conectado al puerto correspondiente en su nodo de clúster asociado:
+
`run * cdpd show-neighbors`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos del clúster e1a y e2a están conectados al mismo puerto en su nodo asociado del clúster:

[listing]
----

cluster::*> run * cdpd show-neighbors
2 entries were acted on.

Node: node1
Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node2           e1a                    FAS3270           137   H
e2a    node2           e2a                    FAS3270           137   H


Node: node2

Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node1           e1a                    FAS3270           161   H
e2a    node1           e2a                    FAS3270           161   H
----
====
. Verifique que todos los LIF del clúster estén `up` y operativas:
+
`network interface show -vserver Cluster`

+
Cada clúster LIF debería mostrar `true` en la columna "`Está en casa`".

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up      10.10.10.1/16 node1         e1a     true
            clus2      up/up      10.10.10.2/16 node1         e2a     true
node2
            clus1      up/up      10.10.11.1/16 node2         e1a     true
            clus2      up/up      10.10.11.2/16 node2         e2a     true

4 entries were displayed.
----
====
+

NOTE: Los siguientes comandos de modificación y migración en los pasos 10 a 13 deben realizarse desde el nodo local.

. Verifique que todos los puertos del clúster estén `up` :
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show -ipspace Cluster

                                       Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link  MTU   Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ----- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Configura el `-auto-revert` parámetro a `false` en los LIF del clúster clus1 y clus2 en ambos nodos:
+
`network interface modify`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
====
+

NOTE: Para la versión 8.3 y posteriores, utilice el siguiente comando: `network interface modify -vserver Cluster -lif * -auto-revert false`

. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step10]] Migrar clus1 al puerto e2a en la consola de cada nodo:
+
`network interface migrate`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra el proceso para migrar clus1 al puerto e2a en node1 y node2:

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus1 -source-node node1 -dest-node node1 -dest-port e2a
cluster::*> network interface migrate -vserver node2 -lif clus1 -source-node node2 -dest-node node2 -dest-port e2a
----
====
+

NOTE: Para la versión 8.3 y posteriores, utilice el siguiente comando: `network interface migrate -vserver Cluster -lif clus1 -destination-node node1 -destination-port e2a`

. Verifique que la migración se haya realizado correctamente:
+
`network interface show -vserver Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo verifica que clus1 se migra al puerto e2a en node1 y node2:

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e2a     false
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e2a     false
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. Desactive el puerto de clúster e1a en ambos nodos:
+
`network port modify`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo desactivar el puerto e1a en los nodos 1 y 2:

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin false
cluster::*> network port modify -node node2 -port e1a -up-admin false
----
====
. Verifique el estado del puerto:
+
`network port show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que el puerto e1a es `down` en el nodo 1 y el nodo 2:

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Desconecte el cable del puerto de clúster e1a en el nodo 1 y, luego, conecte e1a al puerto 1 en el conmutador de clúster cs1, utilizando el cableado adecuado compatible con los conmutadores CN1610.
+
Ellink:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] Contiene más información sobre el cableado.

. Desconecte el cable del puerto de clúster e1a en el nodo 2 y, luego, conecte e1a al puerto 2 en el conmutador de clúster cs1, utilizando el cableado adecuado compatible con los conmutadores CN1610.
. Habilite todos los puertos orientados al nodo en el conmutador de clúster cs1.
+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos del 1 al 12 están habilitados en el switch cs1:

[listing]
----

(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# no shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
====
. Habilite el primer puerto de clúster e1a en cada nodo:
+
`network port modify`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo habilitar el puerto e1a en el nodo 1 y el nodo 2:

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin true
cluster::*> network port modify -node node2 -port e1a -up-admin true
----
====
. Verifique que todos los puertos del clúster estén `up` :
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que todos los puertos del clúster son `up` en el nodo 1 y el nodo 2:

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Revertir clus1 (que se migró previamente) a e1a en ambos nodos:
+
`network interface revert`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo redirigir clus1 al puerto e1a en node1 y node2:

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus1
cluster::*> network interface revert -vserver node2 -lif clus1
----
====
+

NOTE: Para la versión 8.3 y posteriores, utilice el siguiente comando: `network interface revert -vserver Cluster -lif <nodename_clus<N>>`

. Verifique que todos los LIF del clúster estén `up` , operativo y de visualización como `true` en la columna "Está en casa":
+
`network interface show -vserver Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que todos los LIF son `up` en el nodo 1 y el nodo 2 y que los resultados de la columna "Es casa" son `true` :

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. Mostrar información sobre el estado de los nodos en el clúster:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra información sobre el estado y la elegibilidad de los nodos del clúster:

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. Migrar clus2 al puerto e1a en la consola de cada nodo:
+
`network interface migrate`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra el proceso para migrar clus2 al puerto e1a en node1 y node2:

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus2 -source-node node1 -dest-node node1 -dest-port e1a
cluster::*> network interface migrate -vserver node2 -lif clus2 -source-node node2 -dest-node node2 -dest-port e1a
----
====
+

NOTE: Para la versión 8.3 y posteriores, utilice el siguiente comando: `network interface migrate -vserver Cluster -lif node1_clus2 -dest-node node1 -dest-port e1a`

. Verifique que la migración se haya realizado correctamente:
+
`network interface show -vserver Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo verifica que clus2 se migra al puerto e1a en node1 y node2:

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e1a     false
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e1a     false

4 entries were displayed.
----
====
. Desactive el puerto de clúster e2a en ambos nodos:
+
`network port modify`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo desactivar el puerto e2a en los nodos 1 y 2:

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Verifique el estado del puerto:
+
`network port show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que el puerto e2a es `down` en el nodo 1 y el nodo 2:

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Desconecte el cable del puerto de clúster e2a en el nodo 1 y, luego, conecte e2a al puerto 1 en el conmutador de clúster cs2, utilizando el cableado adecuado compatible con los conmutadores CN1610.
. Desconecte el cable del puerto de clúster e2a en el nodo 2 y, luego, conecte e2a al puerto 2 en el conmutador de clúster cs2, utilizando el cableado adecuado compatible con los conmutadores CN1610.
. Habilite todos los puertos orientados al nodo en el conmutador de clúster cs2.
+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que los puertos del 1 al 12 están habilitados en el switch cs2:

[listing]
----

(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# no shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. Habilite el segundo puerto de clúster e2a en cada nodo.
+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo habilitar el puerto e2a en el nodo 1 y el nodo 2:

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====
. Verifique que todos los puertos del clúster estén `up` :
+
`network port show -ipspace Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que todos los puertos del clúster son `up` en el nodo 1 y el nodo 2:

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Revertir clus2 (que se migró previamente) a e2a en ambos nodos:
+
`network interface revert`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo redirigir clus2 al puerto e2a en los nodos 1 y 2:

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
+

NOTE: Para la versión 8.3 y posteriores, los comandos son:
`cluster::*> network interface revert -vserver Cluster -lif node1_clus2` y
`cluster::*> network interface revert -vserver Cluster -lif node2_clus2`





=== Paso 3: Completar la configuración

. Verifique que todas las interfaces muestren `true` en la columna "Está en casa":
+
`network interface show -vserver Cluster`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra que todos los LIF son `up` en el nodo 1 y el nodo 2 y que los resultados de la columna "Es casa" son `true` :

[listing]
----

cluster::*> network interface show -vserver Cluster

             Logical    Status     Network            Current     Current Is
Vserver      Interface  Admin/Oper Address/Mask       Node        Port    Home
-----------  ---------- ---------- ------------------ ----------- ------- ----
node1
             clus1      up/up      10.10.10.1/16      node1       e1a     true
             clus2      up/up      10.10.10.2/16      node1       e2a     true
node2
             clus1      up/up      10.10.11.1/16      node2       e1a     true
             clus2      up/up      10.10.11.2/16      node2       e2a     true
----
====
. Verifique la conectividad de las interfaces del clúster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 y posteriores
--
Puedes usar el `network interface check cluster-connectivity` comando para iniciar una comprobación de accesibilidad para la conectividad del clúster y luego mostrar los detalles:

`network interface check cluster-connectivity start`y `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Espere unos segundos antes de ejecutar el programa. `show` comando para mostrar los detalles.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas las versiones de ONTAP
--
Para todas las versiones de ONTAP , también puede usar el `cluster ping-cluster -node <name>` comando para comprobar la conectividad:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step3]] Verifique que ambos nodos tengan dos conexiones a cada interruptor:
+
`show isdp neighbors`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra los resultados correspondientes para ambos interruptores:

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e1a
node2                  0/2          163       H            FAS3270   e1a
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e2a
node2                  0/2          163       H            FAS3270   e2a
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. Muestra información sobre los dispositivos de tu configuración:
+
`network device discovery show`

. Deshabilite la configuración sin conmutador de dos nodos en ambos nodos utilizando el comando de privilegios avanzados:
+
`network options detect-switchless modify`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra cómo deshabilitar la configuración sin interruptor:

[listing]
----

cluster::*> network options detect-switchless modify -enabled false
----
====
+

NOTE: Para la versión 9.2 y posteriores, omita este paso ya que la configuración se convierte automáticamente.

. Verifique que la configuración esté desactivada:
+
`network options detect-switchless-cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
El `false` El resultado del siguiente ejemplo muestra que la configuración está desactivada:

[listing]
----

cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: false
----
====
+

NOTE: Para la versión 9.2 y posteriores, espere hasta `Enable Switchless Cluster` está establecido en falso.  Esto puede tardar hasta tres minutos.

. Configure los clústeres clus1 y clus2 para que reviertan automáticamente en cada nodo y confirme.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert true
----
====
+

NOTE: Para la versión 8.3 y posteriores, utilice el siguiente comando: `network interface modify -vserver Cluster -lif * -auto-revert true` para habilitar la reversión automática en todos los nodos del clúster.

. Verifique el estado de los nodos miembros del clúster:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra información sobre el estado y la elegibilidad de los nodos del clúster:

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. Vuelva a cambiar el nivel de privilegios a administrador:
+
`set -privilege admin`


