---
permalink: switch-netapp-cn1610/migrate-overview.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, netapp cn1610 
summary: Si tiene un clúster de dos nodos sin conmutadores, puede migrar, sin interrupciones, a un clúster de dos nodos con conmutadores que incluya conmutadores de red de clúster NetApp CN1610. 
---
= Opciones de migración para un clúster conmutado de dos nodos con conmutadores de clúster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene un clúster de dos nodos sin conmutadores, puede migrar, sin interrupciones, a un clúster de dos nodos con conmutadores que incluya conmutadores de red de clúster NetApp CN1610.  El procedimiento que utilice dependerá de si dispone de dos puertos de red de clúster dedicados en cada controlador o de un único puerto de clúster en cada controlador.

La mayoría de los sistemas requieren dos puertos de red de clúster dedicados en cada controlador.

Los nodos FAS22xx permiten un único puerto de clúster en cada controlador.

Existen dos opciones de migración disponibles:

* link:migrate-switched-netapp-cn1610.html["Migrar de un clúster sin conmutador a un entorno de clúster NetApp CN1610 con conmutador"]
* link:migrate-fas22xx-systems.html["Migrar desde un clúster sin conmutador (sistemas FAS22xx con una única conexión de red de clúster)"]

