---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: Puede reemplazar un conmutador de clúster NetApp CN1610 defectuoso sin interrumpir el servicio realizando una secuencia específica de tareas. 
---
= Reemplazar un switch de clúster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos pasos para reemplazar un switch NetApp CN1610 defectuoso en una red de clúster.  Este es un procedimiento no disruptivo (NDU).



== Requisitos de revisión

.Antes de empezar
Antes de realizar la sustitución del switch, deben existir las siguientes condiciones en el entorno actual y en el switch de reemplazo para el clúster y la infraestructura de red existentes:

* Se debe verificar que el clúster existente sea completamente funcional, con al menos un conmutador de clúster totalmente conectado.
* Todos los puertos del clúster deben estar *activos*.
* Todas las interfaces lógicas del clúster (LIF) deben estar activas y no deben haber sido migradas.
* El clúster ONTAP `ping-cluster -node node1` El comando debe indicar que la conectividad básica y la comunicación superior a PMTU se realizan correctamente en todas las rutas.




== Habilitar el registro en la consola

NetApp recomienda encarecidamente que habilite el registro de consola en los dispositivos que esté utilizando y que realice las siguientes acciones al reemplazar su switch:

* Deje activado el AutoSupport durante el mantenimiento.
* Active un AutoSupport de mantenimiento antes y después del mantenimiento para deshabilitar la creación de casos durante la duración del mismo.  Consulte este artículo de la base de conocimientos. https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: Cómo suprimir la creación automática de casos durante las ventanas de mantenimiento programadas"^] Para obtener más detalles.
* Habilite el registro de sesión para cualquier sesión de la CLI.  Para obtener instrucciones sobre cómo habilitar el registro de sesiones, consulte la sección "Registro de salida de sesión" en este artículo de la base de conocimientos. https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Cómo configurar PuTTY para una conectividad óptima a los sistemas ONTAP"^] .




== Reemplace el interruptor

.Acerca de esta tarea
Debe ejecutar el comando para migrar un LIF de clúster desde el nodo donde se aloja el LIF de clúster.

Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de nodos y conmutadores de clúster:

* Los nombres de los dos conmutadores de clúster CN1610 son `cs1` y `cs2` .
* El nombre del interruptor CN1610 que se va a reemplazar (el interruptor defectuoso) es `old_cs1` .
* El nombre del nuevo interruptor CN1610 (el interruptor de repuesto) es `new_cs1` .
* El nombre del conmutador asociado que no se está reemplazando es `cs2` .


.Pasos
. Comprueba que el archivo de configuración de inicio coincide con el archivo de configuración en ejecución.  Debe guardar estos archivos localmente para utilizarlos durante la sustitución.
+
Los comandos de configuración del siguiente ejemplo son para FASTPATH 1.2.0.7:

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)> *enable*
(old_cs1)# *show running-config*
(old_cs1)# *show startup-config*
----
====
. Crea una copia del archivo de configuración en ejecución.
+
El comando del siguiente ejemplo es para FASTPATH 1.2.0.7:

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *show running-config filename.scr*
Config script created successfully.
----
====



NOTE: Puedes usar cualquier nombre de archivo excepto `CN1610_CS_RCF_v1.2.scr` .  El nombre del archivo debe tener la extensión *.scr*.

. [[step3]]Guarde el archivo de configuración en ejecución del switch en un host externo como preparación para el reemplazo.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. Verifique que las versiones del switch y del ONTAP coincidan en la matriz de compatibilidad.  Ver el https://mysupport.netapp.com/site/info/netapp-cluster-switch["Switches NetApp CN1601 y CN1610"^] página para más detalles.
. Desde https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["Página de descargas de software"^] En el sitio de soporte de NetApp , seleccione NetApp Cluster Switches para descargar las versiones adecuadas de RCF y FASTPATH.
. Configura un servidor TFTP (Protocolo de Transferencia de Archivos Trivial) con FASTPATH, RCF y la configuración guardada. `.scr` Archivo para usar con el nuevo interruptor.
. Conecte el puerto serie (el conector RJ-45 etiquetado como “IOIOI” en el lado derecho del switch) a un host disponible con emulación de terminal.
. En el host, configure los ajustes de conexión del terminal serie:
+
.. 9600 baudios
.. 8 bits de datos
.. 1 bit de parada
.. paridad: ninguna
.. Control de flujo: ninguno


. Conecte el puerto de administración (el puerto RJ-45 con forma de llave inglesa en el lado izquierdo del switch) a la misma red donde se encuentra su servidor TFTP.
. Prepárese para conectarse a la red con el servidor TFTP.
+
Si está utilizando el Protocolo de configuración dinámica de host (DHCP), no es necesario que configure una dirección IP para el conmutador en este momento.  El puerto de servicio está configurado para usar DHCP de forma predeterminada.  El puerto de administración de red está configurado como ninguno para los protocolos IPv4 e IPv6.  Si el puerto de su llave inglesa está conectado a una red que tiene un servidor DHCP, la configuración del servidor se configura automáticamente.

+
Para configurar una dirección IP estática, debe utilizar los comandos serviceport protocol, network protocol y serviceport ip.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. Opcionalmente, si el servidor TFTP está en una computadora portátil, conecte el switch CN1610 a la computadora portátil mediante un cable Ethernet estándar y luego configure su puerto de red en la misma red con una dirección IP alternativa.
+
Puedes usar el `ping` comando para verificar la dirección.  Si no puede establecer la conectividad, debe usar una red no enrutada y configurar el puerto de servicio usando la IP 192.168.x o 172.16.x.  Posteriormente podrá reconfigurar el puerto de servicio a la dirección IP de gestión de producción.

. Opcionalmente, verifique e instale las versiones apropiadas del software RCF y FASTPATH para el nuevo switch.  Si ha verificado que el nuevo switch está configurado correctamente y no requiere actualizaciones del software RCF y FASTPATH, debe pasar al paso 13.
+
.. Verifique la nueva configuración del interruptor.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show version*
----
====
.. Descarga el RCF al nuevo switch.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. Verifique que el RCF se haya descargado en el switch.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. Aplique el RCF al interruptor CN1610.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. Guarda el archivo de configuración en ejecución para que se convierta en el archivo de configuración de inicio cuando reinicies el switch.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Descargue la imagen al switch CN1610.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. Ejecute la nueva imagen de arranque activa reiniciando el switch.
+
El switch debe reiniciarse para que el comando del paso 6 refleje la nueva imagen.  Existen dos posibles vistas para la respuesta que podría ver después de ingresar el comando de recarga.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. Copie el archivo de configuración guardado del switch antiguo al switch nuevo.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. Aplique la configuración guardada previamente al nuevo conmutador.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Guarde el archivo de configuración en ejecución en el archivo de configuración de inicio.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
----
====


. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ es la duración de la ventana de mantenimiento en horas.

+
[NOTE]
====
El mensaje de AutoSupport notifica al soporte técnico sobre esta tarea de mantenimiento para que se suprima la creación automática de casos durante la ventana de mantenimiento.

====
. En el nuevo switch new_cs1, inicie sesión como usuario administrador y apague todos los puertos que están conectados a las interfaces del clúster de nodos (puertos 1 a 12).
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1)> *enable*
(new_cs1)#
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)# *shutdown*
(new_cs1)(interface 0/1-0/12)# *exit*
(new_cs1)# *write memory*
----
====
. Migre las LIF del clúster desde los puertos que están conectados al switch old_cs1.
+
Debe migrar cada LIF del clúster desde la interfaz de administración de su nodo actual.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. Verifique que todas las LIF del clúster se hayan movido al puerto de clúster apropiado en cada nodo.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. Desactive los puertos del clúster que están conectados al switch que reemplazó.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. Verifique el estado del clúster.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Verifique que los puertos estén inactivos.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. En el switch cs2, apague los puertos ISL del 13 al 16.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *shutdown*
(cs2)# *show port-channel 3/1*
----
====
. Verifique si el administrador de almacenamiento está preparado para el reemplazo del switch.
. Retire todos los cables del switch old_cs1 y luego conecte los cables a los mismos puertos del switch new_cs1.
. En el switch cs2, active los puertos ISL del 13 al 16.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *no shutdown*
----
====
. Habilite los puertos del nuevo conmutador que están asociados con los nodos del clúster.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/13-0/16)# *no shutdown*
----
====
. En un solo nodo, active el puerto del nodo del clúster que está conectado al conmutador reemplazado y luego confirme que el enlace está activo.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. Revertir los LIF del clúster que están asociados con el puerto en el paso 25 en el mismo nodo.
+
En este ejemplo, las LIF del nodo1 se revierten correctamente si la columna “Es casa” es verdadera.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. Si el LIF del clúster del primer nodo está activo y se revierte a su puerto de origen, repita los pasos 25 y 26 para activar los puertos del clúster y revertir los LIF del clúster en los otros nodos del clúster.
. Muestra información sobre los nodos del clúster.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Confirme que el archivo de configuración de inicio y el archivo de configuración en ejecución sean correctos en el switch reemplazado.  Este archivo de configuración debe coincidir con el resultado del paso 1.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show running-config*
(new_cs1)# *show startup-config*
----
====
. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


