---
permalink: switch-netapp-cn1610/switch-overview-cn1610.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs 
summary: Antes de configurar los switches NetApp CN1610, revise la descripción general del procedimiento. 
---
= Descripción general de la instalación y configuración de los switches NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El CN1610 es un switch de capa 2 administrado de alto ancho de banda que proporciona 16 puertos SFP+ (Small Form-Factor Pluggable Plus) de 10 Gigabit.

El switch incluye fuentes de alimentación redundantes y bandejas de ventiladores que admiten el intercambio en caliente para una alta disponibilidad.  Este switch 1U se puede instalar en un gabinete de sistema NetApp 42U estándar de 19 pulgadas o en un gabinete de terceros.

El switch admite la gestión local a través del puerto de consola o la gestión remota mediante Telnet o SSH a través de una conexión de red.  El CN1610 incluye un puerto de administración RJ45 Gigabit Ethernet dedicado para la administración del switch fuera de banda.  Puede administrar el conmutador ingresando comandos en la interfaz de línea de comandos (CLI) o utilizando un sistema de administración de red (NMS) basado en SNMP.
