---
permalink: get-started/learn-switch-concept.html 
sidebar: sidebar 
keywords:  
summary: Aprenda sobre clústeres, almacenamiento y conmutadores compartidos. 
---
= Obtenga información sobre los sistemas AFX, clúster, almacenamiento y conmutadores compartidos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp ofrece sistemas AFX, clústeres, almacenamiento y conmutadores compartidos que brindan comunicaciones internas con la capacidad de mover datos e interfaces de red sin interrupciones en todo el clúster.

Los switches de “front-end” proporcionan conectividad al almacenamiento del host, mientras que los switches de clúster de “back-end” proporcionan conexiones entre dos o más controladores NetApp .


NOTE: Solo se admiten switches de back-end validados por NetApp(pedidos a NetApp).



== Conmutadores de sistemas AFX

Los conmutadores de sistemas AFX le permiten crear conmutadores de red rápidos, energéticamente eficientes y que ahorran espacio. Su pequeño tamaño y alta densidad de puertos los hacen ideales para manejar redes grandes. Los puertos admiten diferentes velocidades y se pueden dividir en múltiples conexiones. Los conmutadores de sistemas AFX compatibles con NetApp incluyen:

* Cisco Nexus 9332D-GX2B
* Cisco Nexus 9364D-GX2A




== Conmutadores de clúster

Los conmutadores de clúster le permiten crear clústeres ONTAP con más de dos nodos. Los conmutadores de clúster compatibles con NetApp incluyen:

* Broadcom BES-53248
* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




== Conmutadores de almacenamiento

Los conmutadores de almacenamiento permiten enrutar datos entre servidores y matrices de almacenamiento en una red de área de almacenamiento (SAN).  Los switches de almacenamiento compatibles con NetApp incluyen:

* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




== Conmutadores compartidos

Los conmutadores compartidos permiten combinar la funcionalidad de clúster y almacenamiento en una configuración de conmutador compartido, al admitir el uso de RCF de clúster y almacenamiento compartidos.  El switch compartido compatible con NetApp es:

* Cisco Nexus 9336C-FX2




== Fin de disponibilidad

Los siguientes conmutadores de almacenamiento ya no están disponibles para su compra, pero aún cuentan con soporte:

* Cisco Nexus 3232C
* Cisco Nexus 3132Q-V
* Cisco Nexus 92300YC
* NetApp CN1610

