---
permalink: other-procedures/transition-to-two-node-switchless-cluster-index.html 
sidebar: sidebar 
keywords: transition, two-node, switchless, cluster, two, node 
summary: Puede cambiar a un clúster de dos nodos que utilice switches de Cluster Interconnect a uno en el que dos nodos estén conectados directamente. 
---
= Descripción general
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Si tiene un clúster de dos nodos existente que utiliza switches de interconexión de clúster y ejecuta ONTAP 9.3 o una versión posterior, puede reemplazar los switches por conexiones directas de vuelta a atrás entre los nodos.

.Acerca de esta tarea
No se puede usar la función de interconexión de clúster sin switches con más de dos nodos.

La transición a una configuración de clúster de dos nodos sin switch es un funcionamiento no disruptivo. La mayoría de los sistemas tienen dos puertos de interconexión de clúster dedicados en cada nodo, pero también puede usar este procedimiento para sistemas con un número mayor de puertos de interconexión de clúster dedicados en cada nodo, como cuatro, seis u ocho.

En este procedimiento, se describe la transición de un clúster con una red de clúster conmutada a uno donde dos nodos están conectados directamente para ONTAP 9.3 y una versión posterior.
