---
permalink: switch-cisco-92300/92300-overview.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Si desea crear clústeres ONTAP con más de dos nodos, necesitará dos conmutadores de red de clúster compatibles.  Puede utilizar interruptores de administración adicionales, que son opcionales. 
---
= Descripción general del switch Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea crear clústeres ONTAP con más de dos nodos, necesitará dos conmutadores de red de clúster compatibles.  Puede utilizar interruptores de administración adicionales, que son opcionales.

Puede instalar el switch Cisco Nexus 92300YC (X190003/R) en un gabinete de sistema NetApp o en un gabinete de terceros con los soportes estándar que se incluyen con el switch.

La siguiente tabla enumera el número de pieza y la descripción del interruptor, los ventiladores y las fuentes de alimentación 92300YC:

[cols="1,2"]
|===
| Número de pieza | Descripción 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = Escape del lado del puerto)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = Entrada del lado del puerto)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventilador, entrada de aire lateral del puerto Cisco N9K



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventilador, flujo de aire de escape lateral del puerto Cisco N9K



 a| 
X-NXA-PAC-650W-B
 a| 
Fuente de alimentación Cisco de 650 W - entrada lateral del puerto



 a| 
X-NXA-PAC-650W-F
 a| 
Fuente de alimentación Cisco de 650 W - salida de aire lateral (puerto).

|===
Detalles del flujo de aire del switch Cisco Nexus 92300YC:

* Flujo de aire de escape del lado de los puertos (aire estándar): el aire frío entra en el chasis a través de los módulos del ventilador y de la fuente de alimentación en el pasillo frío y sale por el extremo de los puertos del chasis en el pasillo caliente.  Salida de aire de escape por el lado de babor con coloración azul.
* Flujo de aire de entrada del lado del puerto (aire inverso): el aire frío entra al chasis a través del extremo del puerto en el pasillo frío y sale a través del ventilador y los módulos de la fuente de alimentación en el pasillo caliente.  Entrada de aire por el lado de babor con color burdeos.


.Documentación disponible
La siguiente tabla enumera la documentación disponible para los switches Cisco Nexus 92300YC.

|===


| Título | Descripción 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-overview-cisco-92300.html["_Configurar los switches del clúster Cisco® Nexus 92300YC_"^]
 a| 
Describe cómo configurar y poner en marcha sus switches de clúster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-nxos-overview.html["_Instalar NX-OS y los archivos de configuración de referencia (RCF)_"^]
 a| 
Describe cómo instalar NX-OS y los archivos de configuración de referencia (RCF) en el conmutador de clúster Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/configure-install-initial.html["_Configurar un nuevo switch Cisco Nexus 92300YC_"^]
 a| 
Describe cómo migrar de entornos que utilizan switches Cisco más antiguos a entornos que utilizan switches Cisco 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-92300yc.html["_Migrar de un switch Cisco antiguo a un switch Cisco Nexus 92300YC_"^]
 a| 
Describe el procedimiento para reemplazar un switch Cisco antiguo con un switch de clúster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-2n-switched.html["_Migrar desde un clúster sin conmutador de dos nodos_"^]
 a| 
Describe cómo migrar de un entorno de clúster sin conmutador de dos nodos a un entorno conmutado de dos nodos utilizando conmutadores de clúster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/replace-92300yc.html["_Reemplazar un switch de clúster Cisco Nexus 92300YC_"^]
 a| 
Describe el procedimiento para reemplazar un switch Cisco Nexus 92300YC defectuoso en un clúster y descargar el sistema operativo del switch y el archivo de configuración de referencia.

|===