---
permalink: switch-cisco-92300/components-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Si desea crear clústeres de ONTAP con más de dos nodos, necesita dos switches de red de clúster compatibles. Puede usar switches de gestión adicionales, que son opcionales. 
---
= Componentes y números de pieza de los conmutadores Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y mantenimiento del switch Cisco Nexus 92300YC, asegúrese de revisar todos los componentes del switch y sus números de pieza. Consulte https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para obtener más detalles.

En la siguiente tabla se enumeran el número de pieza y la descripción del conmutador 92300YC, los ventiladores y las fuentes de alimentación:

[cols="1,2"]
|===
| Número de pieza | Descripción 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = escape lateral de puerto)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = entrada lateral de puerto)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventilador, flujo de aire de admisión lateral del puerto Cisco N9K



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventilador, flujo de aire de escape lateral del puerto Cisco N9K



 a| 
X-NXA-PAC-650W-B.
 a| 
Fuente de alimentación, Cisco 650W - entrada lateral de puerto



 a| 
X-NXA-PAC-650W-F
 a| 
Fuente de alimentación, Cisco 650W - salida lateral de puerto

|===
Detalles del flujo de aire del switch Cisco Nexus 92300YC:

* Flujo de aire de escape del lado del puerto (aire estándar) -- el aire frío entra en el chasis a través del ventilador y los módulos de alimentación del pasillo frío y sale por el extremo del puerto del chasis en el pasillo caliente. Flujo de aire de escape del puerto con coloración azul.
* Flujo de aire de admisión del lado del puerto (aire de retroceso) -- el aire frío entra en el chasis a través del extremo del puerto en el pasillo frío y sale por los módulos de ventilador y fuente de alimentación del pasillo caliente. Flujo de aire de entrada en el puerto con colorante borgoña.


.¿Qué sigue?
link:required-documentation-92300.html["Documentación requerida"] .
