---
permalink: switch-cisco-92300/components-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Si desea crear clústeres ONTAP con más de dos nodos, necesitará dos conmutadores de red de clúster compatibles.  Puede utilizar interruptores de administración adicionales, que son opcionales. 
---
= Componentes y números de pieza de los conmutadores Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del switch Cisco Nexus 92300YC, asegúrese de revisar todos los componentes del switch y los números de pieza. Ver el https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] Para más detalles.

La siguiente tabla enumera el número de pieza y la descripción del interruptor, los ventiladores y las fuentes de alimentación 92300YC:

[cols="1,2"]
|===
| Número de pieza | Descripción 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = Escape del lado del puerto)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = Entrada del lado del puerto)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventilador, entrada de aire lateral del puerto Cisco N9K



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventilador, flujo de aire de escape lateral del puerto Cisco N9K



 a| 
X-NXA-PAC-650W-B
 a| 
Fuente de alimentación Cisco de 650 W - entrada lateral del puerto



 a| 
X-NXA-PAC-650W-F
 a| 
Fuente de alimentación Cisco de 650 W - salida de aire lateral (puerto).

|===
Detalles del flujo de aire del switch Cisco Nexus 92300YC:

* Flujo de aire de escape del lado de los puertos (aire estándar): el aire frío entra en el chasis a través de los módulos del ventilador y la fuente de alimentación en el pasillo frío y sale por el extremo de los puertos del chasis en el pasillo caliente.  Salida de aire de escape por el lado de babor con coloración azul.
* Flujo de aire de entrada por el lado del puerto (aire inverso): el aire frío entra al chasis a través del extremo del puerto en el pasillo frío y sale a través del ventilador y los módulos de alimentación en el pasillo caliente.  Entrada de aire por el lado de babor con color burdeos.


.¿Qué sigue?
Una vez que haya confirmado sus componentes y números de pieza, puede revisar el link:required-documentation-92300.html["documentación requerida"].
