---
permalink: switch-cisco-92300/configure-reqs-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Si desea crear clústeres ONTAP con más de dos nodos, necesitará dos conmutadores de red de clúster compatibles.  Puede utilizar interruptores de administración adicionales, que son opcionales. 
---
= Requisitos de configuración para los switches Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del switch Cisco Nexus 92300YC, asegúrese de revisar todos los requisitos de configuración y de red.

Si desea crear clústeres ONTAP con más de dos nodos, necesitará dos conmutadores de red de clúster compatibles.  Puede utilizar interruptores de administración adicionales, que son opcionales.



== Requisitos de configuración

Para configurar su clúster, necesita el número y tipo adecuados de cables y conectores de cable para sus conmutadores.  Dependiendo del tipo de switch que esté configurando inicialmente, deberá conectarse al puerto de consola del switch con el cable de consola incluido; también deberá proporcionar información de red específica.



== Requisitos de red

Necesitará la siguiente información de red para todas las configuraciones de conmutadores:

* Subred IP para la gestión del tráfico de red
* Nombres de host y direcciones IP para cada uno de los controladores del sistema de almacenamiento y todos los conmutadores aplicables
* La mayoría de los controladores del sistema de almacenamiento se administran a través de la interfaz e0M conectándose al puerto de servicio Ethernet (ícono de llave inglesa). En los sistemas AFF A800 y AFF A700 , la interfaz e0M utiliza un puerto Ethernet dedicado.


Consulte el https://hwu.netapp.com["Hardware Universe"^] Para obtener la información más reciente.

.¿Qué sigue?
link:components-92300.html["Componentes y números de pieza"].
