---
permalink: switch-cisco-92300/install-switch-92300yc.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 92300YC 
summary: Siga este procedimiento para instalar el conmutador Cisco Nexus 92300YC. 
---
= Instalar el interruptor de grupo 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para configurar y configurar el switch Cisco Nexus 92300YC.

.Antes de empezar
Asegúrese de tener lo siguiente:

* Acceso a un servidor HTTP, FTP o TFTP en el sitio de instalación para descargar las versiones correspondientes del NX-OS y del archivo de configuración de referencia (RCF).
* La versión aplicable de NX-OS, descargada del https://software.cisco.com/download/home["Descarga de software de Cisco"^] página.
* Las licencias aplicables, la información de configuración y red, y los cables.
* Terminadolink:setup-worksheet-92300yc.html["hojas de datos para el cableado"] .
* Los RCF de red de gestión y red de clúster de NetApp aplicables descargados del sitio de soporte de NetApp en http://mysupport.netapp.com/["mysupport.netapp.com"^]. Todos los switches de red de gestión y red de clúster de Cisco llegan con la configuración predeterminada de fábrica de Cisco. Estos conmutadores también tienen la versión actual del software NX-OS pero no tienen cargados los RCF.
* link:required-documentation-92300.html["Documentación necesaria sobre el switch y ONTAP"] .


.Pasos
. Monte en rack la red del clúster y los switches de red de gestión y las controladoras.
+
[cols="1,2"]
|===
| Si está instalando... | Realice lo siguiente... 


 a| 
Cisco Nexus 92300YC en un gabinete de sistema NetApp
 a| 
Consulte la guía _Instalación de un conmutador de clúster Cisco Nexus 92300YC y un panel de paso en un gabinete NetApp para obtener instrucciones sobre cómo instalar el conmutador en un gabinete NetApp .



 a| 
Equipo en un bastidor de Telco
 a| 
Consulte los procedimientos proporcionados en las guías de instalación del hardware del switch y las instrucciones de instalación y configuración de NetApp.

|===
. Conecte los cables de la red de clústeres y los switches de red de gestión a las controladoras mediante las hojas de trabajo de cableado completadas.
. Encienda la red de clúster y los switches de red de gestión y las controladoras.


.El futuro
Opcionalmente, puedeslink:install-switch-netapp-cabinet-92300yc.html["Instalar un conmutador Cisco Nexus 3223C en un gabinete NetApp"] .  De lo contrario, vaya alink:cabling-considerations-92300.html["Revisar el cableado y la configuración"] .
