---
permalink: switch-cisco-92300/install-nxos-software.html 
sidebar: sidebar 
keywords: install nx-os,nx-os configure 
summary: Puede utilizar este procedimiento para instalar el software NX-OS en el switch Nexus 92300YC. 
---
= Instale el software NX-OS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para instalar el software NX-OS en el switch Nexus 92300YC.

NX-OS es un sistema operativo de red para la serie Nexus de switches Ethernet y la serie MDS de switches de red de área de almacenamiento Fibre Channel (FC) proporcionados por Cisco Systems.



== Requisitos de revisión

.Puertos y conexiones de nodos compatibles
* Los enlaces entre conmutadores (ISL) compatibles con los conmutadores Nexus 92300YC son los puertos 1/65 y 1/66.
* Las conexiones de nodo compatibles con los switches Nexus 92300YC son los puertos 1/1 a 1/66.


.Antes de empezar
Asegúrese de tener lo siguiente:

* El software NetApp Cisco NX-OS aplicable para sus switches está disponible en el sitio de soporte de NetApp . http://mysupport.netapp.com/["mysupport.netapp.com"]
* Un clúster en pleno funcionamiento (sin errores en los registros ni problemas similares).
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["página del switch Ethernet de Cisco"^]. Consulte la tabla de compatibilidad del switch para conocer las versiones compatibles de ONTAP y NX-OS.




== Instala el software

Los ejemplos de este procedimiento utilizan dos nodos, pero puede tener hasta 24 nodos en un clúster.

.Acerca de los ejemplos
Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los nombres de los switches Nexus 92300YC son `cs1` y `cs2` .
* El ejemplo utilizado en este procedimiento inicia la actualización en el segundo switch, _*cs2*._
* Los nombres de los clústeres LIF son `node1_clus1` y `node1_clus2` para el nodo 1, y `node2_clus1` y `node2_clus2` para el nodo 2.
* El nombre del espacio IP es `Cluster` .
* El `cluster1::*>` El indicador muestra el nombre del clúster.
* Los puertos del clúster en cada nodo se llaman `e0a` y `e0b` .
+
Ver ellink:https://hwu.netapp.com/Home/Index["_Universo del Hardware^_"] para los puertos de clúster reales compatibles con su plataforma.



.Pasos
. Conecte el conmutador del clúster a la red de administración.
. Utilice el `ping` comando para verificar la conectividad con el servidor que aloja el software NX-OS y el RCF.
+
.Mostrar ejemplo
[%collapsible]
====
Este ejemplo verifica que el switch puede alcanzar el servidor en la dirección IP 172.19.2.1:

[listing, subs="+quotes"]
----
cs2# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Copie el software NX-OS y las imágenes EPLD al conmutador Nexus 92300YC.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.9.2.2.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.2.2.bin  /bootflash/nxos.9.2.2.bin
/code/nxos.9.2.2.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.


cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.9.2.2.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.2.2.img  /bootflash/n9000-epld.9.2.2.img
/code/n9000-epld.9.2.2.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. Verifique la versión en ejecución del software NX-OS:
+
`show version`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2018, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 05.31
  NXOS: version 9.2(1)
  BIOS compile time:  05/17/2018
  NXOS image file is: bootflash:///nxos.9.2.1.bin
  NXOS compile time:  7/17/2018 16:00:00 [07/18/2018 00:21:19]


Hardware
  cisco Nexus9000 C92300YC Chassis
  Intel(R) Xeon(R) CPU D-1526 @ 1.80GHz with 16337884 kB of memory.
  Processor Board ID FDO220329V5

  Device name: cs2
  bootflash:  115805356 kB
Kernel uptime is 0 day(s), 4 hour(s), 23 minute(s), 11 second(s)

Last reset at 271444 usecs after Wed Apr 10 00:25:32 2019
  Reason: Reset Requested by CLI command reload
  System version: 9.2(1)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

cs2#
----
====
. Instale la imagen NX-OS.
+
La instalación del archivo de imagen provoca que este se cargue cada vez que se reinicie el switch.

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *install all nxos bootflash:nxos.9.2.2.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.2.2.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.2.2.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.2.2.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS



Compatibility check is done:
Module  bootable       Impact     Install-type  Reason
------  --------  --------------- ------------  ------
  1       yes      disruptive         reset     default upgrade is not hitless



Images will be upgraded according to following table:

Module   Image         Running-Version(pri:alt            New-Version         Upg-Required
------  --------  --------------------------------------  ------------------  ------------
  1       nxos                                  9.2(1)              9.2(2)         yes
  1       bios    v05.31(05/17/2018):v05.28(01/18/2018)   v05.33(09/08/2018)       yes


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] *y*


Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS
2019 Apr 10 04:59:35 cs2 %$ VDC-1 %$ %VMAN-2-ACTIVATION_STATE: Successfully deactivated virtual service 'guestshell+'

Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. Verifique la nueva versión del software NX-OS después de que el switch se haya reiniciado:
+
`show version`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *show version*

Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2018, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 05.33
  NXOS: version 9.2(2)
  BIOS compile time:  09/08/2018
  NXOS image file is: bootflash:///nxos.9.2.2.bin
  NXOS compile time:  11/4/2018 21:00:00 [11/05/2018 06:11:06]


Hardware
  cisco Nexus9000 C92300YC Chassis
  Intel(R) Xeon(R) CPU D-1526 @ 1.80GHz with 16337884 kB of memory.
  Processor Board ID FDO220329V5

  Device name: cs2
  bootflash:  115805356 kB
  Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 52 second(s)

Last reset at 182004 usecs after Wed Apr 10 04:59:48 2019
  Reason: Reset due to upgrade
  System version: 9.2(1)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
----
====
. Actualice la imagen EPLD y reinicie el switch.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI FPGA                          0x7
IO FPGA                          0x17
MI FPGA2                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2

cs2# *install epld bootflash:n9000-epld.9.2.2.img module 1*
Compatibility check:
Module        Type         Upgradable        Impact   Reason
------  -----------------  ----------    ----------   ------
     1            SUP           Yes       disruptive  Module Upgradable

Retrieving EPLD versions.... Please wait.
Images will be upgraded according to following table:
Module  Type   EPLD              Running-Version   New-Version  Upg-Required
------  ----  -------------      ---------------   -----------  ------------
     1   SUP  MI FPGA                   0x07        0x07             No
     1   SUP  IO FPGA                   0x17        0x19            Yes
     1   SUP  MI FPGA2                  0x02        0x02             No
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] *y*

Proceeding to upgrade Modules.

Starting Module 1 EPLD Upgrade

Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sectors)
Module 1 EPLD upgrade is successful.
Module        Type  Upgrade-Result
------  ------------------  --------------
     1         SUP         Success


EPLDs upgraded.

Module 1 EPLD upgrade is successful.
----
====
. Tras reiniciar el switch, vuelva a iniciar sesión y verifique que la nueva versión de EPLD se haya cargado correctamente.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
cs2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI FPGA                          0x7
IO FPGA                          0x19
MI FPGA2                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2
----
====


.¿Que sigue?
link:install-the-rcf-file.html["Instale el archivo de configuración de referencia"]
