---
permalink: switch-cisco-92300/migrate-to-92300yc-overview.html 
sidebar: sidebar 
keywords: migrate to cisco nx 92300yc cluster switch,new cluster switch migration 
summary: Debe conocer determinada información de configuración, conexiones de puertos y requisitos de cableado cuando sustituya algunos switches de clúster Cisco Nexus anteriores por switches de clúster Cisco Nexus 92300YC. 
---
= Migre desde un switch de Cisco a un switch Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer determinada información de configuración, conexiones de puertos y requisitos de cableado cuando sustituya algunos switches de clúster Cisco Nexus anteriores por switches de clúster Cisco Nexus 92300YC.

* Se admiten los siguientes switches de clúster:
+
** Nexus 92300YC
** Nexus 5596UP
** Nexus 5020
** Nexus 5010


* Los switches de clúster utilizan los siguientes puertos para las conexiones a los nodos:
+
** Puertos e1/1-48 (10/25 GbE), e1/49-64 (40/100 GbE): Nexus 92300YC
** Puertos e1/1-40 (10 GbE): Nexus 5596UP
** Puertos e1/1-32 (10 GbE): Nexus 5020
** Puertos e1/1-12, e2/1-6 (10 GbE): Nexus 5010 con módulo de expansión


* Los switches de clúster utilizan los siguientes puertos de enlace entre switches (ISL):
+
** Puertos e1/65-66 (100 GbE): Nexus 92300YC
** Puertos e1/41-48 (10 GbE): Nexus 5596UP
** Puertos e1/33-40 (10 GbE): Nexus 5020
** Puertos e1/13-20 (10 GbE): Nexus 5010


* La https://["_Hardware Universe_"^] contiene información sobre el cableado compatible para todos los switches de clúster.
* Ha configurado algunos de los puertos en los switches Nexus 92300YC para que se ejecuten a 10 GbE o 40 GbE.
* Ha planificado, migrado y documentado conectividad de 10 GbE y 40 GbE desde los nodos a los switches de clúster Nexus 92300YC.
* Las versiones ONTAP y NX-OS compatibles con este procedimiento son en la https://["Switches Ethernet de Cisco"^] página.
+

NOTE: Una vez finalizada la migración, es posible que necesite instalar el archivo de configuración necesario para admitir el Monitor de estado del conmutador de clúster (CSHM) para los conmutadores de clúster 92300YC. Consulte link:setup-install-cshm-file.html["Instale el archivo de configuración del Monitor de estado del conmutador de clúster (CSHM)"] para obtener más detalles.


