---
permalink: switch-cisco-92300/smart-call-home-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Si desea crear clústeres de ONTAP con más de dos nodos, necesita dos switches de red de clúster compatibles. Puede usar switches de gestión adicionales, que son opcionales. 
---
= Requisitos de Smart Call Home
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para utilizar la función de inicio de llamada inteligente, revise las siguientes directrices.

Smart Call Home supervisa los componentes de hardware y software de su red. Cuando se produce una configuración de sistema crítica, genera una notificación basada en correo electrónico y genera una alerta a todos los destinatarios que están configurados en el perfil de destino. Para utilizar Smart Call Home, debe configurar un conmutador de red de clúster para comunicarse mediante correo electrónico con el sistema Smart Call Home. Además, puede configurar opcionalmente el conmutador de red de clúster para aprovechar la función integrada de soporte Smart Call Home de Cisco.

Antes de poder utilizar Smart Call Home, tenga en cuenta las siguientes consideraciones:

* Debe haber un servidor de correo electrónico.
* El switch debe tener conectividad IP con el servidor de correo electrónico.
* Se debe configurar el nombre del contacto (contacto del servidor SNMP), el número de teléfono y la dirección de la calle. Esto es necesario para determinar el origen de los mensajes recibidos.
* Un ID de CCO debe estar asociado con un contrato de servicio Cisco SMARTnet adecuado para su empresa.
* El servicio Cisco SMARTnet debe estar en su lugar para que el dispositivo se registre.


La http://["Sitio de soporte de Cisco"^] Contiene información acerca de los comandos para configurar Smart Call Home.
