---
permalink: switch-cshm/config-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: 'La función de recopilación de registros del monitor de estado del conmutador Ethernet (CSHM) se utiliza para recopilar registros de los conmutadores de red de clúster o de almacenamiento en ONTAP.' 
---
= Configurar la recopilación de registros
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El monitor de estado del conmutador Ethernet (CSHM) es responsable de garantizar el buen funcionamiento de los conmutadores de red de clúster y almacenamiento y de recopilar los registros de los conmutadores con fines de depuración.  Este procedimiento le guía a través del proceso de configuración de la recopilación, la solicitud de registros detallados de *Soporte* y la habilitación de una recopilación horaria de datos *Periódicos* que recopila AutoSupport.

*NOTA:* Si activa el modo FIPS, deberá completar lo siguiente:

[NOTE]
====
. Regenera las claves SSH en el switch siguiendo las instrucciones del proveedor.
. Regenerar claves SSH en ONTAP usando `debug system regenerate-systemshell-key-pair`
. Vuelva a ejecutar la rutina de configuración de recopilación de registros utilizando `system switch ethernet log setup-password` dominio


====


== Antes de empezar

* El usuario debe tener acceso al interruptor. `show` comandos.  Si estos no están disponibles, cree un nuevo usuario y otórguele los permisos necesarios.
* La monitorización del estado del switch debe estar habilitada.  Verifique esto asegurándose de que `Is Monitored:` El campo se establece en *verdadero* en la salida de `system switch ethernet show` dominio.
* Para la recopilación de registros con switches Broadcom y Cisco :
+
** El usuario local debe tener privilegios de administrador de red.
** Se debe crear un nuevo usuario en el switch para cada configuración de clúster con la recopilación de registros habilitada.  Estos conmutadores no admiten varias claves SSH para el mismo usuario.  Cualquier configuración adicional de recopilación de registros que se realice sobrescribirá las claves SSH preexistentes del usuario.


* Para admitir la recopilación de registros con conmutadores NVIDIA , el _usuario_ encargado de la recopilación de registros debe tener permiso para ejecutar el `cl-support` comando sin necesidad de proporcionar una contraseña.  Para permitir este uso, ejecute el comando:
+
`echo '_<user>_ ALL = NOPASSWD: /usr/cumulus/bin/cl-support' | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/cumulus`





== Pasos

[role="tabbed-block"]
====
.ONTAP 9.15.1 y posteriores
--
. Para configurar la recopilación de registros, ejecute el siguiente comando para cada conmutador.  Se le solicita que ingrese el nombre del switch, el nombre de usuario y la contraseña para la recopilación de registros.
+
*NOTA:* Si responde *sí* a la solicitud de especificación de usuario, asegúrese de que el usuario tenga los permisos necesarios, tal como se describe en<<Antes de empezar>> .

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Para CL 5.11.1, cree el usuario *cumulus* y responda *y* a la siguiente pregunta: ¿Desea especificar un usuario distinto de admin para la recopilación de registros?  {y|n}: *y*

. [[step2]]Habilitar la recopilación periódica de registros:
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -periodic-enabled true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs1*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log modify -device cs2 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs2*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log show*
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       true        scheduled   never-run
cs2                                       true        scheduled   never-run
2 entries were displayed.
----
. Recopilación de registros de soporte de solicitudes:
+
[source, cli]
----
system switch ethernet log collect-support-log -device <switch-name>
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log collect-support-log -device cs1*

*cs1*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log collect-support-log -device cs2*

*cs2*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log show
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       false       halted      initiated
cs2                                       true        scheduled   initiated
2 entries were displayed.
----
. Para ver todos los detalles de la recopilación de registros, incluyendo la habilitación, el mensaje de estado, la marca de tiempo anterior y el nombre de archivo de la recopilación periódica, el estado de la solicitud, el mensaje de estado y la marca de tiempo anterior y el nombre de archivo de la recopilación de soporte, utilice lo siguiente:
+
[source, cli]
----
system switch ethernet log show -instance
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show -instance*

                    Switch Name: cs1
           Periodic Log Enabled: true
            Periodic Log Status: Periodic log collection has been scheduled to run every hour.
    Last Periodic Log Timestamp: 3/11/2024 11:02:59
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:14:20
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz

                    Switch Name: cs2
           Periodic Log Enabled: false
            Periodic Log Status: Periodic collection has been halted.
    Last Periodic Log Timestamp: 3/11/2024 11:05:18
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:18:54
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz
2 entries were displayed.
----


--
.ONTAP 9.14.1 y anteriores
--
. Para configurar la recopilación de registros, ejecute el siguiente comando para cada conmutador.  Se le solicita que ingrese el nombre del switch, el nombre de usuario y la contraseña para la recopilación de registros.
+
*NOTA:* Si responde `y` En la solicitud de especificación de usuario, asegúrese de que el usuario tenga los permisos necesarios como se describe en<<Antes de empezar>> .

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Para CL 5.11.1, cree el usuario *cumulus* y responda *y* a la siguiente pregunta: ¿Desea especificar un usuario distinto de admin para la recopilación de registros?  {y|n}: *y*

. [[step2]] Para solicitar la recopilación de registros de soporte y habilitar la recopilación periódica, ejecute el siguiente comando.  Esto inicia ambos tipos de recopilación de registros: la detallada. `Support` registros y una recopilación horaria de `Periodic` datos.
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -log-request true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
+
Espere 10 minutos y luego compruebe que la recopilación de registros se haya completado:

+
[source, cli]
----
system switch ethernet log show
----


--
====

CAUTION: Si la función de recopilación de registros informa de algún estado de error (visible en la salida de `system switch ethernet log show` ), verlink:log-collection-troubleshoot.html["Solución de problemas de la recopilación de registros"] Para obtener más detalles.

.¿Que sigue?
link:config-snmpv3.html["Configurar SNMPv3 (opcional)"].
