---
permalink: switch-cshm/log-collection-troubleshoot.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: Puedes utilizar los comandos que se proporcionan aquí para... 
---
= Solución de problemas de la recopilación de registros
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si encuentra alguno de los siguientes estados de error notificados por la función de recopilación de registros (visibles en la salida de `system switch ethernet log show` comando), pruebe los pasos de depuración correspondientes:

|===


| *Estado de error de recopilación de registros* | *Resolución* 


 a| 
*Claves RSA no presentes*
 a| 
Regenerar claves SSH de ONTAP .



 a| 
*Error de contraseña del switch*
 a| 
Verificar credenciales, probar la conectividad SSH y regenerar las claves SSH de ONTAP .  Revise la documentación del switch o póngase en contacto con el soporte de NetApp para obtener instrucciones.



 a| 
*Las claves ECDSA no están presentes para FIPS*
 a| 
Si el modo FIPS está habilitado, las claves ECDSA deben generarse en el conmutador antes de volver a intentarlo.



 a| 
*Se encontró un registro preexistente*
 a| 
Elimine el archivo de recopilación de registros anterior del conmutador.



 a| 
*Error en el registro de volcado del switch*
 a| 
Asegúrese de que el usuario del switch tenga permisos de recopilación de registros.  Consulte los requisitos previos anteriores.

|===

NOTE: Si los detalles de la resolución no funcionan, póngase en contacto con el soporte de NetApp .
