---
permalink: switch-cshm/monitor-verify.html 
sidebar: sidebar 
keywords: verify, monitor, cluster, management, network, switches, heath, monitor 
summary: Aprenda cómo verificar que la monitorización de un switch Ethernet funciona correctamente. 
---
= Verifique la monitorización de los switches Ethernet.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El monitor de estado del conmutador Ethernet (CSHM) intenta automáticamente supervisar los conmutadores que descubre; sin embargo, la supervisión podría no producirse automáticamente si los conmutadores no están configurados correctamente.  Debe verificar que el monitor de estado esté configurado correctamente para supervisar sus conmutadores.



== Confirme la monitorización de los switches Ethernet conectados.

Para confirmar que se están monitorizando los conmutadores Ethernet conectados, ejecute:

[source, cli]
----
system switch ethernet show
----
Si el `Model` La columna muestra *OTRO* o la `IS Monitored` Si el campo muestra *falso*, ONTAP no podrá supervisar el switch.  Un valor de *OTRO* normalmente indica que ONTAP no admite ese interruptor para la supervisión del estado.

El `IS Monitored` El campo está establecido en *falso* por la razón especificada en el `Reason` campo.

[NOTE]
====
Si un switch no aparece en la salida del comando, es probable que ONTAP no lo haya detectado.  Compruebe que el interruptor está conectado correctamente.  Si es necesario, puede agregar el interruptor manualmente.  Verlink:monitor-manage.html["Gestionar la monitorización de los conmutadores Ethernet"] Para obtener más detalles.

====


== Confirme que las versiones de firmware y RCF estén actualizadas.

Asegúrese de que el switch esté ejecutando el firmware compatible más reciente y de que se haya aplicado un archivo de configuración de referencia (RCF) compatible.  Puede encontrar más información en elhttps://mysupport.netapp.com/site/downloads["Página de descargas de soporte de NetApp"^] .

Por defecto, el monitor de salud utiliza SNMPv2c con la cadena de comunidad *cshm1!* para la monitorización, pero también se puede configurar SNMPv3.

Si necesita cambiar la cadena de comunidad SNMPv2c predeterminada, asegúrese de que la cadena de comunidad SNMPv2c deseada se haya configurado en el conmutador.

[source, cli]
----
system switch ethernet modify -device SwitchA -snmp-version SNMPv2c -community-or-username newCommunity!
----

NOTE: Verlink:config-snmpv3.html["Opcional: Configurar SNMPv3"] Para obtener detalles sobre la configuración de SNMPv3 para su uso.



== Confirmar la conexión de red de gestión

Verifique que el puerto de administración del switch esté conectado a la red de administración.

Para que ONTAP pueda realizar consultas SNMP y recopilar registros, se requiere una conexión correcta al puerto de administración.
