---
permalink: switch-cshm/monitor-manage.html 
sidebar: sidebar 
keywords: create, remove, switch, cluster, monitor, health, management 
summary: Aprenda cómo crear manualmente, cambiar la configuración de monitoreo predeterminada y eliminar conmutadores Ethernet del monitoreo. 
---
= Gestionar la monitorización de los conmutadores Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En la mayoría de los casos, los conmutadores Ethernet son detectados automáticamente por ONTAP y monitorizados por CSHM.  El archivo de configuración de referencia (RCF) aplicado al switch, entre otras cosas, habilita el protocolo de descubrimiento de Cisco (CDP) y/o el protocolo de descubrimiento de capa de enlace (LLDP).  Sin embargo, es posible que necesite agregar manualmente un interruptor que no se detecte o eliminar un interruptor que ya no esté en uso.  También puede detener la supervisión activa mientras conserva el switch en la configuración, por ejemplo, durante el mantenimiento.



== Crea una entrada de switch para que ONTAP pueda monitorizarlo.

Utilice el `system switch ethernet create` comando para configurar manualmente y habilitar la monitorización de un conmutador Ethernet específico.  Esto resulta útil si ONTAP no agrega el conmutador automáticamente, o si previamente eliminó el conmutador y desea volver a agregarlo.

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
Un ejemplo típico es agregar un switch llamado [DeviceName], con dirección IP 1.2.3.4 y credenciales SNMPv2c configuradas como *cshm1!*.  Usar `-type storage-network` en lugar de `-type cluster-network` Si está configurando un conmutador de almacenamiento.



== Deshabilitar la monitorización sin eliminar el interruptor

Si desea pausar o detener la monitorización de un determinado interruptor, pero conservarla para futuras monitorizaciones, modifique su `is-monitoring-enabled-admim` parámetro en lugar de eliminarlo.

Por ejemplo:

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
Esto le permite conservar los detalles y la configuración del switch sin generar nuevas alertas ni redescubrimientos.



== Quita el interruptor que ya no necesites.

Usar `system switch ethernet delete` Eliminar un interruptor que ha sido desconectado o que ya no es necesario:

[source, cli]
----
system switch ethernet delete -device DeviceName
----
Por defecto, este comando solo tiene éxito si ONTAP no detecta actualmente el switch a través de CDP o LLDP.  Para extraer un interruptor detectado, utilice el `-force` parámetro:

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
Cuando `-force` Si se utiliza, el conmutador podría volver a agregarse automáticamente si ONTAP lo detecta de nuevo.
