---
permalink: switch-cshm/monitor-manage.html 
sidebar: sidebar 
keywords: create, remove, switch, cluster, monitor, health, management 
summary: Aprenda a crear manualmente, cambiar la configuración de supervisión predeterminada y eliminar conmutadores Ethernet de la supervisión. 
---
= Gestionar la supervisión de switches Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En la mayoría de los casos, los conmutadores Ethernet son descubiertos automáticamente por ONTAP y monitoreados por CSHM. El archivo de configuración de referencia (RCF) aplicado al switch, entre otras cosas, habilita el protocolo de detección de Cisco (CDP) y/o el protocolo de detección de capa de enlace (LLDP). Sin embargo, es posible que necesite agregar manualmente un conmutador que no se detecte o eliminar un conmutador que ya no esté en uso. También puede detener la supervisión activa mientras mantiene el interruptor en la configuración, como durante el mantenimiento.



== Cree una entrada de conmutador para que ONTAP pueda supervisarla

Utilice `system switch ethernet create` el comando para configurar y activar manualmente la supervisión de un switch Ethernet especificado. Esto es útil si ONTAP no agrega el conmutador automáticamente, o si ya eliminó el conmutador y desea volver a agregarlo.

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
Un ejemplo típico es agregar un conmutador llamado [DeviceName], con la dirección IP 1,2.3,4, y las credenciales SNMPv2c establecidas en *cshm1!*. Utilice `-type storage-network` en lugar de `-type cluster-network` si va a configurar un switch de almacenamiento.



== Desactive la supervisión sin eliminar el conmutador

Si desea pausar o detener la supervisión de un determinado conmutador, pero aún así conservarlo para una supervisión futura, modifique su `is-monitoring-enabled-admim` parámetro en lugar de eliminarlo.

Por ejemplo:

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
Esto le permite conservar los detalles del switch y la configuración sin generar nuevas alertas o nuevas detecciones.



== Retire un interruptor que ya no necesite

Se utiliza `system switch ethernet delete` para eliminar un interruptor que se ha desconectado o que ya no es necesario:

[source, cli]
----
system switch ethernet delete -device DeviceName
----
De manera predeterminada, este comando solo se ejecuta correctamente si ONTAP no detecta actualmente el switch a través de CDP o LLDP. Para quitar un conmutador detectado, utilice el `-force` parámetro:

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
Cuando `-force` se utiliza, el interruptor puede volver a añadirse automáticamente si ONTAP lo detecta de nuevo.
