---
permalink: switch-nvidia-sn2100-storage/components-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Para la instalación y el mantenimiento del switch NVIDIA SN2100, asegúrese de revisar la lista de componentes y números de pieza para el kit de armarios y rieles. 
---
= Componentes y números de pieza para conmutadores NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del switch NVIDIA SN2100, asegúrese de revisar la lista de componentes y números de pieza para el kit de armarios y rieles.



== Detalles del armario

El conmutador NVIDIA SN2100 (X190006/X190106) se instala en el armario de conmutadores doble/único NVIDIA con los soportes estándar que se incluyen con el conmutador.



== Detalles del kit de rieles

La tabla siguiente muestra el número de pieza y la descripción de los interruptores y kits de raíles MSN2100:

[cols="1,2"]
|===
| Número de pieza | Descripción 


 a| 
X190006-PE
 a| 
Cluster Switch, NVIDIA SN2100, 16PT 100G, PTSX



 a| 
X190006-PI
 a| 
Cluster Switch, NVIDIA SN2100, 16PT 100G, PSIN



 a| 
X190106-FE-PE
 a| 
Conmutador, NVIDIA SN2100, 16PT 100G, PTSX, front-end



 a| 
X190106-FE-PI
 a| 
Conmutador, NVIDIA SN2100, 16PT 100G, PSIN, front-end



 a| 
X-MTEF-KIT-D
 a| 
Kit de rieles, conmutador doble NVIDIA lado a lado



 a| 
X-MTEF-KIT-E
 a| 
Kit de rieles, profundidad corta de un único conmutador NVIDIA

|===

NOTE: Consulte la documentación de NVIDIA para obtener más información acerca de https://docs.nvidia.com/networking/display/sn2000pub/Installation["Instalación del kit de rieles y interruptor SN2100"^].

.¿Qué sigue?
link:required-documentation-sn2100-storage.html["Documentación requerida"] .
