---
permalink: switch-nvidia-sn2100-storage/components-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Para la instalación y el mantenimiento del switch NVIDIA SN2100, asegúrese de revisar la lista de componentes y números de pieza del kit de gabinete y riel. 
---
= Componentes y números de pieza para los interruptores NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del switch NVIDIA SN2100, asegúrese de revisar la lista de componentes y números de pieza del kit de gabinete y riel.



== Detalles del gabinete

Instale el conmutador NVIDIA SN2100 (X190006/X190106) en el gabinete de conmutadores dobles/simples de NVIDIA con los soportes estándar que se incluyen con el conmutador.



== Detalles del kit de rieles

La siguiente tabla enumera el número de pieza y la descripción de los kits de interruptores y rieles MSN2100:

[cols="1,2"]
|===
| Número de pieza | Descripción 


 a| 
X190006-PE
 a| 
Conmutador de clúster, NVIDIA SN2100, 16PT 100G, PTSX



 a| 
X190006-PI
 a| 
Conmutador de clúster, NVIDIA SN2100, 16PT 100G, PSIN



 a| 
X190106-FE-PE
 a| 
Conmutador, NVIDIA SN2100, 16PT 100G, PTSX, Front End



 a| 
X190106-FE-PI
 a| 
Conmutador, NVIDIA SN2100, 16PT 100G, PSIN, Front End



 a| 
X-MTEF-KIT-D
 a| 
Kit de rieles, interruptor doble NVIDIA lado a lado



 a| 
X-MTEF-KIT-E
 a| 
Kit de rieles, interruptor único NVIDIA de profundidad corta

|===

NOTE: Consulte la documentación de NVIDIA para obtener más detalles sobre https://docs.nvidia.com/networking/display/sn2000pub/Installation["Instalación del kit de interruptor y riel SN2100"^] .

.¿Qué sigue?
Una vez que haya confirmado sus componentes y números de pieza, puede revisar el link:required-documentation-sn2100-storage.html["documentación requerida"].
