---
permalink: switch-nvidia-sn2100-storage/configure-reqs-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Para la instalación y el mantenimiento del switch NVIDIA SN2100, asegúrese de revisar todos los requisitos. 
---
= Requisitos de configuración para los switches NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del switch NVIDIA SN2100, asegúrese de revisar todos los requisitos.



== Requisitos de instalación

Si desea crear clústeres ONTAP con más de dos nodos, necesitará dos conmutadores de red de clúster compatibles.  Puede utilizar interruptores de administración adicionales, que son opcionales.

Instale el conmutador NVIDIA SN2100 (X190006/X190106) en el gabinete de conmutadores dobles/simples de NVIDIA con los soportes estándar que se incluyen con el conmutador.

Para obtener instrucciones sobre el cableado, consultelink:cabling-considerations-sn2100-storage.html["Consideraciones sobre el cableado y la configuración"] .



== Soporte ONTAP y Linux

El switch NVIDIA SN2100 es un switch Ethernet de 10/25/40/100 Gb que ejecuta Cumulus Linux.  El conmutador admite lo siguiente:

* ONTAP 9.10.1P3.  El switch SN2100 da servicio a aplicaciones de clúster y almacenamiento en ONTAP 9.10.1P3 a través de diferentes pares de switches.  A partir de ONTAP 9.10.1P3, puede usar conmutadores NVIDIA SN2100 para combinar la funcionalidad de almacenamiento y clúster en una configuración de conmutador compartido.
* Sistema operativo Cumulus Linux (CL) versión 4.4.3.  Para obtener información actualizada sobre compatibilidad, consulte la https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Conmutadores Ethernet NVIDIA"^] Página informativa.
* Puedes instalar Cumulus Linux cuando el switch esté ejecutando Cumulus Linux u ONIE.


.¿Qué sigue?
Después de revisar los requisitos de configuración, puede confirmar su link:components-sn2100-storage.html["componentes y números de pieza"].
