---
permalink: switch-nvidia-sn2100-storage/install-onie-mode-sn2100-storage.html 
sidebar: sidebar 
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode 
summary: 'El sistema operativo Cumulus Linux (CL) se puede instalar cuando el switch ejecuta Cumulus Linux u ONIE.' 
---
= Instalar Cumulus Linux en modo ONIE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para instalar el sistema operativo Cumulus Linux (CL) cuando el switch esté funcionando en modo ONIE.


NOTE: El sistema operativo Cumulus Linux (CL) se puede instalar cuando el switch ejecuta Cumulus Linux u ONIE (véaselink:install-cumulus-mode-sn2100-storage.html["Instalar en modo Cumulus"] ).

.Acerca de esta tarea
Puede instalar Cumulus Linux utilizando Open Network Install Environment (ONIE), que permite la detección automática de una imagen de instalación de red.  Esto facilita el modelo de sistema para asegurar los switches con una elección de sistema operativo, como Cumulus Linux.  La forma más sencilla de instalar Cumulus Linux con ONIE es mediante detección HTTP local.


NOTE: Si su host tiene habilitado IPv6, asegúrese de que esté ejecutando un servidor web.  Si su host está habilitado para IPv4, asegúrese de que esté ejecutando DHCP además de un servidor web.

Este procedimiento muestra cómo actualizar Cumulus Linux después de que el administrador haya arrancado en ONIE.

.Pasos
. Descargue el archivo de instalación de Cumulus Linux al directorio raíz del servidor web.  Cambiar el nombre de este archivo `onie-installer` .
. Conecte su equipo al puerto Ethernet de administración del switch mediante un cable Ethernet.
. Encienda el interruptor.  El switch descarga el instalador de la imagen ONIE y se inicia.  Una vez finalizada la instalación, aparece el indicador de inicio de sesión de Cumulus Linux en la ventana de la terminal.
+

NOTE: Cada vez que se instala Cumulus Linux, se borra y se reconstruye toda la estructura del sistema de archivos.

. Reinicie el switch SN2100:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. Presione la tecla *Esc* en la pantalla de GNU GRUB para interrumpir el proceso de arranque normal, seleccione *ONIE* y presione *Enter*.
. En la siguiente pantalla que aparece, seleccione *ONIE: Instalar SO*.
. El proceso de detección del instalador de ONIE se ejecuta buscando la instalación automática.  Pulse *Enter* para detener temporalmente el proceso.
. Cuando el proceso de descubrimiento se ha detenido:
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. Si el servicio DHCP está en funcionamiento en su red, verifique que la dirección IP, la máscara de subred y la puerta de enlace predeterminada estén asignadas correctamente:
+
`ifconfig eth0`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
====
. Si el esquema de direccionamiento IP se define manualmente, haga lo siguiente:
+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. Repita el paso 9 para verificar que la información estática se haya ingresado correctamente.
. Instalar Cumulus Linux:
+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. Una vez finalizada la instalación, inicie sesión en el switch:
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
====
. Verifique la versión de Cumulus para Linux:
+
`net show version`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----
====


.¿Que sigue?
Una vez instalado Cumulus Linux en modo ONIE, puedeslink:install-rcf-sn2100-storage.html["Instalar o actualizar el script RCF"] .
