---
permalink: switch-nvidia-sn2100-storage/migrate-cisco-storage-switch-sn2100-storage.html 
sidebar: sidebar 
keywords: migrating to a storage switch with NVIDIA SN2100 storage switches, how to migrate 
summary: Puede migrar sin interrupciones los switches Cisco más antiguos de un clúster ONTAP a los switches de almacenamiento NVIDIA SN2100. 
---
= Migrar de un switch de almacenamiento Cisco a un switch de almacenamiento NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede migrar switches Cisco antiguos para un clúster ONTAP a switches de almacenamiento NVIDIA SN2100. Este es un procedimiento que no produce interrupciones.



== Requisitos de revisión

Se admiten los siguientes conmutadores de almacenamiento:

* Cisco Nexus 9336C-FX2
* Cisco Nexus 3232C
* Ver el https://hwu.netapp.com/["Hardware Universe"^] Para obtener información detallada sobre los puertos compatibles y sus configuraciones.


.Antes de empezar
Asegúrese de tener lo siguiente:

* El clúster existente está configurado y funcionando correctamente.
* Todos los puertos de almacenamiento están en estado activo para garantizar un funcionamiento sin interrupciones.
* Los conmutadores de almacenamiento NVIDIA SN2100 están configurados y funcionando bajo la versión correcta de Cumulus Linux instalada con el archivo de configuración de referencia (RCF) aplicado.
* La configuración de red de almacenamiento existente presenta lo siguiente:
+
** Un clúster NetApp redundante y totalmente funcional que utiliza ambos switches Cisco antiguos.
** Conectividad de gestión y acceso a la consola tanto para los switches Cisco antiguos como para los nuevos.
** Todas las LIF del clúster en estado activo están en sus puertos de origen.
** Puertos ISL habilitados y cableados entre los switches Cisco antiguos y entre los switches nuevos.


* Ver el https://hwu.netapp.com/["Hardware Universe"^] Para obtener información detallada sobre los puertos compatibles y sus configuraciones.
* Algunos de los puertos están configurados en los switches NVIDIA SN2100 para funcionar a 100 GbE.
* Has planificado, migrado y documentado la conectividad 100 GbE desde los nodos a los conmutadores de almacenamiento NVIDIA SN2100.




== Migrar los interruptores

.Acerca de los ejemplos
En este procedimiento, se utilizan switches de almacenamiento Cisco Nexus 9336C-FX2 como ejemplos de comandos y salidas.

Los ejemplos de este procedimiento utilizan la siguiente nomenclatura de interruptores y nodos:

* Los switches de almacenamiento Cisco Nexus 9336C-FX2 existentes son _S1_ y _S2_.
* Los nuevos conmutadores de almacenamiento NVIDIA SN2100 son _sw1_ y _sw2_.
* Los nodos son _nodo1_ y _nodo2_.
* Los LIF del clúster son _node1_clus1_ y _node1_clus2_ en el nodo 1, y _node2_clus1_ y _node2_clus2_ en el nodo 2 respectivamente.
* El `cluster1::*>` El indicador muestra el nombre del clúster.
* Los puertos de red utilizados en este procedimiento son _e5a_ y _e5b_.
* Los puertos de ruptura adoptan el formato: swp1s0-3.  Por ejemplo, cuatro puertos de ruptura en swp1 son _swp1s0_, _swp1s1_, _swp1s2_ y _swp1s3_.
* El interruptor S2 se reemplaza primero por el interruptor sw2 y luego el interruptor S1 se reemplaza por el interruptor sw1.
+
** Luego, el cableado entre los nodos y S2 se desconecta de S2 y se vuelve a conectar a sw2.
** A continuación, se desconecta el cableado entre los nodos y S1 de S1 y se vuelve a conectar a sw1.






=== Paso 1: Prepararse para la migración

. Si AutoSupport está habilitado, suprima la creación automática de casos mediante la invocación de un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
donde _x_ es la duración de la ventana de mantenimiento en horas.

. Cambie el nivel de privilegio a avanzado, ingresando *y* cuando se le solicite continuar:
+
`set -privilege advanced`

+
Aparece el indicador avanzado (*>).

. Determinar el estado administrativo u operativo de cada interfaz de almacenamiento:
+
Cada puerto debería mostrarse habilitado para `Status` .





=== Paso 2: Configurar cables y puertos

. Mostrar los atributos del puerto de red:
+
`storage port show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. Verifique que los puertos de almacenamiento de cada nodo estén conectados a los conmutadores de almacenamiento existentes de la siguiente manera (desde la perspectiva de los nodos) utilizando el comando:
+
`network device-discovery show -protocol lldp`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/1           -
node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/2           -
----
====
. En los switches S1 y S2, asegúrese de que los puertos de almacenamiento y los switches estén conectados de la siguiente manera (desde la perspectiva de los switches) utilizando el comando:
+
`show lldp neighbors`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/1         121         S                    e0c
node2                 Eth1/2         121         S                    e0c
SHFGD1947000186       Eth1/10        120         S                    e0a         
SHFGD1947000186       Eth1/11        120         S                    e0a         
SHFGB2017000269       Eth1/12        120         S                    e0a         
SHFGB2017000269       Eth1/13        120         S                    e0a

S2# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability          Port ID
node1                 Eth1/1         121         S                   e5b
node2                 Eth1/2         121         S                   e5b
SHFGD1947000186       Eth1/10        120         S                   e0b         
SHFGD1947000186       Eth1/11        120         S                   e0b         
SHFGB2017000269       Eth1/12        120         S                   e0b         
SHFGB2017000269       Eth1/13        120         S                   e0b
----
====
. En el switch sw2, apague los puertos conectados a los puertos de almacenamiento y nodos de los estantes de discos.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net add interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Traslade los puertos de almacenamiento de nodos del controlador y los estantes de discos del antiguo switch S2 al nuevo switch sw2, utilizando el cableado apropiado compatible con NVIDIA SN2100.
. En el switch sw2, active los puertos conectados a los puertos de almacenamiento de los nodos y los estantes de discos.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Verifique que los puertos de almacenamiento de cada nodo estén conectados a los conmutadores de la siguiente manera, desde la perspectiva de los nodos:
+
`network device-discovery show -protocol lldp`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface      Platform
----------- ------ ------------------------- -------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1           -

node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp2           -
----
====
. Verifique los atributos del puerto de red:
+
`storage port show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. En el switch sw2, verifique que todos los puertos de almacenamiento de nodos estén activos:
+
`net show interface`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. En el switch sw1, apague los puertos conectados a los puertos de almacenamiento de los nodos y los estantes de discos.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. Traslade los puertos de almacenamiento de nodos del controlador y los estantes de discos del antiguo conmutador S1 al nuevo conmutador sw1, utilizando el cableado apropiado compatible con NVIDIA SN2100.
. En el switch sw1, active los puertos conectados a los puertos de almacenamiento de los nodos y los estantes de discos.
+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. Verifique que los puertos de almacenamiento de cada nodo estén conectados a los conmutadores de la siguiente manera, desde la perspectiva de los nodos:
+
`network device-discovery show -protocol lldp`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    sw1 (b8:ce:f6:19:1b:96)   swp1            -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1            -

node2      /lldp
            e0c    sw1  (b8:ce:f6:19:1b:96)  swp2            -
            e5b    sw2  (b8:ce:f6:19:1a:7e)  swp2            -
----
====




=== Paso 3: Verificar la configuración

. Verifique la configuración final:
+
`storage port show`

+
Cada puerto debería mostrarse habilitado para `State` y habilitó para `Status` .

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. En el switch sw2, verifique que todos los puertos de almacenamiento de nodos estén activos:
+
`net show interface`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Verifique que ambos nodos tengan una conexión a cada conmutador:
+
`net show lldp`

+
.Mostrar ejemplo
[%collapsible]
====
El siguiente ejemplo muestra los resultados correspondientes para ambos interruptores:

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e0c
swp2       100G   Trunk/L2  node2                  e0c
swp3       100G   Trunk/L2  SHFFG1826000112        e0a
swp4       100G   Trunk/L2  SHFFG1826000112        e0a
swp5       100G   Trunk/L2  SHFFG1826000102        e0a
swp6       100G   Trunk/L2  SHFFG1826000102        e0a

cumulus@sw2:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e5b
swp2       100G   Trunk/L2  node2                  e5b
swp3       100G   Trunk/L2  SHFFG1826000112        e0b
swp4       100G   Trunk/L2  SHFFG1826000112        e0b
swp5       100G   Trunk/L2  SHFFG1826000102        e0b
swp6       100G   Trunk/L2  SHFFG1826000102        e0b
----
====


. Vuelva a cambiar el nivel de privilegios a administrador:
+
`set -privilege admin`

. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.¿Que sigue?
Después de migrar tus switches, puedes link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
