---
permalink: switch-nvidia-sn2100-storage/replace-sn2100-switch-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia sn2100 cluster switch - nvidia SN2100 
summary: 'Reemplazo de un conmutador de almacenamiento NVIDIA SN2100 defectuoso en un procedimiento no disruptivo (NDU).' 
---
= Reemplazar un conmutador de almacenamiento NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes reemplazar un conmutador de almacenamiento NVIDIA SN2100 defectuoso. Este es un procedimiento que no produce interrupciones.

.Antes de empezar
Antes de instalar el software Cumulus y los RCF en un conmutador de almacenamiento NVIDIA SN2100, asegúrese de lo siguiente:

* Su sistema puede admitir conmutadores de almacenamiento NVIDIA SN2100.
* Has descargado los formularios RCF correspondientes.


El http://hwu.netapp.com["Hardware Universe"^] Proporciona todos los detalles de los puertos compatibles y sus configuraciones.

La configuración de red existente debe tener las siguientes características:

* Completa todos los pasos de solución de problemas para confirmar que necesitas reemplazar tu interruptor.
* Asegúrese de que exista conectividad de gestión en ambos conmutadores.
+

NOTE: Asegúrese de que se hayan completado todos los pasos de solución de problemas para confirmar que su interruptor necesita ser reemplazado.



El switch NVIDIA SN2100 de repuesto debe tener las siguientes características:

* La conectividad de la red de gestión funciona correctamente.
* Puedes acceder al interruptor de repuesto usando la consola.
* La imagen del sistema operativo RCF y Cumulus correspondiente se carga en el switch.
* La personalización inicial del switch está completa.


.Resumen del procedimiento
Este procedimiento reemplaza el segundo conmutador de almacenamiento NVIDIA SN2100 sw2 con el nuevo conmutador NVIDIA SN2100 nsw2.  Los dos nodos son nodo1 y nodo2.

Pasos a seguir:

* Confirme que el interruptor que se va a reemplazar es el SW2.
* Desconecta los cables del interruptor sw2.
* Vuelva a conectar los cables al interruptor nsw2.
* Verifique todas las configuraciones de los dispositivos en el switch nsw2.


.Pasos
. Si AutoSupport está habilitado en este clúster, suprima la creación automática de casos invocando un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ es la duración de la ventana de mantenimiento en horas.

. Cambie el nivel de privilegio a avanzado, ingresando *y* cuando se le solicite continuar:
+
`set -privilege advanced`

. Compruebe el estado de salud de los puertos del nodo de almacenamiento para confirmar la conexión con el conmutador de almacenamiento S1:
+
`storage port show -port-type ENET`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Verifique que el interruptor de almacenamiento sw1 esté disponible:
+
`network device-discovery show -protocol lldp`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. Ejecutar el `net show interface` Comando en el interruptor de funcionamiento para confirmar que puede ver ambos nodos y todos los estantes:
+
`net show interface`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----

cumulus@sw1:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e3a)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e3a)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Verifique los puertos de los estantes en el sistema de almacenamiento:
+
`storage shelf port show -fields remote-device, remote-port`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   swp3          sw1
3.20    1   -             -
3.20    2   swp4          sw1
3.20    3   -             -
3.30    0   swp5          sw1
3.20    1   -             -
3.30    2   swp6          sw1
3.20    3   -             -
cluster1::*>
----
====
. Retire todos los cables conectados al interruptor de almacenamiento sw2.
. Vuelva a conectar todos los cables al interruptor de reemplazo nsw2.
. Vuelva a comprobar el estado de salud de los puertos del nodo de almacenamiento:
+
`storage port show -port-type ENET`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Verifique que ambos interruptores estén disponibles:
+
`net device-discovery show -protocol lldp`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----

cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. Verifique los puertos de los estantes en el sistema de almacenamiento:
+
`storage shelf port show -fields remote-device, remote-port`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     swp3            sw1
3.20    1     swp3            nsw2
3.20    2     swp4            sw1
3.20    3     swp4            nsw2
3.30    0     swp5            sw1
3.20    1     swp5            nsw2
3.30    2     swp6            sw1
3.20    3     swp6            nsw2
cluster1::*>
----
====
. Vuelva a cambiar el nivel de privilegios a administrador:
+
`set -privilege admin`

. Si desactivaste la creación automática de casos, vuelve a activarla mediante un mensaje de AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.¿Que sigue?
Después de haber reemplazado los interruptores, puedes link:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"].
