---
permalink: switch-nvidia-sn2100-storage/required-documentation-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Para la instalación y el mantenimiento del conmutador NVIDIA SN2100, asegúrese de revisar toda la documentación recomendada. 
---
= Requisitos de documentación para los switches NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la instalación y el mantenimiento del conmutador NVIDIA SN2100, asegúrese de revisar toda la documentación recomendada.

En la siguiente tabla se muestra la documentación disponible para los conmutadores NVIDIA SN2100.

[cols="1,2"]
|===
| Título | Descripción 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/install-hardware-sn2100-cluster.html["_Configurar y configurar los switches NVIDIA SN2100_"^]
 a| 
Describe cómo configurar y configurar los conmutadores NVIDIA SN2100, incluida la instalación de Cumulus Linux y RCF aplicables.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-cisco-sn2100-cluster-switch.html["_Migre de un switch Cisco Cluster a un conmutador de clúster NVIDIA SN2100_"^]
 a| 
Describe cómo migrar desde entornos que usan switches de clúster de Cisco a entornos que utilizan switches de clúster NVIDIA SN2100.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-cisco-storage-switch-sn2100-storage.html["_Migre de un switch de almacenamiento de Cisco a un switch de almacenamiento de NVIDIA_"^]
 a| 
Describe cómo migrar desde entornos que usan switches de almacenamiento de Cisco a entornos que utilizan switches de almacenamiento NVIDIA SN2100.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html["_Migre a un clúster con switches de dos nodos con switches de clúster NVIDIA SN2100_"^]
 a| 
Describe cómo migrar a un entorno con switches de dos nodos mediante switches de clúster NVIDIA SN2100.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/replace-sn2100-switch-cluster.html["_Reemplace un conmutador de clúster NVIDIA SN2100_"^]
 a| 
Describe el procedimiento para sustituir un conmutador NVIDIA SN2100 defectuoso en un clúster y descargar Cumulus Linux y el archivo de configuración de referencia.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/replace-sn2100-switch-storage.html["_Reemplace un conmutador de almacenamiento NVIDIA SN2100_"^]
 a| 
Describe el procedimiento para sustituir un conmutador de almacenamiento NVIDIA SN2100 defectuoso y descargar Cumulus Linux y el archivo de configuración de referencia.

|===