---
permalink: switch-nvidia-sn2100-storage/reset-switch-sn2100-storage.html 
sidebar: sidebar 
keywords: SN2100 reset switch to factory defaults, SN2100 switches configuration, efos 
summary: Antes de configurar su conmutador Cisco Nexus SN2100, revise la siguiente información. 
---
= Restablecer el interruptor de almacenamiento SN2100 a los valores predeterminados de fábrica
:allow-uri-read: 


[role="lead"]
Para restablecer el interruptor de almacenamiento SN2100 a los valores predeterminados de fábrica:

* Para Cumulus Linux 5.10 y versiones anteriores, aplique la imagen de Cumulus.
* Para Cumulus Linux 5.11 y posteriores, utilice el `nv action reset system factory-default` dominio.


.Acerca de esta tarea
* Debe estar conectado al conmutador mediante la consola serie.
* Debe tener la contraseña root para acceder a los comandos de sudo.



NOTE: Para obtener más información sobre la instalación de Cumulus Linux, consultelink:configure-software-sn2100-storage.html["Flujo de trabajo de instalación de software para los switches NVIDIA SN2100"] .

.Pasos
[role="tabbed-block"]
====
.Cumulus Linux 5.10 y anteriores
--
. Desde la consola Cumulus, descargue y ponga en cola la instalación del software del conmutador con el comando `onie-install -a -i` Seguido de la ruta del archivo al software del conmutador, por ejemplo:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://<web-server>/<path>/cumulus-linux-5.10.0-mlx-amd64.bin*
----
. El instalador inicia la descarga.  Escriba *y* cuando se le solicite para confirmar la instalación cuando se haya descargado y verificado la imagen.
. Reinicie el conmutador para instalar el nuevo software.
+
`sudo reboot`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
+

NOTE: El conmutador se reinicia y accede a la instalación del software del conmutador, lo que lleva algún tiempo.  Cuando se completa la instalación, el conmutador se reinicia y permanece en el `log-in` inmediato.



--
.Cumulus Linux 5.11 y posteriores
--
. Para restablecer el interruptor a los valores predeterminados de fábrica y eliminar toda la configuración, los archivos del sistema y los archivos de registro, ejecute:
+
`nv action reset system factory-default`

+
Por ejemplo:

+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *nv action reset system factory-default*

This operation will reset the system configuration, delete the log files and reboot the switch.
Type [y] continue.
Type [n] to abort.
Do you want to continue? [y/n] *y*
----


Ver NVIDIA https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-511/Installation-Management/Factory-Reset/["Restablecimiento de fábrica"^] documentación para más detalles.

--
====
.¿Qué sigue?
Después de reiniciar los interruptores, puedeslink:configure-overview-sn2100-storage.html["reconfigurar"] los que necesiten.
