---
permalink: switch-nvidia-sn2100-storage/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for sn2100 switches' 
summary: Puede utilizar este procedimiento para instalar el archivo de configuración aplicable para la supervisión del estado del conmutador de clúster de los conmutadores de almacenamiento NVIDIA SN2100. 
---
= Instale el archivo de configuración del monitor de estado del switch Ethernet.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimiento para instalar el archivo de configuración correspondiente para la monitorización del estado de los switches Ethernet de los clústeres NVIDIA .  Los modelos compatibles son:

* MSN2100-CB2FC
* MSN2100-CB2RC
* X190006-PE
* X190006-PI



NOTE: Este procedimiento de instalación se aplica a ONTAP 9.10.1 y versiones posteriores.

.Antes de empezar
* Verifique que necesita descargar el archivo de configuración ejecutando `system switch ethernet show` y comprobar si aparece *OTRO* para su modelo.
+
Si su modelo sigue mostrando *OTRO* después de aplicar el archivo de configuración, póngase en contacto con el soporte de NetApp .

* Asegúrese de que el clúster ONTAP esté en funcionamiento.
* Habilita SSH para utilizar todas las funciones disponibles en CSHM.
* Borrar el `/mroot/etc/cshm_nod/nod_sign/` directorio en todos los nodos:
+
.. Ingrese al nodeshell:
+
`system node run -node <name>`

.. Cambio a privilegios avanzados:
+
`priv set advanced`

.. Enumere los archivos de configuración en el `/etc/cshm_nod/nod_sign` directorio.  Si el directorio existe y contiene archivos de configuración, muestra una lista con los nombres de los archivos.
+
`ls /etc/cshm_nod/nod_sign`

.. Elimine todos los archivos de configuración correspondientes a los modelos de interruptores conectados.
+
Si no está seguro, elimine todos los archivos de configuración de los modelos compatibles enumerados anteriormente y, a continuación, descargue e instale los archivos de configuración más recientes para esos mismos modelos.

+
`rm /etc/cshm_nod/nod_sign/<filename>`

.. Confirma que los archivos de configuración eliminados ya no se encuentran en el directorio:
+
`ls /etc/cshm_nod/nod_sign`





.Pasos
. Descargue el archivo zip de configuración del monitor de estado del switch Ethernet según la versión de lanzamiento de ONTAP correspondiente.  Este archivo está disponible en https://mysupport.netapp.com/site/info/nvidia-cluster-switch["conmutadores Ethernet NVIDIA"^] página.
+
.. En la página de descarga del software NVIDIA SN2100, seleccione *Archivo Nvidia CSHM*.
.. En la página de Precaución/Lectura obligatoria, seleccione la casilla de verificación para estar de acuerdo.
.. En la página del Acuerdo de Licencia de Usuario Final, seleccione la casilla de verificación para aceptar y haga clic en *Aceptar y continuar*.
.. En la página de descarga de archivos Nvidia CSHM, seleccione el archivo de configuración correspondiente.  Los siguientes archivos están disponibles:




[role="tabbed-block"]
====
.ONTAP 9.15.1 y posteriores
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip


--
.ONTAP 9.11.1 a 9.14.1
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip


--
====
. [[step2]]Cargue el archivo zip correspondiente a su servidor web interno.
. Acceda a la configuración del modo avanzado desde uno de los sistemas ONTAP del clúster.
+
`set -privilege advanced`

. Ejecute el comando de configuración del monitor de estado del switch.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor*
----
. Verifique que el resultado del comando finalice con el siguiente texto para su versión de ONTAP :


[role="tabbed-block"]
====
.ONTAP 9.15.1 y posteriores
--
El sistema de monitorización del estado del switch Ethernet instaló el archivo de configuración.

--
.ONTAP 9.11.1 a 9.14.1
--
SHM instaló el archivo de configuración.

--
.ONTAP 9.10.1
--
El paquete descargado de CSHM se procesó correctamente.

--
====
Si se produce un error, póngase en contacto con el soporte de NetApp .

. [[step6]]Espere hasta el doble del intervalo de sondeo del monitor de estado del switch Ethernet, que se obtiene ejecutando `system switch ethernet polling-interval show` , antes de completar el siguiente paso.
. Ejecutar el comando `system switch ethernet configure-health-monitor show` en el sistema ONTAP y asegúrese de que los conmutadores del clúster se detecten con el campo monitoreado establecido en *Verdadero* y el campo del número de serie no muestre *Desconocido*.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor show*
----


.¿Que sigue?
Después de instalar el archivo CSHM, puedeslink:../switch-cshm/config-overview.html["configurar la monitorización del estado del conmutador"] .
